### PR TITLE
Fixes #6717. Simple typo fix.

### LINKED ISSUE #6717: [low] typo error in an error message
console.warn('Could not register magnet URL handler, are oyu using the latest electron?')
oyu instead you in  browser-laptop/app/filtering.js

//cosmetic

### PR DESCRIPTION
**Pull request by echosa**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.

Already existed. https://github.com/brave/browser-laptop/issues/6717

- [X] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.

### CODE REVIEW

**Comment by echosa** [comment]
I don't understand why CI failed.

File: app/filtering.js [hunk 1]
```diff
@@ -524,7 +524,7 @@ function registerForMagnetHandler (session) {
       session.protocol.unregisterNavigatorHandler('magnet', `${webtorrentUrl}#%s`)
     }
   } catch (e) {
-    console.warn('Could not register magnet URL handler, are oyu using the latest electron?')
```
Comment (maddo) [inline app/filtering.js]: Alternately: "...handler; are you..."

**Comment by bsclifton** [comment]
@echosa we may have too many CI builds running; it failed with:
`The job exceeded the maximum time limit for jobs, and has been terminated.`

Change looks good to me :smile:
