### PR TITLE
Make new tab context menu native

### LINKED ISSUE #7748: New Session tab submenu goes off screen
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
New Session tab submenu goes off screen 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.14.0
rev	77c562c

- Steps to reproduce:
    1. Open bunch of tabs so  that the new tab button is close to the right end of the browser
    2. Right click/long press on new tab button to bring the context menu
    3. Navigate to New Session Tab to show the sub menu, is not contained withing the screen or over the border
    
- Actual result:
New session tab submenu is not shown completely 

- Expected result:
Should show the submenu irrespective of the position of the new tab context menu

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:
#5763
cc: @cezaraugusto

### PR DESCRIPTION
**Pull request by Liunkae**
Fixes #7748

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
1. Open enough tabs to cover the entire tabs bar.
2. Right-click the new tab button (the "+" button).
3. Mouse over the New Session Tab menu item.
4. Make sure the new session submenu is onscreen.

Screenshot:
image

### CODE REVIEW

**Comment by bsclifton** [comment]
@cezaraugusto has tested on macOS and I just tried on Windows- this works great! 😄  very very nice.  Huge thanks for knocking this out so quick

Here's a screenshot, just for folks to see:
screen shot 2017-04-19 at 12 12 33 pm

**Comment by cezaraugusto** [comment]
for reference of https://github.com/brave/browser-laptop/pull/8397#pullrequestreview-33593869. 

Link: https://github.com/brave/browser-laptop/blob/master/test/tab-components/tabTest.js#L105

```
shows a context menu when long pressed (click and hold)
shows a context menu when right clicked
```

**Comment by bsclifton** [comment]
Long term, it would be really nice to have the contextMenus.js code detect whether or not it's running in a test.  If so, it could render the old way (creating a contextMenu object in React).  This would be a big scale change though- for now, marking the failed test with .skip would work 😄 

Now that we have a proposed solution (still needs testing / integration) with https://github.com/brave/muon/pull/161, we should be able to convert all the old style menus to native context menus.  Since you've already done that before, if you wanted to create an issue to track what needs to be converted and then also which has skipped tests (like this one), that would be awesome 😄   I'm going to try my best to dig into the Muon PR above so that we can have async native menus

**Comment by Liunkae** [comment]
I disabled the tests.

@bsclifton Great idea! I'll see what I can do.

**Comment by bbondy** [comment]
💯

File: test/tab-components/tabTest.js [hunk 1]
```diff
@@ -102,14 +102,14 @@ describe('tab tests', function () {
         .click(newFrameButton)
         .waitForExist('[data-test-id="tab"][data-frame-key="2"]')
     })
-    it('shows a context menu when long pressed (click and hold)', function * () {
+    it.skip('shows a context menu when long pressed (click and hold)', function * () {
```
Comment (luixxiul) [inline test/tab-components/tabTest.js]: @Liunkae Was this added to the tracking ticket?

Comment (Liunkae) [inline test/tab-components/tabTest.js]: @luixxiul Thanks! Added.

**Comment by bsclifton** [comment]
Change is small- I pulled this into 0.15.0 per recommendation by @bradleyrichter

**Comment by bsclifton** [comment]
Moving back to 0.15.1. There are some other changes which this relies on. Unfortunately, pulling in is not as easy as I thought ☹️
