### PR TITLE
Stop losing pinned tabs in a window when adding or removing another pinned tab

### LINKED ISSUE #3760: Brave crashes when tabs are pinned(Intermittent issues)
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Brave crashes when tabs are pinned on a clean install build

**Expected behavior:**
Should not crash when tabs are pinned
- Platform (Win7, 8, 10? macOS? Linux distro?):
  Windows 10 x64
- Brave Version:
  0.12.0 RC2 (Clean install)
- Steps to reproduce:
  1. Perform a clean install
  2. Open 5-6 tabs and start pinning each of them
  3. After pinning the first two-three tabs the next tab when pinned browser crashes
- Screenshot if needed:
- Any related issues:

### LINKED ISSUE #9635: Browser crashes by pinning sites, reordering them, and visiting a site via dashboard
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

Also make sure that the STR below does no longer crash the browser

----

**Describe the issue you encountered:** Browser crashes by pinning sites, reordering them, and visiting a site via dashboard.

a

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA):

- Steps to reproduce:
    1. Clear the browser profile
    1. Open https://badssl.com
    2. Open 5 domains from `https-everywhere` to `longextended...`
    3. Pin all of them, including the parent tab
    4. Reorder them randomely
    5. Open a dashboard
    6. Click the twitter tile
    7. Pin the twitter tab
    8. Crash!
    9. Restart the browser
    10. Confirm you have the pinned twitter page at the front of the pinned tabs row

- Actual result: the browser crashes

- Expected result: it should not

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9333

### LINKED ISSUE #10037: pinned tab disappears by reordering and unpinning
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

**Describe the issue you encountered:** pinned tab disappears by reordering and unpinning

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): 0.17.17

- Steps to reproduce:
    1. Open github.com in a tab
    2. Open twitter.com in a new tab
    3. Pin github
    4. Pin twitter
    5. Reorder the two pinned tabs
    6. Unpin github
    
- Actual result: twitter, the other pinned tab, disappears

- Expected result: it should not disapper

- Any related issues:

### LINKED ISSUE #10510: pinned tabs disappear until close/relaunch
## Test plan

https://github.com/brave/browser-laptop/pull/10531#issue-250554691

----

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
Using clean profile, if I pin a couple of sites from new tabs, reorder, and then 'reuse' the about:welcome tab and pin a site, the previously pinned sites disappear until close/relaunch.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
found with 0.18.22, exists in 0.18.14 also.

- Steps to reproduce:
    1. Clean profile
    2. launch Brave
    2. Don't close or use either of the tabs. Leave as is.
    3. Open a new tab
    3. visit a site
    3. pin the tab
    4. Open another new tab
    4. visit a different site,
    4. pin the tab
    4. Move this tab to the first position.
    5. Click on the about:welcome tab.
    5. Change the URL to a different site.
    6. Pin this tab.
    7. two previously pinned tabs are not displayed.
    
- Actual result:
Previously pinned tabs are not displayed. Must close/relaunch Brave to see them.

- Expected result:
Pinned tabs should not disappear.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
missingpinnedtabs

- Any related issues:

### PR DESCRIPTION
**Pull request by petemill**
Fixes #3760
Fixes #9635
Fixes #10037 
Fixes #10510

Possibly addresses: #10117 and #10179

The previous code resulted in tabs being marked as no longer required to be pinned, and closed prematurely. This happened because it maintained a 'cache' of pinned sites (as Immutable Maps), and was using `.equals` to the incoming list of sites. Whilst Immutable Map's `.equals()` (and `.is()`) compare properties of two Maps, the incoming objects are often not equal to the object seen in the past, even though it represents the same 'site'. For example, if we re-order a site, it will have a different Order property.

In these situations, when pinning a tab, all or some previously pinned tabs (ones that had any property change) would be closed. Sometimes this appeared like a 'crash' when the window closed because all the tabs had been (undesirably) closed.

Request review from those involved in Issues: @bsclifton @LaurenWags @luixxiul 

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
#### Case 1 (#9635)
Steps to reproduce:
- Clear the browser profile
- Open https://badssl.com
- Open 5 domains from https-everywhere to longextended...
- Pin all of them, including the parent tab
- Reorder them randomely
- Open a dashboard
- Click the twitter tile
- Pin the twitter tab
- [Should not] Crash!
- Restart the browser
- Confirm you have the pinned twitter page at the front of the pinned tabs row

#### Case 2 (#10037)
Steps to reproduce:
- Open github.com in a tab
- Open twitter.com in a new tab
- Pin github
- Pin twitter
- Reorder the two pinned tabs
- Unpin github
- [Previous] Actual result: twitter, the other pinned tab, disappears
- Expected result: it should not disapper

#### Case 3 (#10510)
- Clean profile
- launch Brave
- Don't close or use either of the tabs. Leave as is.
- Open a new tab
- visit a site
- pin the tab
- Open another new tab
- visit a different site,
- pin the tab
- Move this tab to the first position.
- Click on the about:welcome tab.
- Change the URL to a different site.
- Pin this tab.
- two previously pinned tabs are not displayed.
- [Previous] Actual result: Previously pinned tabs are not displayed. Must close/relaunch Brave to see them.
- Expected result: Pinned tabs should not disappear.

#### Automated Test:
Created new test - pinnedTabs -> Moving pinned tabs -> reorders pins without forgetting about them
Fails on _master_:
```
  1 failing

  1) pinnedTabs Moving pinned tabs reorders pins without forgetting about them:
     element ("[data-test-id="tab-area"][data-frame-key="3"] + [data-test-id="tab-area"][data-frame-key="2"] + [data-test-id="tab-area"][data-frame-key="5"]") still not existing after 10000ms
  Error
```

Succeeds with this PR:
```
  pinnedTabs
    Moving pinned tabs
      ✓ reorders pins without forgetting about them (3266ms)
```

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@petemill this will solve a lot of problems with pinned tabs, thank you. Can you please add some test coverage for this new code and use cases?

File: app/browser/windows.js [hunk 1]
```diff
@@ -62,51 +61,44 @@ const updateWindow = (windowId) => {
   }
 }
 
+const siteMatchesTab = (site, tab) => {
+  const matchesLocation = getLocationIfPDF(tab.get('url')) === site.get('location')
+  const matchesPartition = (tab.get('partitionNumber') || 0) === (site.get('partitionNumber') || 0)
```
Comment (diracdeltas) [inline app/browser/windows.js]: you could use Immutable's notSetValue parameter instead of `||`. https://facebook.github.io/immutable-js/docs/#/Map/get

**Comment by bsclifton** [comment]
Note to reviewers: let's see if this PR closes https://github.com/brave/browser-laptop/issues/9763

**Comment by petemill** [comment]
I'm pretty sure #9763 is a duplicate of #10510 and #9635 @bsclifton. #3760 is more generic about all the issues with losing pinned tabs and #10037 is about *un*pinning something and seeing the behavior, compared to the others which only mention steps to *pin*. But essentially they are caused by the same issue.

File: app/browser/windows.js [hunk 2]
```diff
@@ -62,51 +61,44 @@ const updateWindow = (windowId) => {
...
-        appActions.tabCloseRequested(tab.get('tabId'), true)
-      }
-      win.__alreadyPinnedSites = win.__alreadyPinnedSites.remove(site)
-    })
+    }
+  }
+  for (const tab of pinnedTabs.values()) {
+    const shouldBePinned = tabsWithSites.has(tab)
+    if (!shouldBePinned) {
+      appActions.tabCloseRequested(tab.get('tabId'), true)
```
Comment (darkdh) [inline app/browser/windows.js]: In what case will require us to manually close tab?

Comment (petemill) [reply app/browser/windows.js]: @darkdh this happens when you have > 1 window open, you then unpin a tab in window 1. This code calls upon window 2+ to close the previously-pinned tab. Whether or not this is what we want to happen I guess is beyond the scope of this bug fix, since that is the previous functionality. I myself have noticed some edge-cases that could end up with losing user webview state in a tab, but I'll log a separate issue for that...

**Comment by petemill** [comment]
@NejcZdovc I added more info about what caused this bug - it's the fact that the previously-pinned sites were being stored as Immutable Maps, which were then equality compared to the incoming updated list. Often, the same site would not match one in the 'cache', because some other property changed (such as the `order` after re-ordering the pinned tabs).

I'm in the process of adding a webdriver test for this case.

**Comment by petemill** [comment]
Test added and described in description. Ready for next round of review.

File: app/common/lib/pinnedSitesUtil.js [hunk 3]
```diff
@@ -110,13 +110,16 @@ const getKey = (siteDetail) => {
   if (!siteDetail) {
     return null
   }
+  const location = siteDetail.get('location')
+  const partitionNumber = siteDetail.get('partitionNumber', 0)
+  return getKeyFromLocation(location, partitionNumber)
+}
 
-  let location = siteDetail.get('location')
+const getKeyFromLocation = (location, partitionNumber) => {
```
Comment (NejcZdovc) [inline app/common/lib/pinnedSitesUtil.js]: Not sure why we need to move this in to the new function. You could just create Immutable.Map() in your test (as far as I can see is that the only place that you use it).

```
Immutable.fromJS({
  location: 'something',
  partitionNumber: 1
})
```

Comment (petemill) [reply app/common/lib/pinnedSitesUtil.js]: @NejcZdovc the aim here was to avoid having 2+ separate places where this format of string 'key' for pinned tabs is defined (`${location}|${parititionNumber}`). The action `onPinnedTabReorder` requires this key, the generation of which which was previously hidden inside another function.
Here, I expose the `getKey` function from one place, so that if we want to change that format (perhaps introduce a new property, or change the separator charactor, etc) it is controlled by a single function.
Now that I've explained the why, I'm happy to change it - maybe I can get it from the existing state, or the DOM, or something...  ☺️

Comment (NejcZdovc) [reply app/common/lib/pinnedSitesUtil.js]: Do we have it defined in two places? :smiley: I am not aware of it. For pinnedSites we have only one getKey and format AFAIK

Comment (petemill) [reply app/common/lib/pinnedSitesUtil.js]: Well there would be if I added a new place here 😀 , but I've taken your advice and instead made copies of the 'SiteDetail' structure the original function requires.

**Comment by diracdeltas** [comment]
some of the pinned tab tests are failing but i don't know offhand if they are intermittent failures. i'll restart the travis job. https://travis-ci.org/brave/browser-laptop/jobs/269271637#L3819-L3843

**Comment by bridiver** [comment]
this seems highly likely to conflict with @bbondy's changes

File: app/browser/windows.js [hunk 4]
```diff
@@ -62,51 +61,44 @@ const updateWindow = (windowId) => {
...
+    } else {
+      // if it's not already pinned, create new pinned tab
+      appActions.createTabRequested({
+        url: site.get('location'),
+        partitionNumber: site.get('partitionNumber'),
+        pinned: true,
+        active: false,
+        windowId
       })
-
```
Comment (bsclifton) [inline app/browser/windows.js]: This is definitely a lot easier to read; so basically we're just comparing the sites entries to the pinned tab app state.
- entries in sites AND app state are **removed** (they already exist)
- entries in sites and NOT in app state are **created**
- entries NOT in sites which are in app state are **closed**

File: app/browser/windows.js [hunk 5]
```diff
@@ -62,51 +61,44 @@ const updateWindow = (windowId) => {
...
-  const sitesToAdd = pinnedSites.filter((site) =>
-    !win.__alreadyPinnedSites.find((pinned) => pinned.equals(site)))
```
Comment (bsclifton) [inline app/browser/windows.js]: so this here was the actual bug; comparing site entries from `pinnedSites` to the ones in `__alreadyPinnedSites`

Comment (petemill) [reply app/browser/windows.js]: Yes, though mainly on the previous L100 when determining which should be closed. The bug could have been remedied by hacking that line, but the __alreadyPinnedSites cache wasn't helping much and was growing in size on each call because of L82, so seemed better to rewrite.

**Comment by petemill** [comment]
Thanks all for your review and thanks @bsclifton for adding new unit tests for that module!
