### PR TITLE
Fixes urlBarSuggestions test

### LINKED ISSUE #6980: Automated test failure on urlBarSuggestions
**Describe the issue you encountered:**

https://travis-ci.org/brave/browser-laptop/builds/197222628#L4676

- [ ]  6) urlBarSuggestions selection is not reset when pressing non-input key:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("#urlInput") - brave.js:428:23

- Any related issues: #6828 #6408

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #6980

## Auditors
@bsclifton

## Test Plan
- `npm run uitest -- --grep="urlBarSuggestions"`

### CODE REVIEW

File: test/components/urlBarSuggestionsTest.js [hunk 1]
```diff
@@ -108,11 +108,12 @@ describe('urlBarSuggestions', function () {
   })
 
   it('selects a location auto complete result but not for titles', function * () {
-    const page2Url = Brave.server.url('page2.html')
     yield this.app.client
       .setValue(urlInput, 'http://')
       .waitUntil(function () {
-        return this.getValue(urlInput).then((val) => val === page2Url)
+        return this.getValue(urlInput).then(function (val) {
```
Comment (NejcZdovc) [inline test/components/urlBarSuggestionsTest.js]: I needed to remove `page2Url`, because we are no suggesting shorter url's #7534

File: test/components/urlBarSuggestionsTest.js [hunk 2]
```diff
@@ -150,11 +151,16 @@ describe('urlBarSuggestions', function () {
 
   it('selection is not reset when pressing non-input key', function * () {
```
Comment (bsclifton) [inline test/components/urlBarSuggestionsTest.js]: this test always fails when I run `npm run uitest -- --grep="urlBarSuggestions"`... but passes when it's by itself

Comment (NejcZdovc) [inline test/components/urlBarSuggestionsTest.js]: Ok this is failing, because your history would be different. I reset now history before the test
