### PR TITLE
Responsive tab / refactor to Aphrodite

### LINKED ISSUE #100: Tabs don't resize with window
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

Steps to reproduce:
1. Open Brave and maximize it
2. Keep creating tabs until you reach 6
3. Tabs will finally resize for the window

Not sure what the correct behavior should be here with a fixed number of tabs. Currently they only expand to fit the window size when there are 6 in the tab group. Maybe they should always fit the window width and get smaller until they max out at 6? @bradleyrichter ?

### LINKED ISSUE #1776: Audio indicator on/off button
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

youtube

You have to change where to click in order to mute and unmute audio

## Test plan

1. Play a youtube video
2. Click the indicator to mute
3. Click the same place to unmute

### LINKED ISSUE #5431: Disable close button on tabs if tab size is too small
## Test plan

Under "QA steps" on https://github.com/brave/browser-laptop/pull/7799#issue-215652883

----

**Describe the issue you encountered:** if you click the close button of tab whose size is too small, sometimes you click the close button accidently.

**Expected behavior:** Disable close button on tabs if tab size is too small.

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.8 RC1 

- Steps to reproduce:
    1. Open many tabs
    2. Minimize the width of the window
    3. Select any tab carefully not to close it...

- Screenshot if needed:

clipboard01

- Any related issues:

### LINKED ISSUE #6511: Session tab/private tab icon and text is too spaced out
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Session tab/private tab icon and text is too spaced out

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	0c7a64d

- Screenshot if needed:
0.13.0 vs 0.12.15
image

- Any related issues: #5936

### LINKED ISSUE #6845: tab icons are not constrained to actual tab space
## Test plan

https://github.com/brave/browser-laptop/pull/6900#issue-203781822

<hr>

- Did you search for similar issues before submitting this one?
yes

- Describe the issue you encountered:
when opening a private tab then opening the developer's console, it was found that the icons were overhanging the tab.

this also happened when the number of tabs per set was 20

- Platform (Win7, 8, 10? macOS? Linux distro?):
tested on os x

- Brave Version (revision SHA):
0.13.0 rc5

- Steps to reproduce:
    1. open the max set of tabs per default set (10)
    2. for the last tab in the set, make it a private tab
    3. open the developer console (fn + shift + f8 on mac)
    
- Actual result:
the tab icons extend beyond the tab space

- Expected result:
tab icons should be constrained to the tab space

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no, the current version is close, but constrained to the tab appropriately 
screen shot 2017-01-24 at 10 30 18 pm

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
screen shot 2017-01-24 at 10 16 12 pm
screen shot 2017-01-24 at 10 12 36 pm

- Any related issues:

### PR DESCRIPTION
**Pull request by cezaraugusto**
## Test plan

* Tabs should have a cohesive/pleasant UI with no inconsistent icon alignment/overflow.
* Tabs should be responsive: resizing them should update each icon to fit its container.
* Action of mute/unmute audio icon shouldn't change mouse position for each toggle.

## Automated tests
Covered by automated tests
```
npm run test -- --grep="tabContent components"
```

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bsclifton, @bbondy

/cc @bradleyrichter

Fix #5431
Fix #6511
Fix #6845
Fix #1776
Fix #100

### CODE REVIEW

**Comment by cezaraugusto** [comment]
For reference, @bradleyrichter reported some improvements here: https://github.com/brave/browser-laptop/pull/5918#issuecomment-275538813

**Comment by luixxiul** [comment]
There is a lot of errors which seems to me to be related with the changes: https://travis-ci.org/brave/browser-laptop#L4778

@cezaraugusto will you please check them out? From 35 to 57.

**Comment by bbondy** [comment]
moving to 0.13.2, will consider moving back if tests are fixed up in time. Thanks.

**Comment by bsclifton** [comment]
Once ready, this may also fix https://github.com/brave/browser-laptop/issues/6845

**Comment by cezaraugusto** [comment]
@bsclifton thanks added to PR description

**Comment by cezaraugusto** [comment]
Updated with test fixes.

The above are intermittent, but passed locally:

npm run test -- --grep="remembers findbar input when switching frames"
npm run test -- --grep="shows no tab pages when you have only 1 page"
npm run test -- --grep="Retains user input on tab switches"

File: app/renderer/components/styles/tab.js [hunk 1]
```diff
@@ -0,0 +1,126 @@
+/* This Source Code Form is subject to the terms of the Mozilla Public
+ * License, v. 2.0. If a copy of the MPL was not distributed with this file,
+ * You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+const {StyleSheet} = require('aphrodite')
+const globalStyles = require('./global')
+
+const styles = StyleSheet.create({
```
Comment (bsclifton) [inline app/renderer/components/styles/tab.js]: Really well done here! 😄  This is perfect

File: app/renderer/components/styles/global.js [hunk 2]
```diff
@@ -133,6 +143,19 @@ const globalStyles = {
     zindexSuggestionText: '3100',
     zindexWindowFullScreen: '4000',
     zindexWindowFullScreenBanner: '4100'
+  },
+  fontSize: {
+    tabIcon: '14px',
+    tabTitle: '12px'
+  },
+  appIcons: {
```
Comment (bsclifton) [inline app/renderer/components/styles/global.js]: 👌

File: app/common/lib/platformUtil.js [hunk 3]
```diff
@@ -42,3 +42,8 @@ module.exports.isWindows = () => {
   return process.platform === 'win32' ||
     navigator.platform === 'Win32'
 }
+
+module.exports.isLinux = () => {
+  return !module.exports.isDarwin() &&
+    !module.exports.isWindows()
+}
```
Comment (bsclifton) [inline app/common/lib/platformUtil.js]: this is perfect! For anyone else looking at this... I believe this is the best way because there could be many variations of `navigator.platform` for Linux. We can't rely on process.platform because this code is often invoked in the renderer (like in this PR)

**Comment by luixxiul** [comment]
I moved the `QA/steps-specified` label to the 3 issues which should be solved with this PR.

**Comment by cezaraugusto** [comment]
Updated after https://github.com/brave/browser-laptop/pull/6900#pullrequestreview-19177261 regarding sequential tab closing issue.

File: js/components/tab.js [hunk 4]
```diff
@@ -148,48 +161,69 @@ class Tab extends ImmutableComponent {
...
+  }
+
+  componentWillMount () {
+    this.onUpdateTabSize()
+  }
 
-    const locationHasFavicon = this.props.tab.get('location') !== 'about:newtab'
+  componentDidMount () {
+    // Execute resize handler at a rate of 15fps
+    window.addEventListener('resize', throttle(this.onUpdateTabSize, 66))
```
Comment (bsclifton) [inline js/components/tab.js]: This 66 magic number may make more sense as a constant in `tabUtil.js`

File: js/stores/windowStore.js [hunk 5]
```diff
@@ -353,6 +354,19 @@ const doAction = (action) => {
         updateTabPageIndex(frameStateUtil.getActiveFrame(windowState))
         windowState = windowState.deleteIn(['ui', 'tabs', 'fixTabWidth'])
       }
+
+      const nextFrame = frameStateUtil.getFrameByIndex(windowState, index)
+
+      // Copy the hover state if tab closed with mouse
+      // This allow us to have closeTab button visible
+      // for sequential frames closing, until onMouseLeave event happens.
+      if (hoverState) {
```
Comment (bsclifton) [inline js/stores/windowStore.js]: you may also want to check nextFrame; like `if (hoverState && nextFrame) {`

File: less/tabs.less [hunk 6]
```diff
@@ -68,121 +55,6 @@
...
-    &:hover {
-      opacity: 1;
-    }
-
-    border: 0px solid white;
-    border-radius: 50%;
-    z-index: @zindexTabs;
-  }
-}
-
```
Comment (bsclifton) [inline less/tabs.less]: Seeing all this deleted is beautiful! 😄

**Comment by bsclifton** [comment]
@bbondy did you want to give this one a go? I think you'll like it 😄

**Comment by bbondy** [comment]
wow this is very awesome @cezaraugusto, nice work.

**Comment by bsclifton** [comment]
@cezaraugusto need your help with 2 things 😄 
- For each of the issues listed, can you please put the test plan at the top of each issue?
- I noticed two failing tests (broken selectors?).  They may not be related, but help looking into them is appreciated 😄 
```
npm run test -- --grep="navigationBar tests submit page that does not load resets URL to previous location if page does not load"

npm run test -- --grep="tab pages basic tab page functionality tabs per page setting takes effect immediately"
```

**Comment by cezaraugusto** [comment]
@bsclifton failing tests not related to selector. Failing on master as well.

```npm run test -- --grep="navigationBar tests submit page that does not load resets URL to previous location if page does not load```

Searches for `activeWebview`, which was not modified.

```
npm run test -- --grep="tab pages basic tab page functionality tabs per page setting takes effect immediately"
```

Test is described inside `basic tab page functionality`, and the only selector which was modified is on `before()` action, but other tests wrapped there passes as well, so I don't think it's related. It's also failing on master as well.

Also updated target issues with test plan pointing for this PR top comment.

**Comment by bsclifton** [comment]
Looks like we have navigationBar failures tracked here https://github.com/brave/browser-laptop/issues/6666

And tab failures tracked here: https://github.com/brave/browser-laptop/issues/6981

Since the rest passed (and these are happening in master), I'll go ahead and merge.  Thanks for updating the issues 😄
