### PR TITLE
Notify users when contribution date is pushed back

### LINKED ISSUE #14000: Notify user why contribution is pushed back (30 minute min browsing time)
### Description

We want to display some notification on payments page, when contribution is due, but min browse time is not meet.

### Steps to Reproduce

  1. Enable payments
  2. Visit one site for few minutes
  3. Change reconcile stamp so that you trigger contribution

**Actual result:**

User contribution date was pushed back

**Expected result:**
We should notify user why contribution was pushed back for 3 days.

**Reproduces how often:**

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #14000

new notification
image

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
1) add one site to the ledger table (with time spent less then 30min)
2) add funds
3) close browser and change reconcile stamp to yesterday
4) make sure that date is pushed back for 3 days from the stamp that you set and that you see notification as is shown in the print screen (it can be pushed back for 6 days after restart)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by jasonrsadler** [comment]
The push back notification is delayed if the browser starts with the payments screen open:
screen shot 2018-05-07 at 10 10 29 am

Waited approximately 2 minutes for the switchover:
screen shot 2018-05-07 at 10 12 38 am

Let me know if this is intended.

**Comment by jasonrsadler** [comment]
@bradleyrichter for wording

**Comment by NejcZdovc** [comment]
Updated text based on @bradleyrichter feedback

File: js/constants/appConstants.js [hunk 1]
```diff
@@ -192,6 +192,7 @@ const appConstants = {
   APP_ON_LEDGER_PIN_PUBLISHER: _,
   APP_ON_LEDGER_NOTIFICATION_INTERVAL: _,
   APP_ON_LEDGER_MEDIA_DATA: _,
+  APP_ON_FUZZING: _,
```
Comment (ryanml) [inline js/constants/appConstants.js]: Could this be changed to something like `APP_ON_LEDGER_FUZZING`?

File: js/actions/appActions.js [hunk 2]
```diff
@@ -1981,6 +1981,13 @@ const appActions = {
     })
   },
 
+  onFuzzing: function (newStamp) {
```
Comment (ryanml) [inline js/actions/appActions.js]: Following other comment, maybe this should be `onLedgerFuzzing`

File: js/constants/appConstants.js (hunk 1 above)
Comment (NejcZdovc) [reply js/constants/appConstants.js]: done

File: js/actions/appActions.js (hunk 2 above)
Comment (NejcZdovc) [reply js/actions/appActions.js]: done

File: app/browser/reducers/ledgerReducer.js [hunk 3]
```diff
@@ -503,6 +503,15 @@ const ledgerReducer = (state, action, immutableAction) => {
         state = ledgerApi.onFetchReferralHeaders(state, action.get('error'), action.get('response'), action.get('body'))
         break
       }
+    case appConstants.APP_ON_LEDGER_FUZZING:
+      {
+        state = ledgerState.setAboutProp(state, 'status', ledgerStatuses.FUZZING)
```
Comment (ryanml) [inline app/browser/reducers/ledgerReducer.js]: Should we set this prop after `newStamp` has been validated on line `510`?

Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: I think that as soon as fuzzing is triggered we should display notification, even if something was not send over correctly. wdyt?

File: app/browser/api/ledger.js [hunk 4]
```diff
@@ -2386,6 +2386,10 @@ const onInitRead = (state, parsedData) => {
   return state
 }
 
+const onFuzzing = () => {
+  appActions.onLedgerFuzzing(client.state.reconcileStamp)
```
Comment (jasonrsadler) [inline app/browser/api/ledger.js]: Check for client.state != null

File: app/browser/reducers/ledgerReducer.js (hunk 3 above)
Comment (ryanml) [reply app/browser/reducers/ledgerReducer.js]: That sounds fine yeah, I just assumed that if the check failed the process to that point would be so quick it may not be worth it.

File: app/browser/api/ledger.js (hunk 4 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: null check added

**Comment by NejcZdovc** [comment]
master bced563
0.23 ef994a799
0.22-release3 187f889ab
