### PR TITLE
Bloodhound for URL bar suggestions & move suggestions to browser process

### LINKED ISSUE #5878: URL bar selects autocomplete result on keypress
**Did you search for similar issues before submitting this one?**
I only did a quick search, there may already be an issue (help appreciated finding)

**Describe the issue you encountered:**
Auto-complete results are being chosen when I'm doing a very specific set of key presses when focus is in the URL bar (see steps to repro).

I found this when trying my default logic for copy/paste, which is stupid now that I'm typing it out... but it did uncover this.  If you instead use cmd + A to select the contents of the URL bar (instead of what is outlined in step 3), it does work and you can cmd + C it just fine (which is more efficient anyways)

**Expected behavior:**
Auto-complete result should not be picked unless I use up/down arrow

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version:
0.12.10

- Steps to reproduce:
    1. Visit https://www.oediscountparts.com/partlocator/index.cfm?siteid=215242
    2. Click inside the URL bar to give it focus and delete the path portion of the URL
      - Hit end (windows) or cmd + right arrow (mac) to move cursor to end
      - hold shift and the modifier key (either ctrl on windows or option on mac) and press left arrow key repeatedly, until you've selected `/partlocator/index.cfm?siteid=215242`
      - Press delete or backspace to remove that part
    3. Try to select the rest of whats left
      - hold shift + modifier key (cmd / ctrl) and then press left arrow key
      - notice that the first result is auto-selected (which then overrides the URL you had in the box)

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #7453: Performance : urlbar response is slow when searching across many bookmarks
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
After importing a large number of bookmarks, the urlbar response becomes considerably slow. It was found that bookmarks suggestions was the controlling factor.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.5 (https://github.com/brave/browser-laptop/commit/0e683420964546ac26a8c2903ef871a35a6e71d8)

- Steps to reproduce:
    1. With a clean session, try to visit reddit.com, add a couple bookmarks
    2. Import a large number of bookmarks
    3. With a new tab, try to visit reddit.com
    
- Actual result:
The urlbar becomes considerably laggy.

- Expected result:
The urlbar should be at least as responsive as if the bookmarks were not there. That is, a user should not be penalized for trying to visit a domain root when they have bookmarks to deeper links.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

[2017-03-02 09-52-15.mp4.zip](https://github.com/brave/browser-laptop/files/814365/2017-03-02.09-52-15.mp4.zip)

- Any related issues:

### PR DESCRIPTION
**Pull request by bbondy**
This PR does several things:
- Makes suggestions code independent of window renderer
- Moves URL bar suggestion creating into the browser process
- Creates a wrapper lib for bloodhound autocomplete results for bookmarks and history
- Uses that wrapper lib instead of using indexOf for faster autocomplete results.
- Moves several windowActions around url bar suggestions into app actions and stops naming them set*
- Dispatcher with queryInfo of windowId specified will now always route to the browser process, before it would skip that if the window renderer was routing an app action to itself.  The browser process in that case will not re-dispatch to the window process.
- Various other perf and refactoring improvements.

Fix #7453
Fix #5878
Fix https://github.com/brave/browser-laptop/issues/8919

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Better to not rebase in this case, changes are very cleanly defined in various small refactors leading up to using bloodhound for URL suggestions in the browser process.

Test Plan:
- Test around search options in preferences to make sure they work like they used to
- Import lots of history and bookmarks and make sure it's still snappy to get suggestions
- Make sure google.com shows up first when typing google.com
- Make sure things work at least as good as before in terms of getting results you wanted when typing.
- **QA team:** please do a full pass around URL bar suggestions, try to find things that don't work as expected but used to work before.  Please post follow ups for found things within the context of the same .300 milestone.  Please avoid posting things that have always worked that way in previous versions though.

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run indivually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)

### CODE REVIEW

File: js/actions/appActions.js [hunk 1]
```diff
@@ -1337,6 +1337,21 @@ const appActions = {
       hostPattern: origin,
       key: 'savePasswords'
     })
+  },
+
+  /**
+   * Indicates that the urlbar text has changed, usually from user input
+   *
+   * @param {string} location - The text to set as the new navbar URL input
```
Comment (bsclifton) [inline js/actions/appActions.js]: docs need updating to include the windowId / input fields

Comment (bsclifton) [inline js/actions/appActions.js]: derp- this is an individual commit, will go back to looking at the all files changed view 😛  Disregard

**Comment by bsclifton** [comment]
I think this issue is fixed: https://github.com/brave/browser-laptop/issues/5761

**Comment by bsclifton** [comment]
The weird behavior I noticed with TAB has been logged as a separate issue: https://github.com/brave/browser-laptop/issues/8919

File: app/renderer/components/navigation/urlBarSuggestions.js [hunk 2]
```diff
@@ -36,12 +38,12 @@ class UrlBarSuggestions extends ImmutableComponent {
 
   render () {
     const suggestions = this.props.suggestionList
-    const bookmarkSuggestions = suggestions.filter((s) => s.type === suggestionTypes.BOOKMARK)
-    const historySuggestions = suggestions.filter((s) => s.type === suggestionTypes.HISTORY)
-    const aboutPagesSuggestions = suggestions.filter((s) => s.type === suggestionTypes.ABOUT_PAGES)
-    const tabSuggestions = suggestions.filter((s) => s.type === suggestionTypes.TAB)
-    const searchSuggestions = suggestions.filter((s) => s.type === suggestionTypes.SEARCH)
-    const topSiteSuggestions = suggestions.filter((s) => s.type === suggestionTypes.TOP_SITE)
+    const bookmarkSuggestions = suggestions.filter((s) => s.get('type') === suggestionTypes.BOOKMARK)
```
Comment (bsclifton) [inline app/renderer/components/navigation/urlBarSuggestions.js]: Would it be better to just iterate `suggestionList` once (ex: w/ a forEach) and use a switch to push results onto empty array?

**Comment by bsclifton** [comment]
Food for thought (while it's fresh 😄 ): these improvements could be used to show more relevant results (and also in a more efficient way) for the new tab dashboard.  For more info, see https://github.com/brave/browser-laptop/issues/5338

File: app/sessionStore.js [hunk 3]
```diff
@@ -658,7 +658,8 @@ module.exports.defaultAppState = () => {
     httpsEverywhere: {
       count: 0
     },
-    defaultWindowParams: {}
+    defaultWindowParams: {},
+    searchDetail: null
```
Comment (bsclifton) [inline app/sessionStore.js]: don't forget to add to state.md 😄

File: docs/appActions.md [hunk 4]
```diff
@@ -1023,6 +1023,18 @@ Notifies autoplay has been blocked
 
 
 
+### savePassword()
```
Comment (bsclifton) [inline docs/appActions.md]: Would these be better named as `passwordSaved` / `passwordUpdated`? (to be more consistent with others that you introduced, like urlBarTextChanged)

**Comment by bsclifton** [comment]
Other than the comments above, code and tests look great 😄  I'll keep poking at it for a bit and will post any findings 👍

File: app/renderer/components/navigation/urlBarSuggestions.js (hunk 2 above)
Comment (bbondy) [inline app/renderer/components/navigation/urlBarSuggestions.js]: That would be better but not introduced in this commit so leaving as is for now. The right way is to store it separately in state so no filter is needed at all.

File: app/sessionStore.js (hunk 3 above)
Comment (bbondy) [inline app/sessionStore.js]: done, good catch.

File: docs/appActions.md (hunk 4 above)
Comment (bbondy) [inline docs/appActions.md]: This is actually only showing up because I fixed javadoc comment block on some of anthony's actions.  It's not introduced here.

**Comment by srirambv** [comment]
Bookmark items are not listed when `Show history matches` is enabled. Disabling it brings up the `Show bookmark matches` in the suggested items
bloodhound

**Comment by srirambv** [comment]
Auto complete search term shows complete URL as suggested search term. Selecting doesn't load the site rather searches for the URL.
autosearch
