### PR TITLE
increase version range for pinnedTopSites cleanup

### LINKED ISSUE #12941: top site tiles not being populated when updating profile from 0.19.147
## Test plan

https://github.com/brave/browser-laptop/pull/12968#issue-293390058

----

### Description
I have a profile that I was using with version 0.19.147 which encountered issue https://github.com/brave/browser-laptop/issues/12027 (to the degree that I only have one (default, pinned) top site tile). When this profile was updated to 0.20.27 and I began to browse, I noticed my top site tiles were not being populated.

### Steps to Reproduce

  1. Have a profile from 0.19.x that is missing top site tiles due to https://github.com/brave/browser-laptop/issues/12027
  2. Update profile to 0.20.27.
  3. Open a new tab, note you still have the one (default, pinned) top site tile.
  4. Browse normally (visit some sites in new tabs, etc). 
  5. Open another new tab.

**Actual result:**
No new top site tiles added, only the default, pinned top site tile is displayed:
screen shot 2018-01-30 at 6 14 57 pm

**Expected result:**
Additional top site tiles should appear based on your browsing.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.27
V8 | 6.4.388.40
rev | 76102c5
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
n/a

### Additional Information
Missed when testing https://github.com/brave/browser-laptop/issues/12027

### PR DESCRIPTION
**Pull request by cezaraugusto**
Different fixes were tried for this but all needed to iterate over the list to check for duplicates and ended bulking startup time.

This fix is the same take as previous with a wider range of versions. This is better for performance as it does not iterate over the list on startup/every pin interaction but instead cleans the state at update time so no user-space affected.

fix #12941

## Test Plan:

1. Hack your session-store-1 adding a few duplicated objects inside pinnedTopSites list.
2. Run Brave
3. Quit
4. Check session-store-1 file again. There should be no duplicates
5. Run Brave again. There should be no pinned top sites

## Test Plan (QA specific):

1. Install 0.19.x - have a bunch of top sites
2. Upgrade to 0.20.30 which doesn't have the fix. Verify still broken
3. Update to this release (0.22.x) and verify issue is now fixed

### CODE REVIEW

**Comment by bsclifton** [comment]
@cezaraugusto besides the dupes, this should fix folks who missed your fix (fixing their top sites).

Did we want to capture that scenario in the test plan? ex: 
1. Install 0.19.x - have a bunch of top sites
2. Upgrade to 0.20.30 which doesn't have the fix. Verify still broken
3. Update to this release and verify issue is now fixed

File: app/sessionStore.js [hunk 1]
```diff
@@ -845,11 +845,17 @@ module.exports.runPreMigrations = (data) => {
...
         delete data.cache.bookmarkLocation
       }
+    }
+
+    // pinned top sites were stored in the wrong position in 0.19.x
+    // and on some updates ranging from 0.20.x/0.21.x
+    // allowing duplicated items. See #12941
+    let pinnedTopSitesCleanup = false
+    try {
+      pinnedTopSitesCleanup = compareVersions(data.lastAppVersion, '0.22.00') < 1
```
Comment (bsclifton) [inline app/sessionStore.js]: should we have another check for this, so it only runs once? Specifically we could capture this in the state in an area called "migrations" (which was removed with https://github.com/brave/browser-laptop/commit/ccee1223cbe565c546b6f103b661ae749bc85971#diff-b4e400e260f324745d12616a8c9c1fc6L377 since nothing else is using it).  You could basically store the timestamp this was ran on and default the value to undefined

Comment (bsclifton) [reply app/sessionStore.js]: Also, note to self: we'll want to update this version before we ship. We might want to create an issue to track that

**Comment by cezaraugusto** [comment]
re https://github.com/brave/browser-laptop/pull/13429#issuecomment-372915466 I included your take (thanks) in the test plan. Most users did receive the fix, this PR specifically target all of them and unless someone manages to update from 0.19.x to something >0.22.00, all users should get this fix.

**Comment by bsclifton** [comment]
master 9e91ffefe9e60585c81cd3dd553d4273c3e37c34
0.23.x 23e50ad013a1626b234a877aad1cbad5c896e0d7
0.22.x f1d4f722cc61cfc6cf4f332b567d2b2b3cc0983e
