### PR TITLE
fix syncing error when lastAccessedTime is empty

### LINKED ISSUE #8552: Crash on startup (possibly related to recovering tabs)
- Did you search for similar issues before submitting this one? Yes.

- Describe the issue you encountered: Upon launching the browser, it appears briefly, attemtping to re-load previously tabs and then immediately closes.

If ran through the terminal, I receive the following error.

```
jordan@azurite:~$ brave
Crash reporting enabled
ledger balance warning: {
  "message": "Blockonomics: undefined"
}
[8923:8923:0428/154813.756756:ERROR:CONSOLE(18783)] "(node) warning: possible EventEmitter memory leak detected. %d listeners added. Use emitter.setMaxListeners() to increase limit.", source: chrome://brave/usr/share/brave/resources/app.asar/app/extensions/brave/gen/app.entry.js (18783)
Warning: Can't create site data: {"order":1207,"count":15,"partitionNumber":0,"location":"https://parsecpizzadelivery.com/","title":"Parsec Pizza Delivery trailer - A pixelated deliver 'em up","tags":[],"objectId":[0,63,197,156,48,17,112,109,247,175,79,57,151,123,29,198],"themeColor":"rgb(5, 5, 5)"}
An uncaught exception occurred in the main process Uncaught Exception:
Error: Can't create JS from existingObject! [object Object]
    at Object.module.exports.getExistingObject (/usr/share/brave/resources/app.asar/js/state/syncUtil.js:259:11)
    at records.map (/usr/share/brave/resources/app.asar/app/sync.js:379:39)
    at Array.map (native)
    at EventEmitter.ipcMain.on (/usr/share/brave/resources/app.asar/app/sync.js:375:47)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
/usr/share/brave/resources/app.asar/node_modules/node-anonize2-relic-emscripten/anonize2-jumbo.js:67
            throw ex
            ^

Error: Can't create JS from existingObject! [object Object]
    at Object.module.exports.getExistingObject (/usr/share/brave/resources/app.asar/js/state/syncUtil.js:259:11)
    at records.map (/usr/share/brave/resources/app.asar/app/sync.js:379:39)
    at Array.map (native)
    at EventEmitter.ipcMain.on (/usr/share/brave/resources/app.asar/app/sync.js:375:47)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:204:7)
    at WebContents.<anonymous> (/usr/share/brave/resources/electron.asar/browser/api/web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```

- Platform (Win7, 8, 10? macOS? Linux distro?): Linux - Ubuntu 16.04

- Brave Version (revision SHA): v0.15.0 (71fb730)

- Steps to reproduce: Unfortunately, I'm not certain on what precisely causes the browser to get into the state required to trigger this issue.
    
- Actual result: Browser crashes almost immediately after startup.

- Expected result: Browser does not crash and correctly recovers previously used tabs.

- Will the steps above reproduce in a fresh profile? If not what other info can be added? 

No. Renaming the `/home/username/.config/brave/session-store-1` file and starting the browser works fine, excluding the loss of your previous tabs & some browser settings.

- Is this an issue in the currently released version? Yes.

- Can this issue be consistently reproduced? No. As mentioned, I am uncertain what precisely causes the browser to get into the state required to trigger this issue. It is not related to a particular website unfortunately.

- Any related issues: This appears to occur shortly after a seemingly random crash of the browser, but I can not confirm if this is always the case.

### PR DESCRIPTION
**Pull request by diracdeltas**
fix #8552 

Test Plan: unittests and syncing tests should pass

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

### CODE REVIEW

File: js/state/siteUtil.js [hunk 1]
```diff
@@ -607,7 +607,7 @@ module.exports.isHistoryEntry = function (siteDetail) {
       // This is a Brave default newtab site
       return false
     }
-    return !!siteDetail.get('lastAccessedTime') && !isBookmarkFolder(siteDetail.get('tags'))
+    return !isBookmarkFolder(siteDetail.get('tags'))
```
Comment (ayumi) [inline js/state/siteUtil.js]: I think this change causes all bookmarks to show up as History items.
It might be that https://github.com/brave/browser-laptop/blob/master/app/common/lib/historyUtil.js#L19 is now returning every site not a bookmark folder.

Repro:
1. Start pyramid 0, enable Sync and visit archive.org and wikipedia.org
2. Start pyramid 1, join pyramid 0's sync group
3. Examine pyramid 1's history – it has the 2 sites.

Expected: Pyramid 1's history should be empty because history doesn't sync by default.

Comment (diracdeltas) [inline js/state/siteUtil.js]: oops, good catch

Comment (diracdeltas) [inline js/state/siteUtil.js]: Hm, actually I can't repro this. Did you start from fresh pyramids?

Comment (ayumi) [inline js/state/siteUtil.js]: i did

**Comment by diracdeltas** [comment]
@ayumi i may have fixed it

File: js/state/siteUtil.js [hunk 2]
```diff
@@ -600,14 +600,13 @@ module.exports.isImportedBookmark = function (siteDetail) {
...
+      module.exports.isDefaultEntry(siteDetail) ||
+      isBookmarkFolder(tags)) {
       return false
     }
-    if (module.exports.isDefaultEntry(siteDetail)) {
-      // This is a Brave default newtab site
-      return false
-    }
-    return !!siteDetail.get('lastAccessedTime') && !isBookmarkFolder(siteDetail.get('tags'))
+    return !!siteDetail.get('lastAccessedTime') || !tags || tags.size === 0
```
Comment (ayumi) [inline js/state/siteUtil.js]: @diracdeltas hmm that fixed half of it

try syncing to the `forsaken lindy ...` group. i see a lot of history items.

should this line be
```js
return !!siteDetail.get('lastAccessedTime') && (!tags || tags.size === 0)
```

Comment (diracdeltas) [inline js/state/siteUtil.js]: @ayumi yeah, that is more restrictive so i'll change it to `&&`

Comment (diracdeltas) [inline js/state/siteUtil.js]: @ayumi actually the crash was caused by a history entry which did not have `lastAccessedTime`, so changing it to `!!siteDetail.get('lastAccessedTime') && (!tags || tags.size === 0)` would cause it to crash again. 

when i sync to `forsaken...`, the synced bookmarks appear in `about:history`. this seems like the correct behavior to me because every bookmark is by definition also a history entry.

Comment (ayumi) [inline js/state/siteUtil.js]: i don't think there'd be a crash any more due to the change to downgrade the `throw` into `console.log`.

On bookmarks == history, I think that's not obvious to a user; so if I synced my bookmarks I'd expect history to be empty. It would only make sense if I understood the sites data model. However, this is how it currently happens in `master` so this is probably ok.

Comment (diracdeltas) [inline js/state/siteUtil.js]: @ayumi right, it would fix the crash, but I think the user's data was a valid history entry and should not be ignored by sync.

i think "make synced bookmarks not part of history" is a separate issue
