### PR TITLE
Using souceFrameIndex because new frame hasn't showed up in frames

### LINKED ISSUE #11070: Phantom Tab appears when middle clicking on a link with `Switch to new tabs immediately`
### Description
Sometimes when clicking a URL link in another application (like Slack) a phantom tab appears.

### Steps to Reproduce

1. Go to `about:preferences#tabs`
2. Turn on `Switch to new tabs immediately`
3. Go to any sites in new tab
4. Middle click on any links on the page
5. Go back to the tab in step 3
6. Middle click on any links on the page

**Actual result:**
kapture 2017-09-21 at 9 01 39

**Expected result:**
No phantom tab.

**Reproduces how often:** 
Unsure. I have not been able to repro yet but this was reported by @darkdh 

### Brave Version

**about:brave info:**
Brave | 0.19.12
rev | 063f110
Muon | 4.4.19

**Reproducible on current live release:**
no. cannot be reproduced in 0.18.36. 

### Additional Information
See https://github.com/brave/browser-laptop/issues/11070#issuecomment-332621681
Issue seems as though it was introduced with 0.19.7 because it cannot be reproduced with 0.19.6.

### PR DESCRIPTION
**Pull request by darkdh**
fix #11070

Auditors: @bbondy, @bsclifton

Test Plan: Covered by unittest

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: test/unit/app/renderer/reducers/frameReducerTest.js [hunk 1]
```diff
@@ -291,6 +291,18 @@ describe('frameReducer', function () {
         // Old index 2 moves 1 to the left
         assert.equal(this.newState.toJS().frames[1].tabId, windowState.toJS().frames[2].tabId)
       })
+      it('new frame has not showed up in frames', function () {
+        const action = {
+          actionType: appConstants.APP_TAB_UPDATED,
+          tabValue: {
+            tabId: 13,
+            index: 3,
+            title: 'Bondy Power!'
```
Comment (bbondy) [inline test/unit/app/renderer/reducers/frameReducerTest.js]: :trollface: :)

**Comment by bbondy** [comment]
0.19.x: f5baebab9d824f7bc750a3c7b8bcca322c29cea6
0.20.x: d0385117e387f37c241266d94d998f16246e5cab
master: 3597b81d3e60388c9a514ad77b1edbfb04239793
