### PR TITLE
Fix persistent permissions

### LINKED ISSUE #10957: notifications are not honouring users "Remember this decision"
**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Notifications are not honouring the users decision and will always prompt for permission even though "Remember this decision" has been selected. If you take a look at `about:preferences#security`, you can also see the decision being listed but not being honoured.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

Ubuntu 17.04 x64 - Reproduced
macOS 10.12.6 x64 - Reproduced
Win 10 Pro x86 - Reproduced
Win 10 Pro x64 - Reproduced

**- Brave Version (revision SHA):**

Brave: 0.18.35 rev: 7181ba3ff1fe32528f0a590cb4a3151ec824cfcc 
Muon: 4.3.22 
libchromiumcontent: 61.0.3163.79 

**- Steps to reproduce:**

1. Open Brave and visit https://browserleaks.com/geo
2. Once you get the notification, select "Remember my decision" and select "Allow"
3. Check about:preferences#security and you'll see the decision being correctly listed
4. Revisit the same page and you'll be prompted again
    
**- Actual result:**

"Remember my decision" not working and the permission notification will appear every single time.

**- Expected result:**

"Remember my decision" should honour the users decision.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

No, this is a new regression

**- Can this issue be consistently reproduced?**

Yes, 100% using the above STR.

**Example if issue:**

issue

### PR DESCRIPTION
**Pull request by bbondy**
This merge is only for 0.18.x, I'm going to cherry-pick the commit into brianJ's notification branch PR for 0.19.x.

Submitter Checklist:
 Fix #10957

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
  Already covered by this failing test:

 ```
    1) notificationBar permissions can accept permission request
    persistently:
         Promise was rejected with the following reason: timeout
 ```

- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Introduced here:
https://github.com/brave/browser-laptop/commit/c80b19015f66e9e40afc20d11892c66dcc0ffa82#diff-8a9bac13ef6264feb2b6da7c18d86b3c

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/filtering.js [hunk 1]
```diff
@@ -466,38 +467,44 @@ function registerPermissionHandler (session, partition) {
...
-        const result = !!(buttonIndex)
-        response[index] = result
-        if (persist) {
-          // remember site setting for this host
-          appActions.changeSiteSetting(origin, permission + 'Permission', result, isPrivate)
-        }
-        if (response.length === permissionTypes.length) {
-          permissionCallbacks[message] = null
-          cb(response)
+      const repsonseAutoAdded = responseSizeThisIteration !== response.length
```
Comment (bsclifton) [inline app/filtering.js]: whoops- s/repsonseAutoAdded/responseAutoAdded
