### PR TITLE
Fixes undefined scenarios

### LINKED ISSUE #11684: busyP errors when toggling payments off/on and leaving off
### Steps to Reproduce

1. launch 0.18.36 and enable payments via about:preferences#payments
2. visit several websites and ensure they're appearing under the ledger table
3. disable payments via the "On/Off" switch under about:preferences#payments
4. switch to 0.19.67 while using ledger_verbose=true
5. go to preferences and try to toggle payments on/off multiple times
6. leave toggle set to off for a minute or two

**Actual result:**
After leaving toggle off for a minute or two, 'busyP' errors will display, payments toggle will be stuck in off position. Additionally, @srirambv reported his entire browser was frozen after getting those errors.

**Expected result:**
No errors, toggle/browser should not freeze.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

### Brave Version

**about:brave info:**
Brave | 0.19.67
rev | b3a897e
Muon | 4.5.9

**Reproducible on current live release:**
no

### Additional Information

https://gist.github.com/LaurenWags/effdd07aa2d5eaf95e96064915111e86#file-busyp-txt-L1289

Found on MacOS, reproduced by @srirambv on Windows

### LINKED ISSUE #11703: Uncaught Exception: TypeError: ledgerClient is not a function while transition from .18.x to .19.x
### Description
Uncaught Exception: TypeError: ledgerClient is not a function while transition from .18.x to .19.x

### Steps to Reproduce

  1. Install 0.18.x, enable payments
  2. Upgrade to 0.19.67, wait for transition to wallet start
  3. Close the browser window after the update and relaunch from console
  4. Console logs error, but transition completes successfully, wallet doesn't get into bad state

**Actual result:**
```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: ledgerClient is not a function
    at fs.readFile (C:\Users\Sriram BV\AppData\Local\brave\app-0.19.67\resources\app.asar\app\browser\api\ledger.js:2358:21)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
```

**Expected result:**
Should not log error, transition should happen

**Reproduces how often:** [What percentage of the time does it reproduce?]
Initially noted by @kjozwiak and was able to reproduce consistently  , verified on Windows as well for the same behaviour 

### Brave Version

**about:brave info:**

Brave | 0.1836
-- | --
rev | 7ab85e9
Muon | 4.3.2

Brave | 0.19.67
-- | --
rev | b3a897e
Muon | 4.5.9

**Reproducible on current live release:**

### Additional Information
Not reproduce on macOS by @LaurenWags

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11703
Resolves #11684

Auditors:

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -2445,6 +2444,11 @@ const transitionWalletToBat = () => {
     return
   }
 
+  if (!client) {
+    console.log('client error')
```
Comment (cezaraugusto) [inline app/browser/api/ledger.js]: is this intentional? could be a `console.error` if so

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: Yes it's intentional. Because this is not really an error, it's just log that there was race condition and it' will be triggered again after another call

**Comment by bsclifton** [comment]
master 3bb444ebf2af28f80431a67948a36c220082f608
0.21.x 44ba335862b6225da6cddda77e481789ee6f68dd
0.20.x be52ec37d50ff9087122464b60a25b6f9fa27603
0.19.x 5e5bbb24ad61636a6d92751ccaaeb8d4a2beeb72
