### PR TITLE
Automated tests fixes and refactoring

### LINKED ISSUE #7950: Automated tests fixes
**Describe the issue you encountered**

### NavigationBar
 1) navigationBar tests submit page that does not load sets location to new URL:
     Promise was rejected with the following reason: timeout
  Error
  2) navigationBar tests auto open bookmarks toolbar for the first bookmark should remain hidden if user has bookmarks but has toolbar hidden:
     WaitUntilTimeoutError: element (#navigator .removeBookmarkButton) still not existing after 10000ms
      at isExisting("#navigator .removeBookmarkButton") - waitForExist.js:37:22

### About
1) Regular payment panel tests can setup payments "before each" hook for "shows welcome page":
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getUrl() - brave.js:725:4

### Autofill
 1) Autofill credit card autofills the credit card:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("[name="41ccnumber"]") - brave.js:455:23

  2) Autofill credit card autofills the credit card in a private tab:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("[name="41ccnumber"]") - brave.js:455:23

  3) Autofill credit card autofills the updated credit card when edited:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("[name="41ccnumber"]") - brave.js:455:23

  4) Autofill clear autofill data autofills the credit card:
     WaitUntilTimeoutError: Promise was rejected with the following reason: timeout
      at getValue("[name="41ccnumber"]") - brave.js:455:23

  5) Autofill ad-hoc autofill regular tab "before all" hook:
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

  6) Autofill ad-hoc autofill session tab "before all" hook:
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

  7) Autofill ad-hoc autofill private tab "before all" hook:
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

  8) Autofill ad-hoc autofill clear autocomplete data "before all" hook:
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

 9) Autofill autofill context menu "before each" hook for "hide when scroll":
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

### Findbar
1) findBar remembers findbar input when switching frames:
     NoSuchElement: An element could not be located on the page using the given search parameters.
      at element("[data-test-id="closeTabIcon"]") - click.js:12:17
      at elementIdClick("0.018681700734820783-7") - click.js:20:22

### Preferences
1) General Panel homepage multiple homepages direct input:
     RuntimeError: unknown error: devTools is not defined
      at execute(<Function>, true) - brave.js:485:19

### LINKED ISSUE #8061: Fix Standard.js lint errors
**Describe the issue you encountered:** Fix Standard.js lint errors.

Adding the priority/high label as the errors appear everytime on commit and makes it difficult to detect if errors are related with the commit which you are going to create.

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #7950
Closes #8061 

Changed from
image

to
image

### Auditors
@bsclifton @bbondy 

### Refactor

----

`waitForExist('X, Y, true)` -> `waitForElementCount(X, 0)`

----

```
.waitUntil(function () {
    return this.getText(X).then((val) => val === Y)
})
```
-> `waitForTextValue(X, Y)`

----

`isExisting(X).then((isExisting) => isExisting === false)` -> `waitForElementCount(X, 0)`

----

```
.waitUntil(function () {
        return this.getValue(X).then((val) => val === Y)
})
```
-> `waitForInputText(X, Y)`

----

`waitForVisible(X, Y, true)` -> `waitForElementCount(X, 0)`

----

### Note
In this PR I also added `BRAVE_TEST_COMMAND_LOGS=1` flag to Travis. This way we can see the problem easier and resolve it faster

**DO NOT SQUASH COMMITS**

### Test Plan
- `npm run test`

### CODE REVIEW

File: test/contents/autofillTest.js [hunk 1]
```diff
@@ -213,7 +213,7 @@ describe('Autofill', function () {
         .waitForTextValue('.creditCardPExpirationDate',
           (expMonth < 10 ? '0' + expMonth.toString() : expMonth.toString()) + '/' + expYear.toString())
     })
-    it('autofills the credit card', function * () {
+    it.skip('autofills the credit card', function * () {
```
Comment (luixxiul) [inline test/contents/autofillTest.js]: Update of https://github.com/brave/browser-laptop/issues/5389 is necessary I think.

Comment (NejcZdovc) [inline test/contents/autofillTest.js]: Thank you will do

**Comment by NejcZdovc** [comment]
@darkdh Because of standard I needed to add some brackets to this file `app/browser/ads/adBlockUtil.js`. Can you please double check if everything is still ok?

File: app/browser/ads/adBlockUtil.js [hunk 2]
```diff
@@ -31,16 +31,25 @@ const mapFilterType = {
...
-    mapFilterType[resourceType] !== undefined
+    (
+      resourceType !== 'mainFrame' &&
+      (
+        isThirdPartyHost(firstPartyUrl.hostname || '', url.hostname) ||
+        (
+          siteHacks[firstPartyUrl.hostname] &&
+          siteHacks[firstPartyUrl.hostname].allowFirstPartyAdblockChecks
+        )
+      ) &&
```
Comment (darkdh) [inline app/browser/ads/adBlockUtil.js]: I think this `)` should be in L39 so that `resourceType !== 'mainFrame'` only affect `isThirdPartyHost(firstPartyUrl.hostname || '', url.hostname)`

Comment (NejcZdovc) [inline app/browser/ads/adBlockUtil.js]: Thank you. Please verify the change

Comment (darkdh) [inline app/browser/ads/adBlockUtil.js]: lgtm now! Thanks for doing this 😉

**Comment by bsclifton** [comment]
@NejcZdovc ready for another rebase 😛

**Comment by NejcZdovc** [comment]
We have two tests that can be fixed easily because they can be reproduced, but I don't find what is wrong with it. It fails in `tabHandles()`. This are tests in `bravery-components` and `misc-components`.

cc @bbondy

**Comment by NejcZdovc** [comment]
@bsclifton rebased

File: js/stores/eventStore.js [hunk 3]
```diff
@@ -54,7 +54,7 @@ const addPageView = (url, tabId) => {
     tab.isDestroyed() ||
     !tab.session.partition.startsWith('persist:')
 
-  if (url && isSourceAboutUrl(url) || isPrivate) {
+  if (url && (isSourceAboutUrl(url) || isPrivate)) {
```
Comment (diracdeltas) [inline js/stores/eventStore.js]: i think this should be `(url && isSourceAboutUrl(url)) || isPrivate`, assuming the previous code was correct

Comment (NejcZdovc) [inline js/stores/eventStore.js]: Fixed, thank you

File: app/browser/ads/adBlockUtil.js [hunk 4]
```diff
@@ -31,16 +31,27 @@ const mapFilterType = {
 const shouldDoAdBlockCheck = (resourceType, firstPartyUrl, url, shouldCheckMainFrame) =>
```
Comment (diracdeltas) [inline app/browser/ads/adBlockUtil.js]: i thought this function was supposed to do the following instead:
```
 firstPartyUrl.protocol &&
    // By default first party hosts are allowed, but enable the check if a flag is specified in siteHacks
  (
    shouldCheckMainFrame ||
    (
      (
        resourceType !== 'mainFrame' &&
        isThirdPartyHost(firstPartyUrl.hostname || '', url.hostname)
      ) ||
      (
        siteHacks[firstPartyUrl.hostname] &&
        siteHacks[firstPartyUrl.hostname].allowFirstPartyAdblockChecks
      )
    )
  ) &&
  // Only check http and https for now
  firstPartyUrl.protocol.startsWith('http') &&
  // Only do adblock if the host isn't in the whitelist
  !whitelistHosts.find((whitelistHost) => whitelistHost === url.hostname || url.hostname.endsWith('.' + whitelistHost)) &&
  // Make sure there's a valid resource type before trying to use adblock
  mapFilterType[resourceType] !== undefined
```

Comment (NejcZdovc) [inline app/browser/ads/adBlockUtil.js]: cc @darkdh 

@diracdeltas I am not familiar with this code, so any feedback and help is more then welcome

Comment (diracdeltas) [inline app/browser/ads/adBlockUtil.js]: for reference, here's what was in startAdBlocking prior to 85464b914:
```
    const cancel = firstPartyUrl.protocol &&
      (shouldCheckMainFrame || (details.resourceType !== 'mainFrame' &&
                                Filtering.isThirdPartyHost(firstPartyUrlHost, urlHost))) &&
      firstPartyUrl.protocol.startsWith('http') &&
      mapFilterType[details.resourceType] !== undefined &&
      !whitelistHosts.includes(urlHost) &&
      !urlHost.endsWith('.disqus.com') &&
      adblock.matches(details.url, mapFilterType[details.resourceType], firstPartyUrl.host)
```

Comment (diracdeltas) [inline app/browser/ads/adBlockUtil.js]: cc @bbondy

Comment (bbondy) [inline app/browser/ads/adBlockUtil.js]: yes @diracdeltas is right.  
Please do test that youtube videos do not give ads just to be sure though (logged in and out) and also do the test cases here:
https://github.com/brave/browser-laptop/commit/fc24493f2e090b23ed7ba44fee7ac7b3e8ca6f23#diff-1f92b9d4310a18761948d6ea1fbefc84

Comment (NejcZdovc) [inline app/browser/ads/adBlockUtil.js]: Code from @diracdeltas first comment was added
