### PR TITLE
usernameElement should blur and hide context menu upon submit

### LINKED ISSUE #2532: Autocomplete suggestion remains
**Describe the issue you encountered:** Autocomplete suggestion remains after I logged in to GitHub with <kbd>Enter</kbd>.

**Expected behavior:** It should be removed.

- Platform (Win7, 8, 10? macOS? Linux distro?): OS X

- Brave Version: 0.11.1 Beta1

- Steps to reproduce:
    1. Log out from GitHub
    2. Select "Sign in"
    3. Fill in your mail address and password
    4. Push <kbd>Enter</kbd>

- Screenshot if needed:
screenshot 2016-07-17 9 54 27

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Ran `git rebase -i` to squash commits if needed.

fix #2532

### CODE REVIEW

File: app/extensions/brave/content/scripts/passwordManager.js [hunk 1]
```diff
@@ -74,11 +74,19 @@ if (chrome.contentSettings.passwordManager == 'allow') {
             }, usernameElem.value || '')
         }
       })
+      usernameElem.addEventListener('blur', (e) => {
```
Comment (diracdeltas) [inline app/extensions/brave/content/scripts/passwordManager.js]: this breaks autofill, i think because the username context menu is gone by the time the click event is fired.

Comment (darkdh) [inline app/extensions/brave/content/scripts/passwordManager.js]: But I have it tested on my local side and autofill seems fine.

Comment (diracdeltas) [inline app/extensions/brave/content/scripts/passwordManager.js]: STR:
go to github.com in a new private tab
start entering previously-saved username
click on the context menu that pops up

for me, the entry is not filled at that point. may be a race condition.

Comment (darkdh) [inline app/extensions/brave/content/scripts/passwordManager.js]: Yeah, I cannot click on the pop-up context menu either.
But I got username/password filled when page loaded.

Comment (diracdeltas) [inline app/extensions/brave/content/scripts/passwordManager.js]: sorry, by 'autofill' i meant click-on-context-menu-to-fill

**Comment by darkdh** [comment]
@diracdeltas, I think 109d64b will not break autofill anymore

**Comment by diracdeltas** [comment]
++
