### PR TITLE
Fix Bravery menu to match new spec

### LINKED ISSUE #330: Cleanup Bravery menu
They should work like radio buttons:
screenshot 2016-01-26 09 50 29

- Replace ads does the safe ad insertion, adblock, and TP
- Block ads does the same as above but without the insertion
- Allow ads and tracking (sounds so filthy!:)) will just load pages without adblock and without TP.

### PR DESCRIPTION
**Pull request by diracdeltas**
This also refactors the Bravery menu into a common menu so it can be used
in the hamburger menu later.

Fix #330 

Auditors: @bbondy

### CODE REVIEW

File: js/commonMenu.js [hunk 1]
```diff
@@ -95,3 +100,66 @@ module.exports.findOnPageMenuItem = {
...
+module.exports.buildBraveryMenu = function (settings, init) {
+  const replaceAds = settings[adInsertion] || false
+  const blockAds = settings[adblock] || false
+  const blockTracking = settings[trackingProtection] || false
+  const useHttps = settings[httpsEverywhere] || false
+  return {
+    label: 'Bravery',
+    submenu: [
+      {
+        type: 'radio',
```
Comment (bbondy) [inline js/commonMenu.js]: I didn't know radio existed, nice.

**Comment by bbondy** [comment]
++
