### PR TITLE
Fix default engine display problem for fresh profile

### LINKED ISSUE #3254: address bar input ignored if no default search engine set
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
URL typed into address bar is ignore (after typing return) if a default search engine is not set

**Expected behavior:**
Resolve URL and display page

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version:
Brave: 0.11.5
- Steps to reproduce:
    1. using the Preferences>Search page, make sure that no search engine has a check mark in the default column. (I'm not sure how I initially got into this state because once I selected a default I couldn't get it back into the no-default set state.
    2.In a new tab, type a known good url such as brave.com into the address bar and then hit the return key
    3. nothing happens
    4. go back to the preferences?search page and select some search engine as the default
    5. repeat step ii
    6.  The requested page is display

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Fix #3254

auditor: @bbondy

### CODE REVIEW

File: js/about/preferences.js [hunk 1]
```diff
@@ -365,11 +365,12 @@ class GeneralTab extends ImmutableComponent {
 
 class SearchSelectEntry extends ImmutableComponent {
   shouldComponentUpdate (nextProps, nextState) {
-    return this.props.settings.get(settings.DEFAULT_SEARCH_ENGINE) !== nextProps.settings.get(settings.DEFAULT_SEARCH_ENGINE)
+    return getSetting(settings.DEFAULT_SEARCH_ENGINE, this.props.settings) !==
+      getSetting(settings.DEFAULT_SEARCH_ENGINE, nextProps.settings)
```
Comment (bbondy) [inline js/about/preferences.js]: I commented on the commit on your branch by mistake instead of here:
https://github.com/darkdh/browser-laptop/commit/f82a848a08780ff0b2f4ded95b2000514f937323

Comment (darkdh) [inline js/about/preferences.js]: Thanks for the feedback. Fixed in 1477399
