### PR TITLE
fix data URL phishing warning appear on the wrong tab

### LINKED ISSUE #10754: bypass data: phishing warning by opening a URL in a new tab
STR:
save `<a href='data:,Hello%2C%20World!'>click me</a>` to an HTML file
open it and right-click the anchor element to open in new tab

you should see a data phishing URL warning, but instead you see 'this site is secure' for the current tab.

### PR DESCRIPTION
**Pull request by diracdeltas**
fix #10754

test plan
1. go to https://jsfiddle.net/y3uw6q1w/
2. right click the link and open in new tab
3. no siteInfo popup should appear
4. switch to the new tab
5. siteInfo popup should appear
6. switch to tab 1 and back to tab 2. the siteInfo popup should not appear.

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/reducers/frameReducer.js [hunk 1]
```diff
@@ -183,7 +191,8 @@ const frameReducer = (state, action, immutableAction) => {
         })
       }
       // For potential phishing pages, show a warning
-      state = state.setIn(['ui', 'siteInfo', 'isVisible'], isPotentialPhishingUrl(action.location))
```
Comment (cezaraugusto) [inline app/renderer/reducers/frameReducer.js]: nice find

**Comment by darkdh** [comment]
++
