### PR TITLE
Validate bookmark name before creation Fixes #3188

### LINKED ISSUE #3188: Users can create bookmark folders with no name
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
On the Bookmarks toolbar, if I choose to create a new folder, I do not have to provide a folder name. A folder with no name is created.

**Expected behavior:**
The system should prevent me from creating a folder with no name.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
Discovered in 0.11.5 RC1, but repro'd in 0.11.2. It's probably always been there.

- Steps to reproduce:
    1. Make sure the bookmarks toolbar is visible
    2. Right-click on the toolbar and select 'Add Folder...'
    3. Click Save

- Screenshot if needed:
blank_bookmark_folder

- Any related issues:

### PR DESCRIPTION
**Pull request by Sh1d0w**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. #3188 
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

### CODE REVIEW

**Comment by Sh1d0w** [comment]
Reviewers: @bbondy @bridiver

File: js/components/addEditBookmark.js [hunk 1]
```diff
@@ -12,7 +11,7 @@ const KeyCodes = require('../constants/keyCodes')
 const siteTags = require('../constants/siteTags')
 const siteUtil = require('../state/siteUtil')
 
-class AddEditBookmark extends ImmutableComponent {
+class AddEditBookmark extends React.Component {
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: Thanks for the patch. 

Please keep this as ImmutableComponent, and then just determine in render if it's valid or not and render accordingly.  Also I think this only styles that it's invalid currently and not stops it from submitting it. 

For any visual changes also pls include a screenshot, thanks.

File: less/addEditBookmark.less [hunk 2]
```diff
@@ -5,3 +5,7 @@
 .removeBookmarkLink {
   margin-right: auto;
 }
+
+.invalid-input {
+    border: 1px solid #f2075d;
```
Comment (bbondy) [inline less/addEditBookmark.less]: pls create a variable for this border value in variables.less and use it here.

**Comment by Sh1d0w** [comment]
@bbondy Styles are updated and the class as well. The only visual change that I introduce and has to be re rendered is when the state changes to invalid:



Let me know if I have to tweak something else.

**Comment by bbondy** [comment]
Sorry it doesn't look disabled to me, @bradleyrichter pls provide styling suggestions.

**Comment by Sh1d0w** [comment]
@bbondy  Oh well I am only applying css style to the input, not on the button. 

What would you say to gray it out like this, untilthe name is empty?

**Comment by bradleyrichter** [comment]
@Sh1d0w thanks for working on this.

I would prefer to only use the full-browser grey-out for full-modal dialogs. (needs to be spec'd)

I think your greyed button above combined with the red focus indication will be fine. 

This dialog should also have a cancel button so you can give up and start over/leave with no changes.

Later we can style it more like the new BM door hanger: #2894

**Comment by Sh1d0w** [comment]
@bradleyrichter Thanks. No problems, I like the Brave's idea and I am happy to contribute with what I can.

I just didn't get should I implement the cancel button and should I make any further changes in order the PR to be accepted or it is good to go like this? It is just for fixing the currenct functionality, not to intorduce new one at first place.

The designs look very cool, btw!

**Comment by bbondy** [comment]
I'll add a few more follow up changes, we really appreciate the PR!

File: js/components/addEditBookmark.js [hunk 3]
```diff
@@ -23,7 +23,17 @@ class AddEditBookmark extends ImmutableComponent {
     this.onClick = this.onClick.bind(this)
     this.onSave = this.onSave.bind(this)
     this.onRemoveBookmark = this.onRemoveBookmark.bind(this)
+    this.state = {
+      bookmarkNameValid: true,
+      saveButtonDisabled: true
+    };
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: I'd recommend that you have an accessor defined for this instead:

```
get bookmarkNameValid () {
...
}
```

Note that there is an onChange handler on the bookmark name so the site data is always known, so you can just check it there in `this.props.currentDetail`.

I think you don't need to know whether the bookmark name is valid separately from if the save button should be disabled. In particular the save button should be disabled when the bookmark name is invalid.

File: js/components/addEditBookmark.js [hunk 4]
```diff
@@ -23,7 +23,17 @@ class AddEditBookmark extends ImmutableComponent {
...
   }
+
+  shouldComponentUpdate (nextProps, nextState) {
+    return (Object.keys(nextState).some((prop) => nextState[prop] !== this.state[prop]) || 
+      Object.keys(nextProps).some((prop) => nextProps[prop] !== this.props[prop]))
+  }
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: And remove this `shouldComponentUpdate`, no immutable component should need to ever override it.

File: js/components/addEditBookmark.js [hunk 5]
```diff
@@ -68,6 +78,8 @@ class AddEditBookmark extends ImmutableComponent {
     } else {
       currentDetail = currentDetail.set('customTitle', e.target.value)
     }
+
+    this.setState({saveButtonDisabled: (e.target.value.length === 0)})
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: ImmutableComponents would not have setState either

File: js/components/addEditBookmark.js [hunk 6]
```diff
@@ -79,6 +91,11 @@ class AddEditBookmark extends ImmutableComponent {
     windowActions.setBookmarkDetail(currentDetail, this.props.originalDetail, this.props.destinationDetail)
   }
   onSave () {
+    // First check if the title of the currentDetail is set
+    if (!this.props.currentDetail.get('title') && !this.props.currentDetail.get('customTitle')) {
+      return this.setState({bookmarkNameValid: false});
+    }
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: Here you'd check 
if (!this.bookmarkNameValid) {
  return false
}

File: js/components/addEditBookmark.js [hunk 7]
```diff
@@ -91,15 +108,15 @@ class AddEditBookmark extends ImmutableComponent {
...
+    return this.props.currentDetail.get('title') || ''
   }
   render () {
     return <Dialog onHide={this.onClose} isClickDismiss>
       <div className='genericForm' onClick={this.onClick}>
         <div className='genericFormTable'>
           <div id='bookmarkName' className='formRow'>
             <label data-l10n-id='nameField' htmlFor='bookmarkName' />
-            <input spellCheck='false' onKeyDown={this.onKeyDown} onChange={this.onNameChange} value={this.displayBookmarkName} ref={(bookmarkName) => { this.bookmarkName = bookmarkName }} />
+            <input spellCheck='false' className={this.state.bookmarkNameValid ? '' : 'invalid-input'} onKeyDown={this.onKeyDown} onChange={this.onNameChange} value={this.displayBookmarkName} ref={(bookmarkName) => { this.bookmarkName = bookmarkName }} />
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: `this.bookmarkNameValid` after the above changes

File: less/addEditBookmark.less [hunk 8]
```diff
@@ -2,6 +2,16 @@
...
 .removeBookmarkLink {
   margin-right: auto;
 }
+
+.invalid-input {
+    border: @errorBorderSize solid @errorBorderColor;
+}
+
+.disabled {
+    background-color: #ccc!important;
```
Comment (bbondy) [inline less/addEditBookmark.less]: nit: add a space before  `!important` or just be more specific and then you can bypass the need for it altogether.
background-color: #ccc !important;

**Comment by bbondy** [comment]
OK submitted the review feedback, pls also shoot me an email at brian@brave.com and we'll get you on the community slack channel if you want.

File: js/components/addEditBookmark.js (hunk 3 above)
Comment (Sh1d0w) [inline js/components/addEditBookmark.js]: The only reason I did this is because if I use only one porperty to check for both the button and the input, is that the input will be highlighted in read intially, which I think should happen only if you submit empty string. However with the disabling of the button if it is empty it is not necessary, so I will refactor.

Thanks for the feedback.

**Comment by Sh1d0w** [comment]
@bbondy Thanks for the great feedback. I have refactored the code according your advices.

**Comment by bbondy** [comment]
super clean, thanks!

File: js/components/addEditBookmark.js [hunk 9]
```diff
@@ -24,9 +24,15 @@ class AddEditBookmark extends ImmutableComponent {
     this.onSave = this.onSave.bind(this)
     this.onRemoveBookmark = this.onRemoveBookmark.bind(this)
   }
+
   get isBlankTab () {
     return ['about:blank', 'about:newtab'].includes(this.props.currentDetail.get('location'))
   }
+
+  get bookmarkNameValid () {
+    return (this.props.currentDetail.get('title') || this.props.currentDetail.get('customTitle'))
```
Comment (bbondy) [inline js/components/addEditBookmark.js]: Actually I'll ask for a small follow up if you don't mind, I think no title is valid for bookmarks but not bookmark folders. In that case we display as just the URL.
So the follow up PR would just have something like `return !this.isFolder || ...`

Comment (Sh1d0w) [inline js/components/addEditBookmark.js]: Actually in case of Bookmark `this.props.currentDetail.get('title')` will always be set as the website's title, so even if you have empty customTItle, you should not see grayed button and if you submit the title will fallback to website's title.

Comment (bbondy) [inline js/components/addEditBookmark.js]: oh ok great then
