### PR TITLE
Fix bravery panel width from increasing

### LINKED ISSUE #9839: Avoid bravery panel width from increasing
**Describe the issue you encountered:** Avoid bravery panel width from increasing when you open the blocked resources list.

- Brave Version (revision SHA): 0.17.13

- Extra QA steps:
    1. Open twitter.com
    2. Enable `Block Scripts`
    3. Click the counter
    4. Make sure the panel width does not increase

- Any related issues: https://github.com/brave/browser-laptop/issues/9016#issuecomment-312308575

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #9839
Addresses #9016

Auditors:

Test Plan:
1. Open twitter.com
2. Enable `Block Scripts`
3. Click the counter
4. Make sure the panel width does not increase

twitter

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/main/braveryPanel.js [hunk 1]
```diff
@@ -935,14 +935,18 @@ const styles = StyleSheet.create({
     marginBottom: '.75rem'
   },
   braveryPanel_compact__body__ul: {
-    padding: '0 .5rem',
-    margin: '0 0 .75rem 0',
-    wordBreak: 'break-all',
+    padding: '0 .5rem 1rem',
+    margin: '0 0 .25rem 0',
```
Comment (luixxiul) [inline app/renderer/components/main/braveryPanel.js]: These are set to make the list scrollable (y axis) to its bottom. I could not find out how to do the same thing for x axis.

File: app/renderer/components/main/braveryPanel.js [hunk 2]
```diff
@@ -935,14 +935,17 @@ const styles = StyleSheet.create({
...
     maxHeight: '10vh'
   },
   braveryPanel_compact__body__ul__li: {
     padding: '5px 0',
 
+    // #9839: Avoid the panel width from increasing
+    width: 0,
+    whiteSpace: 'nowrap',
+
```
Comment (cezaraugusto) [inline app/renderer/components/main/braveryPanel.js]: wow elegant fix
