### PR TITLE
Prevent tab icon 'appear' animations running again when tab is moved

### LINKED ISSUE #11470: Tab 'appear' animations run again when tab is moved
## Test plan

https://github.com/brave/browser-laptop/pull/11501#issue-265163822

----

## Description

Tab 'appear' animations run again when tab element is moved via a new sort order.

59deb7b94d9cd406032710

### Steps to Reproduce

  1. Create multiple tabs
  2. Observe that the tab icon fades in with animation
  3. Change tab order

**Actual result:**

  - Observe that tabs that are moved have their icons fade in with animation again

**Expected result:**
  - no fade-in animation

**Reproduces how often:** always

### Brave Version
master, introduced in 33c5d10c16624eade868e2150ee43b96384ed82c for issue #10883 and PR 

## Test Plan
From PR #10691 / issue #10883 (create smooth transitions for tab components)

- close icon, favicon, private, new session icons will have a smooth transition when enabled
- audio icon will slightly scroll to the right when enabled

Resolving this issue
- Create multiple tabs with favicons
- Have a tab with audio playing and audio icon shown
- Move the tabs around, there should be no flicker off / fade-in of favicon or audio icon
- Repeat with tabs showing private icon, and session icon

### PR DESCRIPTION
**Pull request by petemill**
Fix #11470
Note that the following came up in my review of the existing code I saw whilst fixing this. They were beyond the scope of getting a small PR to fix the aforementioned issue though:
- If we want to animate the unmounting of the component (when audio is stopped for example), then we could use https://github.com/reactjs/react-transition-group - the existing code does not animate audio stopped so I did not put in a solution
- I'd also be inclined to suggest 'ease-out' easings should be used across the UI, and at the moment 'linear' is used
- This code could be simplified by changing the component structure somewhat and putting the transitions on the icon element, or similar
- When the tab is hovered, the close button shows, and the private icon / session icons are removed from the DOM rather than hidden. This causes the 'appear' animation to fire again. Perhaps this is intentional, and it's what is the case on master at the moment. But it might have better control (and performance) to simply add a class to these icons, and then they can hide / show using any or no transition
- Theres a bug with the audioTabIcon in that props.showAudioIcon goes from true to false to true when the tab is first loaded and immediately plays audio. This causes a flicker of the icon. Same is true on master.

Before
brave-issue-tab-appear-animations-before2

After
brave-issue-tab-appear-animations-after

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

## Test Plan
From PR #10691 / issue #10883 (create smooth transitions for tab components)

- close icon, favicon, private, new session icons will have a smooth transition when enabled
- audio icon will slightly scroll to the right when enabled

Resolving this issue
- Create multiple tabs with favicons
- Have a tab with audio playing and audio icon shown
- Move the tabs around, there should be no flicker off / fade-in of favicon or audio icon
- Repeat with tabs showing private icon, and session icon

## Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 1]
```diff
@@ -66,19 +101,14 @@ class AudioTabIcon extends React.Component {
       className={css(styles.audioTab__icon)}
       symbol={this.audioIcon}
       onClick={this.toggleMute}
+      ref={this.setRef}
```
Comment (NejcZdovc) [inline app/renderer/components/tabs/content/audioTabIcon.js]: Can we use `ref={(node) => { this. element = node }}`?

I don't see a need to use findDOMNode for this scenario.

Comment (petemill) [reply app/renderer/components/tabs/content/audioTabIcon.js]: @NejcZdovc I'm pretty sure in this case `node` would be the instance of the component class and not the required underlying DOM element, since that `ref={}` attribute is on a custom React component, not a normal HTML element. `findDOMNode` traverses the rendering structure to get the ultimate html element

Comment (petemill) [reply app/renderer/components/tabs/content/audioTabIcon.js]: tbh all this could be refactored to a simpler structure, but that would be a subsequent PR

**Comment by cezaraugusto** [comment]
@petemill could you please rebase?

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 2]
```diff
@@ -56,6 +58,39 @@ class AudioTabIcon extends React.Component {
...
+
+  transitionIfRequired (prevProps) {
+    // transition only if we have an element and we're not pinned
+    if (!this.element || this.props.isPinned) {
+      return
+    }
+    // transition only if audio state changes
+    const hasChanged = !prevProps || this.props.showAudioIcon !== prevProps.showAudioIcon
+    // TODO: if we want to animate the unmounting of the component (when audio is stopped),
+    //       then we should use https://github.com/reactjs/react-transition-group
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/audioTabIcon.js]: nit: just taking advantage of a needed rebase, could you normalize the comment here? like
```diff
-//       TODO:
+// TODO:
```

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 3]
```diff
@@ -56,6 +58,39 @@ class AudioTabIcon extends React.Component {
...
+    if (!hasChanged || !this.props.showAudioIcon) {
+      return
+    }
+    // TODO: measure element width if this ever becomes dynamic since it's not great to specify complex size logic in two places
+    //       ...or animate a child element using transform: translateX in order to achieve the slide-in
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/audioTabIcon.js]: nit2: would be cool if you break comments into more lines/less text. Sorry I have a small monitor. Also same comment from above re normalizing spaces in comments

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 4]
```diff
@@ -56,6 +58,39 @@ class AudioTabIcon extends React.Component {
...
+    const frames = widthIncreaseElementKeyframes(0, globalStyles.spacing.iconSize)
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/audioTabIcon.js]: `frames` is used across several areas to reference the group of frames we have and can lead to confusion. Please change variable name to something more explicit like `elementKeyframes` or something you think fits better

File: app/renderer/components/tabs/content/closeTabIcon.js [hunk 5]
```diff
@@ -46,6 +48,37 @@ class CloseTabIcon extends React.Component {
...
+
+  transitionIfRequired (prevProps) {
+    // transition only if we have an element and we're not pinned
+    if (!this.element || this.props.isPinned) {
+      return
+    }
+    // transition only if relevant state changes
+    const hasChanged = !prevProps || this.props.showCloseIcon !== prevProps.showCloseIcon
+    // TODO: if we want to animate the unmounting of the component (when tab is unhovered),
+    //       then we should use https://github.com/reactjs/react-transition-group
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/closeTabIcon.js]: same as above re comments extra space

File: app/renderer/components/tabs/content/closeTabIcon.js [hunk 6]
```diff
@@ -46,6 +48,37 @@ class CloseTabIcon extends React.Component {
...
+    if (!hasChanged || !this.props.showCloseIcon) {
+      return
+    }
+    const frames = opacityIncreaseElementKeyframes
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/closeTabIcon.js]: same as above re `frames` variable

File: app/renderer/components/tabs/content/favIcon.js [hunk 7]
```diff
@@ -47,6 +53,29 @@ class Favicon extends React.Component {
...
+    this.transitionInIfRequired()
+  }
+
+  componentDidUpdate (prevProps) {
+    this.transitionInIfRequired(prevProps)
+  }
+
+  transitionInIfRequired (prevProps) {
+    // transition only if favicon changes
+    const shouldTransitionIn = this.element && !this.props.tabLoading && (!prevProps || this.props.favicon !== prevProps.favicon)
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/favIcon.js]: nit: would be cool/preferable to have a helper method instead or just break this down like 
```js
const shouldTransitionIn = (
  this.element &&
  !this.props.tabLoading &&
  (!prevProps || this.props.favicon !== prevProps.favicon)
)
```

File: app/renderer/components/tabs/content/newSessionIcon.js [hunk 8]
```diff
@@ -37,6 +43,29 @@ class NewSessionIcon extends React.Component {
...
+    this.transitionInIfRequired()
+  }
+
+  componentDidUpdate (prevProps) {
+    this.transitionInIfRequired(prevProps)
+  }
+
+  transitionInIfRequired (prevProps) {
+    // transition only if showPartitionIcon is newly true
+    const shouldTransitionIn = this.element && !this.props.isPinned && this.props.showPartitionIcon && this.props.partitionNumber !== 0 && (!prevProps || !prevProps.showParitionIcon || this.props.partitionNumber === 0)
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/newSessionIcon.js]: same as above, given `shouldTransitionIn` is shared across files, a helper method would be a nice move

Comment (cezaraugusto) [reply app/renderer/components/tabs/content/newSessionIcon.js]: like inside `tabUIState.js`

File: app/renderer/components/tabs/content/privateIcon.js [hunk 9]
```diff
@@ -35,6 +41,29 @@ class PrivateIcon extends React.Component {
...
+    this.transitionInIfRequired()
+  }
+
+  componentDidUpdate (prevProps) {
+    this.transitionInIfRequired(prevProps)
+  }
+
+  transitionInIfRequired (prevProps) {
+    // transition only if showPrivateIcon is newly true
+    const shouldTransitionIn = this.element && this.props.showPrivateIcon && (!prevProps || !prevProps.showPrivateIcon)
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/content/privateIcon.js]: ditto

**Comment by petemill** [comment]
In case anyone is interested, I had made this codepen to illustrate how animations re-run when elements are moved within the DOM https://codepen.io/petemill/pen/yzqwWE

File: app/renderer/components/tabs/content/audioTabIcon.js (hunk 2 above)
Comment (petemill) [reply app/renderer/components/tabs/content/audioTabIcon.js]: @cezaraugusto just to confirm - by normalize do you mean you don't want the text with the same indentation as I have it? You want it to wrap underneath the 'TODO:' from the previous line?

File: app/renderer/components/tabs/content/audioTabIcon.js (hunk 3 above)
Comment (petemill) [reply app/renderer/components/tabs/content/audioTabIcon.js]: sure - I have about 12k pixels 💻 📺 📺

**Comment by petemill** [comment]
Feedback implemented and rebased on master. Ready for re-review.

@cezaraugusto I did break down the `shouldTransitionIn` implementations for readability, but so far left them defined in each icon's component. Whilst I could create a helper function(s) in tabUIState, it feels like that would be against the style of the existing functions in that module, which all take `state` as a param. This would need to accept the current `props`, and the `previousProps` at least. Also the logic about when to transition-in is slightly different between the icons, so it could be confusing compared to this explicit approach. In any way, this may all change when implementing a new design for tab transitions very soon...

**Comment by cezaraugusto** [comment]
thanks for addressing comments. This looks good to me but I still think `shouldTransitionIn` deserves its own method. We have another place called `tabUtil.js` which seems a good place to host it for now. 

Please move it there and we're good to merge or hit me up over Slack if you have a better take. I wouldn't block on this but for me it's easier to change/remove in the future if we want to.

**Comment by petemill** [comment]
Moved to milestone 0.22.x due to requiring it for a clean merge of #12565 and the same / similar test plan for that version.
