### PR TITLE
Sites and wallet now cannot be deleted when payment is in progress

### LINKED ISSUE #14278: Ledger entries should not be allowed to delete when reconcile is going on
### Description
Ledger entries should not be allowed to delete when reconcile is going on 

### Steps to Reproduce

  1. Install 0.22.723 and enable payments
  2. Visit sites to add in ledger table
  3. Change reconcilestamp to older date to trigger reconcile
  4. Ledger table entries can be deleted while reconcile is in progress

**Actual result:**
Ledger entries should not be allowed to delete when reconcile is going on 

**Expected result:**
Should not be allowed to delete ledger entries 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.22.723
-- | --
V8 | 6.6.346.32
rev | edb3e88
Muon | 6.0.12
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.170

**Reproducible on current live release:**
Yes

### Additional Information
Behaviour should be similar to https://github.com/brave/browser-laptop/issues/8537

### PR DESCRIPTION
**Pull request by jasonrsadler**
Fixes #14278 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:

- Run Brave with appropriate staging environment variables.
- Ensure site can be deleted when a reconcile is not in progress
- Trigger contributions and ensure site cannot be deleted when a reconcile is in progress.

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

cc @bradleyrichter for msgbox text and UI/UX. Current message when trying to delete a site from the ledger during contribution:
`A Brave Payment contribution is in progress. Brave Payment data cannot be cleared during this time.`

When deleting from ledgerTable:
screen shot 2018-06-10 at 7 20 06 pm

In advanced settings:
screen shot 2018-06-10 at 7 19 52 pm

### CODE REVIEW

File: app/renderer/components/preferences/payment/advancedSettings.js [hunk 1]
```diff
@@ -113,15 +113,28 @@ class AdvancedSettingsFooter extends ImmutableComponent {
     }
   }
 
+  deleteWalletDuringReconcile () {
+    const msg = locale.translation('cannotDeleteWalletOnReconcile')
+    window.alert(msg)
+  }
+
   render () {
+    console.log(this.props.inProgress)
```
Comment (ryanml) [inline app/renderer/components/preferences/payment/advancedSettings.js]: Log :)

File: app/renderer/components/preferences/payment/enabledContent.js [hunk 2]
```diff
@@ -462,7 +462,8 @@ class EnabledContent extends ImmutableComponent {
       <LedgerTable ledgerData={this.props.ledgerData}
         settings={this.props.settings}
         onChangeSetting={this.props.onChangeSetting}
-        siteSettings={this.props.siteSettings} />
+        siteSettings={this.props.siteSettings}
+        inProgress={ledgerData.get('status') === ledgerStatuses.IN_PROGRESS} />
```
Comment (ryanml) [inline app/renderer/components/preferences/payment/enabledContent.js]: (Small) could we maybe bake this in to `this.props` so we have something like `this.props.paymentInProgress`?

File: app/renderer/components/preferences/paymentsTab.js [hunk 3]
```diff
@@ -244,6 +245,7 @@ class PaymentsTab extends ImmutableComponent {
             showOverlay={this.props.showOverlay}
             hideOverlay={this.props.hideOverlay}
             setOverlayName={this.props.setOverlayName}
+            inProgress={this.props.ledgerData.get('status') === ledgerStatuses.IN_PROGRESS}
```
Comment (ryanml) [inline app/renderer/components/preferences/paymentsTab.js]: See above

File: app/renderer/components/preferences/payment/advancedSettings.js (hunk 1 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/advancedSettings.js]: gets 'em every time.

File: app/renderer/components/preferences/paymentsTab.js (hunk 3 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/paymentsTab.js]: I can define it above but above this is preferences with a lot getting set in renderer state. I'd prefer to leave this one 'as is' (at least in this file).

File: app/renderer/components/preferences/payment/enabledContent.js (hunk 2 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/enabledContent.js]: I can have it baked at this point.

Comment (ryanml) [reply app/renderer/components/preferences/payment/enabledContent.js]: Sgtm, thanks!

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 4]
```diff
@@ -260,12 +265,20 @@ class LedgerTable extends ImmutableComponent {
             onClick={this.togglePinSite.bind(this, this.getHostPattern(synopsis), publisherKey, !pinned, percentage)}
             data-test-pinned={pinned}
           />
-          <span className={css(
+          {
+            !this.props.inProgress
```
Comment (NejcZdovc) [inline app/renderer/components/preferences/payment/ledgerTable.js]: Can we instead of duplicating span and copy pasting styles, have just one function for this action and then inside that function we can trigger different stuff based on the flag. This way it's easier to refactor things or add some new classes to the span, less error prone.

Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/ledgerTable.js]: Done.

File: app/renderer/components/preferences/paymentsTab.js (hunk 3 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/paymentsTab.js]: Done.

File: app/renderer/components/preferences/payment/enabledContent.js (hunk 2 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/enabledContent.js]: Done.

File: app/renderer/components/preferences/payment/advancedSettings.js (hunk 1 above)
Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/advancedSettings.js]: Gone.

File: app/renderer/components/preferences/payment/advancedSettings.js [hunk 5]
```diff
@@ -113,15 +113,27 @@ class AdvancedSettingsFooter extends ImmutableComponent {
     }
   }
 
+  deleteWalletDuringReconcile () {
```
Comment (ryanml) [inline app/renderer/components/preferences/payment/advancedSettings.js]: Where is this being called? Seems like it should tied in to `deleteWallet`

Comment (jasonrsadler) [reply app/renderer/components/preferences/payment/advancedSettings.js]: It's a placeholder. Waiting for @bradleyrichter or someone from UI to say the text in place of button is ok. If it's not then I'll replace the button and this would be called instead.

Comment (ryanml) [reply app/renderer/components/preferences/payment/advancedSettings.js]: Got it 👍

**Comment by bsclifton** [comment]
master 5f5cbc8796b89d5230593fb471816c82ea679ce7
0.24.x c08a89c3ca7290543e7243b072e1679777584122
