### PR TITLE
prevent Dialog from being uncloseable with long text

### LINKED ISSUE #7930: Alert box with quite lengthy content cannot be closed
**Describe the issue you encountered:**
Alert box with quite lenghty content cannot be closed. This could be used by an attacker (despite of low security concern).

- Brave Version (revision SHA): 0.13.5

- Steps to reproduce:
    1. Open https://jsfiddle.net/c5o7arqu/
    2. Make the browser window small
    3. Click "OK"
    
- Actual result: You cannot scroll the alert box to the "OK" button

- Expected result: It should be possible to scroll the alert box to the button

- Screenshot if needed:

- Any related issues: #2775 #7107

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

- Fix #7930
- Auditors: @luixxiul

Screenshot: 
screen shot 2017-04-28 at 1 59 30 am
screen shot 2017-04-28 at 2 00 12 am

> **Note:** no scrollbar is shown because I have it hidden by default in macOS. It's set as default so each OS will render native scrollbars (per Brad https://github.com/brave/browser-laptop/pull/8475#pullrequestreview-35229895)

/cc @bradleyrichter for design review

Test Plan:

1. Open https://jsfiddle.net/c5o7arqu/
2. Make the browser window small
3. Click "OK"
4. Scrollbar should show, text should be scrollable
5. Remove some text with devTools or open a smaller dialog
6. Scrollbar shouldn't show
7. everything should be properly aligned
8. Resizing screen should resize dialog as well (responsive)

### CODE REVIEW

**Comment by jonathansampson** [comment]
@cezaraugusto @bradleyrichter Can we consider making only the _body text_ scrollable, so the dialog button is always visible? Making the user scroll down to dismiss the dialog seems unnecessary.

**Comment by NejcZdovc** [comment]
Personally I wouldn't go with a full width (90%), but limit it to I don't know maybe 300, 400px (completely random number from top of my head :smiley: )

**Comment by cezaraugusto** [comment]
@jonathansampson that's a great idea. I'll wait for design feedback from Brad and do all together, thanks for reviewing

**Comment by cezaraugusto** [comment]
@NejcZdovc thanks, yep I did a random guess as well

**Comment by jonathansampson** [comment]
Agree with @NejcZdovc that we need a max-width, or a fixed-width.

**Comment by luixxiul** [comment]
+1 unless the title could be so long that it would overflow the dialog.

File: app/renderer/components/styles/commonStyles.js [hunk 1]
```diff
@@ -31,7 +31,29 @@ const styles = StyleSheet.create({
...
+    boxSizing: 'border-box',
+
+    // Add a custom scrollbar for the element
+    '::-webkit-scrollbar': {
+      width: '10px'
+    },
+    '::-webkit-scrollbar-thumb': {
+      background: globalStyles.color.braveOrange,
+      // same as primary button
+      boxShadow: '0px 1px 5px -1px rgba(0, 0, 0, 0.5)',
```
Comment (luixxiul) [inline app/renderer/components/styles/commonStyles.js]: let's replace the box-shadow with a variable on global.js for future use :-)

File: app/renderer/components/styles/commonStyles.js [hunk 2]
```diff
@@ -31,7 +31,29 @@ const styles = StyleSheet.create({
...
+      // match dialog radius
+      borderRadius: '4px'
+    },
+    '::-webkit-scrollbar-track': {
+      boxShadow: 'inset 0 0 4px rgba(0,0,0, 0.3)',
```
Comment (luixxiul) [inline app/renderer/components/styles/commonStyles.js]: ditto.

**Comment by bradleyrichter** [comment]
+++

**Comment by cezaraugusto** [comment]
Updated, set a smaller size and migrated scroll to body

**Comment by luixxiul** [comment]
Isn't the scroll bar too low contrasted?

**Comment by cezaraugusto** [comment]
contrast looks good for me but I don't mind changing it

**Comment by jonathansampson** [comment]
@cezaraugusto Looks really great! Can we do anything about making sure it isn't taller than the window?

image

File: app/renderer/components/common/messageBox.js [hunk 3]
```diff
@@ -154,7 +158,10 @@ const styles = StyleSheet.create({
     marginTop: globalStyles.spacing.dialogInsideMargin,
     minWidth: '425px',
     marginBottom: globalStyles.spacing.dialogInsideMargin,
-    userSelect: 'text'
+    userSelect: 'text',
+    maxHeight: '300px',
```
Comment (luixxiul) [inline app/renderer/components/common/messageBox.js]: what if we would apply `vh` instead of `px`? 300px might be small for full HD monitors.

File: app/renderer/components/styles/commonStyles.js [hunk 4]
```diff
@@ -45,7 +45,11 @@ const styles = StyleSheet.create({
     // Issue #7949
     padding: `${globalStyles.spacing.dialogInsideMargin} 30px`,
     position: 'absolute',
-    top: globalStyles.spacing.dialogTopOffset
+    top: globalStyles.spacing.dialogTopOffset,
+    // Issue #7930
+    boxSizing: 'border-box',
+    maxWidth: '600px',
+    maxHeight: '500px'
```
Comment (luixxiul) [inline app/renderer/components/styles/commonStyles.js]: ditto

File: app/renderer/components/common/messageBox.js (hunk 3 above)
Comment (jonathansampson) [inline app/renderer/components/common/messageBox.js]: Oh, good idea @luixxiul with `vh`. Since dialogs are pretty much always sized and positioned relatively to the viewport, it makes sense to use `vh` and `vw`. What do you think, @cezaraugusto?

Comment (cezaraugusto) [inline app/renderer/components/common/messageBox.js]: that's great, I took a look at other browsers and they take that approach as well. Maybe 80vh is good enough?

**Comment by cezaraugusto** [comment]
PR updated with custom scrollbar removal. New STR and preview here: https://github.com/brave/browser-laptop/pull/8475#issue-223933704

File: app/renderer/components/styles/global.js [hunk 5]
```diff
@@ -110,7 +110,7 @@ const globalStyles = {
     buttonHeight: '25px',
     buttonWidth: '25px',
     navbarHeight: '36px',
-    downloadsBarHeight: '50px',
```
Comment (cezaraugusto) [inline app/renderer/components/styles/global.js]: looking at the component and at variables.less it actually never was 50px

**Comment by jonathansampson** [comment]
Just pulled down the changes; beautiful work, @cezaraugusto!
