### PR TITLE
don't set tab preview for the active frame

### LINKED ISSUE #9929: Preview does not reset if you click a tab until you mouse out of tab
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
If you have 2 tabs, and you use your mouse to change to the second tab, the preview sticks around until you move your mouse out.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Probably all, but I tested on macOS

- Brave Version (revision SHA):
0.7.14.

- Steps to reproduce:
    1. Click on the twitter icon on the new tab page
    2. Open a second tab, wait for the new tab to open.  Which becomes active.
    3. Hover over the twitter page, and then click it
    
- Actual result:
The preview faded look remains

- Expected result:
The preview faded look should go away after active is set.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No, but on the latest preview release.

- Can this issue be consistently reproduced?
Yes

### PR DESCRIPTION
**Pull request by cezaraugusto**
Auditors: @bbondy, @bsclifton
Fix #9929
Test Plan:
covered by automated tests:
`npm run test -- --grep="does not show preview in the active tab`

### CODE REVIEW

File: test/tab-components/tabTest.js [hunk 1]
```diff
@@ -390,6 +390,16 @@ describe('tab tests', function () {
...
     })
+    it('does not show preview in the active tab', function * () {
+      yield this.app.client
+        .moveToObject('[data-test-id="tab"][data-frame-key="2"]')
+        .waitForTextValue('[data-test-id="tab"][data-frame-key="2"]', 'Page 1')
+        .waitForExist('.frameWrapper.isPreview webview[data-frame-key="2"]')
+        .moveToObject('[data-test-id="tab"][data-frame-key="1"]')
+        .click('[data-test-id="tab"][data-frame-key="1"]')
+        .waitForExist('[data-test-active-tab][data-frame-key="1"]')
+        .waitForExist('.frameWrapper.isPreview webview[data-frame-key="2"]', 500, true)
```
Comment (NejcZdovc) [inline test/tab-components/tabTest.js]: I am not sure that I understand this test. You move mouse into frame 1, you click on it, then you wait for frame 1 to be active and then you check if frame 2 is in preview?

Comment (NejcZdovc) [inline test/tab-components/tabTest.js]: is this correct?

Comment (cezaraugusto) [inline test/tab-components/tabTest.js]: nope it wasn't, updated

File: test/tab-components/tabTest.js [hunk 2]
```diff
@@ -390,6 +390,16 @@ describe('tab tests', function () {
...
     })
+    it('does not show preview in the active tab', function * () {
+      yield this.app.client
+        .moveToObject('[data-test-id="tab"][data-frame-key="2"]')
+        .waitForTextValue('[data-test-id="tab"][data-frame-key="2"]', 'Page 1')
+        .waitForExist('.frameWrapper.isPreview webview[data-frame-key="2"]')
+        .moveToObject('[data-test-id="tab"][data-frame-key="1"]')
+        .click('[data-test-id="tab"][data-frame-key="1"]')
+        .waitForExist('[data-test-active-tab][data-frame-key="1"]')
+        .waitForExist('.frameWrapper.isPreview webview[data-frame-key="1"]', 500, true)
```
Comment (NejcZdovc) [inline test/tab-components/tabTest.js]: Me agin :smiley:  Please use `waitForElementCount(..., 0)`, because this negating is hard to read

**Comment by bbondy** [comment]
Thanks @cezaraugusto, I updated with your review comments @NejcZdovc (and agree)
