### PR TITLE
Return about:[name] as origin for about: pages

### LINKED ISSUE #10410: not prompted to restart Brave when changing preferences marked with an asterisk
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Preferences marked with an asterisk are not prompting for Brave to be restarted. This was working in 0.18.20.

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
Brave | 0.18.21
rev | 263b6d5
Muon | 4.3.9

- Steps to reproduce:
    1. In Preferences change language (or any other preference marked with an asterisk)
    2. You are not prompted for restart.

    
- Actual result:
You are not prompted to restart Brave.

- Expected result:
Should be prompted to restart Brave.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No (was last working in 0.18.20)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

Actual:
language_change

Expected:
screen shot 2017-08-10 at 3 01 03 pm

- Any related issues:

### PR DESCRIPTION
**Pull request by bbondy**
This PR is only for merging on master, 0.20.x, and 0.19.x
A different PR will be spun up for 0.18.x.
Fix #10410

Auditors: @diracdeltas

Notes this is in the branch of code which requires muon only so it is already in unit tests but we test it with the wrong url parsing from node.

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
  - See comment in commit, also Yan said she will work on a PR to test it via browser test.
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: js/lib/urlutil.js [hunk 1]
```diff
@@ -429,8 +430,11 @@ const UrlUtil = {
     }
 
     let parsed = urlParse(location)
-    if (parsed.origin) {
-      // parsed.origin is specific to muon.url.parse
+    // parsed.origin is specific to muon.url.parse
+    if (parsed.origin !== undefined) {
+      if (parsed.protocol === 'about:') {
```
Comment (diracdeltas) [inline js/lib/urlutil.js]: for more backwards consistency, the conditional should be `if (parsed.origin === '') {..}` instead of checking if it is 'about:'. it seems like chromium's url parser will return '' as the origin for protocols that don't technically have origin-scoping (ex: 'data:') whereas previously this would return protocol + host.

Comment (diracdeltas) [inline js/lib/urlutil.js]: on second thought, using the path as the hostname as a generic fallback doesn't seem very safe. so i am fine with just having an exception for 'about:' for now.
