### PR TITLE
Auto-include propagates correctly

### LINKED ISSUE #7451: Publishers are auto included even when auto-include sites is turned off
## Test Plan
- Enable payments in settings
- Disable auto-include switch
- Visit brianbondy.com in a new tab, site is added in the list and is not included

## Automated test plan
- `npm run test -- --grep="auto include"`

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Publishers are auto included even when auto-include sites is turned off

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	0e68342

- Steps to reproduce:
    1. Enable payments in settings
    2. Disable `auto-include` switch 
    3. Visit brianbondy.com in a new tab, site is added in the list and is auto included
    
- Actual result:
Publishers are auto included even when auto-include sites is turned off

- Expected result:
If auto-suggest is `off` then it should be set as disabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:
#7429
cc: @mrose17 @cezaraugusto

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #7451

## Auditors
@mrose17

## Test Plan
- Enable payments in settings
- Disable auto-include switch
- Visit brianbondy.com in a new tab, site is added in the list and is not included

## Automated test plan
- `npm run test -- --grep="auto include"`

### CODE REVIEW

**Comment by bsclifton** [comment]
Added @cezaraugusto; during our face to face, this was one that he and @mrose17 were talking about.  I believe Cezar had started looking into this

**Comment by bsclifton** [comment]
Per discussion in https://github.com/brave/browser-laptop/issues/7451, we need to set the include flag (since it currently changes include status for items when you toggle auto include on/off- this is very confusing for the user)

**Comment by NejcZdovc** [comment]
Ok so now I did two things:

1) when publisher is added we set it false if auto include is on `off` https://github.com/brave/browser-laptop/pull/7680/commits/c4094cd3646dd97aee3275573bd3be8780edc976#diff-9b959b675446ba95e1abe0b81e0f7a9bR599
2) I updated clean up functionality, which would go through the `undefined` auto include property of the publisher and set it to `true` (we used true for a default fallback in the UI) https://github.com/brave/browser-laptop/pull/7680/commits/c4094cd3646dd97aee3275573bd3be8780edc976#diff-9b959b675446ba95e1abe0b81e0f7a9bR990

This PR is ready for a second review

File: app/ledger.js [hunk 1]
```diff
@@ -981,8 +986,12 @@ var stickyP = (publisher) => {
...
-    result = synopsis.publishers[publisher].options.stickyP
+  if (typeof result === 'undefined') {
+    if (typeof synopsis.publishers[publisher].options.stickyP !== 'undefined') {
+      result = synopsis.publishers[publisher].options.stickyP
+    } else {
+      result = true
+    }
     appActions.changeSiteSetting(pattern, 'ledgerPayments', result)
   }
   delete synopsis.publishers[publisher].options.stickyP
```
Comment (cezaraugusto) [inline app/ledger.js]: I think you need a check here as well. With those changes `synopsis.publishers[publisher]` is still `undefined` at this point. App is crashing for me and pointing on that line.

Worth note: if you have a site in publisher list error doesn't happen. For publishers on exclusion list (such as Youtube), crash is intermittent. Other publishers instantly crash app.

STR: With a fresh profile (no synopsis, no session, no ledger-state), visit a publisher site (i.e. https://clifton.io)

Comment (NejcZdovc) [inline app/ledger.js]: Ok, but why would be failing now. It was outside the if statement before. It was strange for me, but I left it there because it was there before. Will move it inside the if

Comment (cezaraugusto) [inline app/ledger.js]: nice, let's cc @mrose17 for thoughts

Comment (NejcZdovc) [inline app/ledger.js]: @cezaraugusto can you please try again. I rebase it on the master and now I don't have any crashes.

Comment (cezaraugusto) [inline app/ledger.js]: thanks, no crashes this time. However I followed STR and publisher is still auto-including for me as soon as it populates payments panel. 

I did a look inside publisherToggle (only part besides payments that changes publisher state) but state is only changed there if you hit urlbar icon, so it's must come from ledger itself.

IMO you might want something similar to this:
https://github.com/brave/browser-laptop/pull/7289/files#diff-9b959b675446ba95e1abe0b81e0f7a9bL566

Comment (NejcZdovc) [inline app/ledger.js]: It's working for me. Do you have auto include set to off in payments?

Comment (cezaraugusto) [inline app/ledger.js]: yep. It works until ledger recognizes it as a publisher. Once it does, publisher is set as enabled:

I did two checks on payments panel (shown in GIF below), on first try publisher wasn't there yet, so it was set as disabled. Once payments can _see_ the publisher, it gets enabled.

auto_include_gif

Comment (cezaraugusto) [inline app/ledger.js]: yep, I removed last comment with wrong video showing STR. After your update it's working fine.

What I saw is that, if you have a clear session with a synopsis file, publishers you had previously are affected by changing auto-suggest, which should only be applied for new publishers:

STR:
1. remove session-store file
2. keep ledger-synopsis.json (supposing it has publishers)

gif_auto_include_old_synopsis

I suppose auto-include should only apply for new publishers and not for existing ones? If I'm wrong then PR is good to go ;)

Comment (NejcZdovc) [inline app/ledger.js]: No this is something that needs to be fixed. I have implemented this, but it's causing a crash for some X reason (you noticed this in your first comment). So I removed it for now and will try to find a solution today

Comment (NejcZdovc) [inline app/ledger.js]: @cezaraugusto I changed the logic now, can you please try it again

**Comment by NejcZdovc** [comment]
@bsclifton PR is ready now for a review
