### PR TITLE
Use 'PDF Viewer' instead of 'chrome-extension://...' for notifications

### LINKED ISSUE #11020: PDF Presentation Mode banner lists Chrome Extension
### Description
When you have a PDF open and select the 'Switch to Presentation Mode' button, the notification banner displays 'Allow chrome-extension://jdbefljfgobbmcidnmpjamcbhnbphjnb to use fullscreen mode?'. This is confusing, I as expecting it to say something like 'PDF Viewer' instead of 'chrome-extension...'.

### Steps to Reproduce

  1. Open a PDF/Navigate to a PDF.
  2. Click on the 'Switch to Presentation Mode' button.
  3. Banner displays.

**Actual result:**
screen shot 2017-09-19 at 3 47 13 pm

**Expected result:**
Banner should still display, but say something like 'PDF Viewer' instead of 'chrome-extension...'

**Reproduces how often:** 
every time.

### Brave Version
Brave | 0.18.36
rev | 7ab85e9
Muon | 4.3.22

### PR DESCRIPTION
**Pull request by diracdeltas**
fix #11020

Test Plan:
1. open any PDF in Brave
2. click the fullscreen button
3. the notification should say 'Allow PDF Viewer to use fullscreen?'

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/filtering.js [hunk 1]
```diff
@@ -422,12 +422,13 @@ function registerPermissionHandler (session, partition) {
     // TODO(bridiver) - the permission handling should be converted to an action because we should never call `appStore.getState()`
     // Check whether there is a persistent site setting for this host
     const appState = appStore.getState()
+    const isBraveOrigin = origin.startsWith(`chrome-extension://${config.braveExtensionId}/`)
+    const isPDFOrigin = origin.startsWith(`${pdfjsOrigin}/`)
```
Comment (ayumi) [inline app/filtering.js]: minor: this differs slightly from the other usage in [frame.js](https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L631) where [`pdfjsOrigin` includes the trailing `/`](https://github.com/brave/browser-laptop/blob/master/app/renderer/components/frame/frame.js#L60)
