### PR TITLE
fix "Cannot read property 'size' of undefined" error when getting persistent state

### LINKED ISSUE #7466: updating from 0.13.4 to 0.13.5 RC(1, 2) loses session-store-1 data
platform: OS X

when i update from 0.13.4 to 0.13.5 RC 1 or 2, most of my browser data (history, bookmarks, preferences, tabs, etc.) disappear. session-store-1 goes from 900+ KB to 27 KB.

this does not happen when upgrading to Preview 3, so the culprit is somewhere between 7373a01 and 0e68342

STR:
1. open 0.13.4, add some preferences and bookmarks
2. upgrade to 0.13.5 RC
4. open browser, observe that preferences and bookmarks are gone

### PR DESCRIPTION
**Pull request by diracdeltas**
When upgrading from 0.13.4 to 0.13.5, this was causing getting persistent state
to fail on startup, thereby losing session state. Fix #7466

Test Plan:
1. copy your session-store-1 from Brave 0.13.4 into the brave-development profile folder
2. npm start
3. Brave should show bookmarks, settings, pinned tabs, etc from the 0.13.4 profile

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

File: test/unit/app/common/state/tabStateTest.js [hunk 1]
```diff
@@ -483,6 +483,10 @@ describe('tabState unit tests', function () {
       const expectedAppState = defaultAppState.set('tabs', tabsWithoutField)
       assert.deepEqual(newAppState, expectedAppState)
     })
+    it('returns the state (unchanged) if tabs is falsey', function () {
+      const newAppState = tabState.removeTabField(defaultAppState, 'loginRequiredDetail')
```
Comment (diracdeltas) [inline test/unit/app/common/state/tabStateTest.js]: seems that you would want defaultAppState without the `tabs` field for this test?

Comment (diracdeltas) [inline test/unit/app/common/state/tabStateTest.js]: otherwise lgtm

Comment (bsclifton) [inline test/unit/app/common/state/tabStateTest.js]: yup! it gets passed as input- the `tabState` handle is just the reference to what got exported in `app/common/state/tabState.js`

Comment (bsclifton) [inline test/unit/app/common/state/tabStateTest.js]: Fixing!

Comment (bsclifton) [inline test/unit/app/common/state/tabStateTest.js]: Fixed- that variable exists in other files (with other states- whoops!). Thanks for catching 😄
