### PR TITLE
Polish messageBox.js

### LINKED ISSUE #10119: Line break not recognized in alert window
## Test plan

https://github.com/brave/browser-laptop/pull/10835#issue-255831775

----

- Did you search for similar issues before submitting this one?
Yes, mostly a dupe issue

- Describe the issue you encountered:
Line break not recognized in alerts

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.17.19
-- | --
rev | 4e46480
Muon | 4.1.9

- Steps to reproduce:
    1. Visit https://jsfiddle.net/9o5tmgst/1/
    2. See horribly formatted text on the alert window
    3.
    
- Actual result:
Line break not recognized in alert window

- Expected result:
Should respect line breaks and show content properly

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes, could be a regression so needs triage

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image
image

- Any related issues:
cc: @luixxiul @bsclifton

### PR DESCRIPTION
**Pull request by luixxiul**
Add white-space: pre-wrap to fix #10119
Remove redundant styles

Auditors: @cezaraugusto

Test Plan:
1. Open https://jsfiddle.net/9o5tmgst/1/
2. Make sure the lines are wrapped
3. Open https://jsfiddle.net/c5o7arqu/
3. Make sure everything is properly alinged

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/common/messageBox.js [hunk 1]
```diff
@@ -162,34 +161,31 @@ class MessageBox extends React.Component {
 }
 
 const styles = StyleSheet.create({
-  dialog: {
-    outline: 'none'
```
Comment (luixxiul) [inline app/renderer/components/common/messageBox.js]: Dialog has this style thanks to https://github.com/brave/browser-laptop/commit/2c3126f6f641ab9762f36dad558580e379667cf9#diff-5d3d90fdb0c3efa6acd09057f2d4b101R85 (messageBox is focused by default).

File: app/renderer/components/common/messageBox.js [hunk 2]
```diff
@@ -162,34 +161,31 @@ class MessageBox extends React.Component {
...
-  },
-  container: {
-    outline: 'none',
```
Comment (luixxiul) [inline app/renderer/components/common/messageBox.js]: div has outline: none by default.

File: app/renderer/components/common/messageBox.js [hunk 3]
```diff
@@ -162,34 +161,31 @@ class MessageBox extends React.Component {
...
-    display: 'flex',
-    flexDirection: 'column',
-    justifyContent: 'space-between'
```
Comment (luixxiul) [inline app/renderer/components/common/messageBox.js]: divs are aligned vertically by default so I think those are not necessary.
