### PR TITLE
More robust next tab selection after closing an active tab

### LINKED ISSUE #11526: Tabs Settings option doesn't work correctly after 0.19.48 update
Have you searched for similar issues? Yes. Edit: I found a separate issue #11632 of the preview issue which I initially thought was a result of the tab bar not working correctly.

### Description

I've noticed an error in the tab area, which is when you've got 'Select the next tab' chosen in 'When closing an active tab:', it seems to skip or jump a tab every time you close a tab and it if you've got the 'Show tab preview on hover', after it jumps a tab, it shows a preview of the actual tab it should be on without even moving the mouse over tab.

As a matter of fact I don't think any of the options available in 'When closing an active tab' in about:preferences#tabs is functional.

### Steps to Reproduce

Select 'Show tab previews on hover' and right-click and open several youtube videos and I think you'll get a better understanding of it and or open around a dozen or so links and begin closing them. 
As I mentioned above, I don't think it matters if you've got 'Select the next tab' or 'Select its parent tab' selected, you should encounter exactly the same results.

**Expected result:**  A comment of expectation has been made here - https://community.brave.com/t/new-tabs-vs-closing-tabs/8748

**Reproduces how often:** 100%

### Brave Version

Brave: 0.19.48 
rev: de939f6dcd1647f43de544b22dfdd103585b4ec2 
Muon: 4.4.28 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: Microsoft Windows 
OS Release: 10.0.15063 
OS Architecture: x64

**Reproducible on current live release:**

Is this a problem with the live build? Yes.

### Additional Information

I didn't want to create another issue as I may be incorrect but previously (I'm probably wrong) whenever I used to to accidentally tear of a tab, closing the tab in the accidentally created new window and pressing Ctrl and T used to re-attach it to the main window and back to its original position, where as now, not only does it not go back to it's original position but it also doesn't display the website the tab was on as it currently displays the Brave dashboard.

### LINKED ISSUE #11981: Closing tab switches to the second tab from root tab
### Description
Closing tab switches to the second tab from root tab

### Steps to Reproduce
   1. Open 3 tab pages
   2. Close a tab 
   3. Second tab from closed tab is set to focus instead of the immediate tab next to the closed one

**Actual result:**

**Expected result:**
Should set focus to the immediate tab 

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.93
-- | --
rev | d2708a0
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

### Additional Information
https://github.com/brave/browser-laptop/issues/11632#issuecomment-344521477
cc: @cezaraugusto

### PR DESCRIPTION
**Pull request by petemill**
Set next active tab before closing, instead of after. Avoids race-condition with muon's index-change and active-change tab update events.

Fix #11981
Fix #11526

Notable changes:
- *remove* setting next active tab id in tabReducer, due to out-of-date tab state
- **tab creation:** store the opener tabId
- **tab set-active:** remember the history of active tabs
- **tab will-destroy:** remove the tabId from the history of active tabs, and override muon's next active tab, if appropriate
- **tab did-detach:** remove the opener for the detached tab, and remove the tab from active tabs window history

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

### Automatic Tests

`npm run unittest -- --grep "tabs API"`

### Manual Tests
Manual steps (perform on all platforms since this bug was timing-specific and affected Windows mostly).

_All automatic tab active changes should be observed as immediate, without visually seeing one tab become active and then quickly another tab getting focus._

#### Parent tab
- Preferences: detault (When closing an active tab, select its parent tab)
- Open the new tab page
- Cmd-click all the top sites icons to open 'child' tabs
- Switch active focus to the 3rd tab
- Close the 3rd (current) tab
- Expected: Tab active focus switches to the 1st tab (new tab page)

#### Next tab
- Close the (active) new tab page
- Expected: Tab active focus switches to the tab that was 2nd, and now is 1st
- Preferences: When closing an active tab Select the next tab
- Open the new tab page
- Cmd-click all the top sites icons to open 'child' tabs
- Switch active focus to the 3rd tab
- Close the 3rd (current) tab
- Expected: Tab active focus switches to the tab that was 4th, and is now 3rd

#### Last active tab
- Preferences: When closing an active tab Select the last viewed tab
- Open at least 5 tabs
- Make the 1st tab active
- Make the 3rd tab active
- Make the last tab active
- Close the currently-active tab (the last tab)
- Expected: Tab active focus switches to the 3rd tab
- Close the currently-active tab (the 3rd tab)
- Expected: Tab active focus switches to the 1st tab
- Close the currently-active tab (the 1st tab)
- Expected: Tab active focus switches to the 2nd tab

#### Detached parent tab
- Preferences: detault (When closing an active tab, select its parent tab)
- Open the new tab page
- Cmd-click all the top sites icons to open 'child' tabs
- Detach the parent tab (the first tab) to a new window
- Open another tab in the new window and keep it active (so the original parent is **in**active in the new window)
- In the _original_ window, switch active focus to the 3rd tab in the original window
- Close the 3rd (current) tab
- Expected: Tab active focus switches to the 4th tab in the first window, and no change of active tab changes in the second window, i.e. the parent tab is **not** made active.

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: app/browser/activeTabHistory.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
+// static
```
Comment (bsclifton) [inline app/browser/activeTabHistory.js]: can we put the standard preamble at the top of this file?

File: app/browser/tabs.js [hunk 2]
```diff
@@ -8,14 +8,13 @@ const tabActions = require('../common/actions/tabActions')
...
 const tabState = require('../common/state/tabState')
-const windowState = require('../common/state/windowState')
 const {app, BrowserWindow, extensions, session, ipcMain} = require('electron')
 const {makeImmutable, makeJS} = require('../common/state/immutableUtil')
 const {getTargetAboutUrl, getSourceAboutUrl, isSourceAboutUrl, newFrameUrl, isTargetAboutUrl, isIntermediateAboutPage, isTargetMagnetUrl, getSourceMagnetUrl} = require('../../js/lib/appUrlUtil')
 const {isURL, getUrlFromInput, toPDFJSLocation, getDefaultFaviconUrl, isHttpOrHttps, getLocationIfPDF} = require('../../js/lib/urlutil')
 const {isSessionPartition} = require('../../js/state/frameStateUtil')
 const {getOrigin} = require('../../js/lib/urlutil')
-const {getSetting} = require('../../js/settings')
+const settingsStore = require('../../js/settings')
```
Comment (bsclifton) [inline app/browser/tabs.js]: Any specific reason for changing this? (just curious - I didn't see any other functions from settingsStore being called)

Comment (petemill) [reply app/browser/tabs.js]: @bsclifton I changed this so I could register a stub for `getSetting`. I couldn't see another way to do it unfortunately, but if there's a way to do it whilst preserving the ability to directly reference the child function of the `settingsStore` object in the module, I'd be keen to learn. The function is stubbed with the following:

```
+      this.stubGetSettings = sinon.stub(this.settings, 'getSetting',
+        (settingKey, settingsCollection, value) => {
+          if (settingKey === settings.TAB_CLOSE_ACTION) {
+            return tabCloseSettingValue
+          }
+          return false
+        }
+      )
+    })
```

File: app/browser/activeTabHistory.js (hunk 1 above)
Comment (petemill) [reply app/browser/activeTabHistory.js]: done, and rebased

**Comment by bsclifton** [comment]
master 9b4ccd024ad261b643bfc92944365c49ea5379d2
0.21.x cb0b638700bb255f6d8e6e2b2964ac26e83f2060
