### PR TITLE
Fixes bitcoinDashboard rendering

### LINKED ISSUE #8359: Clicking ledger register button breaks add funds button
**Describe the issue you encountered:** Clicking ledger register button breaks add funds button.

````
generate.js:169 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at generateCSS (generate.js:169)
    at injectStyleOnce (inject.js:167)
    at injectAndGetClassName (inject.js:250)
    at css (exports.js:146)
    at BitcoinDashboard.render (bitcoinDashboard.js:344)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
    at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
    at ReactCompositeComponentWrapper.performInitialMount (ReactCompositeComponent.js:362)
    at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:258)
    at Object.mountComponent (ReactReconciler.js:46)
````

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32bit

- Brave Version (revision SHA): 0.14.2 RC2

- Steps to reproduce:
    1. Open https://jsfiddle.net/LnwtLckc/5/
    2. Click "register" and then choose "Allow"
    3. Open about:preferences#payments
    4. Click "Add funds"

- Expected result: "Transfer BTC" button should be displayed on the modal dialog

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x]  Ran `git rebase -i` to squash commits (if needed).

Resolves #8359

Auditors: @bsclifton @luixxiul

Test Plan:
- Open https://jsfiddle.net/LnwtLckc/5/
- Click "register"
- Open about:preferences#payments
- Click "Add funds"

### CODE REVIEW

File: app/renderer/components/preferences/payment/bitcoinDashboard.js [hunk 1]
```diff
@@ -341,7 +341,7 @@ class BitcoinDashboard extends ImmutableComponent {
                         {/* TODO: refactor button.js */}
                         <Button className={cx({
                           primaryButton: true,
-                          [css(globalStyles.spacing.dialogInsideMargin)]: true
+                          [css(styles.bitcoinAddressButton)]: true
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: I would instead set `styles.dialogInsideMargin` here and under [L378](https://github.com/brave/browser-laptop/pull/8382/files#diff-799b11467a9bfc86f7dbbf11fcaee159R378) which is for me more understandable (as long as there is no styles specific to `bitcoinAddressButton`).

Comment (NejcZdovc) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: we can change a name, but one problem with this name is that is really generic and we only need margin bottom here. What happens if you would need margin top and bottom in this component?

Comment (luixxiul) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: `dialogInsideMarginTop` and `dialogInsideMarginBottom`.

As this is not a big change, I'm not strongly against bitcoinAddressButton.

Comment (luixxiul) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: In BEM it should be `dialogInsideMargin--top` and `dialogInsideMargin--bottom` anyway.

Comment (NejcZdovc) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: let's use BEM then

**Comment by NejcZdovc** [comment]
@luixxiul renamed

**Comment by luixxiul** [comment]
@cezaraugusto in this case should they be with `__` or `--`?

**Comment by NejcZdovc** [comment]
Because it's JS variable we can't use dash

File: app/renderer/components/preferences/payment/bitcoinDashboard.js (hunk 1 above)
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/bitcoinDashboard.js]: @NejcZdovc @bsclifton could you both left a comment on https://github.com/brave/browser-laptop/issues/8340 regarding BEM? We should standardize our Aphrodite stuff as soon as we can to avoid future rework. @luixxiul left some great insights there.
