### PR TITLE
Handle failure in creating a state diff by logging (and crash-reporting) the full path of any keys that are null

### LINKED ISSUE #13239: If state contains a [null] key, all actions will fail with little log evidence
### Description
It's possible, although undesired, to have a javascript object or Immutable Map with a key of [null]. This causes immutabediff to throw an error as it only supports strings as keys. This then further causes all subsequent state updates to not be sent to renderer windows, and a crash log to be generated upon every single action, which halts the browser momentarily.

One instance of this was caught and fixed in #13234, but there could be more, and if there are, we should log and report something more helpful, such as the exact key path where a null key was found.

### PR DESCRIPTION
**Pull request by petemill**
A null key path was fixed in #13234, but there may be other cases, so we should add better logging to the console and for the crash reports.

Performance should be unaffected since v8 can now optimize functions which contain a try...catch block.

Fix #13239

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
This should cause no change in functionality, or extra log lines.
If a dev really wants to check the output in error conditions, they can force a null key path in the state, for example in appStore.js at the top of the `emitChanges` function:
`appState = appState.setIn(['historySites', null], Immutable.fromJS({ hello: 'a' }))`

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
master a4a04cce5db7cc14e6321ab5dd53a3621924b9de
0.22.x dcba3feda93a22b375368242bce3d7c5d0a82268
0.21.x 8fc13f553b46ac83a1cb3613aa21cc02009970d1

File: js/stores/appStore.js [hunk 1]
```diff
@@ -80,8 +80,27 @@ class AppStore extends EventEmitter {
...
-      if (!d.isEmpty()) {
+      let d
+      try {
+        d = diff(this.lastEmittedState, appState)
+      } catch (e) {
+        console.error('Error getting a diff from latest state.')
+        // one possible reason immutablediff can throw an error
+        // is due to null keys, so let's log any that we find
+        const nullKeyPaths = findNullKeyPaths(appState)
+        const error = (typeof e === 'object')
```
Comment (bridiver) [inline js/stores/appStore.js]: I think we should be more specific about the type of error before we do a null key check. We don't want to assume that all exceptions are this specific issue.

File: app/common/state/immutableUtil.js [hunk 2]
```diff
@@ -45,6 +45,22 @@ const api = {
...
+    if (!Immutable.Map.isMap(state) && !Immutable.List.isList(state)) {
+      return nullKeys
+    }
+    for (const key of state.keySeq()) {
+      const keyPath = [...pathToState, key]
+      if (key === null) {
+        nullKeys.push(keyPath)
+      }
+      // recursive, to find deep keys
+      nullKeys.push(...api.findNullKeyPaths(state.get(key), keyPath))
```
Comment (bridiver) [inline app/common/state/immutableUtil.js]: recursion will be substantially more expensive than iteration to go through all the keys

Comment (petemill) [reply app/common/state/immutableUtil.js]: Is it worth spending the time to get this for...of...recurse loop into a flat iteration loop considering that if this code gets run the app is in an unusable state anyway?

File: js/stores/appStore.js (hunk 1 above)
Comment (petemill) [reply js/stores/appStore.js]: The trouble is that immutablediff does not throw an error object, just a (dynamic) string. This is the only case I've seen immutablediff fail so far, and I did not want to go down the route of either:
- parsing the string, since it could change in a later immutablediff version
- assuming string vs Error object would mean a null-key error, since that could also change

Again, since the app will be unusable in this state, I wanted to err on the side of caution with regards to making sure we get the right error output and reported, so that we can solve the issue. But happy to take advice on this.

File: app/common/state/immutableUtil.js (hunk 2 above)
Comment (petemill) [reply app/common/state/immutableUtil.js]: So... I was intrigued by the challenge, and tested what I came up with for a non-recursive function. It runs ~30% slower than the recursive one https://jsperf.com/immutable-find-null-paths-recursion-vs-iteration  Perhaps someone can improve on it.

image

**Comment by bsclifton** [comment]
0.20.x 2c3f9751fad5525cef0cd7a883777dc14e844e18
