### PR TITLE
Fixes duplicated root domains

### LINKED ISSUE #9827: Redundant Suggestions
## Test plan

See below

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Identical history suggestions are offered.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
https://github.com/brave/browser-laptop/commit/f7242c7ae683191b59388f567ccbd13d938b23d4

- Steps to reproduce:
I visit TweetDeck often. I assume you need only do the same in order to reproduce.

TweetDeck URLs show up in a couple different frame histories in my session-store-1 file:

```
"history": [
	"https://tweetdeck.twitter.com/#",
	"https://tweetdeck.twitter.com/#",
	"https://tweetdeck.twitter.com/"
],
…
"history": [
	"https://tweetdeck.twitter.com/#",
	"https://tweetdeck.twitter.com/#"
],
```
    
- Actual result:
Identical history suggestions are offered.

- Expected result:
Suggestions should be a list of unique domains.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
N/A

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:

image

### LINKED ISSUE #10826: Url bar autocomplete has duplicated entries
**Describe the issue you encountered:**

```
  20) urlBar tests autocomplete suffix should clear when it is not a prefix match:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23

  21) urlBar tests autocomplete press escape key "before each" hook for "does select the urlbar text":
     Error: element (".urlBarSuggestions li") still not existing after 10000ms
      at elements(".urlBarSuggestions li") - isExisting.js:46:17
      at isExisting(".urlBarSuggestions li") - waitForExist.js:67:22

  22) urlBar tests autocomplete highlight suggestions with tab autofills from selected suggestion:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23

  23) urlBar tests autocomplete highlight suggestions autofills from selected suggestion:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23
```

@diracdeltas can you please check if this is a problem in the test or we regressed

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #10826
Resolves #9827

Auditors:

Test Plan: specified in #9827

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
travis is passing now for all related tests

```
  20) urlBar tests autocomplete suffix should clear when it is not a prefix match:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23

  21) urlBar tests autocomplete press escape key "before each" hook for "does select the urlbar text":
     Error: element (".urlBarSuggestions li") still not existing after 10000ms
      at elements(".urlBarSuggestions li") - isExisting.js:46:17
      at isExisting(".urlBarSuggestions li") - waitForExist.js:67:22

  22) urlBar tests autocomplete highlight suggestions with tab autofills from selected suggestion:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23

  23) urlBar tests autocomplete highlight suggestions autofills from selected suggestion:
     Error: Promise was rejected with the following reason: timeout
      at elements("#urlInput") - getValue.js:18:17
      at getValue("#urlInput") - brave.js:523:23
```

File: app/common/lib/siteSuggestions.js [hunk 1]
```diff
@@ -25,7 +26,10 @@ const getSiteIdentity = (data) => {
   if (typeof data === 'string') {
     return data
   }
-  return (data.get('location') || '') + (data.get('partitionNumber') ? '|' + data.get('partitionNumber') : '')
+
+  let location = data.get('location') || ''
+  location = urlUtil.stripLocation(location)
+  return location + (data.get('partitionNumber') ? '|' + data.get('partitionNumber') : '')
```
Comment (jonathansampson) [inline app/common/lib/siteSuggestions.js]: We should avoid doing multiple lookups.

```js
let location = data.get('location') || ''
let partitionNumber = data.get('partitionNumber')
return location + (partitionNumber ? '|' + partitionNumber : '')
```

Comment (NejcZdovc) [reply app/common/lib/siteSuggestions.js]: done

File: js/lib/urlutil.js [hunk 2]
```diff
@@ -441,6 +441,13 @@ const UrlUtil = {
       return parsed.slashes ? [parsed.protocol, parsed.host].join('//') : [parsed.protocol, parsed.host].join('')
     }
     return null
+  },
+
+  stripLocation: (url) => {
+    return url
+      .replace(/\/*$/, '')  // remove trailing /
+      .replace(/#*$/, '') // remove trailing  #
```
Comment (bbondy) [inline js/lib/urlutil.js]: nit: I think you can combine these into one regex to be faster:
`.replace(/\/?#?$/, '')`

Comment (NejcZdovc) [reply js/lib/urlutil.js]: Now I saw that it would be great to first remove `#` and then `/`, so that would link like `https://tweetdeck.twitter.com/#` become `https://tweetdeck.twitter.com`.

So old code would be changed to:
```
return url
      .replace(/#*$/, '') // remove trailing  #
      .replace(/\/*$/, '')  // remove trailing /
```

@bbondy Can you please update regex to reflect that change. I played around, but could find correct regex?
