### PR TITLE
firstPartyUrl can be missing in some cases

### LINKED ISSUE #12939: sometimes Brave crashes when closing
### Description
Sometimes after closing Brave, the 'Brave unexpectedly quit' message displays.

### Steps to Reproduce

  1. Use Brave normally.
  2. Quit Brave.
  3.

**Actual result:**
Sometimes Brave crashes when closing.

**Expected result:**
Brave should not crash on close.

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
Brave | 0.20.27
V8 | 6.4.388.40
rev | 76102c5
Muon | 4.7.9
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 64.0.3282.119

**Reproducible on current live release:**
Possibly, also unknown

### PR DESCRIPTION
**Pull request by bridiver**
fix #12939

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/filtering.js [hunk 1]
```diff
@@ -693,13 +693,14 @@ const filterableProtocols = ['http:', 'https:', 'ws:', 'wss:', 'magnet:', 'file:
...
-  if (details.firstPartyUrl === 'data:,') {
+  if (details.firstPartyUrl === 'data:,' || details.url === 'data:,') {
     return false
   }
 
   // Ensure host is well-formed (RFC 1035) and has a non-empty hostname
   try {
-    const firstPartyUrl = urlParse(details.firstPartyUrl)
+    // firstPartyUrl can be empty in some cases so fallback to the url
+    const firstPartyUrl = urlParse(details.firstPartyUrl || details.url)
```
Comment (diracdeltas) [inline app/filtering.js]: maybe want to ensure that there's a fallback if details.url is also false
