### PR TITLE
Dismissing browser activity notice when browsing time has met/surpassed 30 minutes

### LINKED ISSUE #14767: Min browsing activity message is retained even after min criteria is met
### Description
Min browsing activity message is retained even after min criteria is met

### Steps to Reproduce
  1. Create staging wallet using `LEDGER_ENVIRONMENT=staging`
  2. Visit a couple of sites to add to ledger entry keeping browsing time less (ex: 10 mins)
  3. Trigger reconcile by changing `reconcileStamp` in ledger-state.json
  4. Relaunch browser, ensue the min activity message is shown and recocile date is pushed ahead
  5. Complete 30 mins of browsing activity with the sites listed in ledger table
  6. Message doesn't change until a next reconcile happens

**Actual result:**
image

**Expected result:**
Once min browsing time is met, message should change to `Your Wallet is ready` if balance matches budget or `Your account balance is under your budget for this month. Please add funds.` if balance is less than budget 

**Reproduces how often:**
100%

### Brave Version

Brave | 0.23.37
-- | --
V8 | 6.7.288.46
rev | 47b1b59
Muon | 7.1.6
OS Release | 10.0.17134
Update Channel | Release
OS Architecture | x64
OS Platform | Microsoft Windows
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 67.0.3396.103

**Reproducible on current live release:**
Not checked as unable to trigger reconcile with env variables

### Additional Information
cc: @jasonrsadler @NejcZdovc 
Reloading payment page, disable/enable payments, reopen payments tab doesn't refresh the message. It only dismiss when a new reconcile is triggered.

### PR DESCRIPTION
**Pull request by ryanml**
Fixes #14767

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
Test plan is defined in #14767 

The test plan should also be run through with varying ledger statuses, such as `CORRUPTED_SEED` and `SERVER_PROBLEM`, to ensure that those are not incorrectly dismissed when browsing time is met.

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -1113,6 +1113,37 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
   }
 
   state = addNewLocation(state, location, tabId, keepInfo)
+  appActions.onCheckBrowserActivityTime()
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: Do we need appAction? you have state that you need in this function

File: app/browser/api/ledger.js [hunk 2]
```diff
@@ -1113,6 +1113,37 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
...
+  const minTime = 30 * ledgerUtil.milliseconds.minute
+  const publisherKeys = Object.keys(synopsis.publishers)
+
+  if (publisherKeys.length === 0) {
+    return state
+  }
+
+  // Check cached browsing time to avoid unneeded recalculation
+  const ledgerStatus = ledgerState.getAboutProp(state, 'status')
+  const curBrowsingTime = ledgerState.getAboutProp(state, 'browsingTime') || 0
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: Please add this prop into state.md

Comment (ryanml) [reply app/browser/api/ledger.js]: @NejcZdovc added

File: app/browser/api/ledger.js (hunk 1 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: could you have large publisher set with less then 30min?

File: app/browser/api/ledger.js [hunk 3]
```diff
@@ -1113,6 +1113,37 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
...
+  if (curBrowsingTime >= minTime && ledgerStatus !== ledgerStatuses.FUZZING) {
+    return state
+  }
+
+  const browsingTime = publisherKeys.reduce((acc, key) => {
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: Can we optimize this one to stop counting when you are over 30min?

File: app/browser/api/ledger.js (hunk 1 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: I guess if you set visit time to min, then table could be quite big before you reach 30min. Let's keep it like you have it

File: app/browser/api/ledger.js [hunk 4]
```diff
@@ -1117,6 +1119,36 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
   return state
 }
 
+const checkBrowserActivityTime = (state) => {
+  // Fuzzing threshold
+  const minTime = 30 * ledgerUtil.milliseconds.minute
+  const publisherKeys = Object.keys(synopsis.publishers)
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: We should be getting publishers from the state and not synopsis

Comment (ryanml) [reply app/browser/api/ledger.js]: done

File: app/browser/api/ledger.js [hunk 5]
```diff
@@ -1117,6 +1119,38 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
...
+const checkBrowserActivityTime = (state) => {
+  // Fuzzing threshold
+  const minTime = 30 * ledgerUtil.milliseconds.minute
+  const publishers = ledgerState.getPublishers(state)
+
+  if (publishers.isEmpty()) {
+    return state
+  }
+
+  const publisherKeys = Array.from(publishers.keys())
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: This one can be removed and do a reducer directly on `publishers` list.

File: app/browser/api/ledger.js [hunk 6]
```diff
@@ -1117,6 +1119,38 @@ const pageDataChanged = (state, viewData = {}, keepInfo = false) => {
...
+  const ledgerStatus = ledgerState.getAboutProp(state, 'status')
+  const curBrowsingTime = ledgerState.getAboutProp(state, 'browsingTime') || 0
+
+  // Check cached browsing time to avoid unneeded recalculation
+  if (curBrowsingTime >= minTime && ledgerStatus !== ledgerStatuses.FUZZING) {
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: We should do browser activity check only if `ledgerStatuses` is `FUZZING`

`if (curBrowsingTime >= minTime || ledgerStatus !== ledgerStatuses.FUZZING) {`

File: app/browser/api/ledger.js (hunk 5 above)
Comment (ryanml) [reply app/browser/api/ledger.js]: `publishers` is a `Map`, `reduce` should only work on Arrays or other iterables, can we leave this one?

File: app/browser/api/ledger.js (hunk 6 above)
Comment (ryanml) [reply app/browser/api/ledger.js]: In the current conditional, the activity calculation is not done and state is returned as `curBrowsingTime >= minTime && ledgerStatus !== ledgerStatuses.FUZZING` are the requirements. So it will proceed with the check if `ledgerStatus !== ledgerStatuses.FUZZING` or am I missing something?

File: app/browser/api/ledger.js (hunk 5 above)
Comment (ryanml) [reply app/browser/api/ledger.js]: done

**Comment by ryanml** [comment]
@NejcZdovc changes addressed.

I did have to move back the `appAction` call from `paymentPresent` to `pageDataChanged.` It was not being called on tab switch, so you could accrue 30 minutes, tab back over to payments, and not see the fuzzing status go away.

**Comment by NejcZdovc** [comment]
master 1380864
0.24 6b1dc02f0 
0.23 7370c818c
