### PR TITLE
Reduce redundant siteSort to sort once and used everywhere

### LINKED ISSUE #7240: Browser performance reduces when large amount of bookmarks are imported
## Test plan

https://github.com/brave/browser-laptop/pull/8075#issue-219459882

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Browser performance reduces when large amount of bookmarks are imported

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.3
rev	27f447f
Same on 0.13.2 as well

- Steps to reproduce:
    1. Import a large bookmark HTML file 
    2. Open new tabs and open from bookmarks
    3. Open bookmark folders, response on click is too slow
    
- Actual result:
Performance is very slow after large amount of bookmarks are imported

- Expected result:
Imported bookmarks should not impact browser performance

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
0.13.2 http://sendvid.com/ekjiz2cv
0.13.3 http://sendvid.com/0q3t3iey

- Any related issues:
[Community issue](https://community.brave.com/t/system-requirements-brave-slow-sluggish-on-one-computer-but-not-on-another/1212)
cc: @darkdh 
Please change milestone if required

### PR DESCRIPTION
**Pull request by darkdh**
fix #7240

Auditors: @bbondy, @bsclifton

Test Plan:
1. Import bunch of bookmarks
2. Open bookmarks of menu shouldn't affect performance
3. Open about:bookmarks shouldn't affect performance

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

**Comment by bbondy** [comment]
++ please rebase and merge

**Comment by darkdh** [comment]
rebased. please review again.

File: js/stores/appStore.js [hunk 1]
```diff
@@ -255,7 +255,10 @@ class AppStore extends EventEmitter {
 
   emitChanges (emitFullState) {
     if (lastEmittedState) {
-      const d = diff(lastEmittedState, appState)
+      // diff and patch will make map out of order so toList() is to maintain
+      // sites map order
+      const diffAppState = appState.set('sites', appState.get('sites').toList())
```
Comment (darkdh) [inline js/stores/appStore.js]: We need a better way to deal with the our of order.
This will cause significant slowness

Comment (bsclifton) [inline js/stores/appStore.js]: ☹️

**Comment by bsclifton** [comment]
@darkdh is this still a WIP? Sorry for not reviewing earlier ☹️

**Comment by darkdh** [comment]
sorry, this is waiting for shared app state change landed

**Comment by luixxiul** [comment]
@darkdh after resolving the conflicts and if it's ready for review, would you mind adding the label? thanks!

**Comment by darkdh** [comment]
sure thing

**Comment by NejcZdovc** [comment]
let's wait for tests, but on a first glance it looks good to me

**Comment by darkdh** [comment]
There are two failed test I need to look into
1. tab tests tab order with pinned tabs sequentially by default
2. sitesReducerTest APP_MOVE_SITE Moves the specified site

**Comment by darkdh** [comment]
fix `sitesReducerTest APP_MOVE_SITE Moves the specified site`
and `tab tests tab order with pinned tabs sequentially by default` runs correctly on my local env

File: test/unit/app/browser/reducers/sitesReducerTest.js [hunk 2]
```diff
@@ -149,8 +149,8 @@ describe('sitesReducerTest', function () {
       moveAction.prepend = true
       newState = sitesReducer(Immutable.fromJS(newState), moveAction).toJS()
       assert.equal(Object.keys(newState.sites).length, 3)
-      assert.equal(Object.values(newState.sites)[2].location, url)
-      assert.equal(Object.values(newState.sites)[2].order, 1)
+      assert.equal(Object.values(newState.sites)[1].location, url)
```
Comment (NejcZdovc) [inline test/unit/app/browser/reducers/sitesReducerTest.js]: Is this correct change, because the comment at the top states that site should be at the third position (2), but you changed this value to 1

Comment (darkdh) [inline test/unit/app/browser/reducers/sitesReducerTest.js]: Yes, we will sort sites after ADD, REMOVE, MOVE in this PR

Comment (NejcZdovc) [inline test/unit/app/browser/reducers/sitesReducerTest.js]: If this is correct then I would add some description about it beside this comment, otherwise it could be confusing

Comment (darkdh) [inline test/unit/app/browser/reducers/sitesReducerTest.js]: comment added

**Comment by bbondy** [comment]
Please rebase again @darkdh 
Thanks!

**Comment by darkdh** [comment]
@bbondy, rebased!
