### PR TITLE
Fixed balance conversion for big values

### LINKED ISSUE #12054: USD conversion for wallet balance always shows 1.00
### Description

Essentially despite rates being successfully retrieved, the calculated conversion value is never updated and shows `1.00`:

screen shot 2017-11-15 at 12 21 37 pm

See https://github.com/brave/browser-laptop/issues/11931#issuecomment-344743334 after it was closed for original discussion on this issue.

`LEDGER_VERBOSE=1` logs:
```
[ response for GET https://balance.mercury.basicattentiontoken.org/v2/wallet/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/balance ]                                                                                                        [321/10438]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 207
>>> content-type: application/json; charset=utf-8
>>> date: Wed, 15 Nov 2017 23:24:47 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 57
>>> x-rate-limit-reset: 1510788301
>>>
>>> {"altcurrency":"BAT","probi":"7.309622404968674704085e+21","balance":"7309.6224","unconfirmed":"0.0000","rates":{"BTC":"0.00001966","ETH":0.00042591989579941384,"USD":0.1433458965,"EUR":0.12100429176330299}}
[ response for GET https://mercury-proxy.privateinternetaccess.com/v3/publisher/timestamp ]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 35
>>> content-type: application/json; charset=utf-8
>>> date: Wed, 15 Nov 2017 23:24:47 GMT
>>> server: Cowboy
>>> strict-transport-security: max-age=31536000
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 9007199254740991
>>> x-rate-limit-remaining: 9007199254740990
>>> x-rate-limit-reset: 1510788288
>>>
>>> {"timestamp":"6488746555397373953"}
[ response for GET https://balance.mercury.basicattentiontoken.org/v2/wallet/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/balance ]
>>> HTTP/1.1 200
>>> accept-ranges: bytes
>>> cache-control: private
>>> connection: keep-alive
>>> content-length: 207
>>> content-type: application/json; charset=utf-8
>>> date: Wed, 15 Nov 2017 23:24:47 GMT
>>> server: Cowboy
>>> vary: accept-encoding
>>> via: 1.1 vegur
>>> x-rate-limit-limit: 60
>>> x-rate-limit-remaining: 56
>>> x-rate-limit-reset: 1510788300
>>>
>>> {"altcurrency":"BAT","probi":"7.309622404968674704085e+21","balance":"7309.6224","unconfirmed":"0.0000","rates":{"BTC":"0.00001966","ETH":0.00042591989579941384,"USD":0.1433458965,"EUR":0.12100429176330299}}

getBalance refreshes ledger info: 0
```

### Steps to Reproduce

  1.
  2.
  3.

**Actual result:**

**Expected result:**

**Reproduces how often:**

### Brave Version

Brave: 0.19.93
rev: 25085d0
Muon: 4.5.16
libchromiumcontent: 62.0.3202.94
V8: 6.2.414.42
Node.js: 7.9.0
Update Channel: Release
OS Platform: macOS
OS Release: 16.7.0
OS Architecture: x64

**Reproducible on current live release:**

yes (with @darkdh profile)

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #12054

Auditors:

Test Plan:
- wallet should have some really big amount in it (more then 1k USD)
- check if converted BAT is correct (not showing only 1 USD, but 1000+ USD)

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -1504,7 +1511,7 @@ const onWalletProperties = (state, body) => {
     if (amount != null && rate) {
       const bigProbi = new BigNumber(probi.toString()).dividedBy('1e18')
       const bigRate = new BigNumber(rate.toString())
-      const converted = bigProbi.times(bigRate).toFormat(2)
+      const converted = bigProbi.times(bigRate).toFixed(2)
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: main fix

```
> new bigNum('1234').toFixed(2)
'1234.00'
> new bigNum('1234').toFormat(2)
'1,234.00'
```

**Comment by bsclifton** [comment]
master 2779c310954be9c447dbb30d9b1f9b18b6dce22c
0.21.x 10ac0a99074970db8cce902bec9903483cbd02fb
0.20.x 648afe32d98059c0572bdf4c6a58a7d17fa79b22
0.19.x 818f2fe24cea87fad191f4bb08c4b9f35c6902bb
