### PR TITLE
minimum visits and minduration not persisting when changed

### LINKED ISSUE #4822: Set 2 visits on minimum visit for publisher relevancy and automatically back to 5
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:**

I set 2 visits on minimum visit for publisher relevancy and automatically back to 5

**Expected behavior:**

Keep on 2
- Platform (Win7, 8, 10? macOS? Linux distro?): Ubuntu 64
- Brave Version: Dev Channel Beta v0.12.5dev-RC1
- Steps to reproduce:
  1. Go to preferences/payment
     2.Open advanced settings
  2. Set 2 visits

Obs. See the video uploaded to understand the problem
[Brave.ogv.zip](https://github.com/brave/browser-laptop/files/531172/Brave.ogv.zip)

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #4822

Auditors @mrose17 @bsclifton 

Two things here. One, we were multiplying by 1000 before storing the value but that causes a bug when the (now * 1000) value gets back to the UI. So instead, let's just keep the values in milliseconds.

The second thing is we initially store the minDuration and minimumVisits in ledgerData at the root but then we were saving it to ledgerData.synopsisOptions when it changed so the UI was grabbing the old value!

@bsclifton can you think of a good automated test for this? I know we chatted about it yesterday  but I was struggling to implement something that makes sense!

## Test Plan
1. Start Brave
2. Go to Preferences > Payments
3. Click on Advanced Settings
4. Change Minimum Duration to any new value
5. Close and re-open the Advanced Settings modal
6. Make sure the new value persists
7. Do 4-6 with minimum visits as well

### CODE REVIEW

File: app/ledger.js [hunk 1]
```diff
@@ -143,15 +143,14 @@ const doAction = (action) => {
 
         case settings.MINIMUM_VISIT_TIME:
           if (action.value <= 0) break
-
-          synopsis.options.minDuration = action.value * 1000
```
Comment (mrose17) [inline app/ledger.js]: in order for the ledger code to actually do the pruning, you'll need this line. just remove the "* 1000"

File: app/ledger.js [hunk 2]
```diff
@@ -143,15 +143,14 @@ const doAction = (action) => {
...
+          ledgerInfo.minDuration = action.value
           updatePublisherInfo()
           break
 
         case settings.MINIMUM_VISITS:
           if (action.value <= 0) break
 
-          synopsis.options.minPublisherVisits = action.value
```
Comment (mrose17) [inline app/ledger.js]: in order for the ledger code to actually do the pruning, you'll also need this line.

**Comment by bsclifton** [comment]
Will check this out tonite and give feedback :smile:

File: app/ledger.js (hunk 2 above)
Comment (jkup) [inline app/ledger.js]: @mrose17 ok so the problem right now in master is that it's first stored in ledgerData and then here it's added to ledgerData.synopsisOptions.

If it needs to be in synopsisOptions is the fix moving the initial value from the root of ledgerData?

**Comment by jkup** [comment]
@bsclifton thanks for checking it out!

@mrose17 how is this approach? What if we don't set the duration and the minimum visits on the root object? And instead only set it / look for it in synopsisOptions?

If this doesn't work we can keep it in both places, it just seems unnecessary :)

**Comment by mrose17** [comment]
i agree it would be best to maintain the value in one place. in that case, i think that the place to keep the value is in `var synopsis` and to have the value copied from there in to/from `ledgerData/appData`. does that make sense?

**Comment by jkup** [comment]
@mrose17 ok so take minDuration and minPublisher visits out of synopsis.options and move them into synopsis?

File: app/ledger.js (hunk 1 above)
Comment (bsclifton) [inline app/ledger.js]: @mrose17 this is seconds now right? (previously was milliseconds?)

**Comment by bsclifton** [comment]
The ledger code is distinctly different than the rest of the codebase, which can cause confusion (or at least it does for me).  I think with a little work, we can make this more Redux friendly. Give me a few mins to cook up a change...

**Comment by bsclifton** [comment]
OK the ideas I had ended up being MUCH larger scope once I dug in. Details can be read here if anyone is interested:
https://github.com/brave/browser-laptop/issues/3433#issuecomment-263080542

For this PR, it sounds like we need to update `ledgerInfo` to also have this new value and then trigger an update to persist the values in appState

Would you guys be able to work this out on Slack? :smile: Or if it's easier, we can do a Google hangout tomorrow (let me know, I'll set it up)

**Comment by jkup** [comment]
@mrose17 LGTM!

@bsclifton assuming you ++ I think this one is ready to merge!

**Comment by mrose17** [comment]
agreed. @bsclifton - you get the "final say" !

File: app/ledger.js [hunk 3]
```diff
@@ -580,10 +580,11 @@ var enable = (paymentsEnabled) => {
       // cf., the `Synopsis` constructor, https://github.com/brave/ledger-publisher/blob/master/index.js#L167
       value = getSetting(settings.MINIMUM_VISIT_TIME)
       if (!value) {
-        value = 8
+        value = 8 * 1000
         appActions.changeSetting(settings.MINIMUM_VISIT_TIME, value)
       }
-      if (value > 0) synopsis.options.minDuration = value * 1000
+      // for earlier versions of the code...
+      if ((value > 0) && (value < 1000)) synopsis.options.minDuration = value * 1000
```
Comment (bsclifton) [inline app/ledger.js]: :+1:

**Comment by bsclifton** [comment]
@jkup @mrose17 LGTM! Thanks for working it out :smile: I'll check out the tests here and merge

It **could** use a unit test to help prevent any regressions or unintended altering of the behavior :blush: @jkup if you would be willing to check that out, you could address with a follow up :smile: (logic could be broken out into ledgerUtil for easy testing).  Shouldn't be too bad, just checking the value of `settings.MINIMUM_VISIT_TIME` in the assert

**Comment by bsclifton** [comment]
[Tests finished running](https://travis-ci.org/brave/browser-laptop/builds/179555065); the ones passed when I ran them locally.  Merging! :smile:

**Comment by jkup** [comment]
@bsclifton thanks for the merge! created this https://github.com/brave/browser-laptop/issues/5887
