### PR TITLE
Apply panelItem to addFunds button

### LINKED ISSUE #10141: Apply panelItem to addFunds button
**Describe the issue you encountered:** Apply panelItem to addFunds button.

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open `about:prefences#payments`
    
- Extra QA steps:
    1. Make sure `Add funds...` button looks same as the buttons on add funds modal dialog

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #10141

Auditors: @cezaraugusto

Test Plan:
1. Open `about:prefences#payments`
2. Make sure `Add funds...` button looks same as the buttons on add funds modal dialog

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/enabledContent.js [hunk 1]
```diff
@@ -274,14 +275,6 @@ const styles = StyleSheet.create({
     marginBottom: 0
   },
 
-  addFunds: {
-    minWidth: '180px',
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/enabledContent.js]: this is specified with `panelItem`

File: app/renderer/components/preferences/payment/enabledContent.js [hunk 2]
```diff
@@ -274,14 +275,6 @@ const styles = StyleSheet.create({
...
-    width: 'auto',
-    marginTop: 0,
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/enabledContent.js]: the two properties above are specified with `browserButton_default` and `browserButton`

File: app/renderer/components/preferences/payment/enabledContent.js [hunk 3]
```diff
@@ -274,14 +275,6 @@ const styles = StyleSheet.create({
...
-    paddingTop: '6px',
-    paddingBottom: '6px'
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/enabledContent.js]: the two properties above are replaced with ones of `browserButton_default`

**Comment by srirambv** [comment]
>Make sure Add funds... button looks same as the buttons on add funds modal dialog 

Buttons on the modal are not primary buttons. Whats the reference here?

**Comment by luixxiul** [comment]
The add fund dialog has been replaced so there's nothing to check about.
