### PR TITLE
Reset old reconcileStamp when re-enabling Payments

### LINKED ISSUE #4058: Brave payments wrong contribution date
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
I have enabled Brave payments long ago and disabled it for a while. After re-enabling it again the Next contribution date was in the past.

**Expected behavior:**
The next contribution date should never be in the past.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version:
0.12.1

- Steps to reproduce:
    1.Enable Brave payments
    2. Disable Brave paymetns
    3. Wait several days and re-enable

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by ayumi**
Fix #4058

Auditors: @mrose17

Test Plan:
1. Open Brave
2. Enable Payments then disable
2. Close Brave
3. Edit {userData}/ledger-state.json `reconcileStamp` to be way in the past (change 14.. to 13..)
4. Open Brave
5. Enable Payments
6. Note that contribution date is today + 30 days, rather than way in the past

### CODE REVIEW

File: app/ledger.js [hunk 1]
```diff
@@ -441,9 +448,24 @@ var initialize = (onoff) => {
...
+            state
+          )
+
+          // Scenario: User enables Payments, disables it, waits 30+ days, then
+          // enables it again -> reconcileStamp is in the past.
+          // In this case reset reconcileStamp to the future.
+          if (reason === 'changeSettingPaymentsEnabled') {
+            let timeUntilReconcile = client.timeUntilReconcile()
+            if (typeof timeUntilReconcile === 'number' && timeUntilReconcile < 0) {
+              let futureReconcileStamp = underscore.now() + 30 * msecs.day
```
Comment (mrose17) [inline app/ledger.js]: it is better to call `setTimeUntilReconcile` with a `null` timestamp and let the `ledger-client` package figure out the next time.

File: app/ledger.js [hunk 2]
```diff
@@ -441,9 +448,24 @@ var initialize = (onoff) => {
...
+              client.setTimeUntilReconcile(futureReconcileStamp, callback)
```
Comment (mrose17) [inline app/ledger.js]: you shouldn't use `callback` here, since that's used for `client.sync` ... look at how the call to `setBraveryProperties` does it!

File: app/ledger.js [hunk 3]
```diff
@@ -129,8 +129,15 @@ const doAction = (action) => {
       break
 
     case appConstants.APP_CHANGE_SETTING:
-      if (action.key === settings.PAYMENTS_ENABLED) return initialize(action.value)
-      if (action.key === settings.PAYMENTS_CONTRIBUTION_AMOUNT) return setPaymentInfo(action.value)
+      switch (action.key) {
+        case settings.PAYMENTS_ENABLED:
+          return initialize(action.value, 'changeSettingPaymentsEnabled')
```
Comment (mrose17) [inline app/ledger.js]: probably better to get rid of `return` and add a `break` line -- that would be consistent with everything else in the function.

File: app/ledger.js [hunk 4]
```diff
@@ -129,8 +129,15 @@ const doAction = (action) => {
...
+        case settings.PAYMENTS_CONTRIBUTION_AMOUNT:
+          setPaymentInfo(action.value)
+          break
+        default:
```
Comment (mrose17) [inline app/ledger.js]: thank you for adding the `default` case!

File: app/ledger.js [hunk 5]
```diff
@@ -441,9 +448,24 @@ var initialize = (onoff) => {
         }
 
         getStateInfo(state)
+
         try {
-          client = ledgerClient(state.personaId,
-                                              underscore.extend(state.options, { roundtrip: roundtrip }, clientOptions), state)
+          client = ledgerClient(
```
Comment (mrose17) [inline app/ledger.js]: why did the indentation change?

i agree that line 446 is indented too much, that must have been a slip of the finger. i thought it would be:

          client = ledgerClient(state.personaId,
                                underscore.extend(state.options, { roundtrip: roundtrip }, clientOptions), state)

Comment (ayumi) [inline app/ledger.js]: I think it's clearest to indent the 3 parameters equally

File: app/ledger.js (hunk 1 above)
Comment (ayumi) [inline app/ledger.js]: good idea

File: app/ledger.js (hunk 5 above)
Comment (mrose17) [inline app/ledger.js]: except that this is the only example of that style of indentation in the file...

perhaps we can compromise by putting the first parameter right after the "(", and the ")" right after the final parameter?

Comment (ayumi) [inline app/ledger.js]: that sounds fair

File: app/ledger.js (hunk 2 above)
Comment (ayumi) [inline app/ledger.js]: thanks, i've updated it

**Comment by bbondy** [comment]
mrose said it could be merged now, thanks.
