### PR TITLE
Moved UGP request delay up to 1 minute.

### LINKED ISSUE #14616: UGP promo should not be checked at startup
# Test plan
see https://github.com/brave/browser-laptop/pull/14621 and #14732 

### Description

ledger.js has code for the UGP promo to be sent up right away on startup.
`/v1/grants`

We should be avoiding File IO and network requests at startup time in favour of waiting after some initial delay and/or by lazy loading. 

In this case I think some initial delay similar to how `runtimeUpdateCheckDelay` works should be added in the config. Possibly 2 minutes after startup.

### Steps to Reproduce

  1. Add console.log logging to app/browser/api/ledger.js
  2.Start the browser
  3. Observe output at startup time

**Actual result:**
Network requests happens at startup

**Expected result:**
Network request shouldn't happen directly at startup.

**Reproduces how often:**
Always

### Brave Version
0.23.19 

**about:brave info:**
 
Brave: 0.23.19 
V8: 6.7.288.46 
rev: 178c3fbc045a0cbdbe098db08307503cce952081 
Muon: 7.1.3 
OS Release: 17.5.0 
Update Channel: Release 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Tor: 0.3.3.7 (git-035a35178c92da94) 
Brave Sync: v1.4.2 
libchromiumcontent: 67.0.3396.87

**Reproducible on current live release:**
Yes

### PR DESCRIPTION
**Pull request by jasonrsadler**
Fixes #14616 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
- Start Brave with `LEDGER_VERBOSE=true`
- Ensure promotion url calls do not occur until between 45 and 60 seconds after Brave startup (Look for requests to `v1/grants`).

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

Additional Info:
To quickly test that promos are working in the future add `LEDGER_ENVIRONMENT=staging` when running Brave. Promotion url calls will occur between 10 and 15 seconds.

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -1340,7 +1340,9 @@ const enable = (state, paymentsEnabled) => {
 
     togglePromotionTimeoutId = setTimeout(() => {
       checkPromotions()
-    }, random.randomInt({min: 10 * ledgerUtil.milliseconds.second, max: 15 * ledgerUtil.milliseconds.second}))
+    }, process.env.LEDGER_ENVIRONMENT === 'staging'
+      ? random.randomInt({min: 10 * ledgerUtil.milliseconds.second, max: 15 * ledgerUtil.milliseconds.second})
+      : ledgerUtil.milliseconds.minute)
```
Comment (ryanml) [inline app/browser/api/ledger.js]: I think we should capture this in a common variable (whether in `appConfig` or something scoped only to `ledger.js`) then we can share it between all of the needed delays

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: This variable needs to be random so like 45 to 60s min

Comment (jasonrsadler) [reply app/browser/api/ledger.js]: @ryanml It was told to me in the past that the settings object was for settings exposed in preferences (I know there's things in there that don't adhere to that but I think we want to avoid adding more non-user-exposed items to settings). 

@NejcZdovc done.

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: that's true, appConfig shouldn't have this timers in ther

**Comment by jasonrsadler** [comment]
Revert to WIP to reset interval from internal event.

File: app/browser/reducers/ledgerReducer.js [hunk 2]
```diff
@@ -576,8 +577,17 @@ const ledgerReducer = (state, action, immutableAction) => {
...
+      {
+        state = ledgerApi.onRunPromotionCheck(state, getSetting(settings.PAYMENTS_ENABLED))
+        break
+      }
   }
   return state
 }
 
+process.on(messages.APP_INITIALIZED, (state) => {
+  state = ledgerApi.runPromotionCheck()
```
Comment (NejcZdovc) [inline app/browser/reducers/ledgerReducer.js]: I think that state here is not needed

**Comment by NejcZdovc** [comment]
Please remove package-lock

File: app/browser/api/ledger.js [hunk 3]
```diff
@@ -1340,7 +1338,10 @@ const enable = (state, paymentsEnabled) => {
 
     togglePromotionTimeoutId = setTimeout(() => {
       checkPromotions()
-    }, random.randomInt({min: 10 * ledgerUtil.milliseconds.second, max: 15 * ledgerUtil.milliseconds.second}))
+    }, process.env.LEDGER_ENVIRONMENT === 'staging'
+      ? random.randomInt({min: 10 * ledgerUtil.milliseconds.second, max: 15 * ledgerUtil.milliseconds.second})
+      : random.randomInt({min: 60 * ledgerUtil.milliseconds.second, max: 90 * ledgerUtil.milliseconds.second})
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: I think this is not needed any more, because we trigger check only after init is done, so we can stay with 10-15sec

cc @bbondy

Comment (bbondy) [reply app/browser/api/ledger.js]: I prefer the longer one but if there are strong objections or risks of breaking things, I'll leave it to you guys. Thanks for checking.

Comment (jasonrsadler) [reply app/browser/api/ledger.js]: Your call @NejcZdovc

Comment (jasonrsadler) [reply app/browser/api/ledger.js]: Done.

**Comment by NejcZdovc** [comment]
master e685447
0.24 0e8799549
0.23 49baa482e
