### PR TITLE
Fixes time spent min visit time

### LINKED ISSUE #11997: time spent calculations off when minimum page time set to 1min
## Test plan

https://github.com/brave/browser-laptop/pull/12004#issue-274623373

----

### Description

Calculated "Time Spent" values won't match the video's running time when using `1min` under `Minimum page time before logging a visit` via "Advanced Settings".

### Steps to Reproduce

  1. launch `0.19.95` and create/enable the wallet via `about:preferences#payments`
  2. Click on the "Advanced" settings and select `1 minute` & `1 visit`
  3. open a new tab and load https://www.youtube.com/watch?v=8-Cjsnq8kVU
  4. let the video play for ~1.5 min, and switch over to `about:preferences#payments`

**Actual result:**

You'll notice that the "time spent" will be anywhere in the range of ~4-6mins when in reality you've only spent ~1minute on the video.

screen shot 2017-11-15 at 11 55 03 pm

**Expected result:**

Time spend should be around the same time as the video that was watched.

**Reproduces how often:**

100% of the time using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.95 
> rev: cc0ebadfd8950d1b5f454cb39c0c3a64028cc935 
> Muon: 4.5.16 
> libchromiumcontent: 62.0.3202.94 

**Reproducible on current live release:**

N/A

### Additional Information

Platforms:

* macOS 10.12.6 x64 using `0.19.95`- Reproduced
* Win 10 x64 using `0.19.95` - Reproduced
* Ubuntu Ubuntu 17.04 x64 - Reproduced

**CC'ing** @NejcZdovc

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11997

Auditors:

Test Plan:
- enable payments
- set 1min visit time in advance settings
- disable autoplay on youtube
- start watching video that is longer then 3min
- check if after 2min you see channel in ledger table with correct time (not some crazy minutes)
- after you finish with a video time should be the same in ledger table that is in the video

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: test/unit/app/browser/api/ledgerTest.js [hunk 1]
```diff
@@ -586,40 +590,36 @@ describe('ledger api unit tests', function () {
...
 
-      it('min duration is set to minimum visit time if below that threshold', function () {
-        const xhr2 = 'https://www.youtube.com/api/stats/watchtime?docid=kLiLOkzLetE&st=20.338&et=21.339'
-        ledgerApi.onMediaRequest(cacheAppState, xhr2, ledgerMediaProviders.YOUTUBE, 1)
-        assert(publisherFromMediaPropsSpy.notCalled)
-        assert(saveVisitSpy.withArgs(cacheAppState, publisherKey, paymentsMinVisitTime, false).calledOnce)
-      })
-
-      it('min duration is set to minimum visit time if below that threshold (string setting)', function () {
-        paymentsMinVisitTime = '5000'
```
Comment (bsclifton) [inline test/unit/app/browser/api/ledgerTest.js]: Was this intentionally removed? I think it was a good test to have (making sure string setting is converted)

Comment (NejcZdovc) [reply test/unit/app/browser/api/ledgerTest.js]: yeah, because now we don't have this threshold anymore. We are sending actual milliseconds in that we receive from youtube.

Comment (NejcZdovc) [reply test/unit/app/browser/api/ledgerTest.js]: We are sending `ignoreMinTime: true` into `addPublisher`, so we don't need to set min visit time anymore

Comment (bsclifton) [reply test/unit/app/browser/api/ledgerTest.js]: 👍

**Comment by bsclifton** [comment]
master 215da7f4c1bc3db33f4f0c8dfb7307cfcb42223e
0.21.x 66388c6187b7764d49857a739088f3ca79723101
0.20.x 9a74a6e380a511fef91dd862df5e232cab0124b5
0.19.x 6decbaa69eca721064b27977e6e98f2b1e9af643
