### PR TITLE
removes "update to preview" from preferences

### LINKED ISSUE #11638: hiding/removing "update to preview release"
I've started to notice that some of our user base might have the wrong impression of what exactly a "preview" build means. Because the "enable previews" option is easily accessible, I feel that a good percentage of our users are enabling it automatically with the expectation that the "preview" build will be somewhat equal to the release in terms of quality which isn't the case.

We've had several instances in the past few months where we've released a preview version that either:

* completely breaks and stops launching (this has happened a few times)
* crashes every few minutes making the product unstable and unusable

When this happens, we usually get a large influx of support requests/rants/complaints via various social media channels. We're most likely losing users every time a preview build completely breaks the entire Brave experience. These users shouldn't have been on the preview build from the start.

We should still allow users to enable "preview" builds, but we need to ensure that only advanced users that are aware of the risks are using previews, and not regular users who might think that the "preview" build is basically an equivalent to the release build. We could either:

* hide the "preview" toggle deeper into the settings (makes it harder to find/enable)
* remove it entirely from Brave and require a environment variables to download previews

CC'ing @bbond @aekeus, @bsclifton, @LaurenWags, @srirambv

### PR DESCRIPTION
**Pull request by kjozwiak**
Fix #11638

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Test Case 1:

* launch brave and load about:preferences#advanced
* ensure that "Update to preview releases" has been removed

Test Case 2:

* launch brave using the `BRAVE_ENABLE_PREVIEW_UPDATES` environmental variable
* ensure that your'e prompted to update if there's an update available
* ensure that brave updates and relaunches without any issues

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: test/unit/app/renderer/components/preferences/advancedTabTest.js [hunk 1]
```diff
@@ -30,49 +27,13 @@ describe('AdvancedTab component', function () {
...
 
   afterEach(function () {
     mockery.disable()
-  })
-
-  const platformUtilMac = {isLinux: () => false, isWindows: () => false, isDarwin: () => true}
-  const platformUtilLinux = {isLinux: () => true, isWindows: () => false, isDarwin: () => false}
+  }) */
 
   describe('AdvancedTab', function () {
```
Comment (bbondy) [inline test/unit/app/renderer/components/preferences/advancedTabTest.js]: Thanks for leaving this file in place, I'd imagine we'll get more tests than just that one switch in the future.

**Comment by bbondy** [comment]
FYI @LaurenWags @kjozwiak @srirambv 

This will work nicely with Aubrey's server side change that if you're on a preview build you'll auto go to a preview build even if you don't use an env variable.  If however you don't have the env variable, and it updates you to a release, you'll stay on the release. 

So just be careful for first preview if you don't use an env variable to install it.

Probably best for everyone to just set an env variable and forget about it though.

**Comment by bbondy** [comment]
master: 9c6cdae72f79ae64113e41b567c50208043e15c4
0.21.x: bc3b7daa28f5786b7538494e485348e42b3e6dda
0.20.x: 855a8a8433cc32c329ab9fc3b8a88aa87c663adf
0.19.x: bdf4e1a5fbdd6e1d7e2130ee1a88cead140fa63e
