### PR TITLE
punycode.decode only accept ASCII-only input

### LINKED ISSUE #6540: Opening a link causes a crash
**Describe the issue you encountered:**
Open http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml and the browser crashes

**Expected behavior:**
It should return `ERR_NAME_NOT_RESOLVED` like Chrome does

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): 0.12.15

- Steps to reproduce:
    1. Open http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml

- Any related issues:

Before verifying the bug, please make sure that the session data has been safely saved.

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

fix #6540

Auditors: @diracdeltas

Test Plan:
1. Go to http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml
2. There should be a DNS error page

### CODE REVIEW

**Comment by diracdeltas** [comment]
I still get a crash when I copy and paste the URL and hit enter. Stack trace:
```
RangeError: Invalid input
    at error (punycode.js:42:8)
    at decode (punycode.js:235:5)
    at punycode.js:389:6
    at map (punycode.js:57:20)
    at mapDomain (punycode.js:84:18)
    at Object.toUnicode (punycode.js:387:9)
    at module.exports.getBaseDomain (/Users/yan/repos/browser-laptop/js/lib/baseDomain.$s:33:25)
    at Object.module.exports.isThirdPartyHost (/Users/yan/repos/browser-laptop/app/filt$ring.js:448:26)
    at Function.<anonymous> (/Users/yan/repos/browser-laptop/app/filtering.js:254:26)
process exited with code 7
```

**Comment by darkdh** [comment]
`checkASCII` in the PR will catch percent-encoded string

**Comment by darkdh** [comment]
This is what I saw with this PR
screen shot 2017-01-09 at 23 02 12
 and without it I will also see the crash call stack

**Comment by diracdeltas** [comment]
`checkASCII(hostname)` returns true for me. what do you get for `url.parse('http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml').hostname` ?

File: js/lib/baseDomain.js [hunk 1]
```diff
@@ -9,14 +9,27 @@ const LRUCache = require('lru_cache/core').LRUCache
 
 let cachedBaseDomain = new LRUCache(50)
 
+const checkASCII = function (str) {
+  if (typeof str !== 'string') {
+    return false
+  }
+  for (let i = 0; i < str.length; i++) {
+    if (str.charCodeAt(i) > 127) {
```
Comment (bbondy) [inline js/lib/baseDomain.js]: I think charCodeAt is implemented to UCS-2 even know the strings are UTF-16.  So for example a single unicode symbol could be for charCodeAt(0) and charCodeAt(1).  Are there any code units that have their second byte < 127?  Maybe there is a utility function we can use instead for this since these types of checks can easily go wrong? On a side note I think our TP and adblock libs probably need fixes like this.

Comment (bbondy) [inline js/lib/baseDomain.js]: I think the impl is probably right though in regards to what I brought up because you will just return false before it gets to the second code unit, so you can probably ignore my comment above.

File: js/lib/baseDomain.js [hunk 2]
```diff
@@ -9,14 +9,27 @@ const LRUCache = require('lru_cache/core').LRUCache
...
 /**
  * Returns base domain for specified host based on Public Suffix List.
  * @param {string} hostname The name of the host to get the base domain for
  */
 
 module.exports.getBaseDomain = function (hostname) {
   // decode punycode if exists
-  if (hostname.indexOf('xn--') >= 0) {
+  if (hostname.indexOf('xn--') >= 0 &&
+    checkASCII(hostname)) {
```
Comment (diracdeltas) [inline js/lib/baseDomain.js]: i figured out why this was crashing. the `hostname` that gets checked here when i go to http://xn--jp%29-5y3b.f1-live.com/f1/jp/headlines/news/detail/060912193351.shtml is `xn--jp`, which is valid ASCII but invalid punycode. so punycode.js throws a (different) error, and the crash happens. I verified that wrapping `hostname.toUnicode` in a try-catch fixes it for me.

File: js/lib/baseDomain.js [hunk 3]
```diff
@@ -9,15 +9,32 @@ const LRUCache = require('lru_cache/core').LRUCache
...
  * @param {string} hostname The name of the host to get the base domain for
  */
 
 module.exports.getBaseDomain = function (hostname) {
   // decode punycode if exists
-  if (hostname.indexOf('xn--') >= 0) {
-    hostname = punycode.toUnicode(hostname)
+  if (hostname.indexOf('xn--') >= 0 &&
+    checkASCII(hostname)) {
+    try {
```
Comment (bsclifton) [inline js/lib/baseDomain.js]: ++ on the try/catch! You'd be surprised that some domains look legit punycoded but actually fail the decoding process.  Not having try/catch has bitten me multiple times in the past :smile:
