### PR TITLE
about:history enhancements

### LINKED ISSUE #3996: History entries are not properly aligned
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
History entries are not properly aligned

**Expected behavior:**
Should be properly aligned

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x32 on Lenovo Tablet 

- Brave Version:
0.12.0

- Steps to reproduce:
    1. 
    2.
    3.

- Screenshot if needed:
14359861_10207218866163026_620703107_o

- Any related issues:

cc: @bsclifton

### LINKED ISSUE #4072: refine styles in about:history to look more like mockup
current:
image

desired:
image

change list:
- only show column headers at the top (don't duplicate for each table)
- reduce default font sizes
- move blend from bottom of table to be within the header row instead
- set better min-widths for columns so they don't bunch up
- align column header text to column text

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

- styles closer match the mockup; NOTE: style updates are to sortableTable (this may affect search engine page and payments page) 
- text no longer wraps; properly handles overflow
- updated search box
- sortable table now accepts a column type of "cell", allowing for custom controls to be passed rather than html
- delete buttons are stubbed out, ready to be implemented
- will be implementing multi-select soon

Fixes #4072
Fixes #3996

Introduces tests for about:history

Auditors: @bradleyrichter @bbondy 

Screenshot:
screen shot 2016-10-03 at 8 59 10 pm

### CODE REVIEW

File: js/about/history.js [hunk 1]
```diff
@@ -23,6 +23,37 @@ require('../../less/about/siteDetails.less')
...
+  constructor () {
+    super()
+    this.onClick = this.onClick.bind(this)
+  }
+
+  onClick (e) {
+    if (e && e.preventDefault) {
+      e.preventDefault()
+    }
+    // BSCTODO: ...
```
Comment (bbondy) [inline js/about/history.js]: ?

**Comment by bbondy** [comment]
++, just maybe flesh out the TODO more.
Great testss

**Comment by luixxiul** [comment]
The table on``about:preferences#search`` was styled too, which was intended?

**Comment by bsclifton** [comment]
@luixxiul good catch- yes, it was intended... but unfortunately I didn't put a fix in for that. 
Captured this with issue https://github.com/brave/browser-laptop/issues/4493

**Comment by bradleyrichter** [comment]
time column should be fixed width, with no wrap:

image

**Comment by bradleyrichter** [comment]
column headers should also be fixed width and no wrap

image
