### PR TITLE
Some verified publishers no longer remove green tick at sublevels - Fixes issue #10484

### LINKED ISSUE #10484: Green tick on payments icon disappears by moving to sub level of the verified site
**Describe the issue you encountered:**
The green tick on payments icon disappears by moving to sub level of the verified site. Is this intended?

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): 0.18.22

- Steps to reproduce:
    1. Open https://brianbondy.com
    2. Click "Filters"
    
- Actual result: the green tick on the payments icon disappears

- Expected result: ?

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by jasonrsadler**
Fixes #10484

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

I could only get this to repro on the brianbondy site. All other verified pubs didn't have this problem. 

Regardless the addition allows the brianbondy sub levels to show green tick

Review Requested @bsclifton 
Security Review Requested @diracdeltas

### CODE REVIEW

**Comment by jasonrsadler** [comment]
Recommend leaving this until after #12272

**Comment by NejcZdovc** [comment]
@jasonrsadler can you please add test for this one?

**Comment by jasonrsadler** [comment]
@NejcZdovc I've never been able to get the tests to run successfully. Can you tell me what I'm doing wrong. This is on a win10 box. I do npm run watch-test and then npm run test -- --grep="verified". Here's the test:
```
describe('Verified publisher tick', function () {
    Brave.beforeAll(this)

    before(function * () {
      yield setup(this.app.client)
    })

    it('Shows publisher tick on verified publisher site', function * () {
      const page1Url = 'https://brianbondy.com'

      yield this.app.client
        .tabByUrl(Brave.newTabUrl)
        .url(page1Url)
        .waitForUrl(page1Url)
        .windowParentByUrl(page1Url)
      yield this.app.client
        .activateURLMode()
        .waitForExist(verifiedPublisherIcon)
    })

    it('Doesn\'t show publisher tick on non-verified publisher site', function * () {
      const page1Url = 'https://google.com'

      yield this.app.client
        .tabByUrl(Brave.newTabUrl)
        .url(page1Url)
        .waitForUrl(page1Url)
        .windowParentByUrl(page1Url)
      yield this.app.client
        .activateURLMode()
        .waitForExist(nonVerifiedPublisherIcon)
    })
  })
```
and this is the result:
```
Ledger table
    2 publishers
      1) "before each" hook for "toggle non-verified option"
      2) "after each" hook for "toggle non-verified option"

  navigationBar tests
    Verified publisher tick
{ Error: ENOENT: no such file or directory, scandir 'C:\Users\Gooses\AppData\Local\Temp\brave-test\1522869977658758'
    at Object.fs.readdirSync (fs.js:904:18)
    at rmDir (E:/jsTuts/browser-laptop/test/lib/brave.js:34:20)
    at Context.cleanup (E:/jsTuts/browser-laptop/test/lib/brave.js:1192:26)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Gooses\\AppData\\Local\\Temp\\brave-test\\1522869977658758' }
      3) "before all" hook
      4) "after all" hook

  ledger api unit tests
{ Error: ENOENT: no such file or directory, scandir 'C:\Users\Gooses\AppData\Local\Temp\brave-test\1522869987913838'
    at Object.fs.readdirSync (fs.js:904:18)
    at rmDir (E:/jsTuts/browser-laptop/test/lib/brave.js:34:20)
    at Context.cleanup (E:/jsTuts/browser-laptop/test/lib/brave.js:1192:26)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Gooses\\AppData\\Local\\Temp\\brave-test\\1522869987913838' }
    when timing does not need to be checked
      checkVerifiedStatus
        √ change publisher verified status from true to false (40ms)

  PublisherToggle component
    default behaviour (when autoSuggest is ON)
      5) Show as verified if publisher is shown as verified on ledger
locations list


  1 passing (14s)
  5 failing

  1) Ledger table 2 publishers "before each" hook for "toggle non-verified option":
     Error: ChromeDriver did not start within 5000ms
      at E:\jsTuts\browser-laptop\node_modules\spectron\lib\chrome-driver.js:63:25
      at Request._callback (E:\jsTuts\browser-laptop\node_modules\spectron\lib\chrome-driver.js:120:23)
      at self.callback (E:\jsTuts\browser-laptop\node_modules\request\request.js:186:22)
      at Request.onRequestError (E:\jsTuts\browser-laptop\node_modules\request\request.js:878:8)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  2) Ledger table 2 publishers "after each" hook for "toggle non-verified option":
     TypeError: Cannot read property 'waitForBrowserWindow' of undefined
      at promises.push.callback (E:/jsTuts/browser-laptop/test/lib/brave.js:1201:23)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\parallel.js:31:39
      at replenish (E:\jsTuts\browser-laptop\node_modules\async\internal\eachOfLimit.js:64:17)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\eachOfLimit.js:68:9
      at eachOfLimit (E:\jsTuts\browser-laptop\node_modules\async\eachOfLimit.js:39:36)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\doLimit.js:9:16
      at _parallel (E:\jsTuts\browser-laptop\node_modules\async\internal\parallel.js:30:5)
      at series (E:\jsTuts\browser-laptop\node_modules\async\series.js:83:26)
      at Promise (E:/jsTuts/browser-laptop/test/lib/brave.js:1210:7)
      at new Promise (<anonymous>)
      at Context.stopApp (E:/jsTuts/browser-laptop/test/lib/brave.js:1209:12)
      at Context.<anonymous> (E:/jsTuts/browser-laptop/test/lib/brave.js:196:30)
      at callFn (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:326:21)
      at Hook.Runnable.run (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:319:7)
      at Hook.Runnable.run (E:\jsTuts\browser-laptop\node_modules\co-mocha\lib\co-mocha.js:42:16)
      at next (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:298:10)
      at Immediate._onImmediate (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:320:5)

  3) navigationBar tests Verified publisher tick "before all" hook:
     Error: ChromeDriver did not start within 5000ms
      at E:\jsTuts\browser-laptop\node_modules\spectron\lib\chrome-driver.js:63:25
      at Request._callback (E:\jsTuts\browser-laptop\node_modules\spectron\lib\chrome-driver.js:120:23)
      at self.callback (E:\jsTuts\browser-laptop\node_modules\request\request.js:186:22)
      at Request.onRequestError (E:\jsTuts\browser-laptop\node_modules\request\request.js:878:8)
      at Socket.socketErrorListener (_http_client.js:387:9)
      at emitErrorNT (internal/streams/destroy.js:64:8)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  4) navigationBar tests Verified publisher tick "after all" hook:
     TypeError: Cannot read property 'waitForBrowserWindow' of undefined
      at promises.push.callback (E:/jsTuts/browser-laptop/test/lib/brave.js:1201:23)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\parallel.js:31:39
      at replenish (E:\jsTuts\browser-laptop\node_modules\async\internal\eachOfLimit.js:64:17)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\eachOfLimit.js:68:9
      at eachOfLimit (E:\jsTuts\browser-laptop\node_modules\async\eachOfLimit.js:39:36)
      at E:\jsTuts\browser-laptop\node_modules\async\internal\doLimit.js:9:16
      at _parallel (E:\jsTuts\browser-laptop\node_modules\async\internal\parallel.js:30:5)
      at series (E:\jsTuts\browser-laptop\node_modules\async\series.js:83:26)
      at Promise (E:/jsTuts/browser-laptop/test/lib/brave.js:1210:7)
      at new Promise (<anonymous>)
      at Context.stopApp (E:/jsTuts/browser-laptop/test/lib/brave.js:1209:12)
      at Context.<anonymous> (E:/jsTuts/browser-laptop/test/lib/brave.js:167:30)
      at callFn (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:326:21)
      at Hook.Runnable.run (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:319:7)
      at Hook.Runnable.run (E:\jsTuts\browser-laptop\node_modules\co-mocha\lib\co-mocha.js:42:16)
      at next (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:298:10)
      at Immediate._onImmediate (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:320:5)

  5) PublisherToggle component default behaviour (when autoSuggest is
ON) Show as verified if publisher is shown as verified on ledger locations list:
     AssertionError [ERR_ASSERTION]: null == true
      at Context.<anonymous> (E:/jsTuts/browser-laptop/test/unit/app/renderer/components/navigation/publisherToggleTest.js:104:14)
      at callFn (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runnable.js:319:7)
      at Test.Runnable.run (E:\jsTuts\browser-laptop\node_modules\co-mocha\lib\co-mocha.js:42:16)
      at Runner.runTest (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:422:10)
      at E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:528:12
      at next (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:342:14)
      at E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:352:7
      at next (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (E:\jsTuts\browser-laptop\node_modules\mocha\lib\runner.js:320:5)



internal/util.js:183
  throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);
  ^

Error [ERR_UNKNOWN_SIGNAL]: Unknown signal: SIGQUIT
    at convertToValidSignal (internal/util.js:183:9)
    at ChildProcess.kill (internal/child_process.js:379:5)
    at process.on (E:/jsTuts/browser-laptop/test/lib/server.js:112:34)    at emitOne (events.js:121:20)
    at process.emit (events.js:211:7)
    at process.exit (internal/process.js:157:15)
    at done (E:\jsTuts\browser-laptop\node_modules\mocha\bin\_mocha:417:32)
    at afterWrite (_stream_writable.js:454:3)
    at _combinedTickCallback (internal/process/next_tick.js:144:20)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
npm ERR! code ELIFECYCLE
...
```

**Comment by jasonrsadler** [comment]
Thanks for clarifying.

**Comment by jasonrsadler** [comment]
@NejcZdovc, can you tell me what I'm doing wrong?:
```
it('verified publisher', function () {
      const url = 'https://www.duckduckgo.com'
      const prop = 'publisher'
      const state = defaultState.setIn(['ledger', 'locations', url, prop], 'duckduckgo.com')
      const result = ledgerState.getLocationProp(state, url, prop)
      assert.equal(result, 'duckduckgo.com')
    })
```
result is always coming back undefined

**Comment by NejcZdovc** [comment]
@jasonrsadler you are getting undefined, because `url.substring(0, url.indexOf('/', 8) + 1)` is returning empty string and because of that `getIn` is not returning anything. If I understand core correctly what you want to achieve is to change url to domain only url. Is that correct?

**Comment by jasonrsadler** [comment]
*smacks forehead*
Thanks

**Comment by jasonrsadler** [comment]
@NejcZdovc, would you let me know if this provides adequate coverage?
Thanks.

**Comment by NejcZdovc** [comment]
@jasonrsadler can you please add tests for `shortenUrlToDomainTLD` function as well? Thank you

**Comment by jasonrsadler** [comment]
@NejcZdovc, How is this?

File: js/lib/urlutil.js [hunk 1]
```diff
@@ -486,6 +486,14 @@ const UrlUtil = {
     return url
       .replace(/((#?\/?)|(\/#?))$/, '') // remove trailing # and /
       .trim() // remove whitespaces
+  },
+
+  shortenUrlToDomainTLD: (url) => {
+    if (url !== null) {
+      var hasProtocol = url.includes('://')
```
Comment (NejcZdovc) [inline js/lib/urlutil.js]: please replace this with `const`

**Comment by NejcZdovc** [comment]
@jasonrsadler really good tests, great job

File: js/lib/urlutil.js [hunk 2]
```diff
@@ -486,6 +486,14 @@ const UrlUtil = {
     return url
       .replace(/((#?\/?)|(\/#?))$/, '') // remove trailing # and /
       .trim() // remove whitespaces
+  },
+
+  shortenUrlToDomainTLD: (url) => {
+    if (url !== null) {
```
Comment (NejcZdovc) [inline js/lib/urlutil.js]: `url !== null` let's change this to `url != null`. This way we are checking `null` and `undefined`

**Comment by NejcZdovc** [comment]
@jasonrsadler please squash commits and then we are good to go with the code

**Comment by jasonrsadler** [comment]
@NejcZdovc Done. Thanks for the assist and let me know if everything else looks good.

File: test/unit/lib/urlutilTest.js [hunk 3]
```diff
@@ -485,4 +485,50 @@ describe('urlutil', function () {
...
+    })
+
+    it('empty string', function () {
+      const result = urlUtil.shortenUrlToDomainTLD('')
+      assert.equal(result, '')
+    })
+
+    it('normal url', function () {
+      const result = urlUtil.shortenUrlToDomainTLD('https://brave.com')
+      assert.equal(result, 'https://brave.com/')
```
Comment (NejcZdovc) [inline test/unit/lib/urlutilTest.js]: @jasonrsadler this test should fail. We should not apply / at the end if / was not there from the gecko

Comment (NejcZdovc) [reply test/unit/lib/urlutilTest.js]: other unit tests are failing because of that

Comment (jasonrsadler) [reply test/unit/lib/urlutilTest.js]: Agree. But something else is appending the trailing '/' at the end of the url during normal browsing.
Example: using latest release type in brianbondy.com and press enter. The trailing '/' gets appended at the end.

As for the tests, will fix.

Let me know what your opinion is regarding the current navigation behavior.

File: js/lib/urlutil.js [hunk 4]
```diff
@@ -508,6 +508,14 @@ const UrlUtil = {
     return ip.isPrivate(hostname) || hostname === 'localhost' || whitelistSuffixes.some((suffix) => {
       return hostname && hostname.endsWith(`.${suffix}`)
     })
+  },
+
+  shortenUrlToDomainTLD: (url) => {
```
Comment (diracdeltas) [inline js/lib/urlutil.js]: can you just use `getBaseDomain` from js/lib/baseDomain.js ?

Comment (diracdeltas) [reply js/lib/urlutil.js]: nvm, i guess what you want here is the full URL without the path?

this seems like it would fail on URLs that don't include slashes in the protocol, like `mailto:` 

you could do `parsed = urlParse(url); return parsed.path ? parsed.split(parsed.path)[0] : url` or something like that

Comment (diracdeltas) [reply js/lib/urlutil.js]: ^ though i guess that doesn't work with URLs that don't have a protocol

since publishers only works on http or https sites, you could fix by
```
if (!url.startsWith('http://') && !url.startsWith('https://') { url = `https://${url}` }
```

Comment (jasonrsadler) [reply js/lib/urlutil.js]: @diracdeltas That works well. Thanks!

**Comment by jasonrsadler** [comment]
The STR I had I could only reproduce on brianbondy.com. That site seems to be down ATM. Need other sites with this issue to validate.

File: js/lib/urlutil.js (hunk 4 above)
Comment (jasonrsadler) [reply js/lib/urlutil.js]: @diracdeltas I'm going to go with a combo and also to make sure another protocol isn't passed in.
```if (!url.startsWith('http://') && !url.startsWith('https://') && !url.includes('://')) { url = `https://${url}` }```

**Comment by jasonrsadler** [comment]
@NejcZdovc, if a user is on Youtube, Twitch, etc., is the verified publisher icon url dependent? In other words, if it does rely on url and we parse down to non sublevel domain, will this break streamer channels? Thanks,

File: js/lib/urlutil.js [hunk 5]
```diff
@@ -520,6 +520,12 @@ const UrlUtil = {
...
+    if (url != null && (!url.startsWith('http://') && !url.startsWith('https://')) ? `https://${url}` : url) {
```
Comment (diracdeltas) [inline js/lib/urlutil.js]: not sure I understand this `if` condition. `!url.startsWith('https://')) ? `https://${url}` : url` returns a truthy value, but it doesn't set the URL

Comment (diracdeltas) [reply js/lib/urlutil.js]: i think you mean:
```
if (url != null) {
  url = (!url.startsWith('http://') && !url.startsWith('https://')) ? `https://${url}` : url
  return url.substring(0, url.indexOf('/', url.indexOf('://') + 3))
}

File: test/unit/lib/urlutilTest.js [hunk 6]
```diff
@@ -562,4 +562,51 @@ describe('urlutil', function () {
       assert.equal(result, 'http://www.test.com/test.pdf')
     })
   })
+
```
Comment (diracdeltas) [inline test/unit/lib/urlutilTest.js]: tests below should be uncommented?

File: js/lib/urlutil.js (hunk 5 above)
Comment (jasonrsadler) [reply js/lib/urlutil.js]: Yes thank you.

File: test/unit/lib/urlutilTest.js (hunk 6 above)
Comment (jasonrsadler) [reply test/unit/lib/urlutilTest.js]: Which I guess is why the function passed.

Thanks for catching.

File: test/unit/app/common/state/ledgerStateTest.js [hunk 7]
```diff
@@ -622,4 +623,32 @@ describe('ledgerState unit test', function () {
       assert.equal(result, 'corrupted')
     })
   })
+
+  describe('getVerifiedPublisherLocationProp', function () {
```
Comment (diracdeltas) [inline test/unit/app/common/state/ledgerStateTest.js]: minor: it would be good to have a test case for a URL without a protocol, ex: `brianbondy.com`

File: app/common/state/ledgerState.js [hunk 8]
```diff
@@ -67,12 +67,25 @@ const ledgerState = {
     return state.setIn(['ledger', 'locations', url, prop], value)
   },
 
-  getLocationProp: (state, url, prop) => {
+  getVerifiedPublisherLocationProp: (state, url, prop) => {
```
Comment (NejcZdovc) [inline app/common/state/ledgerState.js]: let's remove `prop`, because we changed this to specific publisher function, so it's not needed anymore

File: app/common/state/ledgerState.js [hunk 9]
```diff
@@ -67,12 +67,25 @@ const ledgerState = {
...
     state = validateState(state)
     if (url == null || prop == null) {
       return null
     }
+    if (prop === 'publisher') {
+      url = urlUtil.shortenUrlToDomainTLD(url)
+    }
+    const urlLocations = state.getIn(['ledger', 'locations']).toJS()
```
Comment (NejcZdovc) [inline app/common/state/ledgerState.js]: I think this one can be problematic, perf wise. `getVerifiedPublisherLocationProp` is called from mergeProps, which is called a lot of times. `['ledger', 'locations']` can be a really big list which we convert from immutable to regular (expensive) and then filter that potential big list. 

I didn't run the code yet, but can't we just do `state.getIn(['ledger', 'locations', url, prop])` where `url` is created on line 76?

File: app/common/state/ledgerState.js (hunk 8 above)
Comment (jasonrsadler) [reply app/common/state/ledgerState.js]: Doen

File: app/common/state/ledgerState.js (hunk 9 above)
Comment (jasonrsadler) [reply app/common/state/ledgerState.js]: The problem I was running into is that sometimes the url is formatted inconsistently. Sometimes, there's a '/' at the end, sometimes it's left off which makes it difficult to get an exact match on the key.

I agree ```['ledger', 'locations']``` is too big to pass back and forth. I'll need to rethink this.

Comment (NejcZdovc) [reply app/common/state/ledgerState.js]: if you need someone to brainstorm with just let me know

File: test/unit/app/common/state/ledgerStateTest.js (hunk 7 above)
Comment (jasonrsadler) [reply test/unit/app/common/state/ledgerStateTest.js]: This got me thinking: From everything I've seen in this so far. URLs already have the protocol resolved before they get to this point. @diracdeltas or @NejcZdovc, do you know of any exceptions where URLs don't have a protocol already before getting to the publisherToggle renderer? If not, then I might have been overthinking ```shortenUrlToDomainTLD``` logic

Comment (diracdeltas) [reply test/unit/app/common/state/ledgerStateTest.js]: @jasonrsadler I don't know of any examples but I also am not familiar with this code path at all

Comment (NejcZdovc) [reply test/unit/app/common/state/ledgerStateTest.js]: not that I am aware

File: app/common/state/ledgerState.js [hunk 10]
```diff
@@ -67,12 +68,29 @@ const ledgerState = {
...
+    state = validateState(state)
+    if (url == null) {
+      return null
+    }
+
+    let publisherKey = state.getIn(['ledger', 'locations', url, 'publisher'])
+
+    if (!publisherKey) {
+      const parsedUrl = urlParse(url)
+      if (parsedUrl) {
```
Comment (diracdeltas) [inline app/common/state/ledgerState.js]: IIRC this will always be truthy because urlParse returns {} for non-valid URLs

File: app/common/state/ledgerState.js [hunk 11]
```diff
@@ -67,12 +68,29 @@ const ledgerState = {
...
+        publisherKey = parsedUrl.hostname.replace('www', '')
```
Comment (diracdeltas) [inline app/common/state/ledgerState.js]: `parsedUrl.hostname` may be null

also this would turn `somesitewww.com` into `somesite.com`. i think you want to either omit the `replace` or use a regex (`/^www\./`)

File: app/common/state/ledgerState.js [hunk 12]
```diff
@@ -65,12 +68,28 @@ const ledgerState = {
     return state.setIn(['ledger', 'locations', url, prop], value)
   },
 
+  getVerifiedPublisherLocationProp: (state, url) => {
```
Comment (NejcZdovc) [inline app/common/state/ledgerState.js]: `getVerifiedPublisherLocationProp` -> `getVerifiedPublisherLocation`

Let's rename it, because we don't have prop anymore

File: app/common/state/ledgerState.js [hunk 13]
```diff
@@ -18,6 +18,9 @@ const settings = require('../../../js/constants/settings')
 const getSetting = require('../../../js/settings').getSetting
 const {makeImmutable, isMap} = require('../../common/state/immutableUtil')
```
Comment (NejcZdovc) [inline app/common/state/ledgerState.js]: Please remove this empty line

File: app/common/state/ledgerState.js (hunk 12 above)
Comment (jasonrsadler) [reply app/common/state/ledgerState.js]: Done

File: app/common/state/ledgerState.js (hunk 13 above)
Comment (jasonrsadler) [reply app/common/state/ledgerState.js]: Done

**Comment by NejcZdovc** [comment]
master fcf1667
0.23 7ca75e8d8
0.22 e1113e3ea
