### PR TITLE
(Drag and drop) get full path from custom data in dataTransfer.items from https://git…

### LINKED ISSUE #9699: Dragging and dropping a file onto the browser does not work
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Drag and drop is not working, because path is not in drop event.
- Platform (Win7, 8, 10? macOS? Linux distro?):
all
- Brave Version (revision SHA):
435fa34
- Steps to reproduce:
    1. dnd one file to tabs toolbar
    
- Actual result:
White tab with infinite loader
- Expected result:
File is displayed
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by bridiver**
…hub.com/brave/muon/pull/228

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Fixes #9699

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/bookmarks/bookmarksToolbar.js [hunk 1]
```diff
@@ -86,8 +86,9 @@ class BookmarksToolbar extends ImmutableComponent {
       }
     }
     if (e.dataTransfer.files.length > 0) {
```
Comment (NejcZdovc) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: Here we should probably change from `e.dataTransfer.files.length` into `e.dataTransfer.items.length`

File: app/renderer/components/navigation/navigator.js [hunk 2]
```diff
@@ -115,9 +115,10 @@ class Navigator extends React.Component {
 
   onDrop (e) {
     if (e.dataTransfer.files.length > 0) {
```
Comment (NejcZdovc) [inline app/renderer/components/navigation/navigator.js]: ditto

File: app/renderer/components/tabs/tabs.js [hunk 3]
```diff
@@ -98,9 +98,10 @@ class Tabs extends React.Component {
     }
 
     if (e.dataTransfer.files) {
```
Comment (NejcZdovc) [inline app/renderer/components/tabs/tabs.js]: ditto

File: app/renderer/components/bookmarks/bookmarksToolbar.js (hunk 1 above)
Comment (bridiver) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: no, we specifically don't want to do that because we only want these items when there are files

Comment (NejcZdovc) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: so we didn't replace files object with items, but we only added items into dataTransfer?

**Comment by bsclifton** [comment]
pulling into 0.17.x since we need a new Muon 4.1.x version RE: extensions

File: app/renderer/components/bookmarks/bookmarksToolbar.js (hunk 1 above)
Comment (bridiver) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: files only contains the filename, not the full path. We added the full path for files into items when files are present

Comment (bridiver) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: there are limitations on what we can do with this api without breaking compatibility so rather than change what is contained in file, we added the extra data to items

Comment (NejcZdovc) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: make sense, then we don't need to change this line :smiley:
