### PR TITLE
Fix vertical spacing for all navbar item combinations

### LINKED ISSUE #9370: Brave update bar is misaligned
noticed this on OSX when updating from 0.15.x release to 0.16.6:
screen shot 2017-06-09 at 8 34 01 am

### PR DESCRIPTION
**Pull request by petemill**
Fix #9370 by using collapsible margin so that items without border+padding can be evenly spaced (caption buttons, bookmark, tab pages), and those with border+padding (notifications, tabs) can be touching. Removes empty element for tab pages when there is only a single page, as it had no functional purpose. Instead, margin is used.

### Buttons, Notification, Bookmarks, Tab Pages, Tabs, Find
screenshot 2017-08-15 13 06 42

### Buttons, Notification, Bookmarks, Tab Pages, Tabs
screenshot 2017-08-15 13 07 00

### Buttons, Notification, Tab Pages, Tabs
screenshot 2017-08-15 13 07 19

### Buttons, Notification, Bookmarks, Tabs
screenshot 2017-08-15 13 09 54

### Buttons, Bookmarks, Tab Pages, Tabs
screenshot 2017-08-15 13 07 50

### Buttons, Tab Pages, Tabs
screenshot 2017-08-15 13 08 06

### Buttons, Tabs
screenshot 2017-08-15 13 09 02

### Buttons, Bookmarks, Tabs
screenshot 2017-08-15 13 09 17

### Buttons, Tabs, Find
screenshot 2017-08-15 13 18 45

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

## Test Plan:
- Enable above combinations and check visual regressions compared to screenshots.

### Draggable area regression checks (inspired by #7740)
**Test case 1 - default status**
1. Clear your profile
1. Start the browser
1. Make sure that the area between the URL bar and the tabs bar is draggable

**Test case 2 - text only**
1. Open https://github.com/ in a new tab
1. Open https://github.com/features in a new tab
1. Open https://github.com/explore in a new tab
1. Open https://github.com/pricing in a new tab
1. Display the bookmark toolbar
1. Bookmark them by dragging the lock icon on the URL bar to the bookmark toolbar
1. (Not on Windows) Make sure that the area between the bookmarked items and the URL bar is draggable
1. (Not on Windows) Make sure that the area between the bookmarked items and the tabs bar is draggable

**Test case 3 - text only with tab sets**
1. Open about:preferences#tabs
1. Set the number of tabs per tab set to 6
1. Open several new tabs to create another tab page
1. Narrow the window size to place the tab page indicators under the bookmarked items
1. (Not on Windows) Make sure that the area between the tab page indicators and the bookmark bar is draggable (the tiny area between the indicators is NOT draggable)
1. Make sure that the area between the tab page indicators and the tabs bar is draggable

**Test case 4 - text and favicons with tab sets**
1. Open about:preferences
1. Change "Text only" to "Text and Favicons"
1. Repeat the step 3:5 and 3:6
1. Close several tabs to clear the 2nd tab set
1. (Not on Windows) Make sure that the area around the bookmarks is draggable

**Test case 5 - only tab sets**
1. Hide the bookmark toolbar
1. Make sure that the area around the tab page indicators is draggable

**Test case 6 - favicon only with and without tab sets**
1. Bookmark several other GitHub pages
1. Open about:preferences
1. Change "Text and Favicons" to "Favicon only"
1. Change window size to place the tab page indicators under the bookmark favicons
1. Repeat the step 3:5 and 3:6
1. Close tabs to clear the 2nd tab set
1. (Not on Windows) Make sure that the area around favicons is draggable

**Test case 7 - main menu button (especially *Windows*)**
1. Open a small amount of tabs so there is space between tabs and main menu button
1. Ensure dragging the space between tabs and main menu button *does* drag the window
1. Ensure clicking the main menu button opens the main menu

**Test case 8 - notification bar**
1. Click *'check for updates...'* menu item
1. Make sure that nowhere on the notification bar is draggable

**Test case 9 - find page bar**
1. Visit github.com
1. Open 'find in page' bar using cmd-f / ctrl-f or the menu item
1. Make sure no area of 'find in page' bar is draggable

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
@petemill it looks great! If you don't mind, would you specify the manual test plan, like I did on https://github.com/brave/browser-laptop/pull/7740#issue-214511262 ? You could re-use the test plan, adding another test case with the update bar.

We'd need to make sure this PR does not introduce regressions regarding draggability :-) thanks!

File: app/renderer/components/main/main.js [hunk 1]
```diff
@@ -690,18 +690,22 @@ class Main extends React.Component {
...
-        })}
-          onContextMenu={this.onTabContextMenu}>
-          {
-            this.props.showTabPages
-            ? <TabPages />
-            : null
-          }
-        </div>
+        {
+          this.props.isSinglePage
```
Comment (luixxiul) [inline app/renderer/components/main/main.js]: nice one ;-)

**Comment by petemill** [comment]
@luixxiul I added the test cases concerning window draggability, ran through those cases on mac and windows, and made some fixes as a result. Ready for your review.

**Comment by NejcZdovc** [comment]
@luixxiul can you please re-review? Thank you
