### PR TITLE
Made urlBarIconContainer clickable to display connection info. Fix #7888

### LINKED ISSUE #7888: Connection info click area is on the urlbarIcon, should be on urlbarIconContainer
## Test plan
See https://github.com/brave/browser-laptop/pull/13147

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
The click area is pretty small limited only to the urlbaricon, even a little off causes the click to be not captured. The click should be on the urlbarIconContainer which increases the hit area 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
Brave	0.14.0
rev	ffa6f8f

- Steps to reproduce:
    1. Open any http/https site
    2. Click on the padlock icon the connection info is shown 
    3. Move cursor sightly off the padlock but visually the pointer still looks on the padlock, click not recognized and connection info is not shown 

  **All other browser has the large click area to show the connection info window/modal**
    
- Actual result:
Connection info click area is on the urlbarIcon, should be on urlbarIconContainer

- Expected result:
Connection info not shown if the click is off by a marginal amount

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
What it is now
image
What it should be 
image

- Any related issues: #6704
cc: @bradleyrichter @bsclifton

### PR DESCRIPTION
**Pull request by MargarytaChepiga**
Fixed issue #7888 and issue #13011.
Before:
before
After:
after

I also touched some css, changed few things that had a TODO. In addition to changing a little bit of styling. 
Also, I am not sure if I need to update and/or add new tests for this fix. Please let me know if so :)

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
1. Navigate to wikipedia.org
2. Put mouse in URL bar and try clicking around the lock icon
3. `Secure connection` modal should come up (even near the edges)
4. Verify you can still drag and drop the lock icon to bookmarks toolbar
5. Navigate to github.com
6. Put mouse in URL bar and try clicking around the lock icon
7. Verify secure modal is shown when clicking everything left of where you type (ex: the EV info bar and the lock icon, including the edges)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@MargarytaChepiga I updated your post to include a test plan- can you take a peek and let me know what you think? 😄

**Comment by srirambv** [comment]
Works great ++.

 @MargarytaChepiga would it be possible to add the separator after the lock icon for sites that do not show the EVC  
image

**Comment by MargarytaChepiga** [comment]
@srirambv Good point actually. I will fix it

**Comment by MargarytaChepiga** [comment]
@bsclifton Thank you so much! 😄 I think test plan looks great, and as already mentioned above I will fix the missing separator.

**Comment by bsclifton** [comment]
@MargarytaChepiga there is one other issue, caught by @NejcZdovc 
image

It seems the color used by the EV elements is bleeding through- causing the lock icon on HTTP links to show as green

For your next PR, can you please take a look at this? (along with the separator icon) 😄

**Comment by bsclifton** [comment]
@srirambv as called out in the issue (https://github.com/brave/browser-laptop/issues/13159), we should leave the separator off (at least for now)

I think we just need a fix for the color bleed through for mixed content and we'll be good 😄 I updated the test plan to capture this (thanks, @NejcZdovc!)

File: app/renderer/components/styles/global.js [hunk 1]
```diff
@@ -391,7 +391,6 @@ globalStyles.color.chromeBorderColor = globalStyles.color.chromePrimary
 globalStyles.color.chromeControlsWarningBackground = globalStyles.color.chromePrimary
 globalStyles.color.audioColor = globalStyles.color.highlightBlue
 globalStyles.color.focusUrlbarOutline = globalStyles.color.highlightBlue
-globalStyles.color.siteSecureColor = globalStyles.color.buttonColor
```
Comment (bsclifton) [inline app/renderer/components/styles/global.js]: this might be the cause of the color being green instead of gray

File: app/renderer/components/navigation/urlBar.js [hunk 2]
```diff
@@ -513,13 +517,13 @@ class UrlBar extends React.Component {
...
         noBorderRadius: this.props.publisherButtonVisible
-      })}
+      })} 
       id='urlbar'
     >
       {urlbarIconContainer}
       {
         this.props.titleMode
-        ? <div id='titleBar' data-test-id='titleBar'>
+        ? <div id='titleBar' data-test-id='titleBar' >
```
Comment (bsclifton) [inline app/renderer/components/navigation/urlBar.js]: this extra space at the end is also causing the linter to fail; you can manually run this with:
`npm run lint`

File: less/variables.less [hunk 3]
```diff
@@ -40,7 +40,7 @@
 @settingItemSubtextFontSize: 0.95rem;
 @audioColor: @highlightBlue;
 @focusUrlbarOutline: rgba(55, 169, 253, 0.4);
-@siteSecureColor: @buttonColor;
+@siteSecureColor: green;
```
[the remark this answers is not in the document]
Comment (srirambv) [reply less/variables.less]: Just replacing `green` with `@siteEVColor` fixes it

**Comment by srirambv** [comment]
https://github.com/brave/browser-laptop/pull/13147#discussion_r168684495

File: app/renderer/components/navigation/urlBar.js [hunk 4]
```diff
@@ -513,13 +517,13 @@ class UrlBar extends React.Component {
         urlbarForm: true,
         [css(styles.urlbarForm_wide)]: this.props.isWideURLbarEnabled,
         noBorderRadius: this.props.publisherButtonVisible
-      })}
+      })}
```
Comment (petemill) [inline app/renderer/components/navigation/urlBar.js]: lint error here

**Comment by diracdeltas** [comment]
I think we should revert the color changes for now, pending review by security team. There are some edge cases where I think the behavior is incorrect:
screen shot 2018-02-16 at 1 35 02 pm

BTW this should have been marked for sec review before merge. :(

**Comment by diracdeltas** [comment]
Just catching up here, I see @srirambv already opened https://github.com/brave/browser-laptop/pull/13164. Please be sure to request a security review this time, thanks.

**Comment by bsclifton** [comment]
Removing milestone since this was reverted with https://github.com/brave/browser-laptop/pull/13168
