### PR TITLE
Fix url in LOGIN_RESPONSE

### LINKED ISSUE #2807: Login problem on browserspy.dk/password.php
See: https://github.com/brave/browser-laptop/issues/1997#issuecomment-236237311

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

fix #2807

### CODE REVIEW

File: js/components/loginRequired.js [hunk 1]
```diff
@@ -69,7 +69,7 @@ class LoginRequired extends React.Component {
       username: '',
       password: ''
     })
-    ipc.send(messages.LOGIN_RESPONSE, this.props.frameProps.get('location'), this.state.username, this.state.password)
+    ipc.send(messages.LOGIN_RESPONSE, this.detail.url, this.state.username, this.state.password)
```
Comment (bbondy) [inline js/components/loginRequired.js]: where is this.detail set?

Comment (bbondy) [inline js/components/loginRequired.js]: nevermind I see the property, thanks.
