### PR TITLE
Saving a document doesn't show correct origin

### LINKED ISSUE #8698: Saving a document doesn't show correct origin
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Saving a document doesn't show correct origin 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Alll

- Brave Version (revision SHA):
Brave	0.15.1
rev	ea5024d

- Steps to reproduce:
    1. Enable payments 
    2. Click on advance settings
    3. Save recovery file, download bar shows origin as f`ile:///`
    4. Similar issue when saving pdf file shows as `blob:chrome-extension`
    
- Actual result:
Saving a document doesn't show correct origin 

- Expected result:
Should show the correct origin for files

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes but since origin was not shown before had gone unnoticed 

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image
image

- Any related issues:
Please change milestone if requried

### PR DESCRIPTION
**Pull request by kumarrishav**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #8698

Test Plan:
Open browser
Download file having orgin file:/// or chrome-extension: or other local origin.
It should show text 'Local file' for local origin file/
screen shot 2017-05-10 at 5 48 05 pm

### CODE REVIEW

File: app/renderer/components/downloadItem.js [hunk 1]
```diff
@@ -73,6 +73,8 @@ class DownloadItem extends ImmutableComponent {
   }
   render () {
     const origin = getOrigin(this.props.download.get('url'))
+    const localFileOrigins = ['file:', 'blob:', 'data:', 'chrome-extension:', 'chrome:']
+    const localFile = localFileOrigins.some((localFileOrigin) => origin.startsWith(localFileOrigin))
```
Comment (diracdeltas) [inline app/renderer/components/downloadItem.js]: this should check that origin is not null

File: app/renderer/components/downloadItem.js [hunk 2]
```diff
@@ -160,7 +162,7 @@ class DownloadItem extends ImmutableComponent {
                     ? <span className='fa fa-unlock isInsecure' />
                     : null
                 }
-                <span title={origin}>{origin}</span>
+                <span title={origin}>{localFile ? 'Local file' : origin}</span>
```
Comment (NejcZdovc) [inline app/renderer/components/downloadItem.js]: Please add translation here

File: test/unit/app/renderer/downloadItemTest.js [hunk 3]
```diff
@@ -46,6 +57,29 @@ describe('downloadItem component', function () {
...
+        assert.equal(this.result.find('.downloadFilename').text(), this.download.get('filename'))
+      })
+
+      it('has local origin i.e file: and matches to "Local file" origin', function () {
+        assert.equal(this.result.find('.downloadOrigin').text(), 'Local file')
+      })
+    })
+  })
+
+  Object.values(downloadStates).forEach(function (state) {
```
Comment (NejcZdovc) [inline test/unit/app/renderer/downloadItemTest.js]: I think that you could do this tests insider previous `forEach`

File: app/renderer/components/downloadItem.js (hunk 1 above)
Comment (kumarrishav) [inline app/renderer/components/downloadItem.js]: Did you mean like this:  origin && localFileOrigins.some((localFileOrigin) => origin.startsWith(localFileOrigin)) @diracdeltas

**Comment by kumarrishav** [comment]
@diracdeltas @NejcZdovc review?

**Comment by bsclifton** [comment]
@kumarrishav great job on this 😄
