### PR TITLE
Don't reupload bookmarks to Sync every load

### LINKED ISSUE #8408: Bookmarks are re-synced (uploaded) on every load
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
With Sync, bookmarks are synced every browser load.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
dev, master @ 15b4dbc20ee9383fafaf8e61b908d5b133e89245

- Steps to reproduce:
    1. Enable Sync on a fresh profile.
    2. Visit archive.org and bookmark it. Terminal should show that it synced.
    3. Close archive.org tab.
    4. Restart Brave.
    4. Examine terminal for sync init and sent records.
    
- Actual result:
Bookmark is sent again.

- Expected result:
Bookmark should not be sent.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Any related issues:
#8354

### PR DESCRIPTION
**Pull request by ayumi**
Fix #8408

Auditors: @diracdeltas @bbondy

Test Plan:
1. Open Brave and enable Sync.
2. Visit archive.org and bookmark it. Terminal should show that it synced.
3. Close archive.org tab.
4. Restart Brave.
5. Examine terminal. Bookmark shouldn't be re-synced.

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

File: app/sync.js [hunk 1]
```diff
@@ -189,11 +189,19 @@ module.exports.onSyncReady = (isFirstRun, e) => {
    * @param {Immutable.Map} site
    */
   const folderToObjectId = {}
-  const syncBookmark = (site) => {
-    if (!site || (site.get('objectId') && seed.equals(site.get('originalSeed'))) ||
-      folderToObjectId[site.get('folderId')] || !syncUtil.isSyncable('bookmark', site)) {
-      return
+  const shouldSyncBookmark = (site) => {
```
Comment (diracdeltas) [inline app/sync.js]: minor enhancement: if you apply this as a filter function before sorting in https://github.com/brave/browser-laptop/pull/8409/files#diff-b7794baa4e0cd1fb8cab9449660662baR229, it might improve things slightly since then there are less things to sort

Comment (ayumi) [inline app/sync.js]: g00d idea

**Comment by NejcZdovc** [comment]
@diracdeltas @ayumi should be thins in 0.15.0?

**Comment by NejcZdovc** [comment]
Ok I see that issue is set to 0.15.0, so please @bsclifton pull this into dev-channel

**Comment by ayumi** [comment]
@NejcZdovc thanks yeah, this is an important fix

**Comment by bsclifton** [comment]
@NejcZdovc already 🍒 -picked in 😄

**Comment by NejcZdovc** [comment]
@bsclifton GitHub King :crown:
