### PR TITLE
Context menu now works on sortableTable with no selection

### LINKED ISSUE #5202: Regression : about:bookmarks : context menu for bookmark should provide edit option regardless of whether or not it was selected first
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When right-clicking on a bookmark in about:bookmarks, I expected an edit bookmark option. There was none.

**Expected behavior:**
Regardless of whether or not you select the bookmark first, you should have the option to edit it via the context menu.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.7 RC1

- Steps to reproduce:
    1. Go to about:bookmarks
    2. Right-click on a bookmark
    3. Look for an edit option

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by bsclifton**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Context menu now works on sortableTable with no selection
Also fixes: focus for new folder / edit folder / new bookmark now set properly

Fixes #5202

Auditors: @darkdh

Test plan:
1. Launch Brave and go to about:bookmarks
2. Without selecting an item, right click on any entry to bring up context menu
3. Confirm you see the context menu for a single item
4. Visit about:history
5. without selecting an item, right click on any entry to bring up context menu
6. Confirm you see the context menu for a single item

### CODE REVIEW

File: js/components/addEditBookmark.js [hunk 1]
```diff
@@ -16,9 +16,13 @@ class AddEditBookmark extends ImmutableComponent {
   onClose () {
     windowActions.setBookmarkDetail()
   }
+  componentDidMount () {
```
Comment (bsclifton) [inline js/components/addEditBookmark.js]: this and the change in `addEditBookmarkHanger.js` are changes I missed when originally doing that control, which was submitted with https://github.com/brave/browser-laptop/pull/5118

**Comment by darkdh** [comment]
++ to 0e6ba2884266a62f93a7c9bc8e8914746dbba95b

please review d41a2d835292d32af6e8a56766d888dc91d599cd

**Comment by bsclifton** [comment]
++ thanks for the assist! :smile:

**Comment by luixxiul** [comment]
Did this fix #4811 too?

**Comment by bsclifton** [comment]
@luixxiul it sure does! thanks :smile: I went ahead and closed #4811
