### PR TITLE
Ensuring File > Share context menu items are disabled when no windows are open

### LINKED ISSUE #13928: error in terminal when selecting File > Share without any open windows
### Test plan
See https://github.com/brave/browser-laptop/pull/13933

### Description
Selecting 'File > Share' from the menu bar when there aren't any open windows throws an error in the terminal but does not seem to affect the application (app doesn't hang, crash, etc).

### Steps to Reproduce

  1. Launch Brave from the terminal.
  2. Close any open windows, but ensure Brave is still running.
  3. Select File > Share

**Actual result:**
Error in terminal:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Cannot read property 'get' of undefined
    at simpleShareActiveTab (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/share.js:33:52)
    at shareReducer (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/reducers/shareReducer.js:23:15)
    at reducers.reduce (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:191:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:189:68)
    at handleAppAction (/Applications/Brave.app/Contents/Resources/app.asar/js/stores/appStore.js:253:16)
    at callbacks.forEach (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:107:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:106:20)
    at AppDispatcher.dispatchInternal (/Applications/Brave.app/Contents/Resources/app.asar/js/dispatcher/appDispatcher.js:132:10)
```

**Expected result:**
No error in terminal.

**Reproduces how often:**
easily

### Brave Version

**about:brave info:**
Brave | 0.22.667
V8 | 6.6.346.24
rev | 0433b26
Muon | 5.2.6
OS Release | 16.7.0
Update Channel | Release
OS Architecture | x64
OS Platform | macOS
Node.js | 7.9.0
Brave Sync | v1.4.2
libchromiumcontent | 66.0.3359.117

**Reproducible on current live release:**
yes, reproduces on 0.22.22

### Additional Information
Found by @kjozwiak

### PR DESCRIPTION
**Pull request by ryanml**
Fixes #13928

This PR also includes some refactoring for the menu code concerning setting the `checked` status of a menu item. The functions are now generalized to setting a given attribute, so that `enabled` can be toggled as well.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
  1. Launch Brave from the terminal.
  2. Close any open windows, but ensure Brave is still running.
  3. Select File > Share
  4. Ensure that all of the submenu options are disabled
  5. Ensure that no error is being shown in the terminal
  6. Open a new window
  7. Select File > Share
  8. Ensure that the submenu options are enabled again

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/browser/menu.js [hunk 1]
```diff
@@ -622,17 +634,28 @@ const doAction = (state, action) => {
...
-          setMenuItemChecked(state, locale.translation('bookmarkPage'), isCurrentLocationBookmarked(state))
+          setMenuItemAttribute(state, locale.translation('bookmarkPage'), 'checked', isCurrentLocationBookmarked(state))
+        }
+        break
+      }
+    case appConstants.APP_WINDOW_CLOSED:
+    case appConstants.APP_WINDOW_CREATED:
+      {
+        const windowCount = BrowserWindow.getAllWindows().filter((w) => w.isFocused()).length
+        if (action.actionType === 'app-window-closed' && windowCount === 0) {
```
Comment (bsclifton) [inline app/browser/menu.js]: could you use the constant name here instead?
`if (action.actionType === appConstants.APP_WINDOW_CLOSED && windowCount === 0) {`

File: app/browser/menu.js [hunk 2]
```diff
@@ -622,17 +634,28 @@ const doAction = (state, action) => {
...
+          updateShareMenuItems(state, false)
+        } else if (action.actionType === 'app-window-created' && windowCount === 1) {
```
Comment (bsclifton) [inline app/browser/menu.js]: Same as above comment

File: app/browser/menu.js [hunk 3]
```diff
@@ -622,17 +634,28 @@ const doAction = (state, action) => {
...
           currentLocation = frame.location
-          setMenuItemChecked(state, locale.translation('bookmarkPage'), isCurrentLocationBookmarked(state))
+          setMenuItemAttribute(state, locale.translation('bookmarkPage'), 'checked', isCurrentLocationBookmarked(state))
+        }
+        break
+      }
+    case appConstants.APP_WINDOW_CLOSED:
+    case appConstants.APP_WINDOW_CREATED:
+      {
+        const windowCount = BrowserWindow.getAllWindows().filter((w) => w.isFocused()).length
```
Comment (petemill) [inline app/browser/menu.js]: Please don't use the muon `BrowserWindow` API raw. Instead please use the `app/browser/windows.js` API, specifically `getAllRendererWindows` or `getActiveWindow`. The former should be enough as it makes sure the hidden window isn't included.

Comment (bsclifton) [reply app/browser/menu.js]: Good call- I was wondering that myself 😄

**Comment by ryanml** [comment]
Changes pushed

cc: @bsclifton @petemill

File: app/browser/share.js [hunk 4]
```diff
@@ -19,6 +19,11 @@ const templateUrls = {
   reddit: 'https://reddit.com/submit?url={url}&title={title}'
 }
 
+// Sites that are not currently in the File > Share context menu
+const excludedShareSites = [
```
Comment (petemill) [inline app/browser/share.js]: Do we need this rather than just remove the _digg_ item from `templateUrls`. From a quick search I could not find any other usage of the `templateUrls` export from _share.js_.

Comment (ryanml) [reply app/browser/share.js]: @petemill good thought, I did a search and it looks fine to remove. I've pushed an update removing the `excludedShareSites` addition. I left removing Digg from `templateUrls` a separate commit for ease of search should we want to add it back at any point.

**Comment by bsclifton** [comment]
master ca83ee381e6152704c4c1793f118d89d0770e6dc
0.23.x 1954b5c06d3351d2673be02adea0e09387408be9
0.22.x-release3 4403af239f154d5b072b5c42440581b5c23f9649
