### PR TITLE
Fixes edit flow for bookmarks and folders

### LINKED ISSUE #12484: moving bookmark folder from Bookmarks Toolbar to Other Bookmarks still displays on toolbar
### Test plan
  1. Open Bookmarks Manager
  2. Add a folder under 'Bookmarks Toolbar'
  3. Verify folder displays on the Bookmarks Toolbar.
  4. Drag and drop the folder from step 2 to 'Other Bookmarks'
  5. Folder should move

### Description
Using the Bookmark Manager, if you move a folder from Bookmarks Toolbar to Other Bookmarks, the folder still displays on the toolbar until you add another folder.

### Steps to Reproduce

  1. Open Bookmarks Manager
  2. Add a folder under 'Bookmarks Toolbar'
  3. Verify folder displays on the Bookmarks Toolbar.
  4. Drag and drop the folder from step 2 to 'Other Bookmarks'

**Actual result:**
Folder still displays on the Bookmarks Toolbar:
bookmarktoolbar

**Expected result:**
Bookmark Folder should not display on the Toolbar.

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.20.14
V8 | 6.3.292.48
rev | 5d75826
Muon | 4.5.33

**Reproducible on current live release:**
No, not reproducible due to https://github.com/brave/browser-laptop/issues/12378

### Additional Information
Found by @kjozwiak and reproduced on MacOS

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #12484

Auditors:

Test Plan:

1. Have a folder on Bookmarks Toolbar
2. Right click on the folder, Edit Folder
3. Change location to be 'Other Bookmarks' instead of 'Bookmarks Toolbar', click Done.
4. Folder continues to display on Bookmarks Toolbar.

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/common/state/bookmarkFoldersState.js [hunk 1]
```diff
@@ -74,11 +74,10 @@ const bookmarkFoldersState = {
     return state
   },
 
-  editFolder: (state, editKey, folderDetails) => {
+  editFolder: (state, editKey, oldFolder, folderDetails) => {
     state = validateState(state)
-    const oldFolder = bookmarkFoldersState.getFolder(state, editKey)
 
-    if (oldFolder.isEmpty()) {
+    if (oldFolder == null) {
```
Comment (bsclifton) [inline app/common/state/bookmarkFoldersState.js]: Will this condition ever get hit (null/undefined being passed in)? The caller isn't checking for null/undefined before calling `.isEmpty()` on the param

**Comment by bsclifton** [comment]
master 986e10eb154cf99ad12b15248f3d1e6e490f2667
0.21.x 0a62a7e74ce6edb96254cde67685c96d468f4fd4
0.20.x 999e451082352f895c97202615a27a25b408824a
