### PR TITLE
Fix tabs briefly animating too wide after finishing closing some tabs

### LINKED ISSUE #12566: Closing fixed-width tabs and then moving mouse away animates tabs past bounds of tab-bar
### Description
Bug introduced by #11438 and reported by @luixxiul in https://github.com/brave/browser-laptop/pull/11438#issuecomment-336662415

### Steps to Reproduce
from https://github.com/brave/browser-laptop/pull/11438#issuecomment-337137402
1. Open 10 tabs (until the tab size changes)
2. Click the close button on a tab
3. Move the mouse cursor from the tabs bar

tabs

Should animate to final width, not too wide and then back to final width.

**Reproduces how often:**
100% on master

### Brave Version

**about:brave info:**
0.22

**Reproducible on current live release:**
No

### PR DESCRIPTION
**Pull request by petemill**
Fix #12566

Since each tab's 'fixed width' was being removed at the same time, each one was measuring the width whilst other tab(s) were / were not reset eback to a fluid width, causing measurements to be off.
Flex supports transitions / animations by default, so we do not need to measure the element ourselves in this case, anyway.
Bonus for being able to move from in-component animation to purely defined in styles.

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Test Plan:

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/tabs/tab.js [hunk 1]
```diff
@@ -334,16 +311,17 @@ class Tab extends React.Component {
...
       )}
-      style={this.props.tabWidth ? { flex: `0 0 ${this.props.tabWidth}px` } : {}}
       onMouseMove={this.onMouseMove}
       onMouseEnter={this.onMouseEnter}
       onMouseLeave={this.onMouseLeave}
       data-test-id='tab-area'
       data-frame-key={this.props.frameKey}
       ref={elementRef => { this.elementRef = elementRef }}
-      >
+      style={this.props.tabWidth ? { '--tab-forced-width': `${this.props.tabWidth}px` } : { }}
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/tab.js]: nit: no need for space inside brackets

**Comment by cezaraugusto** [comment]
reverted in c36885b
