### PR TITLE
Replace slashdot with local iframe with adblock

### LINKED ISSUE #8760: Replace slashdot in braveryTestPanel.js with our own iframe to fix travis error
## Test plan
https://github.com/brave/browser-laptop/pull/9148#issue-232353963

`npm run test -- --grep="Adblock stats iframe tests"`

----

**Describe the issue you encountered:** It seems that the travis tests which display `slashdot.org` in an iframe fail a lot of times (or always):

https://travis-ci.org/brave/browser-laptop/jobs/229862037#L4225
https://travis-ci.org/brave/browser-laptop/jobs/229553024#L4252
https://travis-ci.org/brave/browser-laptop/jobs/229253934#L4111

Locally the tests fail intermittently.

The tests are described here: https://github.com/brave/browser-laptop/blob/deddb5a017544cd701ad07e36c03dfcc3652967e/test/bravery-components/braveryPanelTest.js#L239-L292

We would have to create our own iframe to fix the error. I'm assigning the task with @bridiver for now per https://github.com/brave/browser-laptop/commit/f78430c6e9eed74d4f6c42a2fbed9bb97900de04#diff-c98f35b50afd3f874bd2cf4a51548112R215, though someone else could take it I think.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by cezaraugusto**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditors: @bbondy
Close #8760

Test plan:
npm run test -- --grep="Adblock stats iframe tests"

Reviewer Checklist:

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by luixxiul** [comment]
@cezaraugusto would you please remove https://github.com/brave/browser-laptop/blob/78e7a37c3186837daa3ffcbae555bd1a67d3ca10/test/bravery-components/braveryPanelTest.js#L467?

Otherwise, would you please move the 2 tests to that line (See: #8770) ?

**Comment by NejcZdovc** [comment]
Because this is automated test I will change milestone to 0.18, because there is no need to cherry pick this to 0.16 and 0.17 branch.

File: test/bravery-components/braveryPanelTest.js [hunk 1]
```diff
@@ -954,26 +954,23 @@ describe('Bravery Panel', function () {
     })
   })
 
-  // TODO: Fix iframe tests (See: #8760)
   describe('Adblock stats iframe tests', function () {
     Brave.beforeEach(this)
     beforeEach(function * () {
       yield setup(this.app.client)
-      yield this.app.client
-        .waitForDataFile('adblock')
```
Comment (diracdeltas) [inline test/bravery-components/braveryPanelTest.js]: Aren't the two lines above still needed?

File: test/fixtures/adblock2.html [hunk 2]
```diff
@@ -0,0 +1,2 @@
+<h1>serg don't know pokemons</h1>
```
Comment (diracdeltas) [inline test/fixtures/adblock2.html]: OMG is this true about serg

File: test/bravery-components/braveryPanelTest.js [hunk 3]
```diff
@@ -983,37 +980,45 @@ describe('Bravery Panel', function () {
...
+        .moveToObject(adsBlockedStat)
         .waitForTextValue(adsBlockedStat, '0')
         .click(adsBlockedControl)
         .waitForVisible(blockAdsOption)
         .click(blockAdsOption)
+        .moveToObject(adsBlockedStat)
         .waitUntil(function () {
           return this.getText(adsBlockedStat)
-            .then((blocked) => Number(blocked) > 1)
+            .then((blocked) => Number(blocked) >= 1)
```
Comment (diracdeltas) [inline test/bravery-components/braveryPanelTest.js]: Can all of these be `=== 1` instead of `>= 1`

File: test/bravery-components/braveryPanelTest.js (hunk 1 above)
Comment (cezaraugusto) [inline test/bravery-components/braveryPanelTest.js]: I thought it was but removing it increased test speed and adblock was recognized same way. For some reason dataFile is unreachable for a long time and was leading to intermittent fail. Same for other dataFile requests but for adblock seems worse.

File: test/fixtures/adblock2.html (hunk 2 above)
Comment (cezaraugusto) [inline test/fixtures/adblock2.html]: ya unfortunately :___(

**Comment by cezaraugusto** [comment]
earlier feedback addressed and based on
* https://travis-ci.org/brave/browser-laptop/jobs/237647068#L2976 and;
* https://travis-ci.org/brave/browser-laptop/jobs/240228807#L3024 

I'm going to merge. Thanks all
