### PR TITLE
windows restore in the correct order to ensure correct focused window

### LINKED ISSUE #13158: Focused window does not have focus when restarting
note: I noticed this, and made a fix, when testing Buffer Windows in #12438, but it is a regression from 0.20.x or before. Assigning to same milestone as buffer windows, but can be moved if the fix shouldn't land in that milestone.

### Description
This is caused by two reasons:
- An incorrect redux action name is preventing 'focusTime' from getting saved to windowState accurately
- We now open windows asynchronously, so window's could render and be shown, at different times and not in the order the windows were asked to be created

### Test plan / Steps to Reproduce

  1. Open several windows with tabs
  2. Place the windows at different coordinates with different sizes
  2. Focus the windows in a specific order
  2. Quit Brave
  3. Start Brave

**Actual result:**
- The last-focused window does not always have focus.
- The stacking order is not remembered.

**Expected result:**
The windows are layered in the same stacking order as they were previously. The last window to have focus, has focus after restart

### PR DESCRIPTION
**Pull request by petemill**
Do not merge before #12438 since it's best to test this fix with those changes too as that PR changes a lot of window logic. This PR should only show 1 commit to merge.

Fix #13158 

Note that this test plan may never be 100% robust, but this gets us closer.
There will be additional cases that cannot reproduce success (i.e. if a window is macOS fullscreen), but the code to 'fix' those scenarios would likely introduce new issues and/or not be maintainable, for arguably small benefit.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:
On #13158 

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: js/entry.js [hunk 1]
```diff
@@ -77,6 +77,9 @@ ipc.on(messages.INITIALIZE_WINDOW, (e, mem) => {
   const windowValue = message.windowValue
 
   currentWindow.setWindowId(windowValue.id)
+  if (process.env.NODE_ENV === 'development') {
+    console.debug(`This Window's ID is:`, windowValue.id)
```
Comment (petemill) [inline js/entry.js]: Just a little something in each window's console.log to aid window debugging (when in dev mode, and set to show debug messages).

File: js/stores/windowStore.js [hunk 2]
```diff
@@ -752,21 +750,18 @@ const doAction = (action) => {
         }
         break
       }
-    case windowConstants.WINDOW_ON_WINDOW_UPDATE:
```
Comment (petemill) [inline js/stores/windowStore.js]: This constant does not exist

File: js/stores/windowStore.js [hunk 3]
```diff
@@ -752,21 +750,18 @@ const doAction = (action) => {
...
     case appConstants.APP_WINDOW_READY:
-      {
-        const oldInfo = windowState.get('windowInfo', Immutable.Map())
-        let windowValue = makeImmutable(action.windowValue)
-
-        if (windowValue.get('focused')) {
-          windowValue = windowValue.set('focusTime', performance.timing.navigationStart + performance.now())
```
Comment (petemill) [inline js/stores/windowStore.js]: This should be set whenever window is updated (not only when it's ready) as we want to save which window **last** had focus. Also we can use `new Date().getTime()` as milliseconds are perfectly fine, we don't need to resolve to a microsecond for this.

**Comment by bsclifton** [comment]
master 1f4058e5646fa78523b5668ceac05fd55176cd52
0.22.x 7fd3c16bd2810e34c9d1c4931e65b57511e7a97c
0.21.x 9d1d278efded01dbbee0ee5df962cdec942c53a8
