### PR TITLE
Prevent borkiness when session-store file is missing perWindowState[].closedFrames

### LINKED ISSUE #13261: bad session state can result in permanently borked profile
### Description
I haven't reproduced yet, but I was following the test plans set out in https://github.com/brave/browser-laptop/pull/11313 for the keyboard shortcuts. I close Brave and reopened near the end to see if my tab order was preserved and that's when I discovered that my profile is borked. I can't reload existing tabs, new windows are useless, my pinned tabs spin, I can't open new tabs.

### Steps to Reproduce

I don't have exact steps yet, I was using a clean profile to follow the test cases in the PR referenced above. Generally this is what I did:
  1.  Clean profile using 0.21.11
  2. Open several tabs with sites. Use keyboard shortcut ctrl+shift+pg up/down to move tabs around.
  3. Open a second window. Repeat step 2.
  4. In second window, pin some of the tabs. Open some new tabs with different sites.
  5. In second window, move pinned tabs around with keyboard shortcut. 
  6. In second window, move normal (not pinned) tabs around with keyboard shortcut.
  7. Open prefs, change tab count to 6 per tab page.
  8. Close/Reopen Brave.

#### Another STR from #1339
(steps 2 and 3 don't seem required to reproduce, and can reproduce on 0.20)
  1. Clean install 0.21.17
  2. Launch browser with `LEDGER_ENVIRONMENT=staging` (not sure if this makes any difference but issue found when launched with this env variable
  3. Enable payments and add some funds
  4. Open a new tab and type a wrong URL ( i had typed http://epcohconverter.com)
  5. Console shows error 
  6. Try entering correct URL, doesn't work
  7. Try opening a new tab, doesn't load a new tab
  8. Unable to close browser have to kill the app

**Actual result:**
Profile borked. Error in console shows:

Uncaught TypeError: Cannot read property 'filterNot' of undefined
    at R (gen/app.entry.js:1)
    at callbacks.forEach (gen/app.entry.js:1)
    at Array.forEach (<anonymous>)
    at Object.dispatchToOwnRegisteredCallbacks (gen/app.entry.js:1)
    at Object.dispatchInternal (gen/app.entry.js:1)
    at n.cargo (gen/app.entry.js:1)
    at Object.process (gen/app.entry.js:1)
    at gen/app.entry.js:1
    at gen/app.entry.js:1
    at gen/lib.devTools.js:1

**Expected result:**
Profile should not be borked

**Reproduces how often:**
Unknown

### Brave Version

**about:brave info:**
0.21.11

**Reproducible on current live release:**
yes

### Additional Information
I did this with a testing profile, I can provide it if it will be helpful.

### PR DESCRIPTION
**Pull request by petemill**
This would then cause the app never recover, even after restart. Especially with an `about:error` tab in the session-store, which would immediately cause `appActions.removeHistorySite` to fire when it fails to load. The reducer of that action relied on `windowState.closedFrames` being there. This changes it to not rely on that.

Fix #13261, although since that's not reproducible I'm not sure the moving-tab keyboard shortcut necessarily caused it, but something did, and this will allow recovery in that situation.

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: js/stores/appStore.js [hunk 1]
```diff
@@ -328,41 +328,48 @@ const handleAppAction = (action) => {
...
-
-      // Insert notification next to those with the same style, or at the end
-      let insertIndex = notifications.size
-      const style = action.detail.get
-        ? action.detail.get('options').get('style')
-        : action.detail['options']['style']
-      if (style) {
-        const styleIndex = notifications.findLastIndex((notification) => {
-          return notification.get('options').get('style') === style
+      {
```
Comment (bsclifton) [inline js/stores/appStore.js]: added `{` so that variables defined here are scoped

File: js/stores/appStore.js [hunk 2]
```diff
@@ -328,41 +328,48 @@ const handleAppAction = (action) => {
...
-          insertIndex = styleIndex
-        } else {
-          // Insert after the last notification with a style
-          insertIndex = notifications.findLastIndex((notification) => {
-            return typeof notification.get('options').get('style') === 'string'
-          }) + 1
+
+        // Insert notification next to those with the same style, or at the end
+        let insertIndex = notifications.size
+        const style = action.detail
```
Comment (bsclifton) [inline js/stores/appStore.js]: updated this to handle `detail` being falsey

File: js/stores/appStore.js [hunk 3]
```diff
@@ -328,41 +328,48 @@ const handleAppAction = (action) => {
...
       }
-      notifications = notifications.insert(insertIndex, Immutable.fromJS(action.detail))
-      appState = appState.set('notifications', notifications)
-      break
     case appConstants.APP_HIDE_NOTIFICATION:
-      appState = appState.set('notifications', appState.get('notifications').filterNot((notification) => {
-        return notification.get('message') === action.message
-      }))
-      break
+      {
```
Comment (bsclifton) [inline js/stores/appStore.js]: `{` for scope (same as above)

**Comment by petemill** [comment]
0.22.x 4388e3c69
