### PR TITLE
sortabletable fixes, make ledger table sortable

### LINKED ISSUE #4046: ledger synopsis table should be sortable
each of the columns should be sortable

### LINKED ISSUE #4047: about:history sort-by-time sorts in lexicographical order, not chronological
ex:
screen shot 2016-09-15 at 11 50 38 pm

### PR DESCRIPTION
**Pull request by diracdeltas**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #4047 
FIx #4046 
Also refactors SortableTable for performance

Test Plan:
1. make sure sorting by time in about:history sorts in chronological order, not lexicographic
2. go to about:preferences#payments, make sure it's sorted by increasing rank
3. click all of the column headers and make sure it sorts

Auditors: @bsclifton

### CODE REVIEW

File: js/components/sortableTable.js [hunk 1]
```diff
@@ -53,53 +60,51 @@ class SortableTable extends ImmutableComponent {
...
+              data-context-menu-disable={rowAttributes.onContextMenu ? true : undefined}
+              className={this.hasRowClassNames ? this.props.rowClassNames[i] : undefined}>{entry}</tr>
+          })
+        }
       </tbody>
     </table>
   }
 }
 
-SortableTable.defaultProps = {
```
Comment (diracdeltas) [inline js/components/sortableTable.js]: i took this out because no other components use defaultProps

File: js/about/history.js [hunk 2]
```diff
@@ -34,10 +34,15 @@ class HistoryDay extends ImmutableComponent {
     return <div>
       <div className='sectionTitle historyDayName'>{this.props.date}</div>
       <SortableTable headings={['time', 'title', 'domain']}
+        defaultHeading='time'
+        defaultHeadingSortOrder='desc'
         rows={this.props.entries.map((entry) => [
-          entry.get('lastAccessedTime')
-            ? new Date(entry.get('lastAccessedTime')).toLocaleTimeString()
-            : '',
+          {
```
Comment (bsclifton) [inline js/about/history.js]: :heart:

**Comment by bsclifton** [comment]
Pulled it locally and tested- confirmed it's working good. Spacing seems to be a little different with the ledger screen, but still looks great.

Great job :smile:
