### PR TITLE
Stop beach balling with this one simple trick

### LINKED ISSUE #10094: Browser freezes per 5 minutes with existing profile
**Describe the issue you encountered:** Browser freezes with existing profile. The issue is not reproducible for me on macOS. I have not tested the issue on a linux distribution or Windows 7.

A related issue was reported here: https://community.brave.com/t/brave-freezes-after-short-period-of-being-idle/4783/10

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version (revision SHA): 0.17.19

- Steps to reproduce:
    1. Use the browser long (to load much data on the browser's profile)
    2. Load a youtube video (to make the lag noticiable)
    
- Actual result: the browser freezes for seconds per some minutes

- Expected result: the browser should not freeze

- Will the steps above reproduce in a fresh profile?
   No, I don't think so.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #9808 #9311

### PR DESCRIPTION
**Pull request by bbondy**
Fix #10094

The problem is with toJS being called to convert the immutable app state

Instead we just keep everything in Immutable

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:
- Please fully test session restore
  - active tab is preserved
  - windows with tabs are preserved
  - test that updates do not clear session storage
  - etc.
- Note that while testing this I noticed https://github.com/brave/browser-laptop/issues/10349 but it is not related to this task. It happens even on production.

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
Whoops- just noticed this is still a WIP; sorry for assigning folks (I had just picked the recommended reviewers 😄 )

**Comment by cezaraugusto** [comment]
screen shot 2017-08-07 at 11 44 18 pm
screen shot 2017-08-07 at 11 46 44 pm
screen shot 2017-08-07 at 11 54 21 pm

**Comment by bbondy** [comment]
before:
```
cleanAppData: 3159.975ms
getStoragePath: 0.033ms
stringify: 125.966ms
writeImportantBlocking: 83.684ms
writeImportant: 103.235ms
resolve: 0.008ms
```

after:
```
cleanAppData: 0.904ms
getStoragePath: 0.018ms
stringify: 261.541ms
writeImportantBlocking: 57.554ms
writeImportant: 75.337ms
resolve: 0.008ms
```

File: app/common/state/tabState.js [hunk 1]
```diff
@@ -610,7 +610,7 @@ const tabState = {
     state = tabState.removeTabField(state, 'messageBoxDetail')
     state = tabState.removeTabField(state, 'frame')
     state = state.delete('tabsInternal')
-    return state.delete('tabs')
+    return state.set('tabs', Immutable.List())
```
Comment (bridiver) [inline app/common/state/tabState.js]: why the change from `delete` to an empty list?

Comment (bbondy) [inline app/common/state/tabState.js]: because we used to set default app state in 2 places but now just one place.  Via Object.assign after a clean, but I'd of had to have 2 different methods for that, one for immutable and one for not.

**Comment by luixxiul** [comment]
Looking forward to see this landed :-) We will have to search other issues which can be closed thanks to this, ones labelled with [`perf`](https://github.com/brave/browser-laptop/labels/perf).  I'm going to do QA on #10094 with my own browser's profile which cannot be shared.

File: app/common/state/tabState.js (hunk 1 above)
Comment (bridiver) [inline app/common/state/tabState.js]: I think that might be a problem because at some point in the near future we won't be deleting the tabs and so this won't be equivalent to a default state

Comment (bbondy) [inline app/common/state/tabState.js]: that would be perfectly fine to not delete the state.  It's just that if you put undefined for 'tabs' in state here then it won't get filled later.

**Comment by bbondy** [comment]
merged to master, but this is going to take me a while to rebase for other branches. 
I'll update here as I do other branches.

File: test/unit/app/common/state/immutableUtilTest.js [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+      assert.deepEqual(immutableUtil.makeImmutable(Immutable.List()).constructor, Immutable.List)
+    })
+  })
+  describe('deleteImmutablePaths', function () {
+    it('removes properties with simple strings', function () {
+      const data = Immutable.fromJS({a: 'Cezar is a black belt in ameri-do-te', b: 2, c: 3})
+      assert.deepEqual(immutableUtil.deleteImmutablePaths(data, ['a', 'b']).toJS(), {c: 3})
+    })
+    it('removes properties with array string paths', function () {
+      const data = Immutable.fromJS({a: {a1: 4, a2: 8}, c: 'Cezar learnt directly from master ken', d: 5})
```
Comment (luixxiul) [inline test/unit/app/common/state/immutableUtilTest.js]: @cezaraugusto :D

File: test/unit/app/common/state/immutableUtilTest.js [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+    it('converts an Object Immutable.Map to Immutable.Map', function () {
+      assert.deepEqual(immutableUtil.makeImmutable(Immutable.Map()).constructor, Immutable.Map)
+    })
+    it('converts an Array Immutable.List', function () {
+      assert.deepEqual(immutableUtil.makeImmutable(Immutable.List()).constructor, Immutable.List)
+    })
+  })
+  describe('deleteImmutablePaths', function () {
+    it('removes properties with simple strings', function () {
+      const data = Immutable.fromJS({a: 'Cezar is a black belt in ameri-do-te', b: 2, c: 3})
```
Comment (cezaraugusto) [inline test/unit/app/common/state/immutableUtilTest.js]: watch out master ken

File: test/unit/app/common/state/immutableUtilTest.js (hunk 2 above)
Comment (cezaraugusto) [inline test/unit/app/common/state/immutableUtilTest.js]: 👌

**Comment by bbondy** [comment]
Merged to 0.20.x, 0.19.x, and 0.18.x.
Big rebase on 0.20x, other 2 were cleanly applied from the 0.20.x rebase.

**Comment by luixxiul** [comment]
@bbondy should we do QA on each release until 0.21 to see if the rebase was successful?

**Comment by Liunkae** [comment]
Bug possibly caused by this: #10371

**Comment by Liunkae** [comment]
Also, #10376
