### PR TITLE
Removed unneeded context menu items (Fix #3670)

### LINKED ISSUE #3670: New Tab context menu not needed options
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
'Reload' and 'Clone' are not useful in the context menu of a new tab

**Expected behavior:**

- Platform (Win7, 8, 10? macOS? Linux distro?):
Win 10 64

- Brave Version:
0.11.6dev

- Steps to reproduce:
    1. Click the right button on a New Tab

- Screenshot if needed:
new_tab_context_menu

- Any related issues:

### PR DESCRIPTION
**Pull request by Liunkae**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #3670

Don't show "Reload" and "Clone" in the context menu of the new tab page.

### CODE REVIEW

File: js/contextMenus.js [hunk 1]
```diff
@@ -407,30 +407,32 @@ function autofillTemplateInit (suggestions, frame) {
...
-    CommonMenu.separatorMenuItem,
-    {
-      label: locale.translation('reloadTab'),
-      click: (item, focusedWindow) => {
-        if (focusedWindow) {
-          focusedWindow.webContents.send(messages.SHORTCUT_FRAME_RELOAD, frameKey)
+  const location = frameProps.get('location')
+  if (!(location === 'about:blank' || location === 'about:newtab' || isIntermediateAboutPage(location))) {
+    items.push(
+      CommonMenu.newTabMenuItem(frameProps.get('key')),
```
Comment (bbondy) [inline js/contextMenus.js]: Thanks for the patch.
I think new tab should be there regardless

File: js/contextMenus.js [hunk 2]
```diff
@@ -407,30 +407,32 @@ function autofillTemplateInit (suggestions, frame) {
...
-      }
-    }, {
-      label: locale.translation('clone'),
-      click: (item, focusedWindow) => {
-        if (focusedWindow) {
-          focusedWindow.webContents.send(messages.SHORTCUT_FRAME_CLONE, frameKey, {
-            openInForeground: true
-          })
+      }, {
+        label: locale.translation('clone'),
```
Comment (bbondy) [inline js/contextMenus.js]: Actually clone is still a valid operation as well regardless of the current page. Because it clones the full history, you might just want a copy of the history.   Reload isn't needed for now, but it should be for example an intermediate page is also an error page for things like a network connection error.

**Comment by Liunkae** [comment]
@bbondy: I've changed the PR based on your comments.

**Comment by bbondy** [comment]
++
