### PR TITLE
Undefined properties and nested folders handling

### LINKED ISSUE #5291: 1Password and LastPass repeated entries in right click context menu
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
1Password and LastPass repeated entries in right click context menu 

**Expected behavior:**
Should only be shown once

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 Preview 1

- Steps to reproduce:
    1. Enable 1Password from preferences
    2. Right click shows two entries for 1Password in context menu
    3. Enable LastPass from preferences
    4. Right click shows three entries for 1Password in context menu

- Screenshot if needed:
image

- Any related issues:

### LINKED ISSUE #5293: Right Click doesn't work after logging into LastPass extension
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Right Click doesn't work after logging into LastPass extension

**Expected behavior:**
Should be able to right click and open context menu

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.8 Preview 1

- Steps to reproduce:
    1. Enable LastPass from password managers in preferences
    2. Login to your LastPass account
    3. Right click on the page doesn't work, Console shows error 

- Screenshot if needed:
 image

- Any related issues:
cc:  @bridiver

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

fix #5291
fix #5293

requires brave/electron#85

Auditors: @bridiver, @bbondy

Test Plan:
1. Go to about:preferences#security
2. Select Lastpass as password manager
3. Login to Lastpass
4. Right click to show context menu
5. Nested menu of Lastpass should show

Screen shots
---
brave
screen shot 2016-10-31 at 18 23 51

chrome
screen shot 2016-10-31 at 14 16 23

### CODE REVIEW

File: js/contextMenus.js [hunk 1]
```diff
@@ -1093,7 +1093,8 @@ function mainTemplateInit (nodeProps, frame) {
   })
 
   const passwordManager = getActivePasswordManager()
-  if (passwordManager.get('extensionId')) {
+  if (passwordManager.get('extensionId') &&
+    passwordManager.get('displayName') === 'Dashlane') {
```
Comment (bridiver) [inline js/contextMenus.js]: why is this only for dashlane?

Comment (darkdh) [inline js/contextMenus.js]: because dashlane doesn't create context menus and other's do which cause repeated entries shows in https://github.com/brave/browser-laptop/issues/5291

Comment (bridiver) [inline js/contextMenus.js]: we can just remove these then. The only reason we created context menus for the password managers was because we didn't have contextMenu api support.

Comment (darkdh) [inline js/contextMenus.js]: ok, I see. removed!

**Comment by bbondy** [comment]
++
