### PR TITLE
Bypass cookie mismatch error on google login

### LINKED ISSUE #11401: .google.com cookie mismatch after import
## Test plan

https://github.com/brave/browser-laptop/pull/11647#issue-267885634

----

### Description
Import cookies from Chrome/Firefox will cause cookie mismatch error on google.com

### Steps to Reproduce

  1.  Clean cookies on Chrome/Firefox and login in google account
  2.  Import cookies from Chrome/Firefox to Brave
  3.  Login google account on Brave

**Actual result:**

screen shot 2017-10-08 at 2 32 17 pm

**Expected result:**
No cookie mismatch error
**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version
0.19.36
**about:brave info:**

 
Brave: 0.19.36 
rev: d24779f2704b4eb6fd5e7b0502a9ff1227f616bb 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Beta 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64
**Reproducible on current live release:**

Yes
### Additional Information

Opera has the same problem
related to #11356

### PR DESCRIPTION
**Pull request by darkdh**
Auditors: @bbondy, @bsclifton

fix #11401

Test Plan:
1. Clean cookies on Chrome/Firefox and login in google account
2. Import cookies from Chrome/Firefox to Brave
3. Login google account on Brave
4. Import cookies from Chrome/Firefox to Brave and refresh
5. Logout google account on Brave
6. There shouldn't be any cookie mismatch error pages displayed within these steps

Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [ ] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
@darkdh is this related to cr62? if so, please change milestone for this PR to the second 0.19 release

**Comment by darkdh** [comment]
@NejcZdovc no, it is the problem of pure cookie importing on google account. Just hasn't been found before

File: app/importer.js [hunk 1]
```diff
@@ -234,9 +234,17 @@ importer.on('add-cookies', (e, cookies) => {
       httpOnly: cookies[i].httponly,
       expirationDate: cookies[i].expiry_date
     }
+    // Bypassing cookie mistach error in
```
Comment (bsclifton) [inline app/importer.js]: typo here- should be `mismatch`

So this is avoiding the error by not importing Google cookies? Is that an acceptable solution?

File: app/importer.js [hunk 2]
```diff
@@ -234,9 +234,17 @@ importer.on('add-cookies', (e, cookies) => {
...
+    // https://github.com/brave/browser-laptop/issues/11401
+    if (cookie.domain === '.google.com' &&
```
Comment (bsclifton) [inline app/importer.js]: Can we pull this out to a function? So then it would look like:
```
if (shouldSkipCookie(cookie.domain, cookie.url)) {
  continue
}
```

File: app/importer.js (hunk 1 above)
Comment (darkdh) [reply app/importer.js]: They are like blackbox even if I can see the name and value. And it is not a single cookie cause problem so I narrowed them down to a small set.

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/076421c02159a1db9320a56c1cd654b1481132e7
0.20.x https://github.com/brave/browser-laptop/commit/be7b3332fbb4c46eb870a0a1b639004d2dae39f0
0.19.x https://github.com/brave/browser-laptop/commit/53e9e61c84f7ef1bbd48d685b7a29e7ca454328d
