### PR TITLE
Fixed recovery overlay showing invalid amount before completion

### LINKED ISSUE #11790: loading/progress indicator for wallet recovery
### Description
Several users have mentioned that after entering or importing their BAT wallet recovery keys, it doesn't appear as though anything is happening on the UI. They have requested some kind of loading or progress indicator to let the user know something is happening. If a progress indicator isn't possible, maybe some kind of transition overlay (spinning circle?) to let the user know something is going on in the background.

### Steps to Reproduce

  1. Have backup words for a BAT wallet.
  2. Create a new profile and enable payments.
  3. Recover your wallet.

**Actual result:**
Sometimes wallet recovery takes up to 10 minutes, during this time there is no visual indication in the UI that anything is happening.

**Expected result:**
Some kind of visual notifier that a wallet recovery is being attempted.

**Reproduces how often:**
unknown. sometimes wallets recover fast, so this isn't an issue. other times it takes up to 10 minutes.

### Brave Version
BAT Mercury enabled versions (0.19.48, 0.19.70, etc)

**Reproducible on current live release:**
yes

### PR DESCRIPTION
**Pull request by jasonrsadler**
Fixes #11790 

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [x] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Test Plan:

1. Run Brave -> preferences -> payments -> advanced settings
2. Use a recovery file with funds attached to it to recover wallet.
3. If recovery is delayed, overlay will display 'Calculating balance...' where the recovery amount would display

@bradleyrichter for 'Calculating balance...' text

NOTE: Newly made recovery keys may not show the delay that would have shown the incorrect balance. ping @jasonrsadler for keys that can be used to demonstrate.

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/ledgerRecovery.js [hunk 1]
```diff
@@ -65,11 +65,30 @@ class LedgerRecoveryContent extends ImmutableComponent {
     const recoverySucceeded = this.props.ledgerData.get('recoverySucceeded')
     const recoveryError = this.props.ledgerData.getIn(['error', 'error'])
     const recoveryInProgress = this.props.ledgerData.get('recoveryInProgress')
+    const recoveryBalanceRecalculated = this.props.ledgerData.get('recoveryBalanceRecalculated') || false
+    console.log(recoveryBalanceRecalculated)
```
Comment (ryanml) [inline app/renderer/components/preferences/payment/ledgerRecovery.js]: Extra log :)

File: app/browser/api/ledger.js [hunk 2]
```diff
@@ -1162,6 +1162,7 @@ const recoverKeys = (state, useRecoveryKeyFile, key) => {
     return state
   }
 
+  state = aboutPreferencesState.setPreferencesProp(state, 'recoveryBalanceRecalculated', false)
```
Comment (ryanml) [inline app/browser/api/ledger.js]: Could you maybe refactor updates to `recoveryBalanceRecalculated` as its own function inside `aboutPreferencesState`, similar to the other functions dealing with recovery props? Just to keep things consistent :)

Comment (jasonrsadler) [reply app/browser/api/ledger.js]: You got it

**Comment by jasonrsadler** [comment]
Tests coming
