### PR TITLE
Autofill should focus on first entry Fix #8280

### LINKED ISSUE #8280: Autofill should automatically move cursor to first entry when adding a new record
## Test Plan:
1. Open browser and type about:autofill
2. Click on Add Address or Add Credit Card
2. Cursor will focus on first input field

## Original issue description
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When adding a record, I found that I had to click in the modal first to edit values.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.14.2 (f07c142)

- Steps to reproduce:
    1.  visit about:autofill
    2. add a record
    3.
    
- Actual result:
The cursor is not in any available field

- Expected result:
The cursor should move to the first field and save the user a click

- Will the steps above reproduce in a fresh profile? If not what other info can be added?

- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by kumarrishav**
## Test Plan:
1. Open browser and type about:autofill
2. Click on Add Address or Add Credit Card
3. Cursor will focus on first input field

## Description
Fix #8280 
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

screen shot 2017-04-26 at 11 10 15 pm
screen shot 2017-04-26 at 11 10 51 pm
screen shot 2017-04-26 at 11 11 04 pm

### CODE REVIEW

File: app/renderer/components/autofill/autofillAddressPanel.js [hunk 1]
```diff
@@ -136,7 +138,7 @@ class AutofillAddressPanel extends ImmutableComponent {
               )}
                 data-test-id='nameOnAddress'
                 spellCheck='false' onKeyDown={this.onKeyDown} onChange={this.onNameChange}
-                value={this.props.currentDetail.get('name')}
+                value={this.props.currentDetail.get('name') || ''}
```
Comment (kumarrishav) [inline app/renderer/components/autofill/autofillAddressPanel.js]: I added default value as {this.props.currentDetail.get('name') || ''} to avoid the warning (because of react 15 upgrade).
warning.js?8a56:36
Warning: AutofillAddressPanel is changing an uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components.

File: app/renderer/components/autofill/autofillCreditCardPanel.js [hunk 2]
```diff
@@ -115,7 +118,7 @@ class AutofillCreditCardPanel extends ImmutableComponent {
                   spellCheck='false'
                   onKeyDown={this.onKeyDown}
                   onChange={this.onNameChange}
-                  value={this.props.currentDetail.get('name')}
+                  value={this.props.currentDetail.get('name') || ''}
```
Comment (kumarrishav) [inline app/renderer/components/autofill/autofillCreditCardPanel.js]: same here.

**Comment by kumarrishav** [comment]
screen shot 2017-04-27 at 12 01 51 am
Warning in console

**Comment by kumarrishav** [comment]
@darkdh will test/contents/autofillTest.js be right place to test this? As name suggests this is to test the content in input field. I tried to find autofill related test test/app/renderer/components/ but couldn't find any.

**Comment by darkdh** [comment]
@kumarrishav you can add test there for now. All the autofill tests are in `test/contents/autofillTest.js` but we can do refactor later.

**Comment by kumarrishav** [comment]
@darkdh sure will do. 
Btw i am facing this issue. what can be possible issue? https://community.brave.com/t/unable-to-run-test/2370

**Comment by darkdh** [comment]
sorry for the inconvenience. please do the following steps

1. make sure you have `node v7.9.0`
2. make sure your `.npmrc` contains this change https://github.com/brave/browser-laptop/commit/3f589aad953731c54b6596aa55f9efebfb52349f
3. 
```
$ npm clean cache
$ rm -rf ~/.node-gyp
$ rm -rf ~/.electron
$ rm -rf node_modules
$ npm install 
```

**Comment by kumarrishav** [comment]
@darkdh sorry it failed again.
Currently i am on master branch (latest code).
This time different error: 

> brave@0.15.0 test /Users/krishav/Documents/FOSS/Brave/browser-laptop
> cross-env NODE_ENV=test mocha "test/**/*Test.js"

/Users/krishav/Documents/FOSS/Brave/browser-laptop/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: The module '/Users/krishav/Documents/FOSS/Brave/browser-laptop/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 55. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/krishav/Documents/FOSS/Brave/browser-laptop/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/krishav/Documents/FOSS/Brave/browser-laptop/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)

**Comment by kumarrishav** [comment]
why this version issue is happening?

**Comment by darkdh** [comment]
@kumarrishav it is because we have different ABI version. Please contain this commit https://github.com/brave/browser-laptop/commit/576921b2501f1111072e06b8bf1f1be7cee076ef and try again.

**Comment by kumarrishav** [comment]
@darkdh this fixes the issue.

**Comment by kumarrishav** [comment]
@darkdh I am not sure how to test the 'focus' thing in integration test. Also, i am getting this error while running test.
screen shot 2017-04-28 at 6 24 53 pm

**Comment by luixxiul** [comment]
I exactly experience the same thing on macOS to run unit tests. Could anyone let me know how to avoid it?

**Comment by darkdh** [comment]
@kumarrishav please rebase to master and try again. There will be some intermittent errors but at least `Autofill address` and `Autofill credit card` is testable
You can use `waitForElementFocus` to check element is focused and just add a `it('check focus', function * () {})` to `Autofill address` and `Autofill credit card` before `adds` section.

**Comment by kumarrishav** [comment]
@darkdh sorry, but still same error. It fails at beforeEach hook. Though it fills the form, but fails at first it.('adds an autofill address' function * () {}) itself

**Comment by NejcZdovc** [comment]
@kumarrishav I just try running test on the master and it's working for me

image

**Comment by luixxiul** [comment]
@kumarrishav to run webdriver test open a console, run `npm run watch-test`. open another console and run the test specified above. It should work.

**Comment by darkdh** [comment]
@kumarrishav you can also run `npm run watch-all` which allows you to run test and launch browser-laptop

**Comment by kumarrishav** [comment]
Sorry @darkdh Still same error. Don't know why it's not working in my system (Mac OS, Node -v : 7.9.0 and npm 4.2.0). Can we move this test later to UT (and file another issue for same)

**Comment by darkdh** [comment]
@kumarrishav , I've added the test in d1f502ad662ceaf8792fcc25a219c083f6fee577
Thanks for your work.

**Comment by bsclifton** [comment]
Thanks, @kumarrishav! 😄
