### PR TITLE
Handle mergeable entry after adding

### LINKED ISSUE #3368: Editing Autofill entries are not saved. Creates a blank entry
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Editing Autofill entries are not saved. Creates a blank entry. Also the entry modal is not center aligned. Always on the left.
Same issue with editing and saving Credit Card info

**Expected behavior:**
Should save the newly added/removed entries

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.11.6 Beta 3

- Steps to reproduce:
    1. Do a clean install of 0.11.6 Beta 3 
    2. Click on Manage auto fill and enter only name and save
    3. Edit the entry and open a  new tab. All changes made to the entry is gone and shows a blank entry
     4. Add credit card details. Edit the details and save changes
     5. Navigating a new tab clears all edited info added for credit card.

- Screenshot if needed:
ezgif com-video-to-gif 2

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

fix #3368

auditor: @bsclifton

### CODE REVIEW

File: test/components/autofillTest.js [hunk 1]
```diff
@@ -256,6 +256,174 @@ describe('Autofill', function () {
...
+        .tabByUrl(this.page1Url)
+        .refresh()
+        .waitForVisible('.autofillPage')
+        .getText('.creditCardName').should.eventually.be.equal(cardName)
+        .getText('.creditCardNumber').should.eventually.be.equal('***' + cardNumber.slice(-4))
+        .getText('.creditCardPExpirationDate').should.eventually.be.equal(
+          expMonth.toString() + '/' + expYear.toString())
+    })
+    it('Credit Card form test', function * () {
+      const page1Url = 'https://www.roboform.com/filling-test-all-fields'
```
Comment (bsclifton) [inline test/components/autofillTest.js]: Can this be stubbed / replaced with a fixture? (or maybe it is and I just didn't see it).  Would be ideal if we didn't have a dependency on their site :smile:

**Comment by bsclifton** [comment]
Looks great! Well done :smile: ++
