### PR TITLE
BAT integration (BAT Mercury)

### LINKED ISSUE #9740: Second key for Brave Payments is not displayed on the UI after recovering wallet
## Test plan

See below

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Second key for Brave Wallet is not displayed on the UI after recovery. Does not matter if you import keys or copy/past them into fields manually.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.11
rev	bc6d5b8
Muon	4.1.4

- Steps to reproduce:
    1. Enable Payments in Preferences.
    2. Click on the gear icon to open Advanced Settings.
    3. Select Recover your wallet.
    4. Import recovery keys from a previously saved file.
    5. You will get a successful message. Click OK.
    6. Click on gear icon again.
    7. Click on backup your wallet.
    8. Key 2 is not displayed.
    
- Actual result:
Key 2 is not displayed.

- Expected result:
Both keys should be displayed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Repeat steps above except manually copy/paste keys from file instead of importing. Key 2 is still not displayed on the UI.
    2. 
    3.

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #10945: Implement BAT into payments
**Describe the issue you encountered:**
Implement BAT into the existing ledger code.

Notes from @mrose17:
1. you no longer need the `ledger*` packages
2. instead, put this in `package.json`
```
"bat-balance": "^0.9.0",
"bat-client": "^0.9.0",
"bat-publisher": "^0.9.0",
"bignumber.js": "^4.0.4",
```
3. wherever you see `require('ledger-*')` in `app/ledger.js` use the `bat-*` package instead
4. get rid of anything relating to `geoip`, as this is no longer used
5. when you instantiate `ledgerClient = ...` include `version: 'v2'` in the `options` parameter. the easiest way to do this is to add that value to `clientOptions` near the top of the file
6. you can continue to call `ledigerClient.getWalletAddress`, which returns the BAT address, or you can call `ledgerClient.getWalletAddresses` which returns an array of all addresses
7. you will probably make the most changes in the `updateLedgerInfo` and `getPaymentInfo` routines because this is where you get the current wallet state
7a. here is an example of what `getPaymentInfo` gets when the callback to `client.getWalletProperties` invokes the callback:
 ```
{
  "paymentStamp": 0,
  "rates": {
    "USD": 0.19361672240887554
  },
  "addresses": {
    "BAT": "0x7c31560552170ce96c4a7b018e93cddc19dc61b6"
  },
  "altcurrency": "BAT",
  "probi": "32061750000000000000",
  "balance": "32.0618",
  "unconfirmed": "0.0000"
}
```
the  `balance` and `unconfirmed` fields are now denominated in BAT rather than BTC. instead of `satoshis`, the `probi` field shows the BAT "wei", so if you want the exact number of BAT, you'll need to put that into a BigNum and then divide by 10^18. you can convert to USD by doing balance * rates.USD
you may notice that `buyURL`and `buyURLExpires` have gone away.
when we have a buy widget for BAT, then `buyURL` will come back.
7b. here is an example of what `updateLedgerInfo` sees in `ledgerInfo._internal.paymentInfo`:
 ```
{
  "balance": "32.0618",
  "altcurrency": "BAT",
  "probi": "32061750000000000000",
  "address": :0x7c31560552170ce96c4a7b018e93cddc19dc61b6",
  "addresses": {
    "BAT": "0x7c31560552170ce96c4a7b018e93cddc19dc61b6"
  },
  "amount": 5,
  "currency": "USD",
  "BAT": "25.7854"
}
```
again, no `btc` and `satoshis` fields, but `BAT` and `probi` fields.
8. finally, there is one bit of information hiding that i missed in the `ledger-client` package: in `getStateInfo` instead of doing
`ledgerInfo.passphrase = state.properties.wallet.keychains.passphrase`
do
`ledgerInfo.passphrase = ledgerClient.prototype.getWalletPassphrase(state)`

### LINKED ISSUE #11193: implement new add-funds wizard UI to support BAT
The new UI is specified in the attached PDF.

[bat_ledger_integration_spec2.pdf](https://github.com/brave/browser-laptop/files/1339622/bat_ledger_integration_spec2.pdf)

### LINKED ISSUE #11251: Error in undefined: "getWalletProperties" on master
### Description
Error in undefined: "getWalletProperties" on master

### Steps to Reproduce

  1. Build from master 
  2. Enable payments, visit couple of verified publishers site
  3. Console shows error

**Actual result:**

image

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | de5f381
Muon | 4.4.25

**Reproducible on current live release:**

### Additional Information
cc: @NejcZdovc

### LINKED ISSUE #11264: Add 2 decimal places (rounded for display) to BAT wallet balance
image

The actual wallet balance may have 4 decimals but the display should be rounded to 2 decimals.

The monthly budget remains fixed.

CC @mrose17 @zentagonist

### LINKED ISSUE #11278: ledger table data is not cleared properly
### Description
Ledger table data is not cleared properly when clearing Browser History with Payments Disabled.

### Steps to Reproduce

  1. Have a ledger with some entries (some included, some not included).
  2. Note views/amt of time spent for a couple of sites.
  3. Disable payments.
  4. Go to about:preferences#security, click on Clear Browsing Data Now, enable toggle for 
  5. Browser History, click Clear
  6. Enable payments.
  7. Table is blank as expected.
  8. Visit one of the sites you noted that was marked as include. 
  9. Note as soon as the page loads (prior to default value of 8s) your URL heart icon is yellow indicating it is in the table.
  10. Go back to Payments (you might have to refresh due to another issue)
  11. Your site is listed in the table with similar visit#/time spent as prior to clearing data. I was expecting the counters to start over.
  12. Repeat with another site that had been in the table prior to clearing Browser History. You will see a similar result.

**Actual result:**
ledgernotrestartingat0

**Expected result:**
Since table data had been cleared, I was expecting the number of visits and time spent counters to reset. The amount of time of the gif above is less than 1.5 minutes, so it's not possible that I spent 4+ minutes on brianbondy.com and 2+ minutes on thepioneerwoman.com.

**Reproduces how often:** [What percentage of the time does it reproduce?] 100% for me

### Brave Version

**about:brave info:**
Brave | 0.19.28
rev | 08781a5
Muon | 4.4.25

**Reproducible on current live release:**
no

### Additional Information

Reproduced by @srirambv on Windows
cc @kjozwiak 

Ledger table data prior to clearing browsing history:
screen shot 2017-10-04 at 2 27 30 pm

Ledger table data after clearing browsing history and visiting two of the above sites. They're readded and retain some of the previous data:
screen shot 2017-10-04 at 2 43 10 pm

### LINKED ISSUE #11285: Missing text in BAT add funds modal
### Steps to Reproduce

  1. Build from https://github.com/brave/browser-laptop/tree/bat-integration
  2. Enable payments
  3. Click add funds
  4. Text missing as to what to do

**Actual result:**

image

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### LINKED ISSUE #11289: Copied text overlaps on the info message
### Description
Copied text overlaps on the info message

### Steps to Reproduce

  1. Build on the `bat-integration` branch
  2. Enable payments
  3. Click `Add funds`
  4. Click any currencies button
  5. Click the clipboard icon to copy the wallet address,

**Actual result:**

copied text overlaps on the info text

copy**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | 2ca8815
Muon | 4.4.25

**Reproducible on current live release:**

### LINKED ISSUE #11292: Brave wallet backup key 2 overflows
### Description

Brave wallet backup key 2 has a wrong value

### Steps to Reproduce

  1. Open about:preferences#payments
  2. Open advanced settings
  3. Click `Backup your wallet`

**Actual result:**

screenshot 2017-10-05 22 05 50

**Expected result:**

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

2ca88153090ed241b97e08dffb9b37d2e1067250

**Reproducible on current live release:**

### LINKED ISSUE #11293: Recovery keys fail both manual/import
### Description
Recovery keys fail both manual/import

### Steps to Reproduce

  1. Build from 2ca8815
  2. Enable payments and save recovery key
  3. Clear profile and launch new one
  4. Enable payments and import recovery keys from step 2
  5. Recovery fails

**Actual result:**

image

**Expected result:**
Should import successfully
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.21.0
-- | --
V8 | 6.1.534.41
rev | 2ca8815
Muon | 4.4.25

**Reproducible on current live release:**

### LINKED ISSUE #11308: Transition the wallet from BTC to BAT
### Description
For the BAT Mercury launch, we'll want to make a one time call from the client to initiate the transfer of BTC to BAT.

```
// create a new client:
newClient = ledgerClient(null, 
  underscore.extend({roundtrip: roundtrip}, clientOptions), null)

// do not persist newClient's state

// 2. on the existing client, call:
client.transition(newClient.properties.wallet.paymentId, (err) => {
  if (err) complain
  client = newClient
  // persist client's state, overwriting the old state      
})
```

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #9740 - Second key for Brave Payments is not displayed on the UI after recovering wallet
Resolves #10945 - Implement BAT into payments
Resolves #11193 - Implement new add-funds wizard UI to support BAT
Resolves #11251 - Error in undefined: "getWalletProperties" on master
Resolves #11264 - Add 2 decimal places (rounded for display) to BAT wallet balance
Resolves #11278 - Ledger table data is not cleared properly
Resolves #11285 - Missing text in BAT add funds modal
Resolves #11289 - Copied text overlaps on the info message
Resolves #11292 - Brave wallet backup key 2 overflows
Resolves #11293 - Recovery keys fail both manual/import
Resolves #11308 - Transition the wallet from BTC to BAT

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js [hunk 1]
```diff
@@ -0,0 +1,372 @@
...
+              styles.addFundsDialog__main__text,
+              styles.addFundsDialog__main__text_bold
+            )}
+          />
+          <BrowserButton
+            groupedItem
+            secondaryColor
+            custom={[
+              styles.currencyIcon,
+              styles.ethIcon
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js]: how about `styles.icon_currency` and `styles.icon_currency_eth`?

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js [hunk 2]
```diff
@@ -0,0 +1,372 @@
...
+            ]}
+            onClick={this.something}
+          />
+          <BrowserButton
+            groupedItem
+            secondaryColor
+            custom={[
+              styles.currencyIcon,
+              styles.btcIcon
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js]: how about `styles.icon_currency_btc` like above?

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js [hunk 3]
```diff
@@ -0,0 +1,372 @@
...
+      />
+    )
+  }
+
+  get addFundsWizardAddress () {
+    return (
+      <div>
+        <header data-l10n-id='addFundsWizardAddressHeader' />
+        <div className={css(styles.addFundsWizardAddress)}>
+          <main className={css(styles.addFundsWizardAddress__address)}>
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js]: I'd pick `styles.wizard` and `styles.wizard__address` to shrink the length (because it should be already clear what kind of wizard it is, from the name `addFundsWizardAddress`).

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+const BrowserButton = require('../../../common/browserButton')
+
+// Styles
+const {StyleSheet, css} = require('aphrodite')
+const upholdLogo = require('../../../../../extensions/brave/img/ledger/uphold-logo.png')
+
+class AddFundsDialogFooter extends ImmutableComponent {
+  render () {
+    return (
+      <section className={css(styles.addFundsFooter)} data-test-id='AddFundsDialogFooter'>
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js]: Ditto. I would pick `styles.footer` to shrink the classname.

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+        <div className={css(styles.addFundsFooter__start)}>
+          <img src={upholdLogo}
+            className={css(styles.addFundsFooter__init__uphold_logo)}
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js]: As long as there is not another common element, why wouldn't you change this into `styles.addFundsFooter__start__uphold_logo`?

File: app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+          />
+          <div className={css(styles.addFundsFooter__init__uphold_text)}>
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/addFundsDialogFooter.js]: Ditto. We could replace it with `styles.addFundsFooter__start__uphold_text`

File: less/about/preferences.less [hunk 7]
```diff
@@ -1,10 +1,14 @@
 @import "./common.less";
 
-strong, div, span, li, em, p, a {
+div, span, li, em, p, a {
   font-weight: 400;
   -webkit-font-smoothing: antialiased;
 }
 
+strong {
+  font-weight: 600
```
Comment (luixxiul) [inline less/about/preferences.less]: wouldn't this change cause a visual regression?

File: app/renderer/components/common/modalOverlay.js [hunk 8]
```diff
@@ -71,6 +72,18 @@ class ModalOverlay extends ImmutableComponent {
           [customTitleClassesStr]: true
         })} data-l10n-id={this.props.title}
         /> : null)
+      subTitle = (this.props.subTitle
+        ? <aside className={css(styles.dialog__header__subTitle)}>
+          <div className={cx({
+            [css(styles.dialog__header__subTitle_text)]: true,
+            [customTitleClassesStr]: true
```
Comment (luixxiul) [inline app/renderer/components/common/modalOverlay.js]: (TODO: we would remove `customTitleClassesStr` etc. later to avoid `cx` which sometimes prevents properties from cascading properly)

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/jobs/282646416#L1292

````
    ERROR in ./app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js
    Module not found: Error: Can't resolve '../../../../../extensions/brave/img/ledger/fakeQRCode.png' in '/home/travis/build/brave/browser-laptop/app/renderer/components/preferences/payment/addFundsDialog'
     @ ./app/renderer/components/preferences/payment/addFundsDialog/addFundsDialog.js 16:15-83
     @ ./app/renderer/components/preferences/paymentsTab.js
     @ ./js/about/preferences.js
     @ ./js/about/entry.js
     @ multi ./js/about/entry.js
````

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js [hunk 9]
```diff
@@ -0,0 +1,201 @@
...
+  },
+
+  addFundsWizardAddress__main: {
+    display: 'flex',
+    flex: 1,
+    justifyContent: 'space-between',
+    margin: '15px 0'
+  },
+
+  addFundsWizardAddress__main__text_bold: {
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js]: redundant

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js [hunk 10]
```diff
@@ -0,0 +1,201 @@
...
+          styles.addFundsWizardAddress,
+          this.currency === 'eth' && styles.addFundsWizardAddress_eth,
+          this.currency === 'btc' && styles.addFundsWizardAddress_btc,
+          this.currency === 'ltc' && styles.addFundsWizardAddress_ltc,
+          this.currency === 'bat' && styles.addFundsWizardAddress_bat
+      )}>
+        <header data-l10n-id='addFundsWizardAddressHeader' />
+        <div className={css(styles.addFundsWizardAddress__main)}>
+          <main className={css(styles.addFundsWizardAddress__inputBox)}>
+            <GroupedFormTextbox type='text'
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js]: Is this not be applied here? https://github.com/brave/browser-laptop/pull/7164#discussion_r100586892

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js [hunk 11]
```diff
@@ -0,0 +1,202 @@
...
+          <header data-l10n-id='addFundsWizardMainHeader' />
+          <p data-l10n-id='addFundsWizardMainOptions'
+            className={css(
+              styles.addFundsWizardMain__text,
+              styles.addFundsWizardMain__text_bold
+            )}
+          />
+          <BrowserButton groupedItem secondaryColor
+            onClick={this.onClickETH}
+            custom={[styles.addFundsWizardMain__currencyIcon, styles.ethIcon]}
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js]: `styles.ethIcon` -> `styles.addFundsWizardMain__currency__icon_eth`

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+          />
+          <BrowserButton groupedItem secondaryColor
+            onClick={this.onClickBTC}
+            custom={[styles.addFundsWizardMain__currencyIcon, styles.btcIcon]}
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js]: `styles.btcIcon` -> `styles.addFundsWizardMain__currency__icon_btc`

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+          />
+          <BrowserButton groupedItem secondaryColor
+            onClick={this.onClickLTC}
+            custom={[styles.addFundsWizardMain__currencyIcon, styles.ltcIcon]}
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js]: `styles.ltcIcon` -> `styles.addFundsWizardMain__currencyIcon_ltc`

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js [hunk 14]
```diff
@@ -0,0 +1,202 @@
...
+            />
+          <BrowserButton groupedItem secondaryColor
+            onClick={this.onClickBAT}
+            custom={[styles.addFundsWizardMain__currencyIcon, styles.batIcon]}
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardMain.js]: `styles.batIcon` -> `styles.addFundsWizardMain__currencyIcon_bat`

File: package.json [hunk 15]
```diff
@@ -87,6 +87,10 @@
     "ad-block": "^3.0.2",
     "aphrodite": "1.1.0",
     "async": "^2.0.1",
+    "bat-balance": "^0.9.6",
+    "bat-client": "^0.9.0",
+    "bat-publisher": "^0.9.0",
+    "bignumber.js": "^4.0.4",
```
Comment (diracdeltas) [inline package.json]: [minor] there's a new version of bignumber.js out now https://github.com/MikeMcl/bignumber.js/

File: js/constants/config.js [hunk 16]
```diff
@@ -86,7 +86,6 @@ module.exports = {
   pinterestExtensionPublicKey: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDB95q2hyt49ZDuVnYI91XaZhqQkbXu0X3fzoNxPxhFbfqGKwtts90LJ7lD5DCIfnBg8WGFhp3eW4GxOglAKrnksmJoyAD5PnSAufx8fD3trZvo/ZAqFx1x5Xm3Rm34EgvVXdralgHSYiqcEU/FX3kYnLLhr2TS4lcrsn1KZd/lcQIDAQAB',
   metamaskExtensionId: 'nkbihfbeogaeaoehlefnkodbefgpgknn',
   metamaskPublicKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlcgI4VVL4JUvo6hlSgeCZp9mGltZrzFvc2Asqzb1dDGO9baoYOe+QRoh27/YyVXugxni480Q/R147INhBOyQZVMhZOD5pFMVutia9MHMaZhgRXzrK3BHtNSkKLL1c5mhutQNwiLqLtFkMSGvka91LoMEC8WTI0wi4tACnJ5FyFZQYzvtqy5sXo3VS3gzfOBluLKi7BxYcaUJjNrhOIxl1xL2qgK5lDrDOLKcbaurDiwqofVtAFOL5sM3uJ6D8nOO9tG+T7hoobRFN+nxk43PHgCv4poicOv+NMZQEk3da1m/xfuzXV88NcE/YRbRLwAS82m3gsJZKc6mLqm4wZHzBwIDAQAB',
-  coinbaseOrigin: 'https://buy.coinbase.com',
```
Comment (diracdeltas) [inline js/constants/config.js]: please remove buy.coinbase.com from the CSP in app/extensions.js

File: less/about/preferences.less (hunk 7 above)
Comment (cezaraugusto) [reply less/about/preferences.less]: I don't think so, only other `<strong>` tag we have is in URL bar, which is not affected by this

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js (hunk 10 above)
Comment (cezaraugusto) [reply app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js]: I don't think so. works normally in this case

File: js/constants/config.js (hunk 16 above)
Comment (NejcZdovc) [reply js/constants/config.js]: done

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js (hunk 10 above)
Comment (luixxiul) [reply app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsWizardAddress.js]: thanks for checking :-)

File: less/about/preferences.less (hunk 7 above)
Comment (luixxiul) [reply less/about/preferences.less]: I see. the file will eventually be removed so not a great issue anyway.

**Comment by diracdeltas** [comment]
Not sure if this has been logged already, but on the welcome screen before payments is enabled:
screen shot 2017-10-04 at 10 23 46 pm

does the 'Our Partners' text need to be changed? also the FAQ is pointing to https://brave.com/faq-payments/#brave-payments which is out of date

**Comment by diracdeltas** [comment]
on the second screen:
screen shot 2017-10-04 at 10 26 55 pm

1. clicking the settings button doesn't do anything, but it appears enabled instead of greyed-out
2. clicking the 'create wallet' button also doesn't do anything - console shows `ledger client error(1): "Error: HTTP response 404 for GET /v2/wallet/c2f6c9c9-c6da-4071-8ed7-fa9496923469?refresh=true&amount=5&currency=USD"`

File: app/browser/api/ledger.js [hunk 17]
```diff
@@ -1482,9 +1464,10 @@ const getStateInfo = (state, parsedData) => {
     return state
   }
 
+  if (!ledgerClient) ledgerClient = require('bat-client')
   const newInfo = {
     paymentId: parsedData.properties.wallet.paymentId,
-    passphrase: parsedData.properties.wallet.keychains.passphrase,
+    passphrase: ledgerClient.prototype.getWalletPassphrase(parsedData),
```
Comment (diracdeltas) [inline app/browser/api/ledger.js]: [minor] - it seems weird that this code accesses methods on `ledgerClient.prototype` instead of methods on an instance of the Client

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: cc @mrose17

**Comment by NejcZdovc** [comment]
@diracdeltas our partners will change and we have PR already up for it #11244

**Comment by luixxiul** [comment]
@diracdeltas 

> does the 'Our Partners' text need to be changed?

It'll be addressed with #11244

**Comment by bsclifton** [comment]
On the preferences screen, I was able to cause a JavaScript error in the about page which caused the page to freeze (meaning you can't switch tabs).

I launched about:preferences via the kabob menu and opened the payment tab.  Then I switched between that tab and sync one or two times.  Then the UI stopped responding.  When opening the content dev tools, I see the following:
```
(BLESSED_EXTENSION context for mnojpmjdmbbfmejpflffifhffcmidifd) http://localhost:8080/gen/aboutPages.entry.js:39101: Uncaught TypeError: balance.toFixed is not a function{TypeError: balance.toFixed is not a function
    at formatCurrentBalance (http://localhost:8080/gen/aboutPages.entry.js:39101:21)
    at EnabledContent.fundsAmount (http://localhost:8080/gen/aboutPages.entry.js:101301:14)
    at EnabledContent.render (http://localhost:8080/gen/aboutPages.entry.js:101417:39)
    at http://localhost:8080/gen/aboutPages.entry.js:76058:21
    at measureLifeCyclePerf (http://localhost:8080/gen/aboutPages.entry.js:75338:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8080/gen/aboutPages.entry.js:76057:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:8080/gen/aboutPages.entry.js:76084:32)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8080/gen/aboutPages.entry.js:75624:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8080/gen/aboutPages.entry.js:75520:21)
    at Object.mountComponent (http://localhost:8080/gen/aboutPages.entry.js:24948:35)}
```

File: app/browser/reducers/ledgerReducer.js [hunk 18]
```diff
@@ -266,6 +262,15 @@ const ledgerReducer = (state, action, immutableAction) => {
         ledgerApi.addFoundClosed(state)
         break
       }
+    case appConstants.APP_ON_CHANGE_ADD_FUNDS_DIALOG_STEP:
+      {
+        // CC Nejc move this to a helper method as needed
```
Comment (NejcZdovc) [inline app/browser/reducers/ledgerReducer.js]: don't forget to move this

File: app/browser/api/ledger.js [hunk 19]
```diff
@@ -91,7 +90,8 @@ const clientOptions = {
   rulesTestP: process.env.LEDGER_RULES_TESTING,
   verboseP: process.env.LEDGER_VERBOSE,
   server: process.env.LEDGER_SERVER_URL,
-  createWorker: electron.app.createWorker
+  createWorker: electron.app.createWorker,
+  version: 'v2'
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: is this what triggers the client library to use BAT?

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: yes

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: and we use `bat-*` libraries instead of `ledger-*`. Check in `package.json`

File: app/browser/api/ledger.js [hunk 20]
```diff
@@ -1450,8 +1458,12 @@ const roundtrip = (params, options, callback) => {
     underscore.omit(params, ['headers', 'payload', 'timeout']))
 
 // TBD: let the user configure this via preferences [MTR]
-  if (parts.hostname === 'ledger.brave.com' && params.useProxy) {
-    parts.hostname = 'ledger-proxy.privateinternetaccess.com'
+  if (params.useProxy) {
+    if (parts.hostname === 'ledger.brave.com') {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: can we pull these up into a constant? could be a nice opportunity to name them in a more readable way.  For example, why are there two possible values? (ledger.brave.com and ledger.mercury.basicattentiontoken.org) The name of the variable may represent the usecase

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: @mrose17 will not more about it, because he added them

File: app/browser/reducers/ledgerReducer.js [hunk 21]
```diff
@@ -188,6 +188,7 @@ const ledgerReducer = (state, action, immutableAction) => {
       }
     case appConstants.APP_NAVIGATOR_HANDLER_REGISTERED:
       {
+        // TODO will this be changed when switching to BAT
         const hasBitcoinHandler = (action.get('protocol') === 'bitcoin')
```
Comment (bsclifton) [inline app/browser/reducers/ledgerReducer.js]: What action do we need to take here? does BAT have a handler? maybe we should remove this and create a new issue to address

Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: This is TODO for me, because I am not sure that we need bitcoin handler anymore. We don't use it anymore. @mrose17 can we remove this?

File: app/common/lib/ledgerExportUtil.js [hunk 22]
```diff
@@ -234,13 +234,13 @@ module.exports.getTransactionCSVRows = (transactions, viewingIds, addTotalRow, s
 
   const currency = (publishers.length ? txContribData[publishers[0]].contribution.currency : 'USD')
 
-  const headerRow = ['Publisher', 'Votes', 'Fraction', 'BTC', currency].join(',')
+  const headerRow = ['Publisher', 'Votes', 'Fraction', 'BAT', currency].join(',')
```
Comment (bsclifton) [inline app/common/lib/ledgerExportUtil.js]: looking at this, this brings up an interesting question... what do previous transactions look like?

ex: we switch over to BAT. Can I still view the reports for the Bitcoin payments I've made? Do we store (in the state) which digital currency was used to settle each transaction?

File: app/extensions/brave/locales/en-US/preferences.properties [hunk 23]
```diff
@@ -3,7 +3,30 @@ accountBalance=account balance
...
+addFundsWizardMainHeader=Brave makes it easy to transfer funds from your existing crypto-currency wallet to your Brave BAT Wallet.
+addFundsWizardMainOptions=Select one of the currencies below to begin a new transfer.
+addFundsWizardMainReminder=Reminder: The Brave Wallet is unidirectional and BAT flows to publisher sites. For more information about Brave Payments, please visit
+theFAQ=the FAQ.
+addFundsWizardAddressHeader=Go to your external {{currencyName}} account and send a minimum of 5.00 USD in {{currency}} to your Brave wallet address below:
+addFundsWizardAddressInputNote=Note: we recommend starting with enough {{currency}} to cover your first contribution of {{funds}}.
+addFundsWizardAddressFooter=Your {{currency}} will be converted to BAT and appear in your Brave wallet in minutes.
+addFundsWizardAddressFooterBAT=Your additional BAT will appear in your Brave wallet after a few minutes.
+or=or
+qrCodeVersion=QR Code Version
```
Comment (bsclifton) [inline app/extensions/brave/locales/en-US/preferences.properties]: can we sort this (alphabetically?) 😄

File: app/common/lib/ledgerExportUtil.js (hunk 22 above)
Comment (NejcZdovc) [reply app/common/lib/ledgerExportUtil.js]: nice catch I forgot to implement this part, which @mrose17 told me about it. @bsclifton can you please crate issue for it, so that I don't forget :smiley: (add release-blocking to it)

File: app/common/lib/ledgerExportUtil.js [hunk 24]
```diff
@@ -249,10 +249,10 @@ module.exports.getTransactionCSVRows = (transactions, viewingIds, addTotalRow, s
   rows = rows.concat(publishers.map(function (pub) {
     var pubRow = txContribData[pub]
 
-    let rowBTC = pubRow.contribution.satoshis / Math.pow(10, 10)
+    let rowBAT = pubRow.contribution.satoshis / Math.pow(10, 10)
```
Comment (bsclifton) [inline app/common/lib/ledgerExportUtil.js]: should this be satoshis? or probi?

Comment (NejcZdovc) [reply app/common/lib/ledgerExportUtil.js]: we should have probi everywhere

**Comment by NejcZdovc** [comment]
Current blockers:

- [ ] backup is not working, more info in #11292
- [ ] add transition logic BTC->BAT (we need to trigger one function in library, we can use logic from @bsclifton PR for notification)
- [ ] transactions are not working for 50BAT

**Comment by luixxiul** [comment]
https://travis-ci.org/brave/browser-laptop/jobs/283688270#L3424

````
4) Regular payment panel tests ledger history is CLEARED if payment is disabled before the close and clear history is true:
     Error: element ("[data-test2-id="addFunds"]") still not enabled after 10000ms
      at elements("[data-test2-id="addFunds"]") - isEnabled.js:18:17
      at isEnabled("[data-test2-id="addFunds"]") - waitForEnabled.js:73:22

  5) Regular payment panel tests auto include site is added automatically:
     Error: Promise was rejected with the following reason: timeout
      at execute(<Function>) - brave.js:487:19

  6) Ledger table 2 publishers pin publisher:
     Error: Promise was rejected with the following reason: Cannot read property 'get' of undefined
      at elements("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - getText.js:18:17
      at getText("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - ledgerTableTest.js:104:23

  7) Ledger table 2 publishers pin excluded publisher:
     Error: element ("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") still not visible after 10000ms
      at elements("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - isVisible.js:54:17
      at isVisible("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - waitForVisible.js:73:22

  8) Ledger table 4 publishers pin 3 publishers and check unpinned value:
     Promise was rejected with the following reason: timeout
  Error

  9) Ledger table 4 publishers "before each" hook for "pin 3 publishers over 100 value and check unpinned value":
     Error: timeout of 30000ms exceeded. Ensure the done() callback is being called in this test.
````

File: app/common/lib/ledgerExportUtil.js (hunk 22 above)
Comment (NejcZdovc) [reply app/common/lib/ledgerExportUtil.js]: will be fixed with #11296

File: app/common/lib/ledgerExportUtil.js (hunk 24 above)
Comment (NejcZdovc) [reply app/common/lib/ledgerExportUtil.js]: fixed in #11296

File: app/browser/api/ledger.js (hunk 17 above)
Comment (diracdeltas) [reply app/browser/api/ledger.js]: as of https://github.com/brave-intl/bat-client/pull/13, i think you will need to construct an instance of ledgerClient in order for some stuff to work

File: app/browser/api/ledger.js [hunk 25]
```diff
@@ -174,10 +174,11 @@ const notifications = {
       // - if payments are enabled
       // - user has a positive balance
       // - this is an existing profile (new profiles will have firstRunTimestamp matching batMercuryTimestamp)
+      // - wallet has been transitioned
       // - notification has not already been shown yet
       // (see https://github.com/brave/browser-laptop/issues/11021)
       const hasBeenNotified = state.getIn(['migrations', 'batMercuryTimestamp']) !== state.getIn(['migrations', 'btcToBatNotifiedTimestamp'])
-      if (!isNewInstall && !hasBeenNotified) {
+      if (!isNewInstall && hasUpgradedWallet && !hasBeenNotified) {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: If the wallet transition fails, don't show the alert 👍

File: app/browser/reducers/ledgerReducer.js (hunk 21 above)
Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: just received confirmation from @mrose17 that we still need to keep it

Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: removing TODO tag

File: app/extensions/brave/locales/en-US/preferences.properties [hunk 26]
```diff
@@ -156,15 +164,15 @@ ja-JP=Japanese (Japan)
 ko-KR=Korean
 lastContribution=Last contribution:
 lastPass=LastPass&reg;
-ledgerBackupContent=Below, you will find the anonymized recovery keys that are required if you ever lose access to this computer.
+ledgerBackupContent=Below, you will find the anonymized recovery key that is required if you ever lose access to this computer.
```
Comment (diracdeltas) [inline app/extensions/brave/locales/en-US/preferences.properties]: This needs some text to indicate that the recovery key should not be shared or posted publicly (like what we do for the sync passphrase)

Comment (NejcZdovc) [reply app/extensions/brave/locales/en-US/preferences.properties]: @diracdeltas any suggestions on the copy?

Comment (diracdeltas) [reply app/extensions/brave/locales/en-US/preferences.properties]: bold font: "Make sure you keep this key private, or else your wallet will be compromised." ?

**Comment by diracdeltas** [comment]
i suggest using a different font style for the recovery key phrase or putting it in a bounding box so it's obvious that the recovery key does not include the words "Recovery Key" above it.

what it looks like now:
screen shot 2017-10-06 at 7 51 41 pm

this is what sync does (`pre` element in a different color):
screen shot 2017-10-06 at 7 53 46 pm

File: app/extensions/brave/locales/en-US/preferences.properties (hunk 26 above)
Comment (NejcZdovc) [reply app/extensions/brave/locales/en-US/preferences.properties]: @diracdeltas we have text in backup file as well `Note: This key is not stored on Brave servers. This key is your only method of recovering your Brave wallet. Save this key in a safe place, separate from your Brave browser.` should we modify it?

Comment (NejcZdovc) [reply app/extensions/brave/locales/en-US/preferences.properties]: will add the same text that we added in the dialog

Comment (NejcZdovc) [reply app/extensions/brave/locales/en-US/preferences.properties]: done

**Comment by NejcZdovc** [comment]
@diracdeltas implemented your suggestion, new backup screen looks like this

image

File: app/extensions/brave/locales/en-US/preferences.properties (hunk 26 above)
Comment (diracdeltas) [reply app/extensions/brave/locales/en-US/preferences.properties]: lgtm!

**Comment by diracdeltas** [comment]
uncaught exception when Brave starts without internet connectivity:

```
An uncaught exception occurred in the main process Uncaught Exception:            Error: getaddrinfo ENOTFOUND www.bitgo.com www.bitgo.com:443                          at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)                 From previous event:
    at Request.superagent.Request.end (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:47:10)
    at Request.req.end (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:341:37)                                                                     at Request.req.then (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:387:33)                                                                    at Request.superagent.Request.result (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:66:15)
    at BitGo.fetchConstants (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:1487:4)                                                                at new BitGo (/Users/yan/repos/tmp/browser-laptop/node_modules/bitgo/src/bitgo.js:416:8)
    at /Users/yan/repos/tmp/browser-laptop/node_modules/bat-client/index.js:10:15
    at Object.<anonymous> (/Users/yan/repos/tmp/browser-laptop/node_modules/bat-client/index.js:1305:2)
    at Module._compile (module.js:571:32)                                             at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)                                               at Function.Module._load (module.js:439:3)                                        at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getStateInfo (/Users/yan/repos/tmp/browser-laptop/app/browser/api/ledger.js:1538:20)
    at Object.onInitRead (/Users/yan/repos/tmp/browser-laptop/app/browser/api/ledger.js:1950:11)
    at ledgerReducer (/Users/yan/repos/tmp/browser-laptop/app/browser/reducers/ledgerReducer.js:312:27)                                                                 at handleAppAction (/Users/yan/repos/tmp/browser-laptop/js/stores/appStore.js:226:16)
```

**Comment by diracdeltas** [comment]
conversion is showing BAT / BAT instead of BAT / $LOCAL_CURRENCY
screen shot 2017-10-06 at 10 04 14 pm
