### PR TITLE
reset reconciliation time when publisher window is closed

### LINKED ISSUE #4058: Brave payments wrong contribution date
**Did you search for similar issues before submitting this one?**
No

**Describe the issue you encountered:**
I have enabled Brave payments long ago and disabled it for a while. After re-enabling it again the Next contribution date was in the past.

**Expected behavior:**
The next contribution date should never be in the past.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All
- Brave Version:
0.12.1

- Steps to reproduce:
    1.Enable Brave payments
    2. Disable Brave paymetns
    3. Wait several days and re-enable

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by mrose17**
test plan:
1. start with a browser that has ledger payments enabled.
2. quit the browser
3. _carefully_ edit `ledger-state.json` to change the line start starts as ` "reconcileStamp": 14...` to change the `4` to a `3`
4, start the browser
5. verify that the time to reconcile now occurs in the future!

auditor: @ayumi 

fixes #4058

### CODE REVIEW

File: app/ledger.js [hunk 1]
```diff
@@ -458,17 +458,19 @@ var initialize = (paymentsEnabled, reason) => {
           // Scenario: User enables Payments, disables it, waits 30+ days, then
           // enables it again -> reconcileStamp is in the past.
           // In this case reset reconcileStamp to the future.
-          if (reason === 'changeSettingPaymentsEnabled') {
```
Comment (ayumi) [inline app/ledger.js]: as a result of this PR we can remove `changeSettingPaymentsEnabled` at ln 134 and the `reason` arg in this function `initialize(paymentsEnabled,reason)` (it was added to fix this)

Comment (mrose17) [inline app/ledger.js]: true. it is used only in one place. remove it?

**Comment by ayumi** [comment]
lgtm :gift:
