### PR TITLE
Re-block running insecure content

### LINKED ISSUE #3770: Mixed-content lock control should be able to re-lock and reload the page like Firefox.
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing https://github.com/brave/browser-laptop/issues/3443 it was discovered that re-locking the page exhibits counterintuitive behavior. It merely displays the unlocked status rather than re-locking.

**Expected behavior:**
If a user clicks on a closed lock, it should open. If a user clicks on an open lock, it should close. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version:
0.12.0

- Steps to reproduce:
    1. Visit https://forgetfulbc.blogspot.com/2016/08/lastweek-t3.html
    2. Click on the blue lock in the URL bar
    3. Attempt to click on it a second time

- Screenshot if needed:
Chrome:
mixed_content_chrome

Firefox:
mixed_content_firefox

Brave:
mixed_content_brave

- Any related issues:
https://github.com/brave/browser-laptop/issues/3443

### LINKED ISSUE #3795: site settings from private mode should not apply in regular browsing mode
- Steps to reproduce:
    1. open https://mixed-script.badssl.com/ in a private tab
    2. click the lock icon and allow mixed content
    3. open the same page in a regular tab and observe mixed content is still allowed

- Expected behavior:
site-specific settings should never leak from private browsing to regular browsing because this opens up ways for a malicious page to figure out what sites have been visited in private browsing mode. leaks in the other direction (from regular into private) are less serious.

- Any related issues:
https://github.com/brave/browser-laptop/issues/1824

cc @bridiver

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

---
1. Add an option to re-block running insecure content
2. Limit the effect of running insecure content in regular/private frame scope

fix #3770, #3793 

partially fix #3795 (only for runInsecureContent)

Auditors: @diracdeltas

Test Plan:
For re-block option:
1. Go to `https://mixed-script.badssl.com/`
2. Click urlIcon and click `Load Unsafe Scripts`
3. Background should be red
4. Click urlIcon and click `Stop Loading Unsafe Scripts`
5. Background should be grey

For regular frame:
1. Go to https://mixed-script.badssl.com
2. Click urlIcon and click Load Unsafe Scripts
3. Background should be red
4. Go to https://mixed-script.badssl.com by regular new tab
5. Background should be grey
6. Go to https://mixed-script.badssl.com by private new tab
7. Background should be grey
8. Go to https://mixed-script.badssl.com by session new tab
9. Background should be grey

~~For private frame:
1. Go to https://mixed-script.badssl.com by private tab
2. Click urlIcon and click Load Unsafe Scripts
3. Background should be red
4. Go to https://mixed-script.badssl.com by regular new tab
5. Background should be grey
6. Go to https://mixed-script.badssl.com by private new tab
7. Background should be grey
8. Go to https://mixed-script.badssl.com by session new tab
9. Background should be grey~~

### CODE REVIEW

File: app/extensions/brave/locales/en-US/app.properties [hunk 1]
```diff
@@ -190,6 +190,9 @@ phone=Phone
 email=Email
 editAddress=Edit Address
 editCreditCard=Edit Credit Card
-denyRunInsecureContent=Stay Secure
+dismissAllowRunInsecureContent=Stay Secure
 allowRunInsecureContent=Load Unsafe Scripts
+dismissDenyRunInsecureContent=Stay Unsecure
```
Comment (diracdeltas) [inline app/extensions/brave/locales/en-US/app.properties]: s/Unsecure/Insecure

File: app/extensions/brave/locales/en-US/app.properties [hunk 2]
```diff
@@ -190,6 +190,9 @@ phone=Phone
...
+denyRunInsecureContent=Stop Loading Unsafe Scripts
 runInsecureContentWarning=This page is trying to load scripts from insecure sources. If you allow this content to run it will not be encrypted and it may transmit unencrypted data to other sites.
+denyRunInsecureContentWarning=This page is currently loading scripts from insecure sources. If you disallow this content to run it, transmitting data will be more safe with encrpyted connections.
```
Comment (diracdeltas) [inline app/extensions/brave/locales/en-US/app.properties]: second sentence is unnecessary

File: app/extensions/brave/locales/en-US/app.properties (hunk 1 above)
Comment (darkdh) [inline app/extensions/brave/locales/en-US/app.properties]: Updated in 138692c. Thanks

File: app/extensions/brave/locales/en-US/app.properties (hunk 2 above)
Comment (darkdh) [inline app/extensions/brave/locales/en-US/app.properties]: Updated in 138692c. Thanks

File: js/components/siteInfo.js [hunk 3]
```diff
@@ -16,18 +16,28 @@ class SiteInfo extends ImmutableComponent {
...
   }
   onAllowRunInsecureContent () {
-    appActions.changeSiteSetting(siteUtil.getOrigin(this.isBlockedRunInsecureContent), 'runInsecureContent', true)
+    appActions.changeSiteSetting(siteUtil.getOrigin(this.isBlockedRunInsecureContent),
+      'runInsecureContent', true, this.isPrivate)
     ipc.emit(messages.SHORTCUT_ACTIVE_FRAME_LOAD_URL, {}, this.isBlockedRunInsecureContent)
     this.props.onHide()
   }
+  onDenyRunInsecureContent () {
+    appActions.removeSiteSetting(siteUtil.getOrigin(this.runInsecureContent), 'runInsecureContent')
```
Comment (diracdeltas) [inline js/components/siteInfo.js]: should this have `this.isPrivate` as the last argument?

File: js/components/frame.js [hunk 4]
```diff
@@ -764,7 +764,7 @@ class Frame extends ImmutableComponent {
         const runInsecureContent = parsedUrl.protocol === 'https:' && this.runInsecureContent()
         windowActions.setSecurityState(this.frame, {
           secure: isSecure,
-          runInsecureContent: runInsecureContent
+          runInsecureContent: runInsecureContent ? this.props.location : null
```
Comment (diracdeltas) [inline js/components/frame.js]: why does location need to be in the securityState? `SiteInfo` can just do `frameProps.get('location')`

File: js/state/contentSettings.js [hunk 5]
```diff
@@ -172,6 +172,16 @@ const getContentSettingsFromSiteSettings = (appState) => {
       addContentSettings(contentSettings.referer, hostPattern, '*', 'allow')
     }
   }
+
+  // temporarySiteSettings
```
Comment (diracdeltas) [inline js/state/contentSettings.js]: temporary site settings should only be added here if they are being sent to webcontents in a private session. cc @bridiver.

Comment (diracdeltas) [inline js/state/contentSettings.js]: more generally, there needs to be some way to scope siteSettings/contentSettings by session since in general these settings should not be shared across sessions.

File: test/components/navigationBarTest.js [hunk 6]
```diff
@@ -322,10 +325,135 @@ describe('navigationBar', function () {
...
+        .waitUntil(() => {
+          return this.app.client.getCssProperty('body', 'background-color').then((color) =>
+            color.value === 'rgba(128,128,128,1)'
+          )
+        })
+        .windowByUrl(Brave.browserWindowUrl)
+        .click(urlbarIcon)
+        .waitForExist(urlbarIcon + '.fa-lock')
+    })
+    it('Limit effect of running insecure content in frame', function * () {
```
Comment (diracdeltas) [inline test/components/navigationBarTest.js]: this test is timing out: https://travis-ci.org/brave/browser-laptop/builds/158405114#L3620

File: js/state/contentSettings.js (hunk 5 above)
Comment (diracdeltas) [inline js/state/contentSettings.js]: but i think this has the correct behavior right now since the `runInsecureContent` setting is reset at the end of page load, which means it's not a blocker for merging

Comment (bridiver) [inline js/state/contentSettings.js]: contentSettings don't have to worry about regular vs private. The private session has an overlay pref store that reads from the main profile, but writes to an in-memory store that doesn't transfer to the main profile

**Comment by bridiver** [comment]
the regular vs private profile code can be removed and is handled by https://github.com/brave/electron/commit/b956fa5eed12f85e7cdcbe2988baed72e9036e3b

**Comment by bridiver** [comment]
I guess my comment above is completely accurate because we are still writing them to the app state. We need to fully migrate site settings to content settings to fix the problem completely. In the meantime I suggest that we disallow the setting in private tabs for now just like the others

**Comment by diracdeltas** [comment]
++, i think this feature should just be disabled in private tabs for now. sorry about that @darkdh

File: js/components/siteInfo.js (hunk 3 above)
Comment (darkdh) [inline js/components/siteInfo.js]: ah, you are right. I forgot to add it.

File: js/components/frame.js (hunk 4 above)
Comment (darkdh) [inline js/components/frame.js]: Sounds better. I will changed to use `frameProps.get('location')`

**Comment by darkdh** [comment]
@diracdeltas , feedback addressed in 7aded75

File: js/components/siteInfo.js [hunk 7]
```diff
@@ -16,18 +16,29 @@ class SiteInfo extends ImmutableComponent {
   constructor () {
     super()
     this.onAllowRunInsecureContent = this.onAllowRunInsecureContent.bind(this)
+    this.onDenyRunInsecureContent = this.onDenyRunInsecureContent.bind(this)
   }
   onAllowRunInsecureContent () {
-    appActions.changeSiteSetting(siteUtil.getOrigin(this.isBlockedRunInsecureContent), 'runInsecureContent', true)
+    appActions.changeSiteSetting(siteUtil.getOrigin(this.isBlockedRunInsecureContent),
+      'runInsecureContent', true, this.isPrivate)
     ipc.emit(messages.SHORTCUT_ACTIVE_FRAME_LOAD_URL, {}, this.isBlockedRunInsecureContent)
```
Comment (diracdeltas) [inline js/components/siteInfo.js]: the code above can also use `this.location` instead of `this.isBlockedRunInsecureContent`

Comment (diracdeltas) [inline js/components/siteInfo.js]: but that is more of a refactor issue so this looks good to merge now. :)
