### PR TITLE
Fixes tab title on tab update

### LINKED ISSUE #8908: Title is not updated when using navigation buttons
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Title is not updated when using navigation buttons
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
8bb62f7
- Steps to reproduce:
    1. go to site clifton.io
    2. create a history
    3. click on back/forward buttons

    
- Actual result:
sometimes tab title is not display (location is shown)
- Expected result:
title should be displayed
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
no
- Can this issue be consistently reproduced?
not all the time but with few clicks you can see a problem

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #8908

Auditors: @bsclifton @bridiver

Test Plan:
- go to site clifton.io
- create a history
- click on back/forward buttons
- check that title is always correct

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/reducers/frameReducer.js [hunk 1]
```diff
@@ -92,7 +92,7 @@ const frameReducer = (state, action, immutableAction) => {
         }
       }
 
-      const title = immutableAction.getIn(['changeInfo', 'title'])
+      const title = immutableAction.getIn(['tabValue', 'title'])
```
Comment (bridiver) [inline app/renderer/reducers/frameReducer.js]: this may help, but won't be a complete fix because it doesn't address the race condition. Getting the title from `tabValue` will only fix the title when the tab state changes for some other reason. I think this change is ok for now, but we should add a comment/TODO that the race condition with appState is the real problem

Comment (bridiver) [inline app/renderer/reducers/frameReducer.js]: we also shouldn't mark this as resolving the issue for the same reason

Comment (NejcZdovc) [inline app/renderer/reducers/frameReducer.js]: Currently the only problem with the title not updating is when you use navigation buttons, so when tab state changes. What should I wrote in todo? `TODO fix race condition with appState`
