### PR TITLE
Fixes twitch, updated to the new data

### LINKED ISSUE #13597: twitch not working with brave, time not being recorded/added in ledger
### Description

Looks like Twitch has regressed around Friday and is not being added into the ledger table on both the latest `0.22.7` 8bb7e77 BETA and the current `0.21.24` 19c78a1 released/live build.

I don't think this is a regression with the client as it also stopped working on `0.21.24` 19c78a1. Seems like the issue is either server side, or Twitch pushed an update that broke Brave.

### Test plan / Steps to Reproduce

  1. launch `0.21.24` 19c78a1 or
  2. enable payments via `about:preferences#payments`
  3. visit twitch.tv and watch a video (either live/vod) for ~2mins

You'll notice that the entry isn't being added into the ledger table under Payments.

**Actual result:**

Twitch entries are not being added into the ledger table under Payments.

**Expected result:**

Twitch entries should be added into the ledger table under Payments when viewing content.

**Reproduces how often:**

100% reproducible when using the above STR.

### Brave Version

**about:brave info:**

Brave: 0.22.7 
V8: 6.5.254.41 
rev: 8bb7e77f69bca186429aafda4bc6ba4d82a5de47 
Muon: 5.1.1
libchromiumcontent: 65.0.3325.181
OS Release: 17.4.0 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.4.2 

**Reproducible on current live release:**

Yes, currently reproducible using `0.21.24` 19c78a1 which is the latest released version.

### Additional Information

* Win 10 x64 - Reproduced
* macOS 10.13.3 - Reproduced

Also reproduced by both @btlechowski and @LaurenWags as well.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #13597

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [ ] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/common/lib/ledgerUtil.js [hunk 1]
```diff
@@ -424,6 +447,8 @@ const getTwitchDuration = (state, data, mediaKey) => {
     return 0
   }
 
+  if (data.event === twitchEvents.START) debugger
```
Comment (petemill) [inline app/common/lib/ledgerUtil.js]: @NejcZdovc did you mean to leave `debugger` statement in?

Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: it's still WIP

File: app/common/lib/ledgerUtil.js [hunk 2]
```diff
@@ -226,6 +226,7 @@ const getMediaId = (data, type) => {
       }
     case ledgerMediaProviders.TWITCH:
       {
+        console.log(data.event)
```
Comment (NejcZdovc) [inline app/common/lib/ledgerUtil.js]: remove at the end

File: app/common/lib/ledgerUtil.js [hunk 3]
```diff
@@ -524,7 +555,7 @@ const getMediaProvider = (url, firstPartyUrl, referrer) => {
       (firstPartyUrl && firstPartyUrl.startsWith('https://www.twitch.tv/')) ||
       (referrer && referrer.startsWith('https://player.twitch.tv/'))
     ) &&
-    url.startsWith('https://api.mixpanel.com/')
+    url.includes('ttvnw.net/v1/segment')
```
Comment (diracdeltas) [inline app/common/lib/ledgerUtil.js]: this could lead to origin confusion, like if some site with a Twitch referrer embeds `https://evilsitettvnw.net/v1/segment` - can you make this check more specific?

Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: Not sure how I could do this. Any suggestions?

Comment (diracdeltas) [reply app/common/lib/ledgerUtil.js]: either a regex or `url.includes('.ttvnw.net/v1/segment') || url.includes('https://ttvnw.net/v1/segment')` (if the top-level page is HTTPS, the resources are probably also HTTPS)`

Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: updated

File: app/common/lib/ledgerUtil.js [hunk 4]
```diff
@@ -425,6 +447,15 @@ const getTwitchDuration = (state, data, mediaKey) => {
...
 
   const previousData = ledgerVideoCache.getDataByVideoId(state, mediaKey)
+
+  // remove duplicate events
+  if (
+    previousData.get('event') === data.event &&
+    previousData.get('time') === data.properties.time
+  ) {
+    return null
+  }
```
Comment (bsclifton) [inline app/common/lib/ledgerUtil.js]: this is great 👍

File: app/common/lib/ledgerUtil.js [hunk 5]
```diff
@@ -262,36 +262,58 @@ const getMediaData = (xhr, type) => {
...
+        }
+
+        result = queryString.parse(query)
         break
       }
     case ledgerMediaProviders.TWITCH:
       {
-        result = queryString.parse(parsedUrl.query)
-        if (!result.data) {
+        const data = details.getIn(['uploadData', 0, 'bytes'])
```
Comment (bsclifton) [inline app/common/lib/ledgerUtil.js]: There's ALMOST enough logic here that we might consider making `youTubeUtils` / `twitchUtils` / etc and having a single method exposed (ex: `getTwitchData`).  This could allow for documenting what is being parsed in a clear way

Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: yeah we can refactor this in the next version, so that is easier for the further implementations

File: app/common/lib/ledgerUtil.js [hunk 6]
```diff
@@ -524,7 +555,10 @@ const getMediaProvider = (url, firstPartyUrl, referrer) => {
       (firstPartyUrl && firstPartyUrl.startsWith('https://www.twitch.tv/')) ||
       (referrer && referrer.startsWith('https://player.twitch.tv/'))
     ) &&
-    url.startsWith('https://api.mixpanel.com/')
+    (
+      url.includes('.ttvnw.net/v1/segment/') ||
+      url.includes('https://ttvnw.net/v1/segment/')
```
Comment (bsclifton) [inline app/common/lib/ledgerUtil.js]: Reading this if can be a little difficult; one approach would be to pull the conditions into variables. Something like:
```
const firstPartyTwitch = firstPartyUrl && firstPartyUrl.startsWith('https://www.twitch.tv/')
const referrerTwitch = referrer && referrer.startsWith('https://player.twitch.tv/')
const isTwitch = (firstPartyTwitch || referrerTwitch) && [
  '.ttvnw.net/v1/segment/',
  'https://ttvnw.net/v1/segment/'
].some(segment => segment.includes(url))

if (isTwitch) {
  return ledgerMediaProviders.TWITCH
}

```

File: app/filtering.js [hunk 7]
```diff
@@ -126,7 +126,7 @@ function registerForBeforeRequest (session, partition) {
       // Ledger media
       const provider = ledgerUtil.getMediaProvider(url, firstPartyUrl, details.referrer)
       if (provider) {
-        appActions.onLedgerMediaData(url, provider, details.tabId)
+        appActions.onLedgerMediaData(url, provider, details)
```
Comment (bsclifton) [inline app/filtering.js]: This will be much more useful (having a whole details object vs just what is needed) for when more providers are added 😻

**Comment by NejcZdovc** [comment]
master f482935
0.23 e7f688326
0.22 b170925a5
