### PR TITLE
Hide bookmark bar when removing last item

### LINKED ISSUE #14047: Bookmark bar stays visible after all bookmarks are deleted
### Steps to Reproduce

1. Clean install
2. Click the star
3. Click 'Remove'

**Actual result:**
Bookmark bar stays visible
image

**Expected result:**
Bookmark bar is hidden

**Reproduces how often:**
100%

### Brave Version
```
Brave: 0.22.702 
V8: 6.6.346.26 
rev: e4a853d9990c62328a8a4320fec21f58c9cdc0c1 
Muon: 6.0.7 
OS Release: 4.13.0-21-generic 
Update Channel: Beta 
OS Architecture: x64 
OS Platform: Linux 
Node.js: 7.9.0 
Brave Sync: v1.4.2 
libchromiumcontent: 66.0.3359.139
```
Also reproduced on Mac and Windows by @srirambv @LaurenWags @kjozwiak 

**Reproducible on current live release:**
No. Tested v0.22.669

Cc @bsclifton @petemill

### PR DESCRIPTION
**Pull request by petemill**
Fix #14047
The bookmark bar has always remained 'visible' when removing the last item. It just happened to be reduced to a few pixels tall. This was a defect as it affected the vertical rhythm of the UI. With #13758, the toolbar always remains the set height. With this change, the toolbar is hidden automatically when the last item is removed, just like it already automatically shows when the first item is added.

Also fixes `getSetting` so check for whether an object is `Immutable.Map` correctly, so that it can be used in tests.

### Automated
- `npm run unittest -- --grep 'bookmarksReducer'`

### Manual
- Add several bookmark items, including folders
- Remove some items
  - observe the toolbar is still shown
- Move some items
  - observe the toolbar is still shown
- Delete all items
  - observe the toolbar is not shown anymore
- Recreate items, and use 'move' to put all items in a folder that is not on the bookmark bar
  - observe the toolbar is not shown anymore

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: test/unit/app/browser/reducers/bookmarksReducerTest.js [hunk 1]
```diff
@@ -548,6 +560,19 @@ describe('bookmarksReducer unit test', function () {
         .deleteIn(['cache', 'bookmarkLocation', 'https://clifton.io/'])
       assert.equal(spy.calledOnce, true)
       assert.deepEqual(newState.toJS(), expectedState.toJS())
+      console.log('settings', newState.get('settings').toJS(), newState.getIn(['settings', settingsConstants.SHOW_BOOKMARKS_TOOLBAR]))
```
Comment (bsclifton) [inline test/unit/app/browser/reducers/bookmarksReducerTest.js]: Whoops, left a console.log in there 😄

File: app/browser/reducers/bookmarksReducer.js [hunk 2]
```diff
@@ -89,6 +94,12 @@ const bookmarksReducer = (state, action, immutableAction) => {
 
         const destinationDetail = bookmarksState.findBookmark(state, action.get('destinationKey'))
         state = syncUtil.updateObjectCache(state, destinationDetail, STATE_SITES.BOOKMARKS)
+
+        // close bookmark bar when going to 0
+        const bookmarkBarItemCount = bookmarksState.getBookmarksWithFolders(state, 0).size
```
Comment (bsclifton) [inline app/browser/reducers/bookmarksReducer.js]: A little nit-picky... but could we move this code to app/common/lib/bookmarkUtils? Since it's the same as the code above in bookmarkFoldersReducer.js, each of these could be replaced with a single call (maybe the method would be called like `closeBookmarksToolbarIfEmpty` or something like that)

Should make the logic easier to unit test too 😄 👍

File: test/unit/app/browser/reducers/bookmarksReducerTest.js [hunk 3]
```diff
@@ -548,6 +560,19 @@ describe('bookmarksReducer unit test', function () {
...
+      assert.ok(onChangeSettingSpy.neverCalledWith(settingsConstants.SHOW_BOOKMARKS_TOOLBAR, false), 'bookmarks toolbar enabled setting is unaffected by removing 1 bookmark')
+    })
+
+    it('hides bookmarks toolbar when all toolbar bookmarks are removed', function () {
```
Comment (bsclifton) [inline test/unit/app/browser/reducers/bookmarksReducerTest.js]: Do we need a test for bookmarksReducer too?

**Comment by petemill** [comment]
master 2a55706
0.23.x 56b080fc9
0.22.x-release3 4f59d4268
