### PR TITLE
Fixed edit bookmark hanger showing when adding bookmark

### LINKED ISSUE #5508: Add bookmark from toolbar/right click context menu brings up "edit bookmark" modal
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
Add bookmark form toolbar brings up edit bookmark modal

**Expected behavior:**
Should show "Bookmark added" and show the hanger, not the modal

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version:
0.12.9 Preview 1
0.12.8 shows bookmark added modal

- Steps to reproduce:
    1. Enable Bookmark toolbar
    2. Right click, Add boomark, shows edit bookmark modal for the current active tab instead of add new bookmark modal
    3. Click star+ icon from about:bookmark, shows create bookmark modal 

- Screenshot if needed:
bmktoolbar

- Any related issues:

  cc: @bsclifton 
  Adding 0.12.10 as milestone, please change if required

### PR DESCRIPTION
**Pull request by jkup**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #5508 

Auditors @bbondy @bsclifton 

Test Plan:

1. Open Brave
2. Go to any site you don't currently have bookmarked
3. Right click on the page
4. Click 'Add Bookmark'
6. Make sure the "Bookmark Added" text shows, not the "Edit Bookmark"

### CODE REVIEW

**Comment by bbondy** [comment]
btw pls update the commit message too to have Fix #5508. Thanks!

File: js/contextMenus.js [hunk 1]
```diff
@@ -53,7 +53,7 @@ const addBookmarkMenuItem = (label, siteDetail, closestDestinationDetail, isPare
       if (isParent) {
         siteDetail = siteDetail.set('parentFolderId', closestDestinationDetail && (closestDestinationDetail.get('folderId') || closestDestinationDetail.get('parentFolderId')))
       }
-      windowActions.setBookmarkDetail(siteDetail, siteDetail, closestDestinationDetail, true)
```
Comment (jkup) [inline js/contextMenus.js]: Oh really? The current behavior is we don't show the location when you are adding from a page because we know the location. So there are only two states: Adding a bookmark (no location) or editing an existing bookmark (location).

Should we make a third state for Adding a bookmark but also showing location? Should we still hide location when you click the star?

Comment (jkup) [inline js/contextMenus.js]: Should it only show the location if you already have the site bookmarked (similar to the star behavior)? Or always show the location when you cmd+d or select it from the menu?

**Comment by bsclifton** [comment]
I think this PR might be trying to fix the wrong thing (cc: @srirambv, @bradleyrichter).  Personally, I like what this PR does better (although, I agree with Brian, it would be ideal if we could show location). Having an empty "create bookmark" modal would be confusing if you already have a page loaded.

I think @srirambv was reporting that the current behavior is showing this:
screen shot 2016-11-19 at 12 58 19 am

But he's expecting it to show this (notice all details blank), just like on the about:bookmarks page:
screen shot 2016-11-19 at 12 55 46 am

**Comment by jkup** [comment]
Sorry, I'm not understanding what I'm supposed to be doing in this ticket. @bsclifton is it that when you add a bookmark from right clicking the bookmarks toolbar menu it should always be blank?

**Comment by bsclifton** [comment]
@jkup apologies- after re-reading the issue, I think I misunderstood what @srirambv was asking for

I went back and updated #5508 to have a more clear title and expected case :smile: We're G2G! :shipit:

**Comment by bbondy** [comment]
Sorry I should have been more explicit with my comment that I was requesting changes and this should not be merged as is.  On all other browsers if you right click the bookmarks toolbar and add a bookmark it shows options to change the URL.  In chrome it doesn't even show the current site as defaults.   It is mostly meant for a generalized bookmarking and not for a current page bookmark.  I don't mind defaulting the values as we do now, but the main purpose is to bookmark an arbitrary site.

**Comment by jkup** [comment]
@bbondy Ah... that makes total sense. I just didn't understand at first, will put up a fix for that!
