### PR TITLE
Fix alignment of the buttons and keys on Brave wallet backup dialog

### LINKED ISSUE #10389: Buttons and keys are not aligned properly on wallet backup dialog
**Describe the issue you encountered:** Buttons and keys are not aligned properly on wallet backup dialog. This is because the width of the strings are sometimes different though the number of the characters are same.

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open about:preferences#payments
    2. Open Brave wallet backup dialog
    
- Actual result:

  screenshot 2017-08-10 17 46 09

- Expected result:

  screenshot 2017-08-10 18 26 18

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes #10389

Auditors: @cezaraugusto

Test Plan:
1. Open about:preferences#payments
2. Open Brave wallet backup dialog
3. Make sure the buttons and keys are aligned

screenshot 2017-08-10 18 26 18

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/ledgerBackup.js [hunk 1]
```diff
@@ -93,21 +98,31 @@ class LedgerBackupFooter extends ImmutableComponent {
 }
 
 const styles = StyleSheet.create({
-  copyKeyContainer: {
+  ledgerBackupContent: {
+    // Align the buttons and keys even when the width of the strings is not equal
+    width: 'max-content',
```
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/ledgerBackup.js]: this is super cool
