### PR TITLE
Fixes overlay problem with 0.19

### LINKED ISSUE #11432: animation overlay not stopping after wallet has been created
### Description

When enabling payments under v0.19.38 rev: fa3d144edb796192487ccc89ac771f4f9b954e57 with a zero balance, the progress overlay that's being displayed during the transition phase will keep going and will never "complete" despite the wallet being ready. The animation will keep going until you either disable/enable the wallet or restart the browser.

Also tried the following:

* checking console via "option + command + i"
* checking console via "fn + shift + f8"
* closing the about:preferences page and re-opening (animation kept going)

### Steps to Reproduce

  1. install & launch v0.19.38 rev: fa3d144edb796192487ccc89ac771f4f9b954e57 
  2. visit about:preferences#payments and enable payments

**Actual result:**

The overlay animation will keep going despite the wallet being ready.

Attached log from macOS: [log.txt](https://github.com/brave/browser-laptop/files/1374244/log.txt)

**Expected result:**

Once the transition phase has been completed, the animation overlay should stop and the wallet should be displayed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% reproducible using the above STR.

### Brave Version

**about:brave info:**

> Brave: 0.19.38 
> rev: fa3d144edb796192487ccc89ac771f4f9b954e57 
> Muon: 4.4.25 
> libchromiumcontent: 61.0.3163.100 

**Reproducible on current live release:**

BAT integration was added in `0.19.x` and isn't available under `0.18.x`, hence not reproducible in the latest release.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11432

Auditors:

Test Plan:
- clean profile
- start browser and enable payments
- there shouldn't be any overlay

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/sessionStore.js [hunk 1]
```diff
@@ -994,7 +994,8 @@ module.exports.defaultAppState = () => {
     migrations: {
       batMercuryTimestamp: now,
       btc2BatTimestamp: now,
-      btc2BatNotifiedTimestamp: now
+      btc2BatNotifiedTimestamp: now,
+      btc2BatTransitionDone: true
```
Comment (bbondy) [inline app/sessionStore.js]: maybe better called `btc2BatTransitionPending`?
