### PR TITLE
Fixed wallet preference page refresh

### LINKED ISSUE #6770: wallet preference page is not refreshing itself when a bitcoin handler is registered
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
When executing the ledger regression tests, it was found that https://jsfiddle.net/LnwtLckc/5/ did not appear to have registered appropriately. Upon further investigation, it was discovered that the real issue was that the preference page was not updating when the handler was being registered/unregistered like it had in prior releases. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X

- Brave Version (revision SHA):
0.13.0 Preview 10 (c60b783)

- Steps to reproduce:
    1. clear your session, open brave
    2. open preferences, create a wallet
    3. in a new tab, visit https://jsfiddle.net/LnwtLckc/5/, click on register
    4. switch tabs back to preferences, check add funds modal, notice lack of 'transfer btc' button
    
- Actual result:
'transfer btc' button does not appear in the modal

- Expected result:
'transfer btc' button should appear in the modal

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
no

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
btc_handler

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #6770

Auditors:
@alexwykoff @bsclifton @mrose17

## Test Plan
- described in #6770

### CODE REVIEW

File: app/filtering.js [hunk 1]
```diff
@@ -561,11 +561,24 @@ function initForPartition (partition) {
...
     options.parent_partition = ''
   }
+
   let ses = session.fromPartition(partition, options)
-  fns.forEach((fn) => { fn(ses, partition, module.exports.isPrivate(partition)) })
+  fns.forEach((fn) => {
+    fn(ses, partition, module.exports.isPrivate(partition))
+  })
+  ses.on('register-navigator-handler', (e, protocol, location) => {
+    appActions.navigatorHandler(ses.partition, protocol, location, true)
```
Comment (bridiver) [inline app/filtering.js]: we should try to keep the declarative naming conventions here so maybe `navigatorHandlerRegistered` and `navigatorHandlerUnregistered`?

File: app/ledger.js [hunk 2]
```diff
@@ -232,6 +232,11 @@ const doAction = (action) => {
       setTimeout(networkConnected, 1 * msecs.second)
       break
 
+    case appConstants.APP_NAVIGATOR_HANDLER_UPDATE:
```
Comment (bridiver) [inline app/ledger.js]: related to the above comment, the app constant name should match the action name

File: app/filtering.js (hunk 1 above)
Comment (bsclifton) [inline app/filtering.js]: Good call 👍  Since this is already merged, please feel free to do as a follow up, @NejcZdovc 😄
