### PR TITLE
Increase pinned tabs width

### LINKED ISSUE #10368: Increase Padding on Pinned Tabs
## Test plan

https://github.com/brave/browser-laptop/pull/10533#issue-250567316

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Pinned tabs would benefit from better UI/UX with greater lateral padding. See [this tweet](https://twitter.com/orangefallz/status/895322726436528133) by a Brave user.

If this request is implemented, we should probably consider the UI/UX of narrow tabs in general. A cursory glance at the current implementation reveals that pinned tabs, and standard narrow tabs, are displayed differently.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Desktop

- Brave Version (revision SHA):
N/A

- Steps to reproduce:
    1. Create a pinned tab
    
- Actual result:
Padding is tight, at `2px`.

- Expected result:
More lateral padding (perhaps `5px`?)

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Screenshot if needed:
(Top: Safari, Bottom: Brave)
image

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #10368

screenshot 2017-08-16 18 48 53

Auditors: @cezaraugusto

Test Plan:
1. Open brave.com in a new tab
2. Open github.com in another new tab
3. Pin them
4. Make sure the width of the pinned tabs is enough

Test Plan 2:
1. Open example.com
2. Pin the tab
3. Make sure the default icon appears at the center of the pinned tab

Test Plan 3:
1. Open youtube video
2. Make sure the spacing around the audio icon, favicon and tab's title is equal

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/styles/tab.js [hunk 1]
```diff
@@ -68,12 +71,6 @@ const styles = StyleSheet.create({
     overflow: 'hidden'
   },
 
-  // Add extra space for pages that have no icon
-  // such as about:blank and about:newtab
-  noFavicon: {
```
Comment (luixxiul) [inline app/renderer/components/styles/tab.js]: This is not called anywhere.

File: app/renderer/components/styles/tab.js [hunk 2]
```diff
@@ -89,18 +86,19 @@ const styles = StyleSheet.create({
   },
 
   isPinned: {
-    paddingLeft: globalStyles.spacing.defaultIconPadding,
-    paddingRight: globalStyles.spacing.defaultIconPadding
+    padding: 0,
+    width: `calc(${globalStyles.spacing.tabsToolbarHeight} * 1.1)`,
```
Comment (luixxiul) [inline app/renderer/components/styles/tab.js]: `26px * 1.1` is nearly equal to the pinned tab width where the padding is increased from 2px to 4px.

File: app/renderer/components/styles/tab.js [hunk 3]
```diff
@@ -138,11 +136,6 @@ const styles = StyleSheet.create({
     fontSize: globalStyles.fontSize.tabIcon,
     backgroundPosition: 'center',
     backgroundRepeat: 'no-repeat',
-    display: 'flex',
-    alignSelf: 'center',
-    position: 'relative',
-    textAlign: 'center',
-    justifyContent: 'center',
```
Comment (luixxiul) [inline app/renderer/components/styles/tab.js]: We don't need those.

File: app/renderer/components/tabs/content/tabIcon.js [hunk 4]
```diff
@@ -17,14 +17,13 @@ const globalStyles = require('../../styles/global')
 class TabIcon extends ImmutableComponent {
   render () {
     const styles = StyleSheet.create({
-      icon: {
+      tabIcon: {
```
Comment (luixxiul) [inline app/renderer/components/tabs/content/tabIcon.js]: Replaced as it is confusing (we already have `icon` on `/style/tab.js`).

File: app/renderer/components/tabs/content/tabIcon.js [hunk 5]
```diff
@@ -17,14 +17,13 @@ const globalStyles = require('../../styles/global')
...
         fontSize: this.props.symbolContent ? '8px' : 'inherit',
         display: 'flex',
-        alignSelf: 'center',
         width: globalStyles.spacing.iconSize,
         height: globalStyles.spacing.iconSize,
         alignItems: 'center',
-        justifyContent: this.props.symbolContent ? 'flex-end' : 'left',
+        justifyContent: this.props.symbolContent ? 'flex-end' : 'center',
```
Comment (luixxiul) [inline app/renderer/components/tabs/content/tabIcon.js]: This makes the default icon appear on the center of the pinned tab

File: app/renderer/components/styles/tab.js [hunk 6]
```diff
@@ -89,18 +86,19 @@ const styles = StyleSheet.create({
...
-    paddingLeft: globalStyles.spacing.defaultIconPadding,
-    paddingRight: globalStyles.spacing.defaultIconPadding
+    padding: 0,
+    width: `calc(${globalStyles.spacing.tabsToolbarHeight} * 1.1)`,
+    justifyContent: 'center'
   },
 
   active: {
     background: `rgba(255, 255, 255, 1.0)`,
-    height: globalStyles.spacing.tabHeight,
```
Comment (luixxiul) [inline app/renderer/components/styles/tab.js]: redundant

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 7]
```diff
@@ -61,17 +61,11 @@ class AudioTabIcon extends React.Component {
 
   render () {
     return <TabIcon
-      className={css(tabStyles.icon, styles.audioIcon)}
+      className={css(tabStyles.icon, tabStyles.icon_audio)}
```
Comment (luixxiul) [inline app/renderer/components/tabs/content/audioTabIcon.js]: Specifying a style in each file will create style inconsistency quite easily.

File: app/renderer/components/styles/tab.js (hunk 2 above)
Comment (cezaraugusto) [reply app/renderer/components/styles/tab.js]: this seems fragile to me. What if at a given point we decide to update tabs toolbar height?

pinned tabs sizing are also are not used anywhere else so I won't mind having the size explicitly described here.
