### PR TITLE
Check for no frame info in tab content components

### LINKED ISSUE #9686: Sometimes no active tab is selected after closing a tab
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Closing a tab can sometimes lead to no active tab being set. 

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS, but probably all.

- Brave Version (revision SHA):
0.17.7

- Steps to reproduce:
    1. Open a bunch of tabs, make a google docs spreadsheet the active one.
    2. Command+W
     
- Actual result:
You may find that there's no active tab set after the tab close.
Shift+F8 gives console error pointing to frame.get where frame is undefined in AudioTabIcon component.

- Expected result:
Should close and select a new tab as active.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
I don't think it's more or less likely on a new profile.

- Is this an issue in the currently released version?
I don't think so.

- Can this issue be consistently reproduced?
No.

### PR DESCRIPTION
**Pull request by bbondy**
NOTE FOR MERGE: This is a PR against 0.17.x because unit tests are currently failing too much on other branches. So when merging merge it to 0.18.x, and master.

Auditors: @NejcZdovc

Fix #9686

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/tabs/content/audioTabIcon.js [hunk 1]
```diff
@@ -43,7 +44,10 @@ class AudioTabIcon extends React.Component {
 
   mergeProps (state, dispatchProps, ownProps) {
     const currentWindow = state.get('currentWindow')
-    const frame = frameStateUtil.getFrameByKey(currentWindow, ownProps.frameKey)
+
+    // AudioIcon will never be created if there is no frameKey, but for consistency
+    // across other components I added teh || Immutable.Map()
```
Comment (NejcZdovc) [inline app/renderer/components/tabs/content/audioTabIcon.js]: nit: `teh` -> `the`
