### PR TITLE
Fixes url bar shape when payment is disabled

### LINKED ISSUE #8170: URL bar shape is different with payments enabled/disabled when visiting a site
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
URL bar shape is different with payments enabled/disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):
0.14.1 Preivew 1

- Steps to reproduce:
    1. Open a new tab and see the URL bar has rounded corners on all sides
    2. Visit a site in the new tab, the right corners change from rounded to sharp edge
    3. Enable payments and visit  a new site in a new tab
    4. The inclusion of the verified publisher button causes the edge to be rounded but the URL bar inside still has sharp edges
    
- Actual result:
URL bar shape is different with payments enabled/disabled when visiting a site

- Expected result:
Corners should be same irrespective of payments enabled/disabled

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Mostly need to verify with an older build

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
urlshape

- Any related issues:
cc: @bradleyrichter  @cezaraugusto

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Resolves #8170

### Auditors
@srirambv @bsclifton

### Test Plan
- with payments disabled visit a site
- url border should be shaped

### CODE REVIEW

**Comment by bsclifton** [comment]
@srirambv would you be able to give this one a go? 😄

File: app/renderer/components/navigation/navigationBar.js [hunk 1]
```diff
@@ -242,7 +246,7 @@ class NavigationBar extends ImmutableComponent {
         urlbar={this.props.navbar.get('urlbar')}
         onStop={this.onStop}
         menubarVisible={this.props.menubarVisible}
-        noBorderRadius={!isSourceAboutUrl(this.props.location)}
+        noBorderRadius={(isSourceAboutUrl(this.props.location) && this.isPublisherButtonEnabled) || this.isPublisherButtonEnabled}
```
Comment (cezaraugusto) [inline app/renderer/components/navigation/navigationBar.js]: I think you don't need to check aboutUrls since it will return false with `UrlUtil.isHttpOrHttps`. 

`noBorderRadius={this.isPublisherButtonEnabled}` should work as expected

Comment (NejcZdovc) [inline app/renderer/components/navigation/navigationBar.js]: Yes we need it, because otherwise you get a rounded shape while loading some pages

**Comment by NejcZdovc** [comment]
@bsclifton @cezaraugusto I now changed logic to be the same as is for `publisherToggle` component. This way as soon as we display publisher icon we change the shape of the url bar.

**Comment by srirambv** [comment]
Tested on Windows. Looks good and neat 👍
