### PR TITLE
Change sites from List to Map

### LINKED ISSUE #4879: long hang on Firefox import
**Did you search for similar issues before submitting this one?** Yes

**Describe the issue you encountered:** Importing Firefox data (history, bookmarks, and cookies) hung the Brave app for a good 30 seconds. Windows reported Brave as "(Not Responding)" for the duration. 

**Expected behavior:** Brave shouldn't hang. Also a progress indicator of some sort would be helpful if it's gonna take that long. 
- Platform (Win7, 8, 10? macOS? Linux distro?): Win10 
- Brave Version: 0.12.4
- Steps to reproduce:
  1. visit settings and import all types data from Firefox
  2. notice brave become unresponsive
  3. check task manager and see Not Responding for about 30 seconds
- Screenshot if needed:
- Any related issues: why no import passwords?

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:

fix #4879

Auditors: @bbondy, @bsclifton, @cezaraugusto

Test Plan:
Performance:
1. Import bulk bookmarks (4000+) from other browsers (Don't merge into toolbar)
2. The process should finish instantly
3. Delete Import from XXX folder
4. The process should finish instantly

Migration:
1. Make sure session-store-1 contains the sites data before 0.12.10
2. Lauch Brave and Close
3. sites of session-store-1 should change from [] tp {}

### CODE REVIEW

File: app/sessionStore.js [hunk 1]
```diff
@@ -432,6 +432,16 @@ module.exports.loadAppState = () => {
...
+      // sites refactoring migration
+      if (Array.isArray(data.sites) && data.sites.length) {
+        let sites = {}
+        data.sites.forEach((site) => {
+          let key = siteUtil.getSiteKey(Immutable.fromJS(site), site.tags)
+          sites[key] = site
+        })
+        data.sites = sites
+      }
+
```
Comment (bsclifton) [inline app/sessionStore.js]: Great job with the above :smile: It's super important to have migrations for the session data

File: docs/state.md [hunk 2]
```diff
@@ -34,7 +34,8 @@ AppStore
       }
     }
   },
-  sites: [{
+  sites: {
+  [siteKey]: { // Calculated by siteUtil.getSiteKey()
```
Comment (bsclifton) [inline docs/state.md]: could you just put the format of the key? like folder specifies folderId, URLs use location/partition/folderId?

File: js/state/siteUtil.js [hunk 3]
```diff
@@ -25,22 +25,20 @@ const isBookmarkFolder = (tags) => {
...
-module.exports.getSiteIndex = function (sites, siteDetail, tags) {
-  if (!sites || !siteDetail) {
-    return -1
+module.exports.getSiteKey = function (siteDetail, tags) {
+  if (!siteDetail) {
+    return null
   }
-  if (isBookmarkFolder(tags)) {
-    return sites.findIndex((site) => isBookmarkFolder(site.get('tags')) && site.get('folderId') === siteDetail.get('folderId'))
+  const folderId = siteDetail.get('folderId')
```
Comment (bsclifton) [inline js/state/siteUtil.js]: with this refactor, the tags field really isn't needed (which is nice).  Because you can determine if it's a folder or not by the `folderId`.  It might clean things up to remove it

File: js/state/siteUtil.js [hunk 4]
```diff
@@ -105,9 +106,14 @@ const mergeSiteDetails = (oldSiteDetail, newSiteDetail, tag, folderId) => {
   let site = Immutable.fromJS({
     lastAccessedTime: lastAccessedTime,
     tags,
-    title: newSiteDetail.get('title')
+    title: newSiteDetail.get('title'),
+    order
   })
 
+  if (oldSiteDetail && oldSiteDetail.get('order') !== undefined) {
+    site = site.set('order', oldSiteDetail.get('order'))
```
Comment (bsclifton) [inline js/state/siteUtil.js]: At some point (doesn't have to be now, something for all of us to keep in mind :smile:), I think it might be worth creating util methods to help with type conversion / default values.  Something like this:

```
const safeNumber = (value, default) => {
  const num = Number(value)
  return isNaN(num) ? default : num
}
```

File: js/state/siteUtil.js [hunk 5]
```diff
@@ -277,28 +284,40 @@ module.exports.isMoveAllowed = (sites, sourceDetail, destinationDetail) => {
...
 
   let newIndex = destinationSiteIndex + (prepend ? 0 : 1)
-  let sourceSite = sites.get(sourceSiteIndex)
-  let destinationSite = sites.get(destinationSiteIndex)
-  sites = sites.splice(sourceSiteIndex, 1)
+  let sourceSite = sites.get(sourceKey)
+  let destinationSite = sites.get(destinationKey)
+  sites = sites.delete(sourceKey)
+  sites = sites.map((site) => {
+    const siteOrder = site.get('order')
```
Comment (bsclifton) [inline js/state/siteUtil.js]: Would it make sense to pull this re-ordering out to a common method?

File: js/stores/appStore.js [hunk 6]
```diff
@@ -439,10 +439,15 @@ const handleAppAction = (action) => {
           appState = appState.set('sites', siteUtil.addSite(appState.get('sites'), s, action.tag))
         })
       } else {
-        appState = appState.set('sites', siteUtil.addSite(appState.get('sites'), action.siteDetail, action.tag, action.originalSiteDetail))
+        let sites = appState.get('sites')
+        if (!action.siteDetail.get('folderId')) {
+          action.siteDetail = action.siteDetail.set('folderId', siteUtil.getNextFolderId(sites))
+        }
+        appState = appState.set('sites', siteUtil.addSite(sites, action.siteDetail, action.tag))
       }
```
Comment (bsclifton) [inline js/stores/appStore.js]: Much cleaner + easier to read :smile:

**Comment by bsclifton** [comment]
Looks good! :+1: I left some comments with feedback.  This is a great step in making the code better :smile:

**Comment by darkdh** [comment]
Thanks for the review effort @bsclifton. It has been addressed in https://github.com/brave/browser-laptop/pull/5531/commits/d8d2b6604c174aecf339b1e248260cfbd0ca5891

**Comment by cezaraugusto** [comment]
@darkdh only issue I could found was fixed by @bsclifton 

@bsclifton edits made a regression where topSites are no longer collecting favicons instantly.

Otherwise LGTM. Awesome team work!

**Comment by bbondy** [comment]
`npm run test -- --grep="auto open bookmarks toolbar for the first bookmark"` is failing in automated tests for navigationBar because of this.

Also I noticed the navigation bar star icon no longer works after this. It seems to create 3 site entries for a single website. And only the third has a bookmark tag.  Sites should always be unique.  Since this can cause some session store corruption I'm going to revert this.
