### PR TITLE
Fixes close tabs to the left/right

### LINKED ISSUE #9789: Close tabs to the left/right (tab page)
## Test plan

https://github.com/brave/browser-laptop/pull/9790#issue-239711691

----

- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you try to close all tabs except selected one and you have open tab pages, tabPage index is not updated. Found this bug when working on #7806
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
4cc1273
- Steps to reproduce:
    1. open so many tabs that you have at least two tab pages
    2. right click on the last tab
    3. select "Close tabs to the left"
    
- Actual result:
image

- Expected result:
We should see our last tab
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?
yes
- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
when you have multiple tab pages

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #9789

Auditors: @bsclifton

Test Plan:
- open so many tabs that you have at least two tab pages
- right click on the last tab
- select "Close tabs to the left"

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
PR blocked by #9773

**Comment by NejcZdovc** [comment]
This is done, but test will fail, because of this bug #9420

File: app/renderer/reducers/frameReducer.js [hunk 1]
```diff
@@ -186,21 +186,33 @@ const frameReducer = (state, action, immutableAction) => {
...
       break
     case windowConstants.WINDOW_CLOSE_OTHER_FRAMES:
-      const currentIndex = frameStateUtil.getIndexByTabId(state, action.tabId)
-      if (currentIndex === -1) {
-        return
-      }
+      {
+        const currentIndex = frameStateUtil.getIndexByTabId(state, action.tabId)
+        if (currentIndex === -1) {
+          return
```
Comment (bbondy) [inline app/renderer/reducers/frameReducer.js]: I know it was like this before as well but this should be returning state here.

**Comment by bbondy** [comment]
Ideally this whole thing would happen in the browser side instead but I know this is just a small fix to an existing bug so it's ok in general.   But longer term we should refactor it.  Test problem and returning state are blockers though.

File: app/renderer/reducers/frameReducer.js (hunk 1 above)
Comment (NejcZdovc) [inline app/renderer/reducers/frameReducer.js]: fixed

**Comment by NejcZdovc** [comment]
@bbondy Test fixed as well. Should be good to go now

**Comment by bbondy** [comment]
Doesn't apply without redux to 0.18.x so we're moving this to 0.19.x
