### PR TITLE
Show Locale Strings on Extensions Page

### LINKED ISSUE #7826: bitwarden: unknown title and description on about:extensions
**Describe the issue you encountered:**

clipboard01

CC @kspearrin

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10 32 bit

- Brave Version (revision SHA): 0.14.0 Preview 4

- Steps to reproduce:
    1. Enable bitwarden
    2. Open about:extensions
 
- Expected result: the title and description should be specified

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #4776

### PR DESCRIPTION
**Pull request by jonathansampson**
## Test Plan
1. Enable Dashlane
2. Navigate to about:extensions
3. Confirm that Dashlane's name and description are shown

## Description
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Fixes #7826 #7683 

image

### CODE REVIEW

File: app/extensions.js [hunk 1]
```diff
@@ -363,6 +364,25 @@ module.exports.init = () => {
...
+  let insertLocaleStrings = (installInfo) => {
+    let pattern = /^__MSG_(.*)__$/
+    let properties = ['name', 'description']
+    let defaultLocale = installInfo.manifest.default_locale
+    if (defaultLocale) {
+      let msgPath = path.join(installInfo.base_path, '_locales', defaultLocale, 'messages.json')
+      if (fs.existsSync(msgPath)) {
+        let messages = JSON.parse(fs.readFileSync(msgPath).toString())
+        properties.forEach((property) => {
+          let key = installInfo[property].match(pattern)[1]
```
Comment (cezaraugusto) [inline app/extensions.js]: fyi: log error happened while toggling last pass and pocket

Comment (jonathansampson) [inline app/extensions.js]: @cezaraugusto What do you mean by _toggling_? Were you enabling and disabling the extension(s) in Preferences?
