### PR TITLE
Follow up for sites splits PR #10296

### LINKED ISSUE #10296: Follow up of site splits
Original PR #10136

### Known issues
- [x] bookmark toolbar is not refreshing when reordering https://github.com/brave/browser-laptop/pull/10136#issuecomment-320026616 (fix https://github.com/brave/browser-laptop/pull/10136#issuecomment-320083825) - fixed in #10325

### Tests
- [x] app/common/lib/historyUtil.js
- [x] app/common/state/aboutHistoryState.js
- [x] app/common/state/aboutNewTabState.js
- [x] app/common/state/bookmarkFoldersState.js
- [x] app/common/state/bookmarksState.js

### LINKED ISSUE #10348: Bookmarked icon keeps displayed after the bookmark is deleted
**Describe the issue you encountered:** Bookmarked icon keeps displayed after the bookmark is moved to a bookmark folder and deleted.

screenshot 2017-08-09 10 49 11

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Bookmark twitter.com
    2. Create a bookmark folder
    3. Move the bookmark into the folder
    4. Delete the bookmark 
    
- Actual result: the bookmarked icon is still displayed

- Expected result: it should not

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### LINKED ISSUE #10503: Favicons of imported bookmarks on the toolbar are missing
**Describe the issue you encountered:**
Favicons of imported bookmarks on the toolbar are missing. So are the title and the URL.

Brave: 0.20.0 
V8: 6.0.286.52 
rev: 46b16c5841988ec98b7ce15a667a0218564c2db2 
Muon: 4.4.7 
OS Release: 16.7.0 
Update Channel: dev 
OS Architecture: x64 
OS Platform: macOS 
Node.js: 7.9.0 
Brave Sync: v1.3.5 
libchromiumcontent: 60.0.3112.90

- Steps to reproduce 1:
    1. Import bookmarks from Safari
    2. Open about:bookmarks
    3. Move `icloud.com` to `Bookmarks Toolbar`
    4. Open about:preferences
    5. Change the favicon setting to `Text and Favicons`
    6. Click `iCloud`
    7. **The favicon is not displayed. The bookmark's URL and title are not populated on the dialog either**
      screenshot 2017-08-15 20 36 05
    1. Input something on the empty fields
    2. Click `Done`
    3. **The bookmark is duplicated**
    4. Click the dupe
    5. **The UI hangs with this error:**
    ````
    bookmarkFoldersState.js:39 Uncaught TypeError: Cannot read property 'toString' of undefined
        at Object.getFolder (bookmarkFoldersState.js:39)
        at Object.findBookmark (bookmarksState.js:56)
        at mergeProps (bookmarkToolbarButton.js:179)
        at buildPropsImpl (reduxComponent.js:14)
        at ReduxComponent.buildProps (reduxComponent.js:88)
        at ReduxComponent.componentWillReceiveProps (reduxComponent.js:74)
        at ReactCompositeComponent.js?d2b3:610
        at measureLifeCyclePerf (ReactCompositeComponent.js?d2b3:75)
        at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js?d2b3:609)
        at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js?d2b3:546)
    assert.js?9281:84 Uncaught AssertionError {name: "AssertionError", message: "state must contain an Immutable.Map of historySites", actual: false, expected: true, operator: "==", …}

    ````

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #10296

Auditors:

Test Plan: covered with automated tests

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
blocked by #10325

**Comment by cezaraugusto** [comment]
@NejcZdovc I'm going to close as stale for now please re-open when you have a window. Thanks!

File: app/common/lib/historyUtil.js [hunk 1]
```diff
@@ -15,20 +15,32 @@ const sortTimeDescending = (left, right) => {
 }
 
 const getHistory = (sites) => {
-  sites = makeImmutable(sites) ? makeImmutable(sites).toList() : new Immutable.List()
+  if (sites == null) {
+    return Immutable.List()
+  }
+
+  sites = makeImmutable(sites) ? makeImmutable(sites).toList() : Immutable.List()
```
Comment (bsclifton) [inline app/common/lib/historyUtil.js]: I know this logic is the same as before, but I think it's wrong.  Should it be:
`sites = sites ? makeImmutable(sites).toList() : Immutable.List()`

Comment (bsclifton) [reply app/common/lib/historyUtil.js]: (makeImmutable won't return falsey values basically)

Comment (bsclifton) [reply app/common/lib/historyUtil.js]: Since the above is checking == null (which should also return true for undefined, right?), I think we can simply make it
`sites = makeImmutable(sites).toList()`

Comment (NejcZdovc) [reply app/common/lib/historyUtil.js]: fixed

File: app/common/lib/historyUtil.js [hunk 2]
```diff
@@ -15,20 +15,41 @@ const sortTimeDescending = (left, right) => {
...
 
 const getHistory = (sites) => {
-  sites = makeImmutable(sites) ? makeImmutable(sites).toList() : new Immutable.List()
+  if (sites == null) {
+    return Immutable.List()
+  }
+
+  sites = makeImmutable(sites)
+
+  if (!isList(sites)) {
```
Comment (bsclifton) [inline app/common/lib/historyUtil.js]: 😄 👌

**Comment by cezaraugusto** [comment]
master ea04284
0.21.x 387fe00e4
0.20.x d8712bc46
