### PR TITLE
Fixes publisher not added to the ledger

### LINKED ISSUE #11273: Ledger table doesnt auto populate the publishers
### Description
Ledger table doesnt auto populate the publishers

### Steps to Reproduce

  1. Clean install 0.19.28
  2. enable payments
  3. keep the payments tab open
  2. Visit brianbondy.com in a new tab 
  3. Wait for a minute,
  3. switch to payments tab,
  4. publisher is not shown in ledger table
  4. Reload the preferences page
  4. publisher is shown in the ledger table
  5. Visit clifton.io in a new tab, 
  5. stay on the tab for a minute,
  5. switch to preferences tab,
  5. publisher not shown,
  5. reload the preferences tab,
  5. publisher shows up

**Actual result:**

autoincludepuubs

**Expected result:**
Should auto-refresh ledger table when criteria is met

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

No
### Additional Information

cc: @LaurenWags @kjozwiak

### LINKED ISSUE #11274: Site not added to publisher list even after spending ~10 mins on the site
### Description
Site not added to publisher list even after spending ~10 mins on the site

### Steps to Reproduce

  1. Install 0.19.28
  2. Enable payments, 
  3. Change min time to 5sec (optional step, I did that)
  4. Visit news.google.com, click on any news entry (i had opened newsweekly)
  5. Browse the site for ~10 mins 
  6. Go back to payments, no entry for visited site.
  7. Open a new tab, visit a different site 
  8. After ~1 min reload preferences tab, entry shown for site visited in step 7

**Actual result:**
Site not added to publisher list even after spending ~10 mins on the site

**Expected result:**
Should add entry in ledger table after min criteria is met
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.28
-- | --
rev | 08781a5
Muon | 4.4.25
libchromiumcontent | 61.0.3163.100
V8 | 6.1.534.41
Node.js | 7.9.0
Update Channel | Beta
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**

No
### Additional Information

@kjozwiak was able to repro this on ledger refactor branch

### LINKED ISSUE #11553: Publishers auto-included  even with auto-include switch disabled
### Description
Publishers auto-included  even with auto-include switch disabled 

### Steps to Reproduce

  1. Enable payments  in 0.18.36
  2. Upgrade to 0.19.48 so that wallet is converted to BAT
  3. While conversion is happening, disable the auto-include switch
  4. Visit some random sites, some of them gets auto included even though `auto-include` switch is turned off

**Actual result:**
Publishers auto-included  even with auto-include switch disabled

**Expected result:**
No publisher should be included if auto-include switch is turned off

**Reproduces how often:** [What percentage of the time does it reproduce?]
Reproduced and confirmed by @LaurenWags 
### Brave Version

**about:brave info:**

Brave | 0.19.48
-- | --
rev | de939f6
Muon | 4.4.28

**Reproducible on current live release:**

Yes 

### Additional Information

#7451 #7850

### LINKED ISSUE #11575: Page data refactor
## Test plan

https://github.com/brave/browser-laptop/pull/11592#issue-266394313

----

### Description

Refactor page data so that we handle about pages as well.

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11553 - Publishers auto-included even with auto-include switch disabled
Resolves #11575 - Page data refactor
Resolves #11273 - Ledger table doesn't auto populate the publishers
Resolves #11274 - Site not added to publisher list even after spending ~10 mins on the site

Auditors:

Test Plan:

**for every test plan you need to clean your profile and enable payments**

Plan A
- open preferences, go to payments
- open a new tab
- load a site
- stay on that site for 15s
- switch to preference tab and site should be added

Plan B
- open preferences, go to payments
- open a new tab
- load a site
- stay on that site for 15s
- open a a new tab
- switch to preference tab and site should be added

Plan C
- do plan B
- switch to the site tab and stay on it for 15s
- open new tab and visit different site for 15s
- switch to preference tab and new site should be added and old site should have 2 visits

Plan D
- open preferences, go to payments
- change min visit time to 1min
- open new tab
- load a site stay on that site for 15s
- open another app (so that focus will be out)
- click back on opened site in brave and wait for 1m
- switch to preference tab and site should be added

Plan E
- do plan B
- go back to site tab and stay on that site for 15s
- switch to preference tab and site should have 1 visit, but 20+ seconds visit time

Plan F
- Open preferences, go to payments
- Disable `auto-include` settings 
- Visit some random sites so that the sites are added to the ledger table
- Ensure no site is auto included that gets added to the table

Plan G
- open preferences, go to payments
- open a new tab
- load a site stay on that site for 15s
- open a private tab
- load a new site stay on that site for 15s
- switch to preference tab and table should only contain site visited in normal tab and not from private tab

Plan H
- do plan A
- disable payments
- visit few more sites in new tabs
- switch to preference tab and ledger table should only have site from plan A

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
I am done with an initial work. I am waiting for some feedback regarding what is visit, then I will do final clenup

File: app/browser/reducers/ledgerReducer.js [hunk 1]
```diff
@@ -3,6 +3,8 @@
  * You can obtain one at http://mozilla.org/MPL/2.0/. */
 
 const Immutable = require('immutable')
+const electron = require('electron')
```
Comment (bbondy) [inline app/browser/reducers/ledgerReducer.js]: this is fine but I think preferred style is const {BrowserWindow} = require('electron')

File: app/browser/reducers/ledgerReducer.js [hunk 2]
```diff
@@ -335,6 +323,85 @@ const ledgerReducer = (state, action, immutableAction) => {
...
+        if (action.getIn(['details', 'resourceType']) === 'mainFrame') {
+          const pageUrl = action.getIn(['details', 'newURL'])
+
+          // create a page view event if this is a page load on the active tabId
+          const lastActiveTabId = pageDataState.getLastActiveTabId(state)
+          const tabId = action.get('tabId')
+          if (!lastActiveTabId || tabId === lastActiveTabId) {
+            state = ledgerApi.pageDataChanged(state, {
+              location: pageUrl,
+              tabId: tabId
```
Comment (bbondy) [inline app/browser/reducers/ledgerReducer.js]: nit on style:
just `tabId` instead of `tabId: tabId`

File: app/browser/reducers/ledgerReducer.js (hunk 1 above)
Comment (bbondy) [reply app/browser/reducers/ledgerReducer.js]: I see it was moved code, so feel free to leave as is.

File: app/extensions/brave/content/scripts/idleHandler.js [hunk 3]
```diff
@@ -1,5 +1,6 @@
 chrome.idle.setDetectionInterval(15 * 60)
 chrome.idle.onStateChanged.addListener((idleState) => {
+  // uses appConstants.APP_IDLE_STATE_CHANGED action constant
```
Comment (bbondy) [inline app/extensions/brave/content/scripts/idleHandler.js]: nit: start comment with capital and end in period.

File: test/unit/app/browser/reducers/ledgerReducerTest.js [hunk 4]
```diff
@@ -215,25 +215,38 @@ describe('ledgerReducer unit tests', function () {
...
-    before(function () {
+    beforeEach(function () {
       pageDataChangedSpy = sinon.spy(fakeLedgerApi, 'pageDataChanged')
-      addVisitSpy = sinon.spy(fakeLedgerApi, 'addVisit')
+    })
+
+    afterEach(function () {
+      pageDataChangedSpy.restore()
+    })
+    it('doesnt calls ledgerApi.pageDataChanged when no idle state is provided', function () {
```
Comment (bbondy) [inline test/unit/app/browser/reducers/ledgerReducerTest.js]: nit: does not

File: test/unit/app/browser/reducers/ledgerReducerTest.js [hunk 5]
```diff
@@ -215,25 +215,38 @@ describe('ledgerReducer unit tests', function () {
...
+    it('calls ledgerApi.pageDataChanged when not in idleState', function () {
+      returnedState = ledgerReducer(appState, Immutable.fromJS({
+        actionType: appConstants.APP_IDLE_STATE_CHANGED,
+        idleState: 'notActive'
+      }))
       assert(pageDataChangedSpy.withArgs(appState).calledOnce)
     })
-    it('calls ledgerApi.addVisit', function () {
-      assert(addVisitSpy.calledOnce)
+    it('doesnt calls ledgerApi.pageDataChanged when in idleState', function () {
```
Comment (bbondy) [inline test/unit/app/browser/reducers/ledgerReducerTest.js]: nit does not or doesn\'t

File: app/common/lib/ledgerUtil.js [hunk 6]
```diff
@@ -18,49 +18,24 @@ const settings = require('../../../js/constants/settings')
...
  * Is page an actual page being viewed by the user? (not an error page, etc)
  * If the page is invalid, we don't want to collect usage info.
- * @param {Map} view - an entry from ['pageData', 'view']
- * @param {List} responseList - full ['pageData', 'load'] List
+ * @param {Map} tab - data about provided tab
  * @return {boolean} true if page should have usage collected, false if not
  */
-const shouldTrackView = (view, responseList) => {
-  if (view == null) {
+const shouldTrackView = (tab) => {
```
Comment (bbondy) [inline app/common/lib/ledgerUtil.js]: nit: please rename this to tab because we usually mean tab as the webContents in code.

File: app/browser/api/ledger.js [hunk 7]
```diff
@@ -913,23 +917,38 @@ const setLocation = (state, timestamp, tabId) => {
...
+  // We always want to have the latest active tabId
+  const currentTabId = pageDataState.getLastActiveTabId(state)
+  state = pageDataState.setLastActiveTabId(state, tabId)
   if (location === currentUrl) {
     return state
   }
 
-  state = setLocation(state, timestamp, tabId)
+  /*
+    Save previous recorder page
```
Comment (bbondy) [inline app/browser/api/ledger.js]: nit: * to align with other stars

File: app/browser/api/ledger.js [hunk 8]
```diff
@@ -913,23 +917,38 @@ const setLocation = (state, timestamp, tabId) => {
...
+      tab.isDestroyed() ||
+      !tab.session.partition.startsWith('persist:')
+
+    const tabFromState = tabState.getByTabId(state, currentTabId)
 
-  const lastUrl = pageDataState.getLastUrl(state)
-  const aboutUrl = getSourceAboutUrl(lastUrl) || lastUrl
-  if (aboutUrl && aboutUrl.match(/^about/)) {
-    state = pageDataState.resetInfo(state)
+    // add visit to the ledger when we are not in a private tab
```
Comment (bbondy) [inline app/browser/api/ledger.js]: nit comment style

File: app/browser/api/ledger.js [hunk 9]
```diff
@@ -913,23 +917,38 @@ const setLocation = (state, timestamp, tabId) => {
...
   }
 
-  location = getSourceAboutUrl(location) || location
+  if (location === locationDefault && !keepInfo) {
+    state = pageDataState.resetInfo(state)
+  }
 
-  currentUrl = (location && location.match(/^about/)) ? locationDefault : location
-  currentTimestamp = timestamp
+  // update to the latest view
```
Comment (bbondy) [inline app/browser/api/ledger.js]: nit comment style

File: app/browser/reducers/ledgerReducer.js (hunk 2 above)
Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: done

File: app/browser/reducers/ledgerReducer.js (hunk 1 above)
Comment (NejcZdovc) [reply app/browser/reducers/ledgerReducer.js]: done

File: app/extensions/brave/content/scripts/idleHandler.js (hunk 3 above)
Comment (NejcZdovc) [reply app/extensions/brave/content/scripts/idleHandler.js]: done

File: test/unit/app/browser/reducers/ledgerReducerTest.js (hunk 4 above)
Comment (NejcZdovc) [reply test/unit/app/browser/reducers/ledgerReducerTest.js]: done

File: test/unit/app/browser/reducers/ledgerReducerTest.js (hunk 5 above)
Comment (NejcZdovc) [reply test/unit/app/browser/reducers/ledgerReducerTest.js]: done

File: app/common/lib/ledgerUtil.js (hunk 6 above)
Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: done

File: app/browser/api/ledger.js (hunk 7 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

File: app/browser/api/ledger.js (hunk 9 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

File: app/browser/api/ledger.js (hunk 8 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

**Comment by NejcZdovc** [comment]
master 3cf6a5082f8fd03a5fe1e178130166a634fe44c1
0.21 2fa2f881637ed41281facd737174b469c8e821c8
0.20 820ed5b769378e379cee06226f0c06c08bb888d4
0.19 61c92a80e4704a450f1c9a23a2cf241c4bf4b154
