### PR TITLE
Fixed empty modal on payments

### LINKED ISSUE #11639: Backup Wallet notification shows no empty overlay modal
### Description
Backup Wallet notification shows no empty overlay modal

### Steps to Reproduce

  1. Install 0.18.36, enable payments
  2. Upgrade to 0.19.62
  3. No transition overlay is shown, Payment goes into bad state, shows wrong USD-BAT value 
  4. Wait till it shows the notification to  backup wallet
  5. click on Backup wallet button, shows empty modal
  6. Open preferences, ensure USD-BAT value is normal, shows proper recovery code

**Actual result:**

overlay

**Expected result:**
Should  show the transition overlay and show the backup code when clicked on notification

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

Brave | 0.19.62
-- | --
rev | fe3f350
Muon | 4.5.7

**Reproducible on current live release:**

### Additional Information

cc: @LaurenWags

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11639

Auditors:

Test Plan: specified in #11639

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by bsclifton** [comment]
@NejcZdovc I can't reproduce this original error.  When I use a session from 0.18.36 and then switch to 0.19.x (freshly npm installed), it correctly shows the transition.  I am seeing a different error, however:
```
TypeError: ledgerClient is not a function
    at fs.readFile (/Users/clifton/Documents/browser-laptop/app/browser/api/ledger.js:2398:21)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:439:3)
ledger client transition error:  SyntaxError: Unexpected token # in JSON at position 0
    at JSON.parse (<anonymous>)
    at request.request (/Users/clifton/Documents/browser-laptop/app/browser/api/ledger.js:1561:68)
    at Function.defaultSession.webRequest.fetch (/Users/clifton/Documents/browser-laptop/js/lib/request.js:55:5)
```
cc: @evq

File: app/browser/tabs.js [hunk 1]
```diff
@@ -134,6 +134,15 @@ const aboutTabUpdateListener = (tabId) => {
   }
 }
 
+const isOnAboutLocation = (url, search) => {
+  if (url == null) {
+    return false
+  }
+
+  const path = url.split('?')
+  return Array.isArray(path) && path[0] === search
```
Comment (bsclifton) [inline app/browser/tabs.js]: Nice! this is a great way to solve it 😄  For those who may not be aware, the link to the backup page is generated here:
https://github.com/brave/browser-laptop/blob/2d3fd8f19a09fb67a15115f2c073fa5ea8ffa976/app/browser/api/ledger.js#L248-L251

(Notice how the visible flag comes after the ?, which is what caused the original issue)

**Comment by bsclifton** [comment]
UPDATE: I cleared my profile, started with a fresh 0.18.36 one. After that, I was able to manually test the fix and confirm it works as expected 👍

**Comment by bsclifton** [comment]
master https://github.com/brave/browser-laptop/commit/811a5d41eb96d9a681d06398844ece3f3e28dc02
0.21.x https://github.com/brave/browser-laptop/commit/4001f5544e820c09e673c4d8858c571c18845b52
0.20.x https://github.com/brave/browser-laptop/commit/bafa261009eb51a451f8b7bceb7e39da543a1519
0.19.x https://github.com/brave/browser-laptop/commit/215b00b04b268cd020d6848cab2bd74082478aaa
