### PR TITLE
Using customTitle for folder of imported bookmark

### LINKED ISSUE #4280: Regression: Creating a second bookmark folder via bookmarks toolbar deletes the first.
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
When testing the bookmarks toolbar I found that creating a second folder deletes the first.

**Expected behavior:**
A user should be able to create as many bookmark folders as they like.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Tested on OS X and Windows 7 x64

- Brave Version:
0.12.2 RC4

- Steps to reproduce:
    1. On a fresh install, create a bookmarks folder via the context menu on the toolbar
    2. Create a second folder

- Screenshot if needed:
bookmark_folders

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

fix #4280

Auditors: @bbondy

Test Plan:
1. Create folder "test1" on bookmarks toolbar
2. Create folder "test2" on bookmarks toolbar
3. There should be "test1" and "test2" on bookmarks toolbar

1. Import bookmarks from the same browser twice
2. There should not exist any duplicate folders

### CODE REVIEW

File: js/state/siteUtil.js [hunk 1]
```diff
@@ -113,7 +113,7 @@ module.exports.addSite = function (sites, siteDetail, tag, originalSiteDetail) {
   if (!oldSite && tag === siteTags.BOOKMARK_FOLDER) {
```
Comment (bsclifton) [inline js/state/siteUtil.js]: Really stupid nitpick (sorry)- s/Remve/Remove :smile:

**Comment by bsclifton** [comment]
LGTM :smile:

File: js/state/siteUtil.js (hunk 1 above)
Comment (darkdh) [inline js/state/siteUtil.js]: Thanks. fixed it
