### PR TITLE
Whitespace in url fixes #3167

### LINKED ISSUE #3167: Brave can't handle URLs with whitespace in it
**Did you search for similar issues before submitting this one?**

Yes.

**Describe the issue you encountered:**
If you try to visit url, which has whitespace in it, Brave will assume you want to search via your default engine, not matter that the url starts with http or https. How I discovered this was just simply uploading an image with whitespace in it to postimage for another issue here. The generated url was this:

`https://s10.postimg.org/snp1s3aah/Screenshot+from 2016-08-13 17-50-27.png`

Now if you past this url in Chrome or FF they will actually visit this url, in Brave I get my default search engine queried.

I have rised a PR to fix this behaviour.

**Expected behavior:**
When I paste this url `https://s10.postimg.org/snp1s3aah/Screenshot+from 2016-08-13 17-50-27.png` in the url bar I expect to see the image.

- Platform (Win7, 8, 10? macOS? Linux distro?):
Every platform.

- Brave Version:
0.11.4
- Steps to reproduce:
    1.Paste `https://s10.postimg.org/snp1s3aah/Screenshot+from 2016-08-13 17-50-27.png` in the url bar
    2. Hit eneter

- Screenshot if needed:

- Any related issues:

### PR DESCRIPTION
**Pull request by Sh1d0w**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. #3167 
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

cc @bbondy @bridiver @bsclifton 

This PR allows to open valid URLs whith whitespace in it such as 

`https://s10.postimg.org/snp1s3aah/Screenshot+from 2016-08-13 17-50-27.png`

The original behaviour to query the search engine is preserved if you type a word or set of words. But if the string starts with scheme, no matter it has whitespace in it it will try to load the url.

What is the behaviour now?

| String typed in the url bar        | Before                  | Now                     |
|-----------------------------------|-------------------------|-------------------------|
| google.com                        | open https://google.com | open https://google.com |
| test                              | searches for test       | searches for test       |
| test test                         | searches for test test  | searches for test test  |
| `http://example.com/test image.jpg` | searches for `http://example.com/test image.jpg` via default search engine         | opens `http://example.com/test image.jpg`           |

### CODE REVIEW

File: js/components/urlBar.js [hunk 1]
```diff
@@ -108,7 +108,7 @@ class UrlBar extends ImmutableComponent {
           const isLocationUrl = isUrl(location)
           // If control key is pressed and input has no space in it add www. as a prefix and .com as a suffix.
           // For whitepsace we want a search no matter what.
```
Comment (neeklamy) [inline js/components/urlBar.js]: Should probably update this comment about whitespace and searching too.

File: js/lib/appUrlUtil.js [hunk 2]
```diff
@@ -130,7 +130,7 @@ module.exports.isTargetAboutUrl = function (input) {
  */
 module.exports.isUrl = function (input) {
```
Comment (bridiver) [inline js/lib/appUrlUtil.js]: @bbondy we should just get rid of this method and use UrlUtil

**Comment by bridiver** [comment]
Thanks for the PR! Can you add some unit tests for this in `urlUtilTest.js`? I'm also not sure this is 100% correct because while spaces are legal in the path (encoded as `%20`), they are not legal in a domain name or the scheme. `my protocol://blah`, `test domain.com`, `http: //domain.com`, etc..  should return `false` for `isUrl`

File: js/lib/appUrlUtil.js (hunk 2 above)
Comment (bbondy) [inline js/lib/appUrlUtil.js]: yes I agree it was only ever added here at some point because urlUtil used to be an external module we couldn't modify.

**Comment by Sh1d0w** [comment]
@bridiver You are completely right. I have fixed this behaviour and added tests as you requested.

File: js/lib/urlutil.js [hunk 3]
```diff
@@ -91,30 +91,40 @@ const UrlUtil = {
...
     // for cases, quoted strings
     const case1Reg = /^".*"$/
     // for cases, ?abc and "a? b" which should searching query
     const case2Reg = /^(\?)|(\?.+\s)/
     // for cases, pure string
     const case3Reg = /[\?\.\/\s:]/
-    // for cases, data:uri and view-source:uri
-    const case4Reg = /^\w+:.*/
+    // for cases, data:uri, view-source:uri and about
+    const case4Reg = /^data|view-source|about\:.*/
```
Comment (bridiver) [inline js/lib/urlutil.js]: I think those might just be examples and not an exhaustive list. We also have registered and app protocols like bitcoin, 1password, etc... @bbondy ?

**Comment by bridiver** [comment]
Thanks! Can you add just a few more tests to cover all the changes? The other cases I can think of are
1. multiple words
2. space in schema
3. an arbitrary registered protocol
if those pass I think this is good to merge

**Comment by bridiver** [comment]
can you do an `npm run lint` and fix any issues? The CI tests are failing on some lint issues

**Comment by Sh1d0w** [comment]
@bridiver I think linting is failing generally even on master, it is not a fault on my branch.

Can you please tell me what are the registered protocols for lastpass, bitcoint ect, so I can add them to the test as well? I believe they should invoke `chrome-extension://` protocol, no?

**Comment by bridiver** [comment]
at least some of the lint errors appear to be related to these changes https://travis-ci.org/brave/browser-laptop/builds/152446285
don't worry about any lint changes that are not related to you changes, but feel free to fix them :) 
I wouldn't worry too much about the exact protocols, but maybe add `chrome-extension` just to verify that `-` is valid for an extension. Maybe also check that `chrome extension://` fails?

**Comment by bridiver** [comment]
lint normally runs as a precommit hook on other platforms, but doesn't run on windows. I'm switching it to a pre-push hook that should work everywhere

**Comment by Sh1d0w** [comment]
@bridiver Fixed linting. Added few more test cases.

Let me know if you find anything else that seems not ok.

**Comment by bridiver** [comment]
Looks good! Just waiting for CI to finish and I'll merge if everything looks good there. I know some tests are broken in master right now so I'm only looking for yours to pass.

**Comment by Sh1d0w** [comment]
@bridiver Cool, thanks man!

**Comment by bridiver** [comment]
++
