### PR TITLE
status bar position fix

### LINKED ISSUE #1712: change "status bar" so that it can not be covered by downloads bar

### PR DESCRIPTION
**Pull request by luixxiul**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits if needed.

Close #1712

### CODE REVIEW

File: js/components/frame.js [hunk 1]
```diff
@@ -380,7 +380,8 @@ class Frame extends ImmutableComponent {
         case messages.LINK_HOVERED:
           method = (href, position) => {
             position = position || {}
-            let nearBottom = position.y > (window.innerHeight - 150) // todo: magic number
```
Comment (bbondy) [inline js/components/frame.js]: I don't think the changes in frame.js is necessary is it?

Comment (luixxiul) [inline js/components/frame.js]: Without this the status bar appears always left, even though the downloads bar is displayed. The value of the const is based on [this](https://github.com/brave/browser-laptop/blob/master/less/downloadBar.less#L21).

**Comment by bbondy** [comment]
Thanks for taking this, great work :)
