### PR TITLE
Fix sync-after-import-bookmark hierarchy

### LINKED ISSUE #8892: importing bookmarks after sync causes loss of hierarchy
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
I installed 0.15.304 on two different OS X laptops

- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS

- Brave Version (revision SHA):
0.15.304 (b872523)

- Steps to reproduce:
    1. with a clean profile for each, enable a new sync group on one device
    2. join the sync group with the other device
    3. import bookmarks on the primary device
    
- Actual result:
the folder hierarchy is lost versus if an import occurs without sync.

- Expected result:
the folder hierarchy should be maintained and the name should match the pattern 'imported from <browser name>'

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes

- Is this an issue in the currently released version?
likely

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
screen shot 2017-05-16 at 3 15 39 pm

- Any related issues:

### LINKED ISSUE #9404: sync records are sent twice
i accidentally ignored the skipSync field in #9308 

test plan:
1. start pyramid 0
2. sync pyramid 1 to pyramid 0
3. add some bookmarks to pyramid 1, wait for pyramid 0 to fetch the bookmarks
4. in the console, you should not see pyramid 0 sending the bookmarks that it just fetched

### LINKED ISSUE #9405: sync objectsById should be cleared when browser quits
since the cache gets rebuilt when sync starts, there is no need to write it to disk

test plan:
1. start pyramid 0, enable sync
2. bookmark some sites
3. close the browser
4. you should not see 'objectsById' in the session-store-1 file

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix #8892

Test plan:
1. Setup sync on pyramid 0 (desktop)
2. Sync pyramid 1 (desktop) to pyramid 0
3. Save the following as an HTML file and import it into pyramid 0 in about:bookmarks:
```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file. It will be read and overwritten. DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
  <DT><H3 PERSONAL_TOOLBAR_FOLDER="true">Bookmarks Bar</H3>
  <DL><p>
    <DT><A HREF="https://twitter.com/">Twitter. It's what's happening.</A>
    <DT><H3>abc</H3>
    <DL><p>
      <DT><A HREF="https://www.facebook.com/">Facebook - Log In or Sign Up</A>
    </DL><p>
  </DL><p>

</DL><p>
```
4. You should see an 'Imported' folder appear in Pyramid 0 with some bookmarks in it.
5. Wait for the bookmarks to sync to Pyramid 1. It should have the same folder structure as Pyramid 0.

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/sessionStore.js [hunk 1]
```diff
@@ -296,6 +296,10 @@ module.exports.cleanAppData = (data, isShutdown) => {
   if (data.dragData) {
     delete data.dragData
   }
+  if (data.sync) {
+    // clear sync site cache
+    data.sync.objectsById = {}
```
Comment (diracdeltas) [inline app/sessionStore.js]: fix #9405

File: app/sync.js [hunk 2]
```diff
@@ -95,6 +95,11 @@ const appStoreChangeCallback = function (diffs) {
     const entry = state.getIn(statePath)
     const isSite = type === 'sites'
 
+    if (action === writeActions.CREATE && entry && entry.get('skipSync')) {
+      // Don't re-create objects that were fetched by sync
+      return
```
Comment (diracdeltas) [inline app/sync.js]: fix #9405

**Comment by diracdeltas** [comment]
on second though, i'm going to split this into separate PRs

**Comment by diracdeltas** [comment]
@ayumi the test should be fixed now
