### PR TITLE
Fixes invalid url error

### LINKED ISSUE #12826: JS Error in Ledger code
### Description
```
Error: invalid url parameter at Object.module.exports.request (/Applications/Brave.app/Contents/Resources/app.asar/js/lib/request.js:41:29) at roundtrip (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:1302:11) at request.request (/Applications/Brave.app/Contents/Resources/app.asar/app/browser/api/ledger.js:1321:16) at Function.defaultSession.webRequest.fetch (/Applications/Brave.app/Contents/Resources/app.asar/js/lib/request.js:55:5)
```
Found in several crash reports (ex: https://stats.brave.com/dashboard#crash/5a68a022836579001fd85b25)

### Steps to Reproduce
Unknown STR

**Actual result:**
Error/Possible crash

**Expected result:**

**Reproduces how often:**
Unknown

### Brave Version
0.19.141

**Reproducible on current live release:**

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #12826

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

## Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: js/lib/request.js [hunk 1]
```diff
@@ -49,8 +49,15 @@ module.exports.request = (options, callback) => {
     })
   }
 
+  let urlParsed = null
+  try {
+    urlParsed = urlParse(options.url)
```
Comment (diracdeltas) [inline js/lib/request.js]: are you sure this fixes the crash?  `muon.url.parse` doesn't throw an error for most invalid URLs:

screen shot 2018-04-09 at 12 50 46 pm

if the crash is because the URL is undefined, you could just replace this check with `if (typeof options.url !== 'string') { return callback(new Error('URL is not valid')) }`. then we wouldn't need to do `url.parse` on the URL unless we are in development mode (https://github.com/brave/browser-laptop/pull/13722/files#diff-2565914e73f517d565765ef02f30d306R59)

**Comment by NejcZdovc** [comment]
master 1ec3da9
0.23 a26896999
0.22 593cae3ad
