### PR TITLE
Fix Brave crashing on confirm bug

### LINKED ISSUE #4883: [HackerOne] window.confirm crashes Brave
reported at https://hackerone.com/reports/176076, i can confirm (pun intended!) on mac.

PoC: http://pentesting.x10host.com

cc @bridiver

### PR DESCRIPTION
**Pull request by willy-b**
(Realized that this can be solved with exactly what @bridiver did for alerts in #4798, just copied for confirm dialog, so replacing previous PR I had with @bridiver's sol'n)

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist. #4883 
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
1. Open Brave
2. Visit http://pentesting.x10host.com (entire page content is: `<script>confirm(1)</script>`, so can test with `data:text/html,<script>confirm(1)</script>` as well)
3. Observe that Brave does not crash, and confirm dialog with message content "1" is displayed.

Fix:
- `dialog.showMessageBox` requires that the message and title arguments are strings
- make sure that when `message` is a  number (or other non-string type) it is coerced to a string
- exact same change as what @bridiver did for alerts in #4798, but for confirm dialog

fixes #4883

### CODE REVIEW

File: app/index.js [hunk 1]
```diff
@@ -383,6 +384,8 @@ app.on('ready', () => {
       title = ''
     }
```
Comment (bbondy) [inline app/index.js]: I think this can be removed now
```
if (title == null) {
    title = ''
}
```

**Comment by willy-b** [comment]
@bbondy, thanks for the review, I removed the extra lines. I can rebase and open a new PR or push directly to whatever branch you think is appropriate. Thanks!

**Comment by bbondy** [comment]
Perfect, I'll just do a squash merge, thanks.
