### PR TITLE
make tab previews based on mouse idle time

### LINKED ISSUE #3271: Don't show tab preview unless mouse velocity is low enough (and decelerating?)
## Test plan
See https://github.com/brave/browser-laptop/pull/9887

## Original issue description
**Did you search for similar issues before submitting this one?**

Yes. Related issues: #3113 #3149. Fixing this may relieve pressure on those, or not, TBD.

**Describe the issue you encountered:**

Tab previews are generally liked but most users I've talked to, but it's an unscientific sample and some users dislike them because they trigger too easily and cause flicker and distraction when moving the mouse over the tab bar.

**Expected behavior:**

When moving quickly enough, especially when accelerating away from the tab bar, no preview.
- Platform (Win7, 8, 10? macOS? Linux distro?):

All.
- Brave Version:

0.11.5
- Steps to reproduce:
  1. Open three tabs on three visually distinct pages.
  2. Mouse over the tabstrip quickly, make back and forth and ellipsoidal motions.
  3. See tab previews flicker quickly (too quickly to be useful).
- Screenshot if needed:
- Any related issues: #3113 #3149

### LINKED ISSUE #8860: Make tab preview based on mouse idle time
## Test plan
See https://github.com/brave/browser-laptop/pull/9887

After #12823 please add the NO DELAY (current name) as a check too for undelayed tab previews. Thanks!!

<hr>

## Original issue description
Sometimes tab preview happen unintentionally if you go from urlbar to webview. Tab previews are based on RegExp that checks which element has hovered before current tab preview. 

After taking #3271 this still seems to be the best approach currently but we need to cover other elements that were missing on initial implementation.

### PR DESCRIPTION
**Pull request by cezaraugusto**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Auditors: @bridiver
/cc @luixxiul for QA

Fix #8860
Fix #3271

Test Plan:

Previews are now happening based on mouse idle time. Which means that it will only be fired if you stay the mouse idle over a tab for a given amount of time -- which is defined in prefs->tabs.

The general test plan is to hover over a tab up to a point that the tab previews.

1. Switching to another tab should preview the tab;
2. Moving out of a tab should cancel preview;
3. After each tab leave you will have to wait for the timeout to happen again, so you can preview

For further manual tests please refer to https://github.com/brave/browser-laptop/pull/8852#issue-228194949

Automated tests:
```
npm run test -- --grep="webview previews the next tab when current hovered tab is closed"
npm run test -- --grep="webview previews when tab is hovered"
npm run test -- --grep="TabsTab component"
npm run test -- --grep="tabUtil hasTabAsRelatedTarget"
```

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/tabs/tab.js [hunk 1]
```diff
@@ -40,15 +41,16 @@ const contextMenus = require('../../../../js/contextMenus')
...
 const {isWindows} = require('../../../common/lib/platformUtil')
 const {getCurrentWindowId} = require('../../currentWindow')
 const UrlUtil = require('../../../../js/lib/urlutil')
-const {hasBreakpoint} = require('../../lib/tabUtil')
+const {getSetting} = require('../../../../js/settings')
 
 class Tab extends React.Component {
   constructor (props) {
     super(props)
+    this.onMouseMove = this.onMouseMove.bind(this)
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/tab.js]: @bridiver before sending this I debounced mouse move but even with 10ms it was leading to bad behavior and tabs were previewing without user action, given they were debounced. The event triggered inside onmousemove is canceled with both mouseenter and mouseleave, which I guess cover the event's cost.

File: app/renderer/components/tabs/tab.js [hunk 2]
```diff
@@ -128,12 +130,26 @@ class Tab extends React.Component {
...
+    // if mouse entered another tab, preview will happen
+    // as long as the previewMode is enabled
+    windowActions.setTabHoverState(this.props.frameKey, true, this.props.previewMode)
+  }
+
+  onMouseMove () {
+    // previewMode is only triggered if mouse is idle over a tab
+    // for a given amount of time based on timing defined in prefs->tabs
+    clearTimeout(this.mouseTimeout)
+    this.mouseTimeout = setTimeout(() => {
```
Comment (cezaraugusto) [inline app/renderer/components/tabs/tab.js]: @bridiver I had a hard time moving the delayed state update to frameStateUtil while trying to keep using setTabHoverState (without adding extra actions). 

afaict there's no way to delay state updates without calling an action inside the utils file? Even if so I guess per our convo we are trying to avoid that. If this is not unacceptable I would prefer to leave it as-is.

File: js/actions/windowActions.js [hunk 3]
```diff
@@ -243,20 +243,6 @@ const windowActions = {
   },
 
   /**
-   * Dispatches a message to the store to set a preview frame.
-   * This should only be called internally by `WINDOW_SET_TAB_HOVER_STATE`
-   * when we need to delay updating the preview frame value
-   *
-   * @param {Object} frameKey - the frame key for the webview in question.
-   */
-  setPreviewFrame: function (frameKey) {
```
Comment (cezaraugusto) [inline js/actions/windowActions.js]: we don't use it anymore. `frameStateUtilsetPreviewFrameKey(..args)` now checks for preview mode and returns if there is none. I guess the only use case for that was to delay tab previews for one use case, which we don't have anymore

File: app/renderer/components/tabs/tab.js (hunk 2 above)
Comment (bridiver) [inline app/renderer/components/tabs/tab.js]: we definitely don't want to add a timeout here because we handle that in frameStateUtil

Comment (bridiver) [inline app/renderer/components/tabs/tab.js]: I think the best thing to do here is add a `onTabMouseMoved` action

File: app/renderer/lib/tabUtil.js [hunk 4]
```diff
@@ -36,3 +36,8 @@ module.exports.hasBreakpoint = (breakpoint, arr) => {
   arr = Array.isArray(arr) ? arr : [arr]
   return arr.includes(breakpoint)
 }
+
+module.exports.hasTabAsRelatedTarget = (event) => {
+  const tabComponents = /tab(?=_|area|title|id)|closetab|icon/i
```
Comment (bridiver) [inline app/renderer/lib/tabUtil.js]: this seems fragile to me, we should probably be checking for children with something like https://stackoverflow.com/questions/4697758/prevent-onmouseout-when-hovering-child-element-of-the-parent-absolute-div-withou

**Comment by bbondy** [comment]
needs fixes and rebase so I'm going to move to 0.19.x

File: app/renderer/lib/tabUtil.js (hunk 4 above)
Comment (cezaraugusto) [inline app/renderer/lib/tabUtil.js]: I ended up checking for `parentNode` instead + nulling pointer events for elements I don't want to be triggered. That method is now tested too.

**Comment by cezaraugusto** [comment]
ok rebased + more tests added, ready for re review

File: docs/state.md [hunk 5]
```diff
@@ -667,6 +667,8 @@ WindowStore
       hoverTabIndex: number, // index of the current hovered tab
       tabPageIndex: number, // index of the current tab page
       previewTabPageIndex: number // index of the tab being previewed
+      previewTabPageIndex: number, // index of the tab being previewed
+      previewMode: boolean // whether or not tab preview should be fired based on mouse idle time
```
Comment (NejcZdovc) [inline docs/state.md]: can you please sort this alphabetically?

**Comment by bsclifton** [comment]
I'm getting an error when I test this branch... if I close the tab before it starts the preview:
```
[60162:775:0728/171725.327076:ERROR:CONSOLE(70233)] "Uncaught TypeError: frameStateUtil.getPreviewMode is not a function", source: http://localhost:8080/gen/app.entry.js (70233)
An uncaught exception occurred in the main process Uncaught Exception:
AssertionError: Could not find tab for 9
    at Object.getTabPropertyByTabId (/Users/clifton/Documents/browser-laptop/app/common/state/tabState.js:464:12)
    at Object.getWindowId (/Users/clifton/Documents/browser-laptop/app/common/state/tabState.js:470:21)
    at tabsReducer (/Users/clifton/Documents/browser-laptop/app/browser/reducers/tabsReducer.js:187:39)
    at reducers.reduce (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:385:24)
    at Array.reduce (<anonymous>)
    at applyReducers (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:383:68)
    at handleAppAction (/Users/clifton/Documents/browser-laptop/js/stores/appStore.js:428:14)
    at callbacks.forEach (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:97:7)
    at Array.forEach (<anonymous>)
    at AppDispatcher.dispatchToOwnRegisteredCallbacks (/Users/clifton/Documents/browser-laptop/js/dispatcher/appDispatcher.js:96:20)
```

Also, the preview time seems really high- I'm used to a lightning quick preview.  This branch is making me wait ~3 seconds before the preview is shown

**Comment by cezaraugusto** [comment]
@bsclifton thanks for checking, I updated [a line](https://github.com/brave/browser-laptop/pull/9887/files#diff-e12cc9b3579286a186d0f0c82dfa8186R41) in `frameReducer` without pushing, should be addressed now. 

re: preview timing that was defined by Brad and can be changed by the user in under prefs->tabs. We have three options to choose from, being "long" the default.

**Comment by luixxiul** [comment]
ready for manual test?

**Comment by cezaraugusto** [comment]
yes ready for review

**Comment by luixxiul** [comment]
@cezaraugusto mind rebasing? thanks!

**Comment by cezaraugusto** [comment]
moving to 0.20.x per triage meeting

**Comment by bradleyrichter** [comment]
@bsclifton @cezaraugusto We should use Normal as the default.

**Comment by cezaraugusto** [comment]
ok changed default to NORMAL

**Comment by Jacalz** [comment]
@cezaraugusto could you add an even shorter timing? The shortest time feel too slow, I want to have it as fast as it was before this pr :-1: Great job otherwise :+1:

**Comment by Jacalz** [comment]
It was instant before and I liked that and I think many users liked that, maby a setting called no delay?

**Comment by cezaraugusto** [comment]
@Jacalz I think that's something we should consider

cc @bradleyrichter

**Comment by Jacalz** [comment]
Any news about the no timing mode? I really hate having to wait for tab previews 👎
Should I open an issue for it? 🙂

**Comment by bradleyrichter** [comment]
Agree! Let’s include an instant setting to retain the original feel. 

We might want to consider using that setting for existing users who have previews enabled.

**Comment by cezaraugusto** [comment]
by now you can change to SHORT under prefs->tabs->time to wait before previewing a tab

but ya feel free to open an issue

**Comment by cezaraugusto** [comment]
@Jacalz do you mind opening an issue for this? pls cc me in there let's do it

**Comment by Jacalz** [comment]
Will do 👍

**Comment by Jacalz** [comment]
The short time is too long for me 😅

**Comment by Jacalz** [comment]
Opened the issue for you @cezaraugusto 👍
