### PR TITLE
use data urls for brave extension because chrome-extension urls don't…

### LINKED ISSUE #1656: About page favicon
They were originally added here:
https://github.com/brave/browser-laptop/issues/898#issuecomment-218091747

Maybe broken with extensions @bridiver

### PR DESCRIPTION
**Pull request by bridiver**
… load correctly

fixes #1656

### CODE REVIEW

File: app/extensions.js [hunk 1]
```diff
@@ -54,7 +54,8 @@ let generateBraveManfiest = () => {
       'default-src': '\'self\'',
       'form-action': '\'none\'',
       'referrer': 'no-referrer',
-      'style-src': '\'self\' \'unsafe-inline\''
+      'style-src': '\'self\' \'unsafe-inline\'',
+      'img-src': '\'self\' data:'
```
Comment (bbondy) [inline app/extensions.js]: wouldn't it be possible just to specify the file path of the icon instead?

Comment (bridiver) [inline app/extensions.js]: the loading issue actually has nothing to do with CSP, this was just required to allow the data urls

**Comment by bbondy** [comment]
lgtm
