### PR TITLE
Fix styling of bookmarksToolbar.js

### LINKED ISSUE #12066: Fix bookmarksToolbar styling
### Description

Fix bookmarksToolbar styling.

### Brave Version

**about:brave info:**

c5186d5829e6aa5cd18ec3d6b125aaa4c9d810fe

**Reproducible on current live release:**

Yes.

### PR DESCRIPTION
**Pull request by luixxiul**
Also:
- Remove bookmarksToolbar.less (it is no longer necessary after #11530; See https://github.com/brave/browser-laptop/commit/405b0a4c4dda2be8e98f26e9f198f557ef9ce6de#diff-474538b5e876b82157a7e1b6228743e8)
- Specify the overflow indicator size

Closes #12066

Auditors: @cezaraugusto

Test Plan:
1. Add bookmarks as many as you see the overflow indicator on the bookmarks toolbar
2. Open about:preferences
3. Switch 'Bookmarks Bar' settings
4. Change the browser window's width
5. Make sure you see the overflow indicator on every setting

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/bookmarks/bookmarksToolbar.js [hunk 1]
```diff
@@ -223,30 +220,21 @@ const styles = StyleSheet.create({
...
   },
-  bookmarksToolbar__bookmarkButton: {
-    boxSizing: 'border-box',
-    fontSize: '14px',
-    height: 'auto',
-    lineHeight: '12px',
-    marginLeft: 'auto',
-    marginRight: '5px',
-    width: 'auto',
-    userSelect: 'none'
```
Comment (luixxiul) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: These values are taken care of `<BrowserButton>`.

File: app/renderer/components/bookmarks/bookmarksToolbar.js [hunk 2]
```diff
@@ -181,37 +180,35 @@ class BookmarksToolbar extends React.Component {
...
-              bookmarkKey={bookmarkKey} />)
+              bookmarkKey={bookmarkKey}
+            />)
       }
       {
         this.props.hiddenBookmarks.size !== 0
         ? <BrowserButton
           bookmarksOverflowIndicator
+          iconOnly
+          size='14px'
```
Comment (luixxiul) [inline app/renderer/components/bookmarks/bookmarksToolbar.js]: https://github.com/brave/browser-laptop/pull/12067/files#diff-49b40c07650f6f7cedce3f608d031b54L237

**Comment by petemill** [comment]
Moved to 0.22.x release 3 in order to ease merging of #13758
