### PR TITLE
Removed default highlight for context menu

### LINKED ISSUE #6867: First option in Menu/Hamburger is selected by default
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
New Tab option in kabob/hamburgermenu is highlighted by default

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.0
rev	ebea72a
Verified not happening on RC6 

- Steps to reproduce:
    1. Do a clean install of 0.13.0 RC7
    2. Click on the kabob/hamburger menu
    3. New Tab option is highligted by default
    
- Actual result:
New Tab option is highlighted by default

- Expected result:
None of the options should be highlighted by default and should only highlight on mouse over

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
rc7

- Any related issues:

### PR DESCRIPTION
**Pull request by NejcZdovc**
- [ ] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [ ] Ran `git rebase -i` to squash commits (if needed).

Resolves #6867

Auditors:
@bsclifton @bbondy

Test Plan:
-specified in #6867

### CODE REVIEW

File: test/components/contextMenuTest.js [hunk 1]
```diff
@@ -122,7 +122,7 @@ describe('ContextMenu', function () {
         .keys('\uE007')
         .pause(10)
         .tabByUrl(this.formfill)
-        .getValue(this.input).should.eventually.be.equal(this.values[3])
+        .getValue(this.input).should.eventually.be.equal(this.values[2])
     })
 
     it('check left/right on non sub menu item', function *() {
```
Comment (bbondy) [inline test/components/contextMenuTest.js]: The puase() calls should not be needed by the way, you should instead wait on some element state like a class name. The pause will fail intermittently if it is required.   It was already there though so I'll merge this.  Thanks!

**Comment by bbondy** [comment]
++

**Comment by bsclifton** [comment]
++
