### PR TITLE
Prevent firing updatePinnedTabs repeatedly for the same state/window combination

### LINKED ISSUE #11861: Pinning tabs with multiple windows open results in duplicates
### Description
Pinning tabs often causes those tabs to be pinned multiple times, especially if there is more than 1 window open. This is likely because `updatePinnedTabs` fires cyclically, i.e:
	1. A tab is pinned in windowA
	2. updatePinnedTabs is called to ensure all other windows get the pinned tabs
	3. windowB has the tab pinned, which causes…
	4. updatePinnedTabs to be called
        5. State is not necessarily up to date, so windowB or windowC gets the tab pinned again

### Steps to Reproduce

  1. Open window1
  2. Open window2
  3. Open a tab in window1
  4. Pin a tab in window1

This can then cause some weird errors when a window's tab state is out of sync with what it should have.

**Actual result:**
  - The tab is pinned twice in window2 and once in window1

**Expected result:**
 - The tab is pinned once in window2 and once in window1

**Reproduces how often:**

### Brave Version

**about:brave info:**
master (0.22)

**Reproducible on current live release:**
No

### PR DESCRIPTION
**Pull request by petemill**
Fix #11861 (and #12377)

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

### Steps to Reproduce

  1. Open window1
  2. Open window2
  3. Open a tab in window1
  4. Pin a tab in window1

This can then cause some weird errors when a window's tab state is out of sync with what it should have.

**Expected result:**
 - The tab is pinned once in window2 and once in window1

**Previous actual result:**
  - The tab is pinned twice in window2 and once in window1

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/browser/windows.js [hunk 1]
```diff
@@ -72,19 +75,26 @@ const siteMatchesTab = (site, tab) => {
   return matchesLocation && matchesPartition
 }
 
-const updatePinnedTabs = (win) => {
+const updatePinnedTabs = (win, appState) => {
```
Comment (NejcZdovc) [inline app/browser/windows.js]: not sure why we are passing state in, which we get in the same way as we did before?

Comment (petemill) [reply app/browser/windows.js]: Seems like a better practice and more consistent with the way other functions are structured. Plus it avoids calling AppStore.getstate multiple times in a row for multiple windows (though yes I know it is a very cheap function) and it feels cleaner and easier to test. Plus I’m not sure at all why the function had the AppStore require inside the function before...?? Was it to stop the module from being evaluated in case it wasn’t ever required in the process (I can’t imagine that happening)

File: app/browser/windows.js [hunk 2]
```diff
@@ -92,15 +94,22 @@ const updatePinnedTabs = (win) => {
...
-  let pinnedWindowTabs = getPinnedTabsByWindowId(state, windowId)
+  const statePinnedSites = pinnedSitesState.getSites(appState)
+  // no need to continue if we've already processed this state for this window
+  if (windowPinnedTabStateMemoize.get(win) === statePinnedSites) {
+    return
+  }
+  // cache that this state has been updated for this window,
+  // so we do not repeat the operation until
+  // this specific part of the state has changed
+  // See
```
Comment (bsclifton) [inline app/browser/windows.js]: looks like your comment just drops off here 😛

**Comment by bsclifton** [comment]
master 5d78c1ca8ed98314986a2b73b7e4c6fc0bade2a2
0.21.x 83958edc8371e3bf1e60a14b0a41e1b8b8c7d6d7
0.20.x a718cb866bb0fad97f11cf343a864f3732c5950a
