### PR TITLE
Normalize the sortableTable on about:preferences

### LINKED ISSUE #10356: Fix the wrong spacing around the per cent number on ledger panel
**Describe the issue you encountered:** Polish pinnedInput.js

- Platform (Win7, 8, 10? macOS? Linux distro?): All

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Run `npm run add-simulated-synopsis-visits 100`
    2. Open about:preferences#payments
    3. Pin some sites
    
- Actual result:
  screenshot 2017-08-09 18 48 31

- Expected result: the padding and margin around the input area should be normalized.

- Extra QA steps:
    1.
    2.
    3.

- Any related issues:

### PR DESCRIPTION
**Pull request by luixxiul**
**This blocks #10951**

Addresses #10263
Addresses #10788
Closes #10356

- Polish action icons
- Polish verified icon placement
- Remove alignRight from the sites column (it should be aligned to the left as default)
- Align the include switches to the center
- Align the action buttons to the center

Regression Test:
- Make sure a fix for https://github.com/brave/browser-laptop/issues/11978 does not regress
- Make sure a fix for https://github.com/brave/browser-laptop/issues/11960 does not regress
- Make sure https://github.com/brave/browser-laptop/issues/11942 does not regress

Test Plan:
1. Visit https://www.youtube.com/user/latenight
2. Open about:preferences#payments
3. Make sure the channel title is aligned to the left

Test Plan 2:
1. Run `npm run add-simulated-synopsis-visits 100`
2. Open about:preferences#payments
3. Pin some entries
4. Make sure the table is properly displayed

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 1]
```diff
@@ -113,11 +113,11 @@ class LedgerTable extends ImmutableComponent {
   get columnClassNames () {
     return [
       css(styles.alignRight, styles.verifiedTd), // verified
-      css(styles.alignRight), // sites
-      css(styles.alignLeft),  // include
+      css(styles.alignRight, styles.column_sites), // sites
+      css(styles.alignCenter),  // include
```
Comment (NejcZdovc) [inline app/renderer/components/preferences/payment/ledgerTable.js]: was this done intentionally? we are not using align center anywhere else

Comment (luixxiul) [reply app/renderer/components/preferences/payment/ledgerTable.js]: It is intentional as the switches are aligned to the center as well.

Comment (luixxiul) [reply app/renderer/components/preferences/payment/ledgerTable.js]: Check the case like this:

Before:
screenshot 2017-09-11 16 57 40

After:
screenshot 2017-09-11 16 57 17

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 2]
```diff
@@ -3,7 +3,7 @@
  * You can obtain one at http://mozilla.org/MPL/2.0/. */
 
 const React = require('react')
-const {StyleSheet, css} = require('aphrodite')
+const {StyleSheet, css} = require('aphrodite/no-important')
```
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/ledgerTable.js]: w00t beautiful

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 3]
```diff
@@ -213,15 +213,22 @@ class LedgerTable extends ImmutableComponent {
         value: percentage
       },
       {
-        html: <span>
-          <span className={css(styles.mainIcon, styles.pinIcon, pinned && styles.pinnedIcon)}
+        html: <div className={css(styles.actionIcons)}>
+          <span className={css(
+            styles.actionIcons__icon,
+            styles.actionIcons__icon_pin,
+            pinned && styles.actionIcons__icon_pin_pinned
```
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/ledgerTable.js]: nit: this could be `styles.actionIcons__icon_pin_isPinned`

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 4]
```diff
@@ -350,11 +357,18 @@ const styles = StyleSheet.create({
   },
 
   verifiedTd: {
-    padding: '0 0 0 15px'
+    // Set the same padding with the padding-top and padding-bottom
+    paddingRight: '.3ch !important',
```
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/ledgerTable.js]: I like using `ch` units for width/height but for padding seems obscure. Let me know your thoughts on why this

Comment (luixxiul) [reply app/renderer/components/preferences/payment/ledgerTable.js]: it sounds fair. I will revisit the padding values of sortable table to see which one works most properly.

**Comment by luixxiul** [comment]
@cezaraugusto I've reset the padding with consts: `globalStyles.sortableTable.cell.normal.padding` and `globalStyles.sortableTable.cell.small.padding`.

**Comment by cezaraugusto** [comment]
blocking now until 0.19.x

**Comment by luixxiul** [comment]
This blocks #10951
