### PR TITLE
Keep bookmarked entries on history

### LINKED ISSUE #6160: Bookmarking a site removes entry from history
**Did you search for similar issues before submitting this one?**
yes

**Describe the issue you encountered:**
Bookmarking a visited site removes it from about:history

**Expected behavior:**
Bookmark action should not remove its history entry

- Platform (Win7, 8, 10? macOS? Linux distro?): all

- Brave Version: master (0.13.0)

- Steps to reproduce:
    1. Visit a site
    2. Go to about:history and ensure site is there
    3. Bookmark
    4. Entry is removed

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Auditor: @bsclifton, @darkdh

Fix #6160

Test plan:

Automated tests must pass
```
npm run test -- --grep="returns newSiteDetail value for lastAccessedTime when oldSite value is undefined"
```
```
npm run test -- --grep="returns oldSiteDetail value for lastAccessedTime when newSite value is undefined"
```

Manual tests:

1. Visit a site
2. Go to `about:history` and check entry is there
3. Bookmark that site
4. Entry should still be visible on `about:history`
5. Bookmark `about:history`
6. History should be bookmarked (but not visible on about:history as we don't store about pages)

### CODE REVIEW

**Comment by darkdh** [comment]
We should add this case into
```
siteUtil
    addSite
      for new entries (oldSite is null)
        when adding history
```

**Comment by bsclifton** [comment]
Great fix, @cezaraugusto :smile: Only thing I can add is a +1 for @darkdh's comment for adding a test

**Comment by bsclifton** [comment]
@cezaraugusto does this also fix https://github.com/brave/browser-laptop/issues/5413?

**Comment by cezaraugusto** [comment]
@bsclifton not really, that one happens due to our [site's counter](https://github.com/brave/browser-laptop/blob/master/js/state/siteUtil.js#L136). There's an inconsistency between the moment we add a bookmark, the fix is on the way.

File: test/unit/state/siteUtilTest.js [hunk 1]
```diff
@@ -286,6 +286,14 @@ describe('siteUtil', function () {
           assert.equal(!!processedSites.getIn([0, 'lastAccessedTime']), true)
           assert.deepEqual(processedSites.getIn([0, 'tags']).toJS(), [])
         })
+        it('returns true for bookmarked entries', function () {
+          const siteDetail = Immutable.fromJS({
+            location: testUrl1,
+            lastAccessedTime: 123,
+            tags: [siteTags.BOOKMARK]
+          })
```
Comment (darkdh) [inline test/unit/state/siteUtilTest.js]: I guess you might forgot to call `addSite` for this siteDetail and you may need to leverage previous `processedSites` as first argument.

Comment (bsclifton) [inline test/unit/state/siteUtilTest.js]: @cezaraugusto the above mention by @darkdh is correct; we need to actually call `addSite` (which then calls `mergeSiteDetails`, where the change was made).  When you call `addSite`, you'll want to make a test case for each value.  Where it returns:
- lastAccessedTime = newSiteDetail.get('lastAccessedTime')
- lastAccessedTime = oldSiteDetail.get('lastAccessedTime')
- lastAccessedTime = 0

Comment (cezaraugusto) [inline test/unit/state/siteUtilTest.js]: ok thanks, added one for oldSites and one for newSites. Case for `lastAccessedTime = 0` [was already covered](https://github.com/cezaraugusto/browser-laptop/blob/5f63ca3fa881e3602f68e37058792aa87a78c233/test/unit/state/siteUtilTest.js#L284) by @darkdh, since it's the same case AFAIU, I left it as-is.

**Comment by darkdh** [comment]
lgtm

**Comment by bsclifton** [comment]
[CI had 2 errors](https://travis-ci.org/brave/browser-laptop/builds/190872271); I re-ran both of those locally and they both passed. Merging :smile:
