### PR TITLE
Fixes add funds dialog

### LINKED ISSUE #12078: add funds dialog shows up even if I have BAT already
## Test plan
See https://github.com/brave/browser-laptop/pull/12154

## Original issue description
v0.19.95

I got this message from time to time
image

even though if I click on add funds button, I do have some BAT in the brave wallet
image

### PR DESCRIPTION
**Pull request by NejcZdovc**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #12078

Auditors:

also added unit test for it

## Test Plan:

steps based on comment: https://github.com/brave/browser-laptop/issues/12078#issuecomment-348343208

1) Clean profile
2) start browser with staging server
```
LEDGER_ENVIRONMENT=staging npm run start
```
3) Enable payments
4) Visit some sites so that you have a few ledger entries showing on the Payments tab
5) Fund wallet (ex: claim UGP grant)
6) Close Brave
7) Update `reconcileStamp` in `ledger-state.json` to the epoch for now (or a time in the past). ([This site](https://www.freeformatter.com/epoch-timestamp-to-date-converter.html) is handy for conversions)
8) Launch Brave again using
```
LEDGER_NO_FUZZING=true LEDGER_VERBOSE=true LEDGER_ENVIRONMENT=staging npm run start
```
9) Wait for contribution to be made
10) "Needs deposit" notice should NOT show

## Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledgerNotifications.js [hunk 1]
```diff
@@ -42,8 +42,8 @@ const nextAddFundsTime = 3 * ledgerUtil.milliseconds.day
 const sufficientBalanceToReconcile = (state) => {
   const balance = Number(ledgerState.getInfoProp(state, 'balance') || 0)
   const unconfirmed = Number(ledgerState.getInfoProp(state, 'unconfirmed') || 0)
-  const bat = ledgerState.getInfoProp(state, 'bat')
-  return bat && (balance + unconfirmed > 0.9 * Number(bat))
+  const budget = parseInt(getSetting(settings.PAYMENTS_CONTRIBUTION_AMOUNT), 10) || 25
+  return balance + unconfirmed >= budget
```
Comment (bsclifton) [inline app/browser/api/ledgerNotifications.js]: The prior code that does `getInfoProp(state, 'bat')`... but I'm not seeing anything which sets this.  I think the field name must have been updated from `bat` to `converted` at some point.  

Why this is important: because ledgerUtil does something similar (in fact, maybe this code can be moved to ledgerUtil?):
https://github.com/brave/browser-laptop/blob/567746835c6c70b1fe2ceecd092953d6d22547df/app/common/lib/ledgerUtil.js#L99-L101

The code in ledgerUtil may have a problem too if nothing is setting this value

Comment (NejcZdovc) [reply app/browser/api/ledgerNotifications.js]: we need to fix this line as well, we don't have `bat` anymore

Comment (bsclifton) [reply app/browser/api/ledgerNotifications.js]: @NejcZdovc OK great- did you want to do that here also?

Comment (NejcZdovc) [reply app/browser/api/ledgerNotifications.js]: yeah will fix it in this PR

Comment (NejcZdovc) [reply app/browser/api/ledgerNotifications.js]: fixed, @bsclifton please re-review

**Comment by bsclifton** [comment]
master 8c3ef5e23527baea4f4101635fcae184d83a73e6
0.21.x 9a3ced401bc40ba011a7d7aeb1026be99ec36f7c
0.20.x 893bfa43a8c592176e35898938c3d7f93ae72201
0.19.x 7394478df1cd283c32386db959298937449c41af

**Comment by srirambv** [comment]
Works on Windows. No `Waiting for a deposit` notification shown.
