### PR TITLE
Fixes qr code when it is new

### LINKED ISSUE #12592: sometimes displayed Brave wallet address and QR code do not have the same value
### Description
Originally reported with https://github.com/brave/browser-laptop/issues/12170 but another scenario was found in https://github.com/brave/browser-laptop/issues/12170#issuecomment-350373166 - this issue is for the additional scenario

### Steps to Reproduce

1. Have a wallet created.
2. Close Brave.
3. Delete your ledger* files and folders from ~/Library/Application Support/brave
4. Reopen Brave
5. New wallet is created.
6. QR code does not match displayed wallet address..

**Actual result:**
QR code does not match displayed wallet address:
image

**Expected result:**
Wallet address and QR code should match

**Reproduces how often:**
Easily

### Brave Version

**about:brave info:**
Brave | 0.19.131
rev | da2f347
Muon | 4.5.36
libchromiumcontent | 63.0.3239.132

**Reproducible on current live release:**
yes

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).
- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review). (Ask a Brave employee to help if you cannot access this document.)

Resolves #12592

Auditors:

Test Plan: defined in #12592 

Reviewer Checklist:

- [ ] Request a security/privacy review [as needed](https://github.com/brave/handbook/blob/master/development/security.md#how-to-request-a-security-review) if one was not already requested.

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -1702,6 +1706,15 @@ const onCallback = (state, result, delayTime) => {
     return state
   }
 
+  const newAddress = result.getIn(['properties', 'wallet', 'addresses', 'BAT'])
+  const oldAddress = ledgerState.getInfoProps(state).getIn(['addresses', 'BAT'])
+
+  console.log(newAddress, oldAddress)
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: whoops- looks like you left a console log in there 😄

Comment (NejcZdovc) [reply app/browser/api/ledger.js]: console removed

**Comment by bsclifton** [comment]
master 1181d07af647e5bc48bb8764bc125af5eb1ba5bf
0.21.x 52e6c73b4b3031e0f0b02692fafb39b62c797f34
0.20.x f67993061aed9ba731cab8bf6451e2c4f0ece405
