### PR TITLE
Notify users when autoplay has been blocked and provide option to allow it

### LINKED ISSUE #8738: Video doesn't play when opened
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Video doesn't play when opened

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.15.3
rev	1c04c53

- Steps to reproduce:
    1. Clean install 0.15.3 Preview 3
    2. Open a new tab and click on the YouTube tile
    3. Video buffers and after a min shows message `If playback doesn't start, try restarting your device` instead of playing the video immediately after loading the page
    
- Actual result:
Video doesn't autoplay

- Expected result:
Should play video when the link is opened

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
No

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
youtube

- Any related issues:
#2227 #4045 #7663
cc: @jonathansampson @darkdh @bridiver

### LINKED ISSUE #8739: Disable autoplay tracking ticket
**Describe the issue you encountered:**

- [x] This video should play when you press the play button regardless of how autoplay is set for this page. https://github.com/brave/browser-laptop/issues/8739#issuecomment-302284448 #8897

When autoplay disabled:
- [x] Let users understand that autoplay is disabled by default by adding layer/placeholder (like flash object) for example
    - enabling autoplay on the placeholder should not reload the whole page
- [ ] Stop downloading of video (saving data consumption is one of the main reasons to disable autoplay)
    - If it is not possible, do not reload the page when the switch is changed. It just consumes the data double.

Also:
- [x] Change "Allow Autoplay Media" with disabled by default into "**Block Autoplay Media**" with enabled by default (this is a suggestion from a viewpoint of switch consistency and UX; on the other switches the state "on" means "block", while on the autoplay switch the state "on" means "unblock")

----

- Platform (Win7, 8, 10? macOS? Linux distro?): Debian

- Brave Version (revision SHA): master branch

- Steps to reproduce:
    1. Open any youtube video
    2. Click the top right lion icon

- Extra QA steps:
    1.
    2.
    3.

- Any related issues: #8738 #8847 #2227

### PR DESCRIPTION
**Pull request by darkdh**
Display "Block autoplay" in bravey shield

Fix #8738
Address #8739

Auditors: @bbondy, @bsclifton, @jonathansampson

Test Plan:
Covered by automatic test

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
screen shot 2017-05-07 at 9 57 12 pm

### CODE REVIEW

**Comment by darkdh** [comment]
fixed in b8fc59ced4e99f30f2e2f726753d3b4a743b1ddd

**Comment by luixxiul** [comment]
@darkdh I changed #8739 into a tracking issue, so would you mind removing `Fix #8739` from your commit message? thanks!

**Comment by darkdh** [comment]
ok, done

File: js/actions/appActions.js [hunk 1]
```diff
@@ -1292,6 +1292,19 @@ const appActions = {
...
+  },
+
+  /**
+   * Notifies autoplay has been blocked
+   * @param {string} location - Location of current frame
+   * @param {number} tabId - Tab id of current frame
+   */
+  autoplayBlocked: function (location, tabId) {
+    AppDispatcher.dispatch({
+      actionType: appConstants.APP_AUTOPLAY_BLOCKED,
```
Comment (bbondy) [inline js/actions/appActions.js]: not blocking merging, but why is location needed here?

Comment (darkdh) [inline js/actions/appActions.js]: It is for displaying origin for message box
https://github.com/brave/browser-laptop/pull/8751/files#diff-d4f09c262fdb2f86d8f7407afb926c8eR19

Comment (bbondy) [inline js/actions/appActions.js]: I just mean that the browser process already has this info so it is not needed to send from the window renderer. Pls do for a follow up but not high priority.

Comment (bbondy) [inline js/actions/appActions.js]: Basically it just leaves the chance that someone will use the API wrongly at some point, so better not to include it.

**Comment by bbondy** [comment]
++

File: js/actions/appActions.js (hunk 1 above)
Comment (darkdh) [inline js/actions/appActions.js]: will do

File: app/browser/reducers/autoplayReducer.js [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+      if ((parsedUrl.protocol === 'https:' || parsedUrl.protocol === 'http:')) {
+        ruleKey = `https?://${parsedUrl.host}`
+      }
+      if (buttonIndex === 0) {
+        appActions.changeSiteSetting(ruleKey, 'noAutoplay', false)
+
+        if (tabId) {
+          const tab = webContents.fromTabID(tabId)
+          if (tab && !tab.isDestroyed()) {
+            return tab.reload()
```
Comment (bsclifton) [inline app/browser/reducers/autoplayReducer.js]: What is being returned here?

File: js/constants/appConfig.js [hunk 3]
```diff
@@ -36,8 +36,8 @@ module.exports = {
   cookieblock: {
     enabled: true
   },
-  autoplay: {
-    enabled: false
+  noAutoplay: {
+    enabled: true
```
Comment (bsclifton) [inline js/constants/appConfig.js]: Per our discussions, we want to default this to false, right?  So that content isn't blocked
cc: @bradleyrichter

Comment (darkdh) [inline js/constants/appConfig.js]: If the default is false, the notification won't popup in most of the cases because https://github.com/brave/browser-laptop/pull/8751/files#diff-d4f09c262fdb2f86d8f7407afb926c8eR21
The only case it will show up is users toggle global autoplay to block and without site setting of autoplay to the website

The setting is similar to our default `fullscreen` setting.

Comment (bbondy) [inline js/constants/appConfig.js]: I was under the understanding we were defaulting to on with notification bar.

Comment (bsclifton) [inline js/constants/appConfig.js]: My mistake- I think I missed part of the convo 😄  ++

File: app/browser/reducers/autoplayReducer.js (hunk 2 above)
Comment (darkdh) [inline app/browser/reducers/autoplayReducer.js]: will do a follow-up along with
https://github.com/brave/browser-laptop/blob/b2618c911863b7930b054b3f6562224d6acf3cbe/js/flash.js#L83
