### PR TITLE
block access to fingerprinting methods pulled from child frames issue #11683

### LINKED ISSUE #11683: Fingerprinting protections bypassable
## Test plan

----

### Description
Many of the current fingerprinting protections rely on removing references to methods from the global object.  However, you can get alternate references to the same methods by inserting a configured iframe element and grabbing the references off `iframe.contentWindow` or `iframe.contentDocument`.

### Steps to Reproduce
```
//blocked
console.log(HTMLCanvasElement.prototype.toDataURL);

let iframe = document.createElement("iframe");
iframe.src = "https://www.brave.com/";
document.body.appendChild(iframe);

// Not blocked
console.log(iframe.contentWindow.HTMLCanvasElement.prototype.toDataURL);

// Do the bad stuff
let canvasToDataUrl = iframe.contentWindow.HTMLCanvasElement.prototype.toDataURL;
canvasToDataUrl.apply(someParentFrameCanvasElement);
```

**Actual result:**
You can get references to the fingerprinting related methods.

**Expected result:**
You shouldn't be able to get to these methods.

**Reproduces how often:** 100%

### Brave Version
All versions

**Reproducible on current live release:**
Yes

### PR DESCRIPTION
**Pull request by snyderp**
@diracdeltas 

This PR fixes #11683.  The fix is a little funky, since it requires injecting JS into child pages (the `chrome.webFrame.setGlobal` method wont work here, since we need to call to `Object.definePropery`) but it should be good.

Added a `blocking access to fingerprinting methods on iframe.contentWindow` test to test that things are actually getting blocked

### CODE REVIEW

File: app/extensions/brave/content/scripts/blockCanvasFingerprinting.js [hunk 1]
```diff
@@ -267,4 +267,29 @@ if (chrome.contentSettings.canvasFingerprinting == 'block') {
...
+    (function () {
+        var frameTypesToModify = [window.HTMLIFrameElement, window.HTMLFrameElement]
+        var propertiesToBlock = ["contentDocument", "contentWindow"]
+        var proxyObject = window.HTMLCanvasElement.prototype.toDataURL;
+        var returnProxyGetter = {
+          get: function () {
+            return proxyObject()
+          }
+        }
+
```
Comment (diracdeltas) [inline app/extensions/brave/content/scripts/blockCanvasFingerprinting.js]: minor: line ends in whitespace

**Comment by snyderp** [comment]
@diracdeltas fixed the white space issue (and removed the semicolons, I know you all don't use them), and re-squashed.  I think this should be good, as far as I know

**Comment by bbondy** [comment]
master: d1b6b52a96e72100e40f9913f41f010c1adeba29
0.21.x: 1b5a5c1c74afb5e6d5359bdb826f4cea80497424
0.20.x: 50c2b8d9bad95840ae9e98984afb2678e43442a2
0.19.x: bd39b78a5ad9dd0827c163ace77cf68e611cc2d3

**Comment by bbondy** [comment]
Sorry but I had to revert this because of https://github.com/brave/browser-laptop/issues/11751 
Please do a new pull request for this when that one is addressed. I moved it into 0.19.x hotfix 4.

**Comment by snyderp** [comment]
Sounds good, will do. If the new proposed / amended approach (a counter to limit an infinite recursion) sounds good, I’ll re-PR.
