### PR TITLE
Sanitize PDF url before saving to site data

### LINKED ISSUE #7190: Bookmarked PDF file should have the location of the PDF file itself
## Test Plan
Covered by automatic test
`npm run uitest -- --grep="bookmark pdf"`

## Original issue description
**Describe the issue you encountered:**
Bookmarked PDF file should have the location of the PDF file itself. Currently it includes `chrome-extension://...` as a prefix.

- Platform (Win7, 8, 10? macOS? Linux distro?):  Windows 10

- Brave Version (revision SHA): 0.13.3 RC1

- Steps to reproduce:
    1. Open http://www.orimi.com/pdf-test.pdf
    2. Bookmark it via the star icon on the URL bar
    3. Edit the bookmark via bookmark manager
    
- Actual result: It has `chrome-extension://...` as its prefix.

- Expected result: The location should exclude the prefix.

- Is this an issue in the currently released version? No

- Can this issue be consistently reproduced? Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
clipboard01

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
## Test Plan
Covered by automatic test
`npm run uitest -- --grep="bookmark pdf"`

## Description
fix #7190

Auditors: @bsclfton, @bbondy

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

File: js/about/newtab.js [hunk 1]
```diff
@@ -170,6 +170,8 @@ class NewTabPage extends React.Component {
   onToggleBookmark (siteProps) {
     const siteDetail = siteUtil.getDetailFromFrame(siteProps, siteTags.BOOKMARK)
     const editing = this.isBookmarked(siteProps)
+    // PDFJS will not show up in new tab
+    // siteDetail = siteDetail.set('location', urlUtil.getLocationIfPDF(siteDetail.get('location')))
```
Comment (bsclifton) [inline js/about/newtab.js]: Should this be removed? The comment is fine, but the line of code

Comment (darkdh) [inline js/about/newtab.js]: will do
