### PR TITLE
handle an array of permission types

### LINKED ISSUE #10864: Brave not asking for permissions when loading geolocations
## Test plan

load https://browserleaks.com/geo within Brave

----

**- Did you search for similar issues before submitting this one?**

Yes

**- Describe the issue you encountered:**

Geolocation data is being loaded without prompting the user for permission.

**- Platform (Win7, 8, 10? macOS? Linux distro?):**

Win 7 x86 - Reproduced
Win 10 x64 - Reproduced
macOS 10.12.6 - Reproduced

**- Brave Version (revision SHA):**

Brave: 0.18.31 
rev: a5a7280219b930bc3f3ce1b83a29afedc71bbd79 
Muon: 4.3.17 
libchromiumcontent: 61.0.3163.71 

**- Steps to reproduce:**

1. load https://browserleaks.com/geo within Brave

You'll notice that the geolocation data will load without asking for the required permissions.
    
**- Actual result:**

Users geolocation data loads without asking the user for the required permissions.

**- Expected result:**

Brave should be prompting the user for permission before loading geolocation data.

**- Will the steps above reproduce in a fresh profile? If not what other info can be added?**

Yes

**- Is this an issue in the currently released version?**

No. Looks like it's a new regression in `0.18.31`

**- Can this issue be consistently reproduced?**

Yes

**- Screenshot if needed:**

permissionissue

### PR DESCRIPTION
**Pull request by bridiver**
fix #10864
requires muon 4.3.19+

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/filtering.js [hunk 1]
```diff
@@ -474,50 +447,81 @@ function registerPermissionHandler (session, partition) {
...
+      }
 
-    // If this is a duplicate, clear the previous callback and use the new one
-    if (permissionCallbacks[message]) {
-      permissionCallbacks[message](0, false)
-    }
+      // Always allow fullscreen if setting is ON
+      const alwaysAllowFullscreen = module.exports.alwaysAllowFullscreen() === fullscreenOption.ALWAYS_ALLOW
+      if (permission === 'fullscreen' && alwaysAllowFullscreen) {
+        response.push(true)
```
Comment (diracdeltas) [inline app/filtering.js]: if `permission === 'fullscreen'`, and both `origin.startsWith('chrome-extension://' + config.torrentExtensionId)` and `alwaysAllowFullscreen` are true, wouldn't you be calling `response.push(true)` twice in this loop (since the conditional is `if`, not `else if`)? `response[i] = ...` instead of `response.push(...)` seems clearer

**Comment by diracdeltas** [comment]
some of the permissions tests are failing but could be intermittent https://travis-ci.org/brave/browser-laptop/jobs/274266563

**Comment by bbondy** [comment]
@diracdeltas I pushed a follow up commit to address the feedback of making sure we push at most once per permission type. 
cb4c6d3e047b4897bb12908d6ec5cb35be216553

**Comment by bbondy** [comment]
Sister PR for 4.3.x
https://github.com/brave/browser-laptop/pull/10929

**Comment by bbondy** [comment]
mentioned via slack DM but this is already reviewed and accepted in 4.3, it's just waiting for new builds so we can merge it to 4.4.
