### PR TITLE
Ledger refactoring

### LINKED ISSUE #3433: consolidate state in app/ledger.js with appState
there is a lot of state that is duplicated between `appState` and `ledgerInfo`/`publisherInfo` in app/index.js, which becomes confusing to keep in sync. this should be deduplicated somehow.

### LINKED ISSUE #9641: Ledger pin publishers 0 for unpinned sites
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
When you exclude all unpinned sites, pinned sites should have total of 100. Found while doing #9638
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
63ff18d
- Steps to reproduce:
    1. Enable ledger
    2. Visit two pages
    3. Go to payments
    4. Pin one publisher
    5. Exclude second one
    
- Actual result:
First publisher has the same value as before
- Expected result:
First publisher should have 100%
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #9740: Second key for Brave Payments is not displayed on the UI after recovering wallet
## Test plan

See below

----

- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Second key for Brave Wallet is not displayed on the UI after recovery. Does not matter if you import keys or copy/past them into fields manually.

- Platform (Win7, 8, 10? macOS? Linux distro?):
MacOS

- Brave Version (revision SHA):
Brave	0.17.11
rev	bc6d5b8
Muon	4.1.4

- Steps to reproduce:
    1. Enable Payments in Preferences.
    2. Click on the gear icon to open Advanced Settings.
    3. Select Recover your wallet.
    4. Import recovery keys from a previously saved file.
    5. You will get a successful message. Click OK.
    6. Click on gear icon again.
    7. Click on backup your wallet.
    8. Key 2 is not displayed.
    
- Actual result:
Key 2 is not displayed.

- Expected result:
Both keys should be displayed

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Repeat steps above except manually copy/paste keys from file instead of importing. Key 2 is still not displayed on the UI.
    2. 
    3.

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #9980: Sites visited before payment enabling is shown as 0 views
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sites visited before payment enabling is shown as 0 views

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Found on 0.17.16

- Steps to reproduce:
    1. Clean install 0.17.16
    2. Visit Netflix and view  a video
    3. Enable payments
    4. Visit other sites and visit Netflix 
    5. Netflix shows as views 0 and % 0
    
- Actual result:
Sites visited before payment enabling is shown as 0 views

- Expected result:
Calculation should be done properly 

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Could be checked from 0.16.9 but was not able to reproduce it

- Can this issue be consistently reproduced?
No

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:
cc: @cezaraugusto

### LINKED ISSUE #10036: Sites shows up with 0 views in payments
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Sites shows up with 0 views in payments 

- Platform (Win7, 8, 10? macOS? Linux distro?):
All

- Brave Version (revision SHA):

Brave | 0.17.17
-- | --
rev | dbc3c4d
Muon | 4.1.8

- Steps to reproduce:
    1. Clean install 0.17.17
    2. Enable payments (keep defaults)
    3. Visit sites(both on exclude list and not on exclude list), show up as 0 views instantly after opening the page
    
- Actual result:
Sites shows up with 0 views in payments 

- Expected result:
Should show proper view count for added sites

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes (https://github.com/brave/browser-laptop/issues/9980)

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
image

- Any related issues:
https://github.com/brave/browser-laptop/issues/9980

### LINKED ISSUE #10716: Publisher entry jumps position when enabled/disabled
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Publisher entry jumps position when enabled/disabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):

Brave | 0.19.3
-- | --
rev | 0adbd61
Muon | 4.4.1

- Steps to reproduce:
    1. Enable payments, disable auto-include switch
    2. Visit sites to fill up ledger table
    3. Enable/Disable publisher switch, publisher position jumps around
    
- Actual result:
See attached screenshot

- Expected result:
If all publishers are disabled then enabling it should move the publisher to the top of the list. If publisher is enabled and then disabled based on other publishers state it should either remain in the same position or be listed right after the enabled one

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
Yes. happens on release build as well

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:
publishers

- Any related issues:

### LINKED ISSUE #10955: Site added instantly to the ledger
- Did you search for similar issues before submitting this one?
yes
- Describe the issue you encountered:
Site is added instantly to the ledger, minimum visit time is not used.
- Platform (Win7, 8, 10? macOS? Linux distro?):
macOS
- Brave Version (revision SHA):
b0d7fc0
- Steps to reproduce:
    1. go to payments and enable it
    2. visit a site and switch to payments immediately
    
- Actual result:
image
- Expected result:
site should be added only after 8s on that site
- Will the steps above reproduce in a fresh profile? If not what other info can be added?
yes
- Is this an issue in the currently released version?

- Can this issue be consistently reproduced?
yes
- Extra QA steps:
    1.
    2.
    3.

- Screenshot if needed:

- Any related issues:

### LINKED ISSUE #11009: Ledger refactoring
### Description

This is a tracking issue for ledger refactoring.

#### Phase I #11209
In this phase we will introduce state into the ledger. Everything should be handled with appState now and events should be transmitted via reducers.
**NOTE** This refactor will not have working add founds. This is because we will do complete rewrite of this dialog in next phases

**QA first pass:**
https://github.com/brave/browser-laptop/issues/11214
https://github.com/brave/browser-laptop/issues/11217

MacOS: https://github.com/brave/browser-laptop/pull/11037#issuecomment-333235964
Windows: https://github.com/brave/browser-laptop/pull/11037#issuecomment-333236594

#### Phase || #10945
In this phase we will add support for bat libraries. We will also remove all add found related code that will not be used anymore.

#### Phase ||| #11193
In this phase we will add add found wizard back to the ledger. After this phase ledger should be fully functional again.

#### Phase IV #11210
In the last phase we will do some cleanup and optimisations that were wound while refactoring. We will also add remanning  tests so that coverage will be as good as possible.

### LINKED ISSUE #11080: site that i've never visited shows up in the synopsis
i opened about:preferences#payments yesterday and noticed a site i haven't visited (i subsequently visited it to see what it was): 
screen shot 2017-09-21 at 7 57 46 pm

it appears this site just became a verified publisher yesterday (maybe coincidence, maybe not)

### LINKED ISSUE #11173: Ledger transfer PDF opens another window
### Description

When you open transaction from ledger, you get additional window and brave becomes unresponsive.

### Steps to Reproduce

  1. Create wallet
  2. Generate some transactions
  3. Click on one transaction

**Actual result:**

image

**Expected result:**
There shouldn't be any additional window and brave should work.
**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

 
Brave: 0.19.20 
rev: ec880d04ad36d45b14c162554d58c726c7f0cf7b 
Muon: 4.4.25 
libchromiumcontent: 61.0.3163.100 
V8: 6.1.534.41 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**

Yes
### Additional Information

https://github.com/brave/browser-laptop/pull/10691#issuecomment-329850074

### LINKED ISSUE #11209: Add state to the ledger
### Description

- [x] move functions into ledgerUtil file and add unit tests for them
- [x] create ledger reducer
- [x] create site settings reducer
- [x] move event store into appState
- [x] move ledger state into appState
- [x] remove static call of appState
- [x] pass state into ledger functions
- [x] create ledger state helper
- [x] create update script for session (clear pageData when closing browser from the session)

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #3433 (consolidate state in app/ledger.js with appState)
Resolves #9641 (Ledger pin publishers 0 for unpinned sites)
Resolves #9740 (Second key for Brave Payments is not displayed on the UI after recovering wallet)
Resolves #9980 (Sites visited before payment enabling is shown as 0 views)
Resolves #10036 (Sites shows up with 0 views in payments)
Resolves #10716 (Publisher entry jumps position when enabled/disabled)
Resolves #10955 (Site added instantly to the ledger)
Resolves #11080 (site that i've never visited shows up in the synopsis)
Resolves #11173 (Ledger transfer PDF opens another window)
Resolves #11209 (Add state to the ledger)

Work progress:
- move functions into ledgerApi file
  - [x] create util file
  - [ ] add unit tests
- create ledger reducer
  - [x] create reducer
  - [ ] add unit tests
- create site settings reducer
  - [x] create reducer
  - [x] add unit tests
- move event store into appState
  - [x] move logic
  - [x] add unit test
- move ledger state into appState
  - [x] move logic
  - [ ] add unit test
- remove static call of appState
  - [x] is done
- pass state into ledger functions
  - [x] is done
- create ledger state helper
  - [x] is done
- make it work
  - [x] ledger table
  - [x] wallet recovery
  - [x] transaction view
- create update script for session
  - [x] clear pageData when closing browser from the session
  - [x] crate upgrade path from `ledger-synopsis.json` to appState
  - [x] move `locationInfo` into `ledger->locations`

Auditors:

Test Plan:
- Ledger Refactor Test Cases - MacOS #11214
- Ledger Refactor Test Cases - Win x64 #11217

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

**Comment by NejcZdovc** [comment]
There are 3 tests failing, but as far as I can see they are not related to my changes, but tab handler can't be found. I see correct data on the screen, test just can't verify it.

```
 4) Ledger table 2 publishers pin publisher:
     Error: Promise was rejected with the following reason: Cannot read property 'get' of undefined
      at elements("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - getText.js:18:17
      at getText("[data-tbody-index="0"] [data-row-index="0"] [data-test-id="siteName"]") - ledgerTableTest.js:104:23

  5) Ledger table 2 publishers pin excluded publisher:
     Error: element ("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") still not visible after 10000ms
      at elements("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - isVisible.js:54:17
      at isVisible("[data-tbody-index="1"] [data-row-index="0"] [data-switch-status="false"]") - waitForVisible.js:73:22

  6) Ledger table 4 publishers pin 3 publishers and check unpinned value:
     Promise was rejected with the following reason: timeout
  Error
```

**Comment by NejcZdovc** [comment]
I will squash commits at the end of reviews

**Comment by LaurenWags** [comment]
Issues that I've found:
1. [ ] Buttons on 'Advanced Settings for Brave Payments' are not aligned properly. 
STR: Enable payments, click on cog/wheel icon to open Advanced Payments:
screen shot 2017-09-29 at 4 31 22 pm

2. [ ] Similar to issue 1, buttons on 'Backup your wallet' window are not aligned properly.
STR: In Advanced Settings, click on 'Backup your wallet' button. Buttons on the next screen display like this:
screen shot 2017-09-29 at 4 34 41 pm

3. [ ] Similar to issue 1, buttons on 'Recover your wallet' window are not aligned properly.
STR: In Advanced Settings, click on 'Recover your wallet' button. Buttons on the next screen display like this:
screen shot 2017-09-29 at 4 35 13 pm

**Comment by kjozwiak** [comment]
**Issue 1 - Second Key not appearing after recovery**

issue

STR:

* launch Brave and enable Payments `about:preferences#payments`
* Select "Settings" -> "Backup your wallet" under `about:preferences#payments`
* Copy both keys and close Brave
* Remove the entire profile and restart Brave
* Enable Payments
*  Select "Settings" ->"Recover your wallet"
* add both keys and select "Recover" and click "OK" on the confirmation once the wallet has been recovered
* Go back into "Backup your wallet" and you'll notice that the second key is missing
* Select "Copy" on the second key and you'll get the following error in the console/terminal:

```
An uncaught exception occurred in the main process Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from null
    at EventEmitter.ipcMain.on (C:\projects\browser-laptop\app\index.js:274:26)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (C:\projects\browser-laptop\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\api\web-contents.js:182:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
```

**Comment by luixxiul** [comment]
This fixes the button alignment issue: https://github.com/brave/browser-laptop/pull/11202

**Comment by luixxiul** [comment]
I think we should have tested this PR against `0.19.x` branch, otherwise you would see changes already merged to 0.20.x and 0.21.x, which won't appear on 0.19.x such as the button alignment issue above.

**Comment by NejcZdovc** [comment]
@LaurenWags 

1) will be fixed with #11202 (not a problem on 0.19.x branch)
2) will be fixed with #11202 (not a problem on 0.19.x branch)
3) will be fixed with #11202 (not a problem on 0.19.x branch)
5) Verified icon should be always display, but yes we have some timers that can delay then, for perfomance reasons. But icons should always appear. When you first create wallet we have 5min delay before we trigger request for verified data.

@kjozwiak 
1) I pushed the fix to ledger/bar libraries, so this will be fixed with new versions of libraries https://github.com/brave/browser-laptop/issues/9740 (partial fix was done in this PR as well for status overlay)
2) add founds are not working now and will be enabled back in #10945, even QR code
3) with this PR we remove `ledger-synopsis.json`, we only have `ledger-state.json` now
4) no this was not fixed with this PR, we have issue for that #9677

**Comment by NejcZdovc** [comment]
@luixxiul because we will merge it back to the 0.19. We need this in PR in 0.20 and master as well

**Comment by luixxiul** [comment]
I understand. Here are several reasons why I thought this PR should be based on `0.19.x`:

1) 0.19 release date is fixed
2) nothing will be added to 0.19.x except critical bug fixes
3) we are not sure that this PR would not conflict with `0.19.x` on which 0.19 is released finally.

Even if this PR is merged to 0.19.x and conflict with `0.20.x`, `0.21.x` and `master` (for 0.22.x and later), we will have enough time to fix them.

I'm afraid that we will have a lot of conflicts with 0.19.x after this PR is merged to master and then cherry-picked to 0.19.x. We would then run manual tests again if everything works fine. I think that increases the risk quite a lot.

**Comment by NejcZdovc** [comment]
I agree with this points. For this particular PR I think there shouldn't be a lot of merge conflicts because code is more or less limited to old `ledger.js`. I almost didn't touch components. Issue that will have more problems with conflicts will be #11193

**Comment by NejcZdovc** [comment]
I jus tried cherry picking this PR into 0.19.x and there are only few conflicts regarding imports and app definitions, so we should be fine

**Comment by luixxiul** [comment]
please don't forget to run `npm run test` on `0.19.x` too, so that nothing will be broken with this PR.

**Comment by NejcZdovc** [comment]
@luixxiul will do, thank you for the reminder

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -0,0 +1,2187 @@
...
+// Caching
+let locationDefault = 'NOOP'
+let currentUrl = locationDefault
+let currentTimestamp = new Date().getTime()
+let visitsByPublisher = {}
+let bootP
+let quitP
+let notificationPaymentDoneMessage
+const _internal = {
+  verboseP: true,
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: These items (verboseP, etc) should be accessible outside the file (or should have another way to override them; ex: read a preference). When running unit tests against these, there's a lot of output

File: app/browser/api/ledger.js [hunk 2]
```diff
@@ -0,0 +1,2187 @@
...
+    }
+  }
+
+  publisher.weight = floatNumber
+  publisher.pinPercentage = newPer
+  return publisher
+})
+
+// courtesy of https://stackoverflow.com/questions/13483430/how-to-make-rounded-percentages-add-up-to-100#13485888
+const roundToTarget = (l, target, property) => {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: this might be good in ledgerUtil... although, for now it's fine to keep here since it's still using underscore.  Would be great to have a unit test for this though 😄

File: app/browser/api/ledger.js [hunk 3]
```diff
@@ -0,0 +1,2187 @@
...
+    .map((x, i) => {
+      x[property] = Math.round(x[property]) + (off > i) - (i >= (l.length + off))
+      return x
+    })
+}
+
+// TODO we should convert this function and all related ones into immutable
+// TODO merge publishers and publisherData that is created in getPublisherData
+// so that we don't need to create new Map every single time
+const synopsisNormalizer = (state, changedPublisher) => {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: This function is HUGE and should be broken out. However, that's outside the scope of this PR 😄 

This could use a few good unit tests though- ex: handling when pinned total total > 100%, less than 100%, etc for publishers

File: app/browser/api/ledger.js [hunk 4]
```diff
@@ -0,0 +1,2187 @@
...
+  }
+
+  location = getSourceAboutUrl(location) || location
+
+  currentUrl = location.match(/^about/) ? locationDefault : location
+  currentTimestamp = timestamp
+  return state
+}
+
+const getFavIcon = (state, publisherKey, page) => {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: these could benefit from a falsey check... something like:
```
const protocol = page && page.get('protocol')
if (protocol && publisher && !publisher.get('protocol')) {
```

File: app/browser/api/ledger.js [hunk 5]
```diff
@@ -0,0 +1,2187 @@
...
+  }
+
+  return state
+}
+
+const initSynopsis = (state) => {
+  state = ledgerState.saveSynopsis(state, null, synopsis.options)
+  let value = getSetting(settings.PAYMENTS_MINIMUM_VISIT_TIME)
+  if (!value) {
+    value = 8 * 1000
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: maybe we can pull this magic number up to the top 😄

File: app/browser/api/ledger.js [hunk 6]
```diff
@@ -0,0 +1,2187 @@
...
+    }
+    if (process.env.LEDGER_PUBLISHER_MIN_VISITS) {
+      value = ledgerClient.prototype.numbion(process.env.LEDGER_PUBLISHER_MIN_VISITS)
+      synopsis.options.minPublisherVisits = value
+      state = ledgerState.setSynopsisOption(state, 'minPublisherVisits', value)
+    }
+  }
+
+  const publishers = ledgerState.getPublishers(state)
+  for (let item of publishers) {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: for loop should be much faster performance-wise

File: app/browser/api/ledger.js [hunk 7]
```diff
@@ -0,0 +1,2187 @@
...
+    ],
+    options: {
+      style: 'greetingStyle',
+      persist: false
+    }
+  })
+}
+
+const showNotificationAddFunds = () => {
+  const nextTime = new Date().getTime() + (3 * miliseconds.day)
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: Another magic number (3) that we can pull up to the top as a constant 😄 👍

File: app/browser/api/ledger.js [hunk 8]
```diff
@@ -0,0 +1,2187 @@
...
+
+    _internal.ruleset.raw = ruleset
+    _internal.ruleset.cooked = stewed
+    if (!synopsis) {
+      return state
+    }
+
+    let syncP = false
+    const publishers = ledgerState.getPublishers(state)
+    for (let item of publishers) {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: another one which can benefit from index based for loop.  To get a comparison of each performance, you can check out https://jsperf.com/fastest-array-loops-in-javascript/24

File: app/browser/api/ledger.js [hunk 9]
```diff
@@ -0,0 +1,2187 @@
...
+        amount: getSetting(settings.PAYMENTS_CONTRIBUTION_AMOUNT),
+        address: ledgerInfo.get('address')
+      })
+    state = ledgerState.setInfoProp(state, 'buyURL', buyURL)
+    state = ledgerState.setInfoProp(state, 'buyMaximumUSD', false)
+  }
+
+  // TODO remove when BAT is implemented, we don't need this for BAT
+  /*
+  if ((client) && (now > ledgerInfo._internal.geoipExpiry)) {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: this should be safe to remove now since it's always in source control (if we needed it)

File: app/browser/api/ledger.js [hunk 10]
```diff
@@ -0,0 +1,2187 @@
...
+      }
+    })
+
+    v2RulesetDB.batch(entries, (err) => {
+      if (err) return console.error(v2RulesetPath + ' error: ' + JSON.stringify(err, null, 2))
+
+      if (entries.length === 0) return
+
+      const publishers = ledgerState.getPublishers(state)
+      for (let item of publishers) {
```
Comment (bsclifton) [inline app/browser/api/ledger.js]: for..of 😢  (would benefit from instead being the index based, like `for(let i=0;i<publishers.length;i++)`)

File: app/browser/reducers/siteSettingsReducer.js [hunk 11]
```diff
@@ -0,0 +1,86 @@
...
+ * License, v. 2.0. If a copy of the MPL was not distributed with this file,
+ * You can obtain one at http://mozilla.org/MPL/2.0/. */
+
+'use strict'
+const Immutable = require('immutable')
+const appConstants = require('../../../js/constants/appConstants')
+const siteSettings = require('../../../js/state/siteSettings')
+const urlUtil = require('../../../js/lib/urlutil')
+const {makeImmutable} = require('../../common/state/immutableUtil')
+
```
Comment (bsclifton) [inline app/browser/reducers/siteSettingsReducer.js]: awesome job pulling this out 😄  Nice and clean!! 👍

File: app/common/lib/ledgerUtil.js [hunk 12]
```diff
@@ -106,3 +127,90 @@ module.exports.walletStatus = (ledgerData) => {
   }
   return status
 }
+
+// TODO rename function
+const blockedP = (state, publisherKey) => {
```
Comment (bsclifton) [inline app/common/lib/ledgerUtil.js]: Super niceP having this logicP pulled out of ledger.js.  Makes me happyP!  Good jobP! 😆

File: app/pdf.js [hunk 13]
```diff
@@ -8,14 +8,23 @@ const electron = require('electron')
...
+const renderUrlToPdf = (appState, action) => {
   let url = action.url
   let savePath = action.savePath
   let openAfterwards = action.openAfterwards
 
   let currentBw = BrowserWindow.getFocusedWindow()
 
-  let bw = new BrowserWindow({show: !!testingMode, backgroundColor: '#ffffff'})
+  let bw = new BrowserWindow({
+    show: false,
```
Comment (bsclifton) [inline app/pdf.js]: Just want to confirm: should this be false? (ex: do any tests use it). I remember seeing an issue where the PDF wasn't showing up... is that related? I think you chose to hide it because (on macOS), it opens a window on top of the print dialog, which I understand.

File: app/renderer/components/preferences/payment/ledgerTable.js [hunk 14]
```diff
@@ -51,7 +52,7 @@ class LedgerTable extends ImmutableComponent {
   }
 
   getHostPattern (synopsis) {
-    return `https?://${synopsis.get('site')}`
+    return urlUtil.getHostPattern(synopsis.get('site'))
```
Comment (bsclifton) [inline app/renderer/components/preferences/payment/ledgerTable.js]: ❤️

File: app/browser/api/ledger.js (hunk 6 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: we are for looping Immutable.Map, which I am not sure how can I do it with index based for loop. I use this approach vs `publishers.forEach()` because it should be faster.

File: app/browser/api/ledger.js (hunk 8 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: answered above

File: app/browser/api/ledger.js (hunk 10 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: answered above

File: app/pdf.js (hunk 13 above)
Comment (NejcZdovc) [reply app/pdf.js]: they don't and this should be false. We only create this window to generate PDF which we want to save when window loads.

File: app/browser/api/ledger.js (hunk 1 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

File: app/browser/api/ledger.js (hunk 2 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: yeah my plan for later is to remove underscore and move even more functions into util. Current ledger file is better, but still have a lot of function (which some you can't unit test) in single file

File: app/browser/api/ledger.js (hunk 3 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: agree will try to move it in the next PR's

File: app/browser/api/ledger.js (hunk 4 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: you don't need this check, because `getPublisher` always return Immutable.Map

```
getPublisher: (state, key) => {
    state = validateState(state)
    if (key == null) {
      return Immutable.Map()
    }

    return state.getIn(['ledger', 'synopsis', 'publishers', key]) || Immutable.Map()
  }
```

File: app/browser/api/ledger.js (hunk 5 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

File: app/browser/api/ledger.js (hunk 7 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

File: app/common/lib/ledgerUtil.js (hunk 12 above)
Comment (NejcZdovc) [reply app/common/lib/ledgerUtil.js]: :smile:

File: app/browser/api/ledger.js (hunk 9 above)
Comment (NejcZdovc) [reply app/browser/api/ledger.js]: done

**Comment by NejcZdovc** [comment]
ok travis should be working again

**Comment by srirambv** [comment]
Modal overlay is not correct 
image

**Comment by NejcZdovc** [comment]
@srirambv I pulled in @luixxiul PR so buttons should be ok. Key 2 fix was pushed to the ledger library and will be fixed with new version

**Comment by srirambv** [comment]
**Issue 14 happened on clean profile with visit to github.com**

- [ ] **Issue 15 : Manually changed % value is not retained**
STR:
1. Visit 3-4 sites to get the list in ledger table
2. Pin all the sites in list
3. Manually change value to 3 for one of the pinned site, value is not retained but auto calculated
ledgerrefactor

**Comment by srirambv** [comment]
Separation bar has a bump over the include column
image

**Comment by luixxiul** [comment]
It should be fixed with https://github.com/brave/browser-laptop/pull/10789/files#diff-f14732b3ea914a26c2215676e7208907R347

File: app/renderer/components/navigation/publisherToggle.js [hunk 15]
```diff
@@ -75,6 +75,7 @@ class PublisherToggle extends React.Component {
   }
 
   render () {
+    console.log(this.props)
```
Comment (bsclifton) [inline app/renderer/components/navigation/publisherToggle.js]: should this be removed?

Comment (NejcZdovc) [reply app/renderer/components/navigation/publisherToggle.js]: correct I already removed it, just didn't push it yet :)

**Comment by NejcZdovc** [comment]
master de5f38138bc01a0412a49d8db9a639bbe65d8723
0.20 dddbcee778f10ac6f7e49230de112a6bc7dbe96c
0.19 38c63b0c55b452bba0096655059cc2b5419686c2
