### PR TITLE
Make only BAT TOS text clickable

### LINKED ISSUE #12137: Only TOS text should be clickable
## Test plan

https://github.com/brave/browser-laptop/pull/12140

----

### Description
Only TOS text should be clickable

### Steps to Reproduce

  1. Clean install 0.19.99
  2. Open payments
  3. Hover over TOS div, click anywhere on the div, opens TOS tab 

**Actual result:**
bat-tos

**Expected result:**
Only the TOS text should be clickable

**Reproduces how often:**
100%

### Brave Version

**about:brave info:**

Brave | 0.19.99
-- | --
rev | 43f7a01
Muon | 4.5.16
libchromiumcontent | 62.0.3202.94
V8 | 6.2.414.42
Node.js | 7.9.0
Update Channel | Release
OS Platform | Microsoft Windows
OS Release | 10.0.15063
OS Architecture | x64

**Reproducible on current live release:**
Yes

### Additional Information
cc: @cezaraugusto @NejcZdovc

### PR DESCRIPTION
**Pull request by luixxiul**
Closes #12137

Auditors:

Test Plan 1: `npm run test -- --grep='clicks BAT TOS link'`

Test Plan 2:
1. Open about:preferences#payments
2. Make sure the BAT TOS link text only is clickable
3. Enable/Disable payments
4. Make sure the BAT TOS link text only is clickable

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: test/about/ledgerPanelTest.js [hunk 1]
```diff
@@ -138,6 +139,39 @@ describe('Regular payment panel tests', function () {
...
+    it('clicks BAT TOS link when payments are enabled', function * () {
+      yield this.app.client
+        .tabByIndex(0)
+        .loadUrl(prefsUrl)
+        .waitForVisible(paymentsTab)
+        .click(paymentsTab)
+        .waitForVisible(paymentsWelcomePage)
+        .waitForVisible(walletSwitch)
+        .click(walletSwitch)
+        .waitForEnabled(addFundsButton, ledgerAPIWaitTimeout)
```
Comment (luixxiul) [inline test/about/ledgerPanelTest.js]: I am not sure why this is needed but this line fixes the test failure.

Comment (NejcZdovc) [reply test/about/ledgerPanelTest.js]: because we add timeout to the test sequence which is representing time spent to crate wallet

**Comment by cezaraugusto** [comment]
I'm putting into 0.22.x as there's no milestone set. Please change/uplift as required. Thanks!
