### PR TITLE
Show bookmarks toolbar when bookmarks are synced for the first time

### LINKED ISSUE #7282: Bookmark toolbar is not shown on adding bookmark when sync is enabled
- Did you search for similar issues before submitting this one?
Yes

- Describe the issue you encountered:
Bookmark toolbar is not shown on adding bookmark when sync is enabled

- Platform (Win7, 8, 10? macOS? Linux distro?):
Windows 10 x64

- Brave Version (revision SHA):
Brave	0.13.5
rev	59a41eb

- Steps to reproduce:
    1. Enable Sync from setting and enter the secret code to setup sync
    2. Visit a site in a new tab
    3. Add bookmark, bookmark toolbar is not shown after adding the bookmark
    
- Actual result:
Bookmark toolbar is not shown on adding a first bookmark

- Expected result:
Should either show the bookmark toolbar if it is synced or show the bookmark toolbar on adding the first bookmark on a clean profile which is synced

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes

- Is this an issue in the currently released version?
N/A

- Can this issue be consistently reproduced?
Yes

- Extra QA steps:
    1. Do a clean install of 0.13.5 on device 1
    2. Have sync setup on device 2 
    3. Sync device 1 with device 2 by entering the secret code
    4. Visit a site and add it as a bookmark in device 1
    5. Bookmark toolbar is not shown on adding the bookmark

- Screenshot if needed:
bookmark

- Any related issues:
cc: @ayumi @darkdh @bsclifton

### PR DESCRIPTION
**Pull request by diracdeltas**
Fix #7282

Auditors: @ayumi

Test Plan:
1. automated syncing bookmarks tests should pass
2. open pyramid 0, enable sync
3. open pyramid 1, sync it with pyramid 0
4. add bookmarks to pyramid 0
5. toolbar should appear in pyramid 1 once bookmarks are synced

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

File: app/sync.js [hunk 1]
```diff
@@ -325,7 +324,18 @@ module.exports.init = function (initialState) {
     if (!records || !records.length) {
       return
     }
-    syncUtil.applySyncRecords(records)
+    let showBookmarksToolbar = false
+    if (!initialState.seed) {
+      // syncing for the first time
+      const bookmarks = (AppStore.getState().get('sites') || new Immutable.List()).filter((site) => {
```
Comment (ayumi) [inline app/sync.js]: i think `siteUtil.getBookmarks()` does this

File: app/sync.js [hunk 2]
```diff
@@ -300,9 +300,8 @@ module.exports.init = function (initialState) {
       process.emit(RELOAD_MESSAGE)
     }
   })
-  const isFirstRun = initialized ? false : !initialState.seed && !initialState.deviceId
   ipcMain.on(messages.SYNC_READY, module.exports.onSyncReady.bind(null,
-    isFirstRun))
+    initialized ? false : !initialState.seed && !initialState.deviceId))
```
Comment (ayumi) [inline app/sync.js]: previously we extracted this out for clarity – is moving it into the function call needed?

File: app/sync.js [hunk 3]
```diff
@@ -325,7 +324,18 @@ module.exports.init = function (initialState) {
     if (!records || !records.length) {
       return
     }
-    syncUtil.applySyncRecords(records)
+    let showBookmarksToolbar = false
+    if (!initialState.seed) {
+      // syncing for the first time
```
Comment (ayumi) [inline app/sync.js]: on the first sync, i feel like we should just check `records` for any bookmarks and enable the toolbar here

File: app/sync.js [hunk 4]
```diff
@@ -325,7 +324,18 @@ module.exports.init = function (initialState) {
...
+      const bookmarks = (AppStore.getState().get('sites') || new Immutable.List()).filter((site) => {
+        const tags = site.get('tags')
+        return tags && (tags.includes('bookmark') || tags.includes('bookmark-folder'))
+      })
+      if (!bookmarks.size) {
+        showBookmarksToolbar = true
+      }
+    }
+    syncUtil.applySyncRecords(records, showBookmarksToolbar)
```
Comment (ayumi) [inline app/sync.js]: it seems unnecessary to pass `showBookmarksToolbar` here and 8 more times in `syncUtil.js`

File: app/sync.js (hunk 2 above)
Comment (diracdeltas) [inline app/sync.js]: @ayumi yes, the previous code was incorrect because `initialized` gets changed later

Comment (diracdeltas) [inline app/sync.js]: actually this still seems incorrect (assuming `bind` argument expressions are not re-evaluated)

File: app/sync.js (hunk 1 above)
Comment (diracdeltas) [inline app/sync.js]: :+1:

File: app/sync.js (hunk 3 above)
Comment (diracdeltas) [inline app/sync.js]: i didn't do that because the bookmarks toolbar could show up noticeably earlier than when any bookmarks are actually created (for instance when syncing a large set of records). but it does make the code simpler.

File: app/sync.js (hunk 4 above)
Comment (diracdeltas) [inline app/sync.js]: do you mean unnecessary with https://github.com/brave/browser-laptop/pull/7300#discussion_r101882681 or something else?

**Comment by diracdeltas** [comment]
@ayumi addressed review comments
