### PR TITLE
only update the menu when bookmarks or closed tabs change

### LINKED ISSUE #3782: Cmd+T (New Tab) shortcut becomes disabled while navigation occurs
**Did you search for similar issues before submitting this one?**
Yes

**Describe the issue you encountered:**
While navigating from one GitHub page to another, the Cmd+T shortcut (New Tab) is ignored.

**Expected behavior:**
The shortcut should always be available, regardless of current state

- Platform (Win7, 8, 10? macOS? Linux distro?): macOS

- Brave Version: 0.12.0

- Steps to reproduce:
    1. Open a GitHub listing page, e.g. https://github.com/brave/browser-laptop
    2. Click one of the files, e.g. LICENSE.txt
    3. Quickly, while the loading is still happening, press Cmd+T. I can reproduce the bug consistently if I press Cmd+T as quickly as I can after clicking the link.

### PR DESCRIPTION
**Pull request by bridiver**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

Test Plan:
Add bookmark
1. Go to brave.com
2. Add bookmark
3. Bookmark should appear in menu

Bookmark indicator
1. Open a new tab
2. Bookmark indicator should not be activated
3. Bookmarks menu "Bookmark this page" should not be checked
4. Go back to brave.com tab
5. Bookmark indicator should be active
6. Bookmarks menu "Bookmark this page" should be checked

Last closed Frame
1. Close the brave.com tab
2. History menu should show brave.com under recently closed

Language
1. Change language
2. Restart Brave
3. Text should be translated by language setting
4. Change back and restart Brave
5. Text should be translated by language setting

State
1. Open brave.com
2. Close Brave
3. Reopen Brave and cnn.com tab should be loaded

Fix #3782

### CODE REVIEW

**Comment by bridiver** [comment]
cc @bsclifton

**Comment by bbondy** [comment]
++ thanks

File: app/browser/menu.js [hunk 1]
```diff
@@ -363,13 +365,17 @@ const createHistorySubmenu = (CommonMenu) => {
   return submenu
 }
 
-const createBookmarksSubmenu = (CommonMenu) => {
+const isCurrentLocationBookmarked = () => {
```
Comment (bsclifton) [inline app/browser/menu.js]: Super nice cleanup :smile: The previous code was hacky (because it could be changed in appStore OR in the navigationBar control) and there were definitely ways to cause it to fail (ex: shows checked but its not bookmarked)

File: app/browser/menu.js [hunk 2]
```diff
@@ -572,81 +578,72 @@ const createMenu = (CommonMenu) => {
...
-    if (bookmarksMenu && bookmarksMenu.menu && bookmarksMenu.menu.submenu && bookmarksMenu.index !== -1) {
-      const menu = bookmarksMenu.menu.submenu
-      const menuItems = createBookmarksSubmenu(CommonMenu)
-      menu.clear()
-      menuItems.forEach((item) => menu.append(new MenuItem(item)))
-    }
+const doAction = (action) => {
+  switch (action.actionType) {
+    case windowConstants.WINDOW_SET_FOCUSED_FRAME:
+      // TODO check/uncheck menu item instead of recreating menu
```
Comment (bsclifton) [inline app/browser/menu.js]: Just a ? about this TODO; we solved it already, right? We fetch the item via getMenuItem and then set the checked status

File: app/browser/menu.js [hunk 3]
```diff
@@ -572,81 +578,72 @@ const createMenu = (CommonMenu) => {
...
+      currentLocation = action.frameProps.get('location')
+      let menuItem = menuUtil.getMenuItem(appMenu, locale.translation('bookmarkPage'))
+      menuItem.checked = isCurrentLocationBookmarked()
+      break
+    case windowConstants.WINDOW_UNDO_CLOSED_FRAME:
+      appDispatcher.waitFor([appStore.dispatchToken], () => {
```
Comment (bsclifton) [inline app/browser/menu.js]: [I had to lookup waitFor](https://facebook.github.io/flux/docs/dispatcher.html) and I think I understand this now

To make sure: this code is basically registering another handler for these actions **on top of the existing ones in windowStore**, right? This is **really** cool :smile: Great job!

File: app/locale.js [hunk 4]
```diff
@@ -270,9 +270,24 @@ const defaultLocale = function () {
...
+  if (ipcMain) {
+    // Respond to requests for translations from the renderer process
+    ipcMain.on('translations', function (event, arg) {
+      // Return the entire set of translations synchronously
+      event.returnValue = translations
+    })
+
+    // TODO: There shouldn't need to be a REQUEST_LANGUAGE event at all
+    // Respond to requests for the currently configured language code
+    ipcMain.on(REQUEST_LANGUAGE, function (event) {
```
Comment (bsclifton) [inline app/locale.js]: GJ breaking this out from index.js- much cleaner (and encapsulated)!

Comment (bsclifton) [inline app/locale.js]: wait- just noticed this ipc handling code was already in here LOL- but yeah, I think the locale code that was in index.js was unnecessary

File: app/sessionStore.js [hunk 5]
```diff
@@ -347,35 +341,37 @@ module.exports.loadAppState = () => {
...
-          // Exit immediately without doing the session store saving stuff
-          // since we want the same state saved except for the update status
-          app.exit(0)
-        })
-        return
-      }
+      data = exports.defaultAppState()
     }
-    resolve(data)
+    locale.init(data.settings[settings.LANGUAGE]).then((locale) => {
```
Comment (bsclifton) [inline app/sessionStore.js]: :+1:

File: js/dispatcher/appDispatcher.js [hunk 6]
```diff
@@ -93,7 +93,11 @@ if (process.type === 'browser') {
     let registrant = event.sender
     const callback = function (payload) {
       try {
-        registrant.send(messages.DISPATCH_ACTION, Serializer.serialize(payload))
+        if (registrant.isDestroyed()) {
```
Comment (bsclifton) [inline js/dispatcher/appDispatcher.js]: :+1:

**Comment by bsclifton** [comment]
Great job :smile: ++

File: app/browser/menu.js (hunk 2 above)
Comment (bridiver) [inline app/browser/menu.js]: yep, nice catch. I added the comment before I changed that
