### PR TITLE
Clear state if clear autofill data when shutdown.

### LINKED ISSUE #4818: autofill entry cannot be deleted on restart with Private data option
**Describe the issue you encountered:** autofill entry cannot be deleted on restart with Private data option. Also clicking these crosses does not remove the entries.

clipboard01

**Expected behavior:** The entries should be removed on restart

- Platform (Win7, 8, 10? macOS? Linux distro?): Windows 10

- Brave Version: 0.12.5 RC1

- Steps to reproduce:
    1. Add address and credit card
    2. Enable "autofill data" option of Private Data on about:preferences#security
    3. Restart the browser

- Any related issues:

### PR DESCRIPTION
**Pull request by darkdh**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

because we won't receive personal-data-changed on shutdown

fix #4818 

Auditors: @bridiver

Test Plan:
1. Add autofill data entries in about:autofill
2. Turn on clear "Autofill data" when closing brave in about:preferences#security
3. Restart brave
4. There shouldn't be anything left in about:autofill

### CODE REVIEW

File: app/sessionStore.js [hunk 1]
```diff
@@ -252,6 +252,11 @@ module.exports.cleanAppData = (data, isShutdown) => {
   const clearAutofillData = isShutdown && getSetting(settings.SHUTDOWN_CLEAR_AUTOFILL_DATA) === true
   if (clearAutofillData) {
     autofill.clearAutofillData()
+    const date = new Date().getTime()
```
Comment (bridiver) [inline app/sessionStore.js]: this works, but fyi you can just delete it because it will be-readded from the default session data

**Comment by bridiver** [comment]
++
