### PR TITLE
Fix gridLayout pinning action bug

### LINKED ISSUE #5337: about:newtabs - pinning is not working
I believe this has the same root cause as https://github.com/brave/browser-laptop/issues/5321

Clicking the pin does not work currently. For some items, it would look like it's pinned, but you can't unpin

### PR DESCRIPTION
**Pull request by cezaraugusto**
- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Ran `git rebase -i` to squash commits (if needed).

Fix #5337

Auditors: @bsclifton @bbondy

/cc @luixxiul @srirambv

Our topSites grid have actions connected to each other (pinning/removing/reordering),
so we must ensure all of them are working properly while doing multiple actions.

Test Plan:

* Access new tab page;
* Access several websites (you can grab this JSON https://github.com/cezaraugusto/brave-json/blob/master/newtab-3-rows.json
and copy/paste on session-store-1, it has 18 sites);
* Reordering a tile should work on any position;
* Pin a site. Pinning a site should add a Pin icon on top-right corner and be kept on its position (not jump);
* Keep in mind the website position and reorder it to a new position;
* Access another website and get back to new tab. Ensure that your last pinned website kept its position;
* Remove that site (pinned or not);
* A modal will open. "Undo" removing;
* There should be no pinned icon;
* Website should be back to its original position;
* Pin several websites;
* Reorder pinned websites;
* Access a new website;
* Go back to new tab page: pinned sites should remember their positions;
* Remove a website on removal modal and hit "restore all";
* All sites must be unpinned.

### CODE REVIEW

File: js/about/newtab.js [hunk 1]
```diff
@@ -43,21 +43,10 @@ class NewTabPage extends React.Component {
     const updatedStamp = sanitizedData.getIn(['newTabDetail', 'updatedStamp'])
 
     // Only update if the data has changed.
-    // console.log(updatedStamp + ']DATA_TS==LAST_TS[' + this.state.updatedStamp)
     if (updatedStamp === this.state.updatedStamp) {
       return
     }
 
-    // Ensure top sites only has unique values
```
Comment (bsclifton) [inline js/about/newtab.js]: Since this logic is removed (which is OK), maybe we can move what's left into ipc.on() line :smile: I originally had added this because my state got into a situation where I had many duplicates, which caused problems

**Comment by bsclifton** [comment]
LGTM! Thanks for sticking this one out and taking the time to manually test each of those scenarios; this page is looking great :smile:

File: js/about/newtab.js (hunk 1 above)
Comment (bsclifton) [inline js/about/newtab.js]: (can be done as a follow up in a later commit)

**Comment by srirambv** [comment]
This is not working on Windows. The pinned tabs all moves to the top of the grid after opening  a newtab. Will the fix for #5337 fix this as well?

**Comment by cezaraugusto** [comment]
@srirambv sorry, it was fixed by #5645, which landed on master today. 

I have also added steps for manual testing, feel free to ping me if I missed something.
