### PR TITLE
Reorganize ledgerBackup.js

### LINKED ISSUE #11332: Add additional Add Funds welcome-text to mention market volatility.
image

text:
Note: Due to the inherent volatility of cryptocurrency markets, your balance will typically fluctuate on a daily basis.

cc @zentagonist

### LINKED ISSUE #11343: Reorganize ledgerBackup.js
## Test plan

https://github.com/brave/browser-laptop/pull/11344#issue-263633309

----

### Description

Reorganize ledgerBackup.js 

- Remove obsolete styles
- Split l10n strings to force `font-weight: strong` (On Transifex HTML tags may be deleted by contributors)
- Set `cursor: text` to indicate where you can select the passphrase manually. Since the mouse cursor does not change you often see that the passphrase is not selected, while you though you did.
- Set the same styles as `syncTab.js` to avoid possible style inconsistency
- Split font shorthand to ensure that the styles could be cascaded properly. See: https://github.com/Khan/aphrodite#object-key-ordering

### Steps to Reproduce

  1. Open about:preferences#payments
  2. Enable Payments
  3. Go to the advanced setting
  4. Click `Backup your wallet`

**Actual result:**

**Expected result:**

screenshot 2017-10-07 19 39 47

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Brave Version

**about:brave info:**

**Reproducible on current live release:**

### PR DESCRIPTION
**Pull request by luixxiul**
Fixes #11332
Closes #11343

- Remove obsolete styles
- Split l10n strings to force `font-weight: strong` (On Transifex HTML tags may be deleted by contributors, which should not happen)
- Set `cursor: text` to indicate where you can select the passphrase manually. Since the mouse cursor does not change you often see that the passphrase is not selected, while you though you did.
- Set the same styles as `syncTab.js` to avoid possible style inconsistency
- Split font shorthand to ensure that the styles could be cascaded properly. See: https://github.com/Khan/aphrodite#object-key-ordering

Auditors: @cezaraugusto

Test Plan:
1. Open about:preferences#payments
2. Enable Payments
3. Go to the advanced setting
4. Click `Backup your wallet`
5. Make sure that the cursor changes on the passphrase div

Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [ ] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Test Plan:

Reviewer Checklist:

Tests

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [ ] New files have MPL2 license header

### CODE REVIEW

File: app/renderer/components/preferences/payment/ledgerBackup.js [hunk 1]
```diff
@@ -85,10 +81,12 @@ class LedgerBackupFooter extends ImmutableComponent {
...
 const styles = StyleSheet.create({
+  ledgerBackupText_bottom: {
+    fontWeight: '600',
+    marginTop: globalStyles.spacing.dialogInsideMargin
+  },
+
   ledgerBackupContent: {
-    // Align the buttons and keys even when the width of the strings is not equal
-    width: 'max-content',
-    margin: 'auto',
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/ledgerBackup.js]: Let's not forget to remove what becomes obsolete.

File: app/renderer/components/preferences/payment/ledgerBackup.js [hunk 2]
```diff
@@ -98,23 +96,17 @@ const styles = StyleSheet.create({
...
-    marginLeft: `calc(${globalStyles.spacing.dialogInsideMargin} * 2)`
-  },
-
-  ledgerBackupContent__copyKey__key__header: {
-    marginBottom: globalStyles.spacing.modalPanelHeaderMarginBottom
-  },
+    marginLeft: `calc(${globalStyles.spacing.dialogInsideMargin} * 2)`,
 
-  ledgerBackupContent__copyKey__key__phrase: {
+    // See syncTab.js
```
Comment (luixxiul) [inline app/renderer/components/preferences/payment/ledgerBackup.js]: We could create a common component to avoid style inconsistency, like `PassPhraseContainer`.

File: app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsBatScreen.js [hunk 3]
```diff
@@ -18,10 +19,13 @@ class BatWelcomeScreen extends React.Component {
         className={css(styles.batScreen)}
       >
         <AboutPageSectionTitle data-canWrap data-l10n-id='helloBat' />
-        <p data-l10n-id='helloBatText1'
+        <div data-l10n-id='helloBatText1'
```
Comment (cezaraugusto) [inline app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsBatScreen.js]: any reason why not paragraph?

Comment (luixxiul) [reply app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsBatScreen.js]: not really. I just thought I have not seen `p` many times under `app/renderer/components` (we have a lot of `div` and `span` instead of `p`) and standardizing would help us to keep consistency.

If it should be left as `p`, I'll revert them and that's no problem for me :-)

Comment (cezaraugusto) [reply app/renderer/components/preferences/payment/addFundsDialog/steps/addFundsBatScreen.js]: ya not sure why but please revert this part, the current way is not semantic

**Comment by cezaraugusto** [comment]
also heads-up I just merged #11342

**Comment by luixxiul** [comment]
@cezaraugusto reverted! would you please check again and merge this one if it looks good to you?

**Comment by luixxiul** [comment]
@cezaraugusto would you please merge this to 0.19.x and 0.20.x as well? I'm not quite sure how to and feel I would break the branches. thanks!

**Comment by cezaraugusto** [comment]
I'm doing it now

**Comment by cezaraugusto** [comment]
master 1bb8ff1
0.20.x b1f8771aa2e656b4b711c91fce591e7288277fc4
0.19.x 0f118dcbfddc96649520365d4037c8dc06b64b58

**Comment by luixxiul** [comment]
thanks! 🙏
