### PR TITLE
Fixes contribution notification amount

### LINKED ISSUE #11989: contribution notification says "5 USD" instead of "100 BAT"
## Test plan

https://github.com/brave/browser-laptop/pull/12060#issue-276093993

----

### Steps to Reproduce
  1. Whenever a contribution is made, the notification says "5 USD" instead of "100 BAT"

**Actual result:**

**Expected result:**
The notification says "100 BAT" instead of "5 USD"

**Reproduces how often:**
Every contribution period.

### Brave Version
Brave: 0.19.88 
rev: c29eca63249e3d43584ca1dcc47f3e7a7e904324 
Muon: 4.5.15 
libchromiumcontent: 62.0.3202.89 
V8: 6.2.414.40 
Node.js: 7.9.0 
Update Channel: Release 
OS Platform: macOS 
OS Release: 16.7.0 
OS Architecture: x64

**Reproducible on current live release:**
Yes.

### Additional Information
From `ledger-state.json`:

  "properties": {
    "setting": "adFree",
    "fee": {
      "currency": "BAT",
      "amount": 100
    },

### PR DESCRIPTION
**Pull request by NejcZdovc**
Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).
- [x] Tagged reviewers and labelled the pull request [as needed](https://github.com/brave/browser-laptop/wiki/Pull-request-process).

Resolves #11989 

Auditors:

Test:
- generate some payment history (`npm run add-simulated-payment-history`)
- make sure that last contribution amount is displayed in the notification

Reviewer Checklist:

Tests

- [x] Adequate test coverage exists to prevent regressions
- [x] Tests should be independent and work correctly when run individually or as a suite [ref](https://github.com/brave/browser-laptop/wiki/Code-Guidelines#test-dependencies)
- [x] New files have MPL2 license header

### CODE REVIEW

File: app/browser/api/ledger.js [hunk 1]
```diff
@@ -1309,15 +1309,22 @@ const roundtrip = (params, options, callback) => {
...
   if (current && current.size === transactions.length) {
     return
   }
+
   // Notify the user of new transactions.
   if (getSetting(settings.PAYMENTS_NOTIFICATIONS)) {
     if (transactions.length > 0) {
-      const newestTransaction = transactions[transactions.length - 1]
-      ledgerNotifications.showPaymentDone(newestTransaction.contribution.fiat)
+      const newestTransaction = transactions[0]
```
Comment (NejcZdovc) [inline app/browser/api/ledger.js]: actual fix

Comment (mrose17) [reply app/browser/api/ledger.js]: approved.

**Comment by bsclifton** [comment]
master 8c2225bb5f083da81f505f24bea7b152198bea89
0.21.x 4deea5f8b7141288f8eb40ca70302701d4b52e4e
0.20.x 1b77b1999696b91fd82d78e94e841a78b3440c36
0.19.x 955097602974501ebec5141e16573c474fef69a2
