### PR TITLE
Fix copy to clipboard tooltip

### LINKED ISSUE #8199: about:brave copy to clipboard tooltip is not working
## Test Plan:
1. Open about:brave with kabob > Help > About Brave.
2. Hover over the copy to clipboard button as shown in the screenshot below.
3. Make sure the tooltip `Copy to clipboard` tooltip is shown.

## Original issue description
- Did you search for similar issues before submitting this one?
Yes.

- Describe the issue you encountered:
On the about:brave page, if you hover over the copy to clipboard button, it does not show the tooltip.

- Platform (Win7, 8, 10? macOS? Linux distro?):
All.

- Brave Version (revision SHA):
0.14.1 (3de60d5)

- Steps to reproduce:
    1. Open about:brave with kabob > Help > About Brave.
    2. Hover over the copy to clipboard button as shown in the screenshot below.
    
- Actual result:
No tooltip is shown.

- Expected result:
The tooltip `Copy to clipboard` should be shown.

- Will the steps above reproduce in a fresh profile? If not what other info can be added?
Yes.

- Is this an issue in the currently released version?
Yes, 0.14.1.

- Can this issue be consistently reproduced?
Yes.

- Extra QA steps:
    1. Open about:brave with kabob > Help > About Brave.
    2. Hover over the copy to clipboard button as shown in the screenshot below.
    3. Make sure the tooltip `Copy to clipboard` tooltip is shown.

- Screenshot if needed:
image

- Any related issues:
None.

### PR DESCRIPTION
**Pull request by Liunkae**
## Test Plan:
1. Open about:brave with kabob > Help > About Brave.
2. Hover over the copy to clipboard button as shown in the screenshot below.
3. Make sure the tooltip `Copy to clipboard` tooltip is shown.

## Description
Fixes #8199

- [x] Submitted a [ticket](https://github.com/brave/browser-laptop/issues) for my issue if one did not already exist.
- [x] Used Github [auto-closing keywords](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message.
- [x] Added/updated tests for this change (for new code or code which already has tests).
- [x] Ran `git rebase -i` to squash commits (if needed).

### CODE REVIEW

File: app/renderer/components/clipboardButton.js [hunk 1]
```diff
@@ -37,9 +37,10 @@ class ClipboardButton extends React.Component {
       <span className={css(
         styles.doneLabel,
         this.state.visibleLabel && styles.visible
-      )} onAnimationEnd={this.onAnimationEnd} data-l10n-id='copied'>Copiesd!</span>
+      )} onAnimationEnd={this.onAnimationEnd} data-l10n-id='copied'>Copied!</span>
```
Comment (NejcZdovc) [inline app/renderer/components/clipboardButton.js]: Why do we have english text hardcoded?

Comment (Liunkae) [inline app/renderer/components/clipboardButton.js]: Not sure. I'll remove it.

File: app/renderer/components/clipboardButton.js [hunk 2]
```diff
@@ -37,7 +37,7 @@ class ClipboardButton extends React.Component {
       <span className={css(
         styles.doneLabel,
         this.state.visibleLabel && styles.visible
-      )} onAnimationEnd={this.onAnimationEnd} data-l10n-id='copied'>Copied!</span>
+      )} onAnimationEnd={this.onAnimationEnd} data-l10n-id='copied'></span>
```
Comment (NejcZdovc) [inline app/renderer/components/clipboardButton.js]: Can you please change this to `data-l10n-id='copied' />`

Comment (Liunkae) [inline app/renderer/components/clipboardButton.js]: Sure.

**Comment by Liunkae** [comment]
@NejcZdovc I fixed everything you pointed out and squashed the commits.
